packages/application-shell/package.json, packages/application-shell/src/components/quick-access/butler-container/butler-container.js, yarn.lock
Before, the error was swallowed by the component, now we log an error in case react loadable has the `error` prop.
=> fix(app-shell/quick-access): missing dep, log if component cannot be loaded

packages/application-shell/src/components/navbar/config.js, packages/application-shell/src/components/navbar/feature-toggles.js
- removes `PRODUCT_TYPES_ADMINISTRATION ` feature toggle
I will remove the LD config once this is merged/released
=> chore(navbar/feature-toggles): remove PRODUCT_TYPE_ADMINISTRATION

packages/mc-scripts/config/create-webpack-config-for-development.js, packages/mc-scripts/config/create-webpack-config-for-production.js
- changes the order of execution based on [this](https://github.com/csstools/postcss-preset-env/blob/master/lib/ids-by-execution-order.js) to avoid confusion
- `postcssPostcssColorModFunction -> postcssColorModFunction`
=> refactor(create-webpack-config-for-*): correct naming of color-mod, change order of execution

packages/mc-http-server/Dockerfile, packages/mc-http-server/README.md, packages/mc-http-server/cloudbuild.yaml
No more manual trigger. Now when we cut a new release, a new tag is created and the image is built with the same version as the release tag.
=> chore(http-server): trigger cloudbuild on each tag/release

packages/application-shell/src/components/navbar/navbar.js, packages/application-shell/src/components/navbar/navbar.mod.css, packages/application-shell/src/components/navbar/navbar.spec.js
The "absolute" positioned items in the NavBar, covered other items when the menu got expanded in smaller height screens
This PR adds a FixedMenu and a ScrollableMenu so **if the screen gets smaller** it will add a scrolling bar inside the items which gets rendered inside the `ScrollableMenu` section
* Components
The NavBar is being refactored, so this is a quick fix for the problem
**Before**
**After**
**SUPPORT LINK**
https://jira.commercetools.com/browse/SUPPORT-3996
=> fix(navbar): adds Scrollable and FixedMenu

packages/application-shell/src/components/navbar/navbar.mod.css
Right now, when in Spanish mode, you get this behaviour because the active item isn't wide enough. (because the text is Support - in english) instead of just support
Make active item wider so that this doesn't happen.
cc @mariabarrena
=> fix(nav-bar): widen expanded navbar to fit spanish support text

package.json, packages/application-shell/package.json, packages/react-notifications/package.json, yarn.lock
Upgrades ui-kit to the latest version to avoid serving two different versions of ui-kit in the MC. Also upgrades `commitlint/cli`.
There are a bunch of outdated dependencies in app-kit right now, but I didn't put the effort into updating them (sorry).
=> chore: upgrade ui-kit and commitlint

packages/application-shell/src/apollo-links/__snapshots__/header-link.spec.js.snap, packages/application-shell/src/apollo-links/header-link.js, packages/application-shell/src/apollo-links/header-link.spec.js
The project key is read from the url in a project related appliation context.
This holds for most applications like `application-categories`, `application-discounts` etc. However, the `application-account` does not run with the project key being part of the url. As a result we allow passing the project key as a variable on the operation allowing it to be the fallback.
=> [application-shell]: Allow passing project key as variable on operation

packages/application-shell/src/components/project-switcher/project-switcher-fragments.graphql
This pull request fixes the GraphQL query to use expiry over expired.
Expired is a deprecated field and expiry should be used instead. The project list component itself already uses expiry.isActive. I am not sure how this slipped in again but it should be fixed with the next release.
=> fix(application-shell): to use expiry not expired in project list

packages/application-shell/src/components/quick-access/index.js
Quick Access not opening was reported as a bug:
So far it was not possible to open Quick Access by pressing `f` while a link had focus.
This PR enables that by exempting links from the early return we are doing. This early return is what stops Quick Access from opening while a user types into a form input for example.
I think it's a fair assumption to open Butler while a link has focus.
=> feat(quick-access): support opening quick access when link has focus

packages/babel-preset-mc-app/index.js, packages/babel-preset-mc-app/package.json, yarn.lock
This pull requests suggests adding the stage-1 nullish-coalescing-operator to our babel config.
We are more and more using optional chaining but it's often a bit naive. More [here](https://github.com/tc39/proposal-nullish-coalescing).
=> Add nullish-coalescing-operator to babel-preset-mc-app

packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.js, packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.spec.js
- does not report to sentry when error `code=invalid_scope` and message contains `has expired`
When a project expires, the API responds with an [invalid_scope](https://tools.ietf.org/html/rfc6749#section-5.2) error.
For the moment, we receive logs from Sentry about this. However these are not helpful since they are not actionable.
Instead, I propose that whenever there is an invalid_scope in conjunction with a project being expired, we do nothing..
Why invalid_scope for expired projects?
When a project is expired, the token for the project is expired as well along with its api-clients, so this error code does make sense if we look into the specification of OAuth, however not helpful nor actionable at all in the UI code.
I've initiated a discussion with a couple of backends on what we …
=> fix(components/notification-kinds): do not report error to sentry for `invalid_scope`

packages/application-shell/src/components/project-expired/__snapshots__/project-expired.spec.js.snap, packages/application-shell/src/components/project-expired/project-expired.js, packages/application-shell/src/from-core/page-not-found/__snapshots__/page-not-found.spec.js.snap, packages/application-shell/src/from-core/page-not-found/page-not-found.js
In `project-not-found` and `project-expired`, we have a few warnings due to the babel transformation / rollup.
```js
https://rollupjs.org/guide/en#error-this-is-undefined
src/from-core/page-not-found/page-not-found.js
13:     lineNumber: 9
14:   },
15:   __self: this
^
16: }, React.createElement(FormattedMessage, Object.assign({}, messages.helpDesk, {
17:   __source: {
...and 1 other occurrence
src/components/project-expired/project-expired.js
13:     lineNumber: 9
14:   },
15:   __self: this
^
16: }, salesEmail);
```
The issue was that we were creating React components for the links, but we weren't creating them as class or functional components. So this was undefined.
The compiled code looked like
```js
var salesEmail = 'sales@commercetools.com';
var mailto = React.createElement("a", { …
```
=> chore: fix this undefined due to malformed react components

packages/application-shell/src/components/navbar/navbar.js, packages/application-shell/src/components/quick-access/create-commands.js, packages/application-shell/src/components/quick-access/quick-access.js, packages/application-shell/src/components/quick-access/sub-commands.js
Will fix some warnings with rollup.
Besides, let's used the named export instead of depending on their directory structure remaining static 🤷‍♂️
=> chore: prefer named imports

packages/application-shell/src/components/login-locked/async.js, packages/application-shell/src/components/login-sso-callback/async.js, packages/application-shell/src/components/login-sso/async.js, packages/application-shell/src/components/login/async.js, packages/application-shell/src/components/quick-access/quick-access.js
Currently, we have a few places where a new chunk contains mixed exports. This isn't great for CJS builds.
This will help remove some rollup warnings and shouldn't have any effects on consumers, as they would have to be directly importing from these code split components to be effected.
=> chore: don't mix named and default exports on code splitting

packages/i18n/README.md, packages/i18n/load-i18n.js, packages/i18n/locale-data/de.js, packages/i18n/locale-data/en.js, packages/i18n/locale-data/es.js, packages/i18n/moment-data/de.js, packages/i18n/moment-data/en-gb.js, packages/i18n/moment-data/es.js
We can't use dynamic code splitting in rollup like we were in webpack. This is more explicit. The downside, is we can't define something like "supportedLanguages" in one place. The upside, is we don't need to care about the location of the files, as rollup will split on them.
I'm going to do the same thing in l10n as preparation for the rollup PR as well.
=> chore: refactor i18n for better code splitting

.eslintrc.yaml, packages/application-shell/src/components/quick-access/quick-access.spec.js, packages/application-shell/src/test-utils.js, packages/application-shell/src/test-utils.spec.js
This enhances the capabilities of our `test-utils`.
The application-kit exports `render` (and a bunch of other `react-testing-library` functions) from `@commercetools-frontend/application-shell/src/test-utils`. The `test-utils` file contains a `render` function which can be used to render any component as-if it was rendered by `AppShell`. The `render` function sets up the context providers for the component-under-test. It accepts some options which influence what that context looks like.
The context includes:
- `IntlProvider`
- `ApolloProvider`
- `ConfigureFlopFlip`
- `ApplicationStateProvider`
- `Router`
- permissions
Tests in applications can now test their components using this `render` function like so:
```jsx
// The component under test
// A dumb component which prints the users …
```
=> Add ApplicationState to test-utils

packages/application-shell/src/apollo-links/header-link.js, packages/application-shell/src/apollo-links/header-link.spec.js, packages/application-shell/src/configure-store.js, packages/application-shell/src/utils/get-correlation-id/__snapshots__/get-correlation-id.spec.js.snap, packages/application-shell/src/utils/get-correlation-id/get-correlation-id.js, packages/application-shell/src/utils/get-correlation-id/get-correlation-id.spec.js, packages/application-shell/src/utils/select-user-id/select-user-id.js, packages/application-shell/src/utils/select-user-id/select-user-id.spec.js, packages/sdk/middleware/middleware.js
Branches off #62 (to make the diff a bit more clear)
We now explicitly pass `userId` to the `getCorrelationId` function and `selectUserId` requires the apollo client/cache to be injected.
=> refactor(app-shell): pass userId to getCorrelationId to avoid circular dependency

packages/application-shell/package.json, packages/application-shell/src/apollo-links/header-link.js, packages/application-shell/src/apollo-links/header-link.spec.js, packages/application-shell/src/configure-store.js, packages/application-shell/src/utils/get-correlation-id/__snapshots__/get-correlation-id.spec.js.snap, packages/application-shell/src/utils/get-correlation-id/get-correlation-id.js, packages/application-shell/src/utils/get-correlation-id/get-correlation-id.spec.js, packages/application-shell/src/utils/select-user-id/select-user-id.js, packages/application-shell/src/utils/select-user-id/select-user-id.spec.js, packages/sdk/middleware/middleware.js
Currently, in our `header-link`, we are using apolloClient to read query to get the user id. This causes a circular dependency that looks something like
```(!) Circular dependency: src/configure-apollo.js -> src/apollo-links/index.js -> src/apollo-links/header-link.js -> src/utils/index.js -> src/utils/select-user-id/index.js -> src/utils/select-user-id/select-user-id.js -> src/configure-apollo.js```
Instead of importing `apolloClient` in `select-user-id`, we pass in the cache, which we can get inside of the headerLink using `getContext()`. Then we execute getQuery on the cache. Also added two missing deps to `application-shell/package.json`
=> fix: circular dependency fix

packages/application-shell/src/components/quick-access/butler/butler.js, packages/application-shell/src/components/quick-access/create-commands.js, packages/application-shell/src/components/quick-access/quick-access.js, packages/application-shell/src/components/quick-access/quick-access.spec.js
This adds a feature requested by @antonboyko to QuickAccess which allows opening the result in a new tab by pressing either <kbd>cmd+click</kbd> or by using <kbd>cmd+enter</kbd> when on the selected result. On windows the combination is <kbd>ctrl+click</kbd> or <kbd>ctrl+enter</kbd>.
This also gets rid of the behaviour where Privacy and Help were opened in a new tab/window by default.
=> QuickAccess: allow opening in new tab by cmd+click or cmd+enter

packages/application-shell/src/components/application-shell/global-style-imports.js, packages/application-shell/src/components/application-shell/grid.mod.css, packages/application-shell/src/components/application-shell/reset.mod.css
`ui-kit` is moving it's styles internally, and the `grid.mod.css` and `reset.mod.css` files are (in the next release) located inside of `materials/internal` and could be removed in a later release.. [ref](https://github.com/commercetools/ui-kit/issues/185)
I propose we move `grid.mod.css` and `reset.mod.css` into the app-shell.
* Closes #26
=> refactor: self contained styles

packages/application-shell/src/components/navbar/config.js, packages/application-shell/src/components/navbar/feature-toggles.js
Let's clean up these feature toggles.
This was introduced in conjunction with issues that we faced with multi-cloud. I'd like to release this upon merge. any objections?
=> refactor(navbar): remnove `CAN_VIEW_PRODUCTS` feature toggle

.gitignore, CHANGELOG.md, packages/application-shell/package.json
We were exposing `test-utils` from the `dist` folder by accident which is inconvenient for consumers, and not what we explain in our docs.
After this PR importing `test-utils` will work as documented:
```diff
- import { render } from '@commercetools-frontend/application-shell/dist/test-utils';
+ import { render } from '@commercetools-frontend/application-shell/test-utils'; 
```
=> fix(application-shell): expose test-utils

packages/jest-preset-mc-app/setup-test-framework.js, packages/jest-preset-mc-app/setup-tests.js
This way we don't need to transpile this when we run jest.
=> fix: use commonjs for jest preset

packages/mc-scripts/config/create-webpack-config-for-production.js, packages/mc-scripts/package.json, yarn.lock
Currently unable to uglify "pegjs" output with this new update. Will have to investigate further before going to the new version.
=> fix: revert uglify js update

packages/application-shell/package.json
Build cjs version of test utils in app-shell instead of es version.
=> fix: cjs for test-utils instead of es

packages/application-shell/src/components/login-sso-callback/login-sso-callback.js, packages/application-shell/src/components/login-sso-callback/login-sso-callback.spec.js, packages/application-shell/src/components/login-sso/login-sso.js, packages/application-shell/src/components/login-sso/login-sso.spec.js, packages/storage/index.js
Long story short: redirecting to the IdP `/authorize` endpoint with the `redirect_url` with some query parameters does not guarantee that those params are sent back.
Since we rely on the `organizationId` to authorize the user, we need to be able to "get it" back when the IdP redirects to our `/login/sso/callback` route.
Following [the tips in here](https://auth0.com/docs/protocols/oauth2/oauth-state#how-to-use-the-parameter-to-restore-application-state) I refactored the code a bit to store the `organizationId` as a "state" object within the `nonce` in the ~~`localStorage`~~ `sessionStorage`.
This will result in the `redirect_url` to be only e.g. `https://mc.commercetools.com/login/sso/callback` and the saved nonce will contain the needed state:
```js
// sessionStorage
"nonce_123": { …
```
=> refactor(login-sso): avoid query params in authorize url, use session storage and state nonce

packages/i18n/index.js, packages/i18n/load-i18n.js
Same problem we had with the ui-kit when we switched to rollup. 
The messages were exposed in an object `{ default: { /* messages */ } }`.
With this change, the messages returned is correct
=> fix(i18n): exports to not include default key

packages/application-shell/src/components/login-sso-callback/login-sso-callback.js, packages/application-shell/src/components/login-sso-callback/login-sso-callback.spec.js, packages/application-shell/src/components/login-sso/login-sso.js, packages/application-shell/src/components/login-sso/login-sso.spec.js, packages/application-shell/src/components/login/login.js, packages/application-shell/src/components/logout/logout.js, packages/application-shell/src/components/logout/logout.spec.js, packages/application-shell/src/constants.js
This is mostly an internal refactor/clean up of the SSO login flow. There will be a new specific endpoint `/tokens/sso` in the MC BE to perform the login, this PR is in preparation for that.
NOTE: those changes do not affect any application directly, as the login routes are usually served by the fallback application.
=> refactor(login-sso): use new /tokens/sso endpoint

packages/application-shell/package.json, yarn.lock
`@flopflip/react-broarcast@7.2.3` contains a fix for the issue of not passing props to toggled component. 
Let's update to this version!
=> chore: update @flopflip version

packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap, packages/application-shell/src/components/app-bar/app-bar.js, packages/application-shell/src/components/app-bar/app-bar.spec.js, packages/application-shell/src/components/app-bar/messages.js, packages/application-shell/src/components/application-shell/application-shell.js, packages/i18n/data/core.json
This pull request replaces the ProjectSwitcher with a "Back to project" link in any application not running within a project context.
=> Replace ProjectSwitcher with a "Back to project" link in AppBar

packages/i18n/README.md, packages/i18n/index.js, packages/i18n/package.json
Even though we were using `import()`  for the react-intl-localized-strings used by the app-kit, it wasn't resulting in any code splitting because
* we weren't using `experimentalCodeSplitting` in the rollup config for this package
* we were exporting the json directly from index.js
This PR resolves both of those and updates the README for the i18n package.
I'm not sure I would consider this a breaking change, because the app-kit messages are only really supposed to be used inside of the app-kit 🤔.
If we want to keep the direct exports of the i18n files, we should look into using multiple entry points here... But I don't think it's necessary. WDYT?
=> feat(i18n): fix code splitting for mc-app-kit messages

packages/application-shell/src/components/application-shell/application-shell.js, packages/application-shell/src/components/quick-access/create-commands.js, packages/application-shell/src/components/quick-access/index.js, packages/application-shell/src/components/quick-access/quick-access.js, packages/permissions/src/utils/has-permissions.js
We found out that when the app was requesting a project that does not exist (or the user does not have access to), the app would crash.
The problem was that in some places we were assuming that the `project` was defined, which might not always be. Now, when the project is not found, we render the app correctly and show the 404 page.
=> fix: app crashing when project is not found

CONTRIBUTING.md, package.json
Following the [decision](https://github.com/commercetools/ui-kit/pull/250) in the ui-kit about releasing to `next` by default.
=> chore: publish to next dist-tag by default, add command to move to latest

packages/mc-scripts/config/create-webpack-config-for-production.js
Build is falling when you encounter something like this.
```
background-color: color-mod(var(--color-green) alpha(20%)) !important;
```
fix is re-arrange the plugins. They were already in this order for development.
=> fix: rearrange postcss plugins

packages/application-shell/src/configure-apollo.js, packages/application-shell/src/test-utils/test-utils.js
I am about to try new way of mocking Graphql: one which will mock http requests, and not relay on `<MockProvider />`. To do this, I need:
1.  a way to render Component under test with production Apollo setup
2. force `render` method from `test-utils` to re-create Apollo Client before each test, so that tests will not share the same Apollo Cache.
Our current approach of mocking Graphql is utilising `<MockProvider/>` helper from `react-apollo`, but that has a bunch of drawbacks:
1. Tests are too tightly coupled to the implementation of a Component being tested, because
* test have to import Graphql queries used by those Components
* appropriate responses are matched based on query variables values, which is implementation detail of a Component under test.
2. `<MockProvider/>` does not do a …
=> feat(test-utils): run tests agains actual ApolloProvider

packages/application-shell/src/components/navbar/navbar.js, packages/application-shell/src/components/navbar/navbar.spec.js
As discussed, this removes the `import { Icons } from '@commercetools-frontend/ui-kit'` and uses a component to statically render an icon (explicitly imported) based on the icon name as string.
=> refactor(navbar): use IconSwitcher to statically render icons based on icon names

packages/mc-scripts/extract-intl.js
=> fix(mc-scripts/extract-intl): do not overwrite existing core messages by default

packages/l10n/country-information.js, packages/l10n/currency-information.js, packages/l10n/language-information.js, packages/l10n/time-zone-information.js
Currently locale data imports don't work when using the CJS bundle, as default export isn't available with the CJS build.
Remove the `.default` from the import.
With ES bundle
With CJS
I also tested both bundles with the MC-FE.
=> Make locale data work with CJS bundle

packages/application-shell/src/components/fetch-project/fetch-project.graphql
This pull request adds fetching the new permissions through the fetch project query.
As reviewed on our backends, those permissions will initially default to `true` to unblock FE development so we can wrap our components with permissions. Later "enabling" them is mc-be related.
=> Add new permissions to project query of app-shell

packages/application-shell/src/components/navbar/navbar.js
Custom apps currently all have the `WorldIcon`. We need to keep it for backwards compatibility.
=> fix(navbar): keep WorldIcon for backwards compatibility

playground/webpack.config.dev.js, playground/webpack.config.prod.js
Since `ui-kit` v4.0.0, we no longer access material variables by @importing them in our css files. So we no longer need to pass this folder to our webpack configs.
Stop passing `ui-kit` materials folder to webpack configs in playground.
=> chore(playground): remove ui-kit materials transpilation

.travis.yml
Closes #156 
If the tests fail on CI, the apps still build. See [here](https://travis-ci.org/commercetools/merchant-center-application-kit/builds/461379125?utm_source=github_status&utm_medium=notification) for an example.
Add `set -e` to the beginning of our scripts (instructs bash to quit if there is an error), and add `set +e` to unset the flag at the end of our scripts, as travis can sometimes have internal scripts that exit with a non zero code that we wouldn't result in our build failing.
Check [here](https://travis-ci.org/commercetools/merchant-center-application-kit/builds/463221055?utm_source=github_status&utm_medium=notification) for an example of this PR resulting in a fail fast.
[https://github.com/travis-ci/travis-ci/issues/1066](https://github.com/travis-ci/travis-ci/issues/10 …
=> Fail fast on CI

packages/application-shell/package.json, packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap, packages/application-shell/src/components/app-bar/app-bar.js, packages/application-shell/src/components/app-bar/app-bar.spec.js, packages/application-shell/src/components/application-shell/application-shell.js, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/user-settings-menu/__snapshots__/user-settings-menu.spec.js.snap, packages/application-shell/src/components/user-settings-menu/user-settings-menu.js, packages/application-shell/src/components/user-settings-menu/user-settings-menu.mod.css, packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js, yarn.lock
Ticket: https://jira.commercetools.com/browse/MCD-1509
Design: https://projects.invisionapp.com/d/main#/projects/prototypes/16095086
This PR contains the changes to refactor the user settings menu to the new designs including:
* add downshift for the outer click functionality
* Address minor design issues (border, inside padding, separators, user information)
* Hide projects, organizations and profile options if we are in account section.
* Pass email from `app-bar` so we can use it
| When in the MC | When in account section  |  
|:-:|---|
| ![image](https://user-images.githubusercontent.com/11442895/49215421-0dc83200-f3c9-11e8-8a95-226e7dc588f7.png) | ![image](https://user-images.githubusercontent.com/11442895/49215435-14ef4000-f3c9-11e8-904d-bc7bb45ca6ac.png) |
=> [MCD-1509] Refactor dropdown user settings menu

packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap, packages/application-shell/src/components/app-bar/app-bar.js, packages/application-shell/src/components/app-bar/app-bar.spec.js, packages/application-shell/src/components/application-shell/application-shell.js, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/user-settings-menu/__snapshots__/user-settings-menu.spec.js.snap, packages/application-shell/src/components/user-settings-menu/messages.js, packages/application-shell/src/components/user-settings-menu/user-settings-menu.js, packages/application-shell/src/components/user-settings-menu/user-settings-menu.mod.css, packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js, packages/i18n/data/core.json
Only two points for the UX review.
No hiding sections in the menu when in the account part.
Change item text to "Organizations & Teams"
=> MCD-1509(user-settings-menu): address UX review

packages/application-shell/src/components/application-shell/application-shell.js, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/login/login.js, packages/application-shell/src/components/login/login.spec.js
To prevent possible unwanted redirects to 3rd party "malicious" websites after the user logs in, we should check that the `redirectTo` query parameter matches the current `Origin`.
So if you're in `https://mc.commercetools.com/login`, the `redirectTo` is valid if it contains the same origin `https://mc.commercetools.com` (e.g. `https://mc.commercetools.com/my-project/orders`).
To make the validation possible, the `redirectTo` now contains the `origin`, where previously it only contained the uri path.
=> refactor(login): validate same origin for redirect target url after login

packages/actions-global/global.js, packages/actions-global/global.spec.js
This adds a `isArray` check the the action creator to wrap the `errors` into an `Array` given it is not passed as such.
In our own application we have some code which goes like
```js
.catch(({ graphQLErrors }) =>
this.props.showApiErrorNotification({
errors: Array.isArray(graphQLErrors) ? graphQLErrors : [graphQLErrors],
source: 'InternationalCountriesPanel/updateProject',
})
);
```
to avoid the boilerplate of that check we move it down into the action creator here.
=> Add array wrapping to showApiErrorNotification (through .isArray)

packages/application-shell/src/components/fetch-project/fetch-project.graphql
This pull request removes the recently added but not yet used permissions and visibility overwrites from the project's query permissions field.
After various rounds of meetings with API, POs and UX we decided on the following conceptually:
1. OAuth scopes can be derived from action restrictions
- Given I have no restrictions (e.g. removePrice) then I need manage_products
- Given I have everything restricted then I get only view_products (in this case)
2. Permissions and Visibility Hiding (name may change) are split
- Conceptually I can say `addCategories` as a permission and then hide it in the menu but have it visible in other apps
- This may sound a bit strange but we had multiple hours of meetings and concrete examples agreeing that this is the only feasible path forward
Moreover, …
=> Remove visibility overwrites from permissions

packages/application-shell/package.json, packages/application-shell/src/components/quick-access/index.js, packages/application-shell/src/components/quick-access/pim-indexer-states.js, packages/application-shell/src/components/quick-access/quick-access.graphql, packages/application-shell/src/components/quick-access/quick-access.js, packages/application-shell/src/components/quick-access/quick-access.spec.js, packages/application-shell/src/configure-store.js, packages/application-shell/src/test-utils/test-utils.js
This PR
- adds support for pim-search to Quick Access.
- also adds support of mocking `sdk` requests made through the sdk middleware to `test-utils` - similar to how `ApolloMockProvider` lets us mock GraphQL requests.
I might eventually split the PR up into the two separate parts, but I left it in one PR while gathering feedback for now.
=> Add pim search to quick access

packages/application-shell-connectors/src/components/application-context/application-context.js, packages/application-shell-connectors/src/components/application-context/application-context.spec.js, packages/application-shell/src/components/fetch-project/fetch-project.graphql, packages/application-shell/src/components/fetch-project/fetch-project.js, packages/application-shell/src/components/fetch-project/fetch-project.spec.js
This pull request adds the not yet implemented (@qmateub is on it) `allAppliedPermissions` field.
For the underlying system nothing should change. We map back the `allAppliedPermissions` of shape `[ { name: string, value: boolean } ]` into `{ [name: string]: boolean }`. 
This all in all should decouple app-kit from any app in the future in regards to permissions as anything the mc-be decides to flush through will be available. The only left-over dependency is constants.
=> Add `allAppliedPermissions` and remove `permissions`

.travis.yml, packages/application-shell/src/test-utils/test-utils.spec.js, packages/permissions/src/components/authorized/authorized.js, packages/permissions/src/components/authorized/authorized.spec.js, packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.js, packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.spec.js, packages/permissions/src/utils/has-permissions.js, packages/permissions/src/utils/has-permissions.spec.js
After the mc-fe now can work with `allAppliedPermissions` as a more flexible `Array<AppliedPermission>` we should also improve the behaviour of `Authorized`. 
`Authorized` currently used the constants to determine in its prop-types if the permission is known. This is a bit inflexible:
1. Introducing new permissions requires an app-kit release
2. Tight coupling and duplication of consumer and producer
Give that we can loosen the contract a bit maybe by _validating known (actual) and required (demanded)_ permissions against one another. Given we find one which we do not know about we give a prop-type warning.
Side note: I find the naming of `demanded` and `actual` a bit misleading cause it doesn't provide an inverse: what's the opposite of actual?
=> Refactor `Authorized` in permissions pkg to not rely on constants

packages/application-shell/src/components/navbar/navbar.js
This removes the constant based prop-type testing from the navbar in the application shell. 
The prop-type check should be performed by `RestrictedByPermission` (and is) based on the configured permissions. Not at any given layer of the component tree which just forwards props and pretends to have knowledge and/or a say in what permissions it should allow forwarding without even doing anything with them.
=> refactor(application-shell): permission prop-type form navbar

package.json, packages/create-mc-app/templates/starter/package.json
We include the template packages in yarn workspaces so that lerna can apply the version changes when we do a new release.
=> chore: include create-mc-app templates in yarn workspaces

.travis.yml, CONTRIBUTING.md, package.json
This is more of an idea, as I've been seeing many libraries doing this recently.
The idea is that every time the `master` branch is built on CI, Lerna will publish a new canary version to the `canary` dist channel. The version should look like this: `1.0.0-canary.0+{sha}`.
What are the benefits from doing that?
This makes it easier to test early if changes are properly working, before cutting a normal release.
What do you think? Should we give it a try?
=> chore: publish canary releases on CI for master branch

.travis.yml, scripts/release_canary.sh
Follow up of #243 
I forgot to configure npm to publish with our automation bot account.
Btw: this would have been the version to be published last time out.
=> chore: configure npm to release canary builds with automation bot account

scripts/release_canary.sh
So apparently the `TRAVIS_BRANCH` env variable is set to the target branch (e.g. `master`) for builds triggered by `pr`.
Therefore, we can check extra that the build is not triggered by a PR.
=> build(travis): skip canary release if build is triggered by a pull request

application-templates/starter/package.json, application-templates/starter/src/index.js, scripts/install_app_template.sh
I used the canary build to try the new installation approach of the template for `create-mc-app`.
The template is correctly installed but the app does not start because of the missing `redux` dependency.
So now I changed the installation script on CI to install the app outside of the app-kit repo (to avoid using hoisted dependencies) and we also run tests and build, just to make sure that everything works out of the box.
=> fix: template starter missing dependency

packages/babel-preset-mc-app/index.js, packages/babel-preset-mc-app/package.json, packages/mc-scripts/config/create-webpack-config-for-development.js, packages/mc-scripts/config/create-webpack-config-for-production.js, playground/webpack.config.prod.js, yarn.lock
This pull request adds a babel plugin to remove console.* statements on production.
Given we are building for production we can remove console log statements. It's not strictly needed but also can not hurt much.
There are other alternatives to do this:
1. During uglification
- Decided against it as it create a lock-in to a minifier
2. Overwriting `console.log = () => {}`
- It's not really a good practice to overwrite built-ins
- It also affects code which is not "ours"
Given that I went with a simple babel plugin applied only when building for prod. Moreover the babel plugin allows only overwriting specific loggers (so if needed later we can keep `error` again etc).
=> feat(babel-preset-mc-app): disable console on production

packages/application-shell/src/configure-apollo.js, packages/jest-preset-mc-app/package.json, packages/jest-preset-mc-app/setup-test-framework.js, packages/mc-scripts/config/polyfills.js, packages/sdk/src/middleware/client.js
This pull request re-adds the usage or unfetch as a polyfill. More in the code comment and in app PRs.
=> fix(mc-scripts): use unfetch as polyfill

packages/application-shell/src/configure-apollo.js, packages/application-shell/src/middleware/logger.js, packages/application-shell/src/utils/logger.js, packages/babel-preset-mc-app/index.js, packages/babel-preset-mc-app/package.json, packages/mc-scripts/config/create-webpack-config-for-production.js, packages/mc-scripts/package.json, packages/sdk/src/utils/logger.js, packages/sdk/src/utils/utils.js, playground/package.json, playground/webpack.config.prod.js, yarn.lock
Follow up of #272 
I've been giving it some more thoughts and I think we can solve this problem a bit differently, which is why I'm proposing this new approach.
In general, if we think about it, libraries usually don't log anything. So there is no need to run the babel transform in every node module.
On the other hand, the AppShell is like a mix of library and application code, which is why it logs some stuff (apollo, redux).
At the end, we want to disable logging on production BUT **when we need it, we should be able to see those logs**.
Therefore, we can these applications logs are enabled based on some runtime configuration:
- `process.env.DEBUG === 'true'`
- app is built for development (not test, not production)
- if the app is built for production and there is a `debug=true` query …
=> refactor: disable loggers based on runtime configuration

packages/l10n/country-information.js, packages/l10n/currency-information.js, packages/l10n/language-information.js, packages/l10n/time-zone-information.js
We had some mixed up l10n imports, as calls to german were returning spanish and vice versa.
=> fix(l10n): return correct localized information

packages/application-shell/src/components/handle-apollo-errors/README.md, packages/application-shell/src/components/handle-apollo-errors/handle-apollo-errors.js, packages/application-shell/src/components/handle-apollo-errors/handle-apollo-errors.spec.js, packages/application-shell/src/components/handle-apollo-errors/index.js, packages/application-shell/src/components/navbar/navbar.js, packages/application-shell/src/components/user-settings-menu/user-settings-menu.js, packages/application-shell/src/components/with-applications-menu/with-applications-menu.js, packages/application-shell/src/components/with-applications-menu/with-applications-menu.spec.js, packages/application-shell/src/index.js
As I was developing #289 I noticed that handling apollo query errors is not very much straightforward, especially in our case that we want to dispatch a notification error and not render an error within the component.
So I decided to experiment a bit and came up with the `handleApolloErrors` HOC. The implementation should be documented and tested well enough, so please try to read through and see if it's clear enough.
=> feat: add handleApolloErrors HOC to automatically dispatch query errors

.travis.yml, jest.test.config.js
I tried [different things](https://github.com/commercetools/merchant-center-application-kit/commits/nm-fix-ci-install-app-template) but I couldn't get the symlinking to work outside of the monorepo directory.
So to unblock CI, I think we can just keep building the apps within the monorepo, to ensure the deps are properly symlinked.
However, we need to be aware that we might bump into the issue of having missing dependencies again (see #270). I guess it's a tradeoff.
=> chore: build template app within monorepo, to use linked dependencies

packages/application-components/package.json
🤦‍♂️
The file was not in the published package because of the wrong name
=> fix(application-components): name file correctly

packages/jest-preset-mc-app/jest-preset.js
This pull request adds the new `setupFilesAfterEnv` option for jest@24. Jest deprecated the old `setupTestFrameworkScriptFile` which will be removed in a future version.
I suggest we keep the `setupTestFrameworkScriptFile` around until jest removes it (and maybe longer) and then make that part of a breaking release for app-kit to require jest@24.
Ref: https://jestjs.io/docs/en/configuration.html#setupfilesafterenv-array
=> chore: add setupFilesAfterEnv (for jest@24)

packages/application-shell/src/components/quick-access/butler/butler.js, packages/application-shell/src/components/quick-access/butler/butler.mod.css, packages/application-shell/src/components/quick-access/messages.js, packages/i18n/data/core.json
This pull request adds a placeholder text to the input of quick access.
=> Add placeholder to quick-access input

packages/application-shell/src/configure-apollo.js
Fixes a small regression from #310 
TL;DR: the custom apps menu config and the apps menu config use (unfortunately) the same type name `NavbarMenu`, which causes the cache to override the menu items of custom apps within the custom apps list view.
Since custom apps menu query returns ids, we can simply check that the `result` contains an id before returning a `__typename` + `key` cache id.
As follow ups, we might consider to do different things:
- rename the app menu types (not for custom apps)
- make the `dataIdFromObject` more robust
- allow to pass a custom mapping function to the `dataIdFromObject`
=> fix(apollo-cache): to use __typename + key for whitelisted types only if the id is not present

packages/notifications/middleware/middleware.spec.js, packages/notifications/package.json, packages/notifications/reducer/reducer.spec.js, yarn.lock
This is part of the OSS licenses review process.
The `deep-freeze` dependency has an unknown/outdated licence. Moreover, the package is basically useless and very much outdated.
=> chore: drop unnecessary deep-freeze dependency

packages/application-shell/src/components/navbar/navbar.js, packages/application-shell/src/components/navbar/navbar.spec.js
This pull request "fixes" the GraphQL query to load custom application menus to only run when the feature is enabled.
Custom applications is not enabled for all users yet. Furthermore, it's not available on AWS deployments yet. Given the query runs in such an env the server will respond with `{ __status__: 'not-configured' }` which Apollo seems to fail to parse and throw an error for. In addition to responding with an empty `data: {}` I'd suggest to not run the query at all. We can then setup a targeting rule using the `tenant` being `aws`.
=> Fix fetching custom application menu only when feature is enabled

packages/browser-history/index.js
Caused by: https://github.com/commercetools/merchant-center-application-kit/pull/348
We need to omit the `?` otherwise parts of applications relying on it will break.
=> fix(browser-history): to omit the question mark

packages/l10n/data/countries/de.json, packages/l10n/data/countries/en.json, packages/l10n/data/countries/es.json, packages/l10n/data/languages/de.json, packages/l10n/data/languages/en.json, packages/l10n/data/languages/es.json
As of February 12th, Macedonia is now known as Northern Macedonia. 🇲🇰 
I got the german name from [here](https://de.wikipedia.org/wiki/Streit_um_den_Namen_Mazedonien)
And the spanish name from [here](https://es.wikipedia.org/wiki/Disputa_sobre_el_nombre_de_Macedonia)
and english from [here](https://www.theguardian.com/world/2019/feb/12/nato-flag-raised-ahead-of-north-macedonias-prospective-accession)
=> feat(l10n): rename Macedonia -> North Macedonia 🇲🇰 🇲🇰 🇲🇰 🇲🇰 🇲🇰 🇲🇰 🇲🇰 

packages/application-shell/src/components/application-shell/application-shell.js, packages/application-shell/src/components/quick-access/quick-access.js, packages/application-shell/src/components/quick-access/quick-access.spec.js
This pull request adds the feature (needed as a fix) for QuickAccess to support redirects with full page reloads. 
When QuickAccess is rendered in the application-fallback we can not render a `RouteCatchAll` as a result never triggering a full page reload from there to any other app. As a result we see the 404 page served by the application-fallback app itself.
We have the notion of `INTERNAL__isApplicationFallback` the NavBar already uses for these cases. We use the same concept, passing it the same as `useFullRedirectsForLinks` to `open` instead of `push` to history.
=> fix(app-shell): quick-access to support full reloads

.travis.yml, packages/application-shell/src/components/quick-access/quick-access.spec.js
This part of the `QuickAccess` test has been failing locally (but passing on CI...) for some time. Both @emmenko and I looked into it and we couldn't figure out why. At this point, I'm not sure it makes sense to continue spending time on it.
=> chore: comment out failing test

packages/application-shell/src/components/quick-access/quick-access.js, packages/application-shell/src/components/quick-access/quick-access.spec.js
We noticed that in some browsers this opens a new tab. Instead now we use the same redirect mechanics as in the nav-bar.
=> fix(app-shell): to not open in new tab

application-templates/starter/webpack.config.prod.js, packages/mc-scripts/config/create-webpack-config-for-production.js, packages/mc-scripts/config/polyfills.js, packages/mc-scripts/package.json, playground/webpack.config.prod.js, yarn.lock
Currently, our production bundles have code like this in it.
```js
const n=r("../node_modules/omit-empty/node_modules/kind-of/index.js");
```
```js
const a=(e,t)=>{let r=!!t&&t.omitZero```
```
This is bad because arrow functions are **NOT** supported by IE 11.
Passing a new parameter to createWebpackConfigForProduction and compiling those deps.
Explicitly compiling dependencies that are shipping ES6 code with babel.
Here's a screenshot of trying to use the MC with IE11. Notice how it crashes and doesn't load the login page.
=> Update uglify plugin / stop shipping es6 code to ie

packages/jest-preset-mc-app/jest-preset.js, packages/jest-preset-mc-app/package.json, packages/mc-scripts/config/create-webpack-config-for-development.js, packages/mc-scripts/config/create-webpack-config-for-production.js, packages/mc-scripts/package.json, yarn.lock
Pegjs is only used in discounts. Instead of including this loader in our webpack config, we should just do it in the discounts webpack config like so:
```js
// discounts/webpack.config.js
config.module.rules = config.module.rules.concat({
test: /\.pegjs$/,
use: [require.resolve('pegjs-loader')],
});
```
I also removed it from the jest config
The migration in apps that need pegjs will have to do something like this
```js
const preset = require('@commercetools-frontend/jest-preset-mc-app');
module.exports = {
...preset,
transform: {
...preset.transform,
'^.+\\.pegjs$': 'pegjs-jest',
},
// ...
};```
=> feat: remove pegjs loader from webpack config

packages/application-shell/src/configure-apollo.js
Adds a special mapping for `DeliveryItem` type of graphql. Basically it contains two attributes, `id` and `quantity`. But the `id` is really the line item id referenced in the delivery item, so once it gets in the apollo cache we get the wrong data. See screenshots:
|Response  | After apollo caches it |
|---|---|
|![image](https://user-images.githubusercontent.com/11442895/53508374-e8c38800-3ab9-11e9-8035-d6afccb39c15.png)  | ![image](https://user-images.githubusercontent.com/11442895/53508444-0abd0a80-3aba-11e9-906e-036174dbe3b0.png) |
See how the `typeName` is wrong for the delivery item.
The documentation is also clear about this:
=> refactor(configure-apollo): add special mapping for DeliveryItem type

packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap, packages/application-shell/src/components/app-bar/app-bar.js, packages/application-shell/src/components/app-bar/app-bar.spec.js, packages/application-shell/src/components/application-shell/application-shell.js, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/navbar/navbar.js, packages/application-shell/src/components/navbar/navbar.spec.js, packages/application-shell/src/components/quick-access/quick-access.js, packages/application-shell/src/components/quick-access/quick-access.spec.js, packages/application-shell/src/components/route-catch-all/route-catch-all.js, packages/application-shell/src/components/route-catch-all/route-catch-all.spec.js, packages/application-shell/src/components/user-settings-menu/user-settings-menu.js, packages/application-shell/src/components/with-applications-menu/with-applications-menu.js, packages/application-shell/src/components/with-applications-menu/with-applications-menu.spec.js
Fixes #407
Previously we were basing the logic to load the apps menu config from the local file or remotely based on the `NODE_ENV` variable. However, when testing the production bundle locally in production mode, the app would break because the graphql endpoint does not exist.
Now we base the logic on the `servedByProxy` flag.
Additionally, I also removed the prop `INTERNAL__isApplicationFallback` and assume that the `useFullRedirectsForLinks` comes from the `env.json`. We only use it internally in our fallback app, so I don't consider it a breaking change.
=> fix(apps-menu): to trigger remote query based on servedByProxy value

packages/application-shell/README.md
Just noticed. I guess forgotten when moved to `/src`.
=> docs(app-shell): fix test-utils link to readme

packages/sdk/package.json, packages/sdk/src/actions/actions.js, packages/sdk/src/actions/actions.spec.js, yarn.lock
`sdk-middleware-http` from https://github.com/commercetools/nodejs now supports sending HEAD requests. This PR upgrades that package and adds `head` redux-action.
=> Support HEAD-requests

packages/mc-scripts/config/create-webpack-config-for-production.js, packages/mc-scripts/package.json, yarn.lock
Uglify-js is not recommended to be used anymore. Also CRA uses terser. Furthermore, uglify-js has issues with hooks. Just google for "Cannot set property 'lastEffect' of null".
=> fix(mc-scripts): use terser as minifier

application-templates/starter/package.json, package.json, packages/application-shell/package.json, packages/react-notifications/package.json, playground/package.json, visual-testing-app/package.json, yarn.lock
This pull request updates to react-router v5 which doens't have any breaking changes for us.
We recently (maybe even overly eager) update to 4.4 which is now unpublished and makes app-kit kind of be in lala-land.
Release notes here: https://reacttraining.com/blog/react-router-v5/
> There are no breaking changes in this release. If you are already using version 4.x, you can use version 5 immediately with zero code changes. 🎉 Version 5 will pick up where the 4.x roadmap (now the 5.x roadmap) left off.
=> fix: update react-router to v5

packages/application-shell/src/components/quick-access/butler/butler.js, packages/application-shell/src/components/quick-access/butler/butler.mod.css, packages/application-shell/src/components/quick-access/messages.js, packages/application-shell/src/components/quick-access/quick-access.js, packages/application-shell/src/components/quick-access/quick-access.spec.js
Adds a no results message to QuickAccess to give better user feedback.
This is meant to look similar to the offline message.
=> feat(app-shell): quick-access to have noresults message

packages/application-shell/package.json, yarn.lock
The bundle is now built with rollup, before it was built with parcel and apparently I either did something wrong or it didn't work as expected.
=> chore: update omit-empty-es to v1.0.3

application-templates/starter/src/components/main-view/main-view.spec.js, packages/application-shell/src/components/fetch-project/fetch-project.spec.js, packages/application-shell/src/components/fetch-user/fetch-user.spec.js, packages/application-shell/src/components/handle-apollo-errors/handle-apollo-errors.spec.js, packages/application-shell/src/components/inject-reducers/inject-reducers.spec.js, packages/application-shell/src/components/login-locked/login-locked.spec.js, packages/application-shell/src/components/login/login.spec.js, packages/application-shell/src/components/project-suspended/project-suspended.spec.js, packages/application-shell/src/components/quick-access/quick-access.spec.js, packages/application-shell/src/components/with-applications-menu/with-applications-menu.spec.js, packages/application-shell/src/test-utils/README.md, packages/application-shell/src/test-utils/test-utils.js, packages/application-shell/src/test-utils/test-utils.spec.js, playground/src/components/state-machines-list/state-machines-list.spec.js
Using the latest babel version, we get this error when testing the apps that consume the `test-utils` bundle.
The problem seems to be the way we export our custom `render` function, which clashes with the re-exported `render` function of RTL.
Solution: we should export our custom render function under different names.
| Before | After |
| --- | --- |
| `render` | `renderApp` |
| `renderWithRedux` | `renderAppWithRedux` |
| `experimentalRender` | `experimentalRenderAppWithRedux` |
More info:
- https://github.com/kentcdodds/react-testing-library/issues/169
- https://github.com/kentcdodds/react-testing-library/pull/179
=> refactor(test-utils): to avoid conflicting named exports with rtl render function

packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.js, packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.spec.js
This PR adds a new prop to the  `SetupFlopFlipProvider` to manually set the `shouldDeferAdapterConfiguration` flag of `ConfigureFlopFlip`. 
When `shouldDeferAdapterConfiguration` is defined, it is used.
When it's not defined, it defaults to the same as before: by negating the existence of the user prop.
=> feat(app-shell): Add prop do defer adapter config on flop flip provider setup

packages/application-shell/src/components/application-shell/application-shell.mod.css
Fixes #505 
**Before**
**After**
=> fix(app-shell): css height for app container

packages/application-shell/index.js
Trigger a release. Just changing the CircleCI config doesn't as lerna opts out due to no changes to any package.
=> chore(app-shell): minor documentation change to trigger release

CHANGELOG.md
We will first try out the canary release. Eventually this is the release notes when hitting latest.
=> docs(changelog): for v13.0.0 [skip ci]

packages/application-shell/src/components/authenticated/authenticated.js, packages/application-shell/src/components/authenticated/authenticated.spec.js
This pull request fixes and edge case with the following repo case:
1. Log in
2. Remove the `mcAccessToken` cookie
3. Reload the page
Then you will end up in an infite redirect loop as the app assumes the user is still logged in (local storage cache) while the query `amILoggedIn` in the background fails due to the missing cookie.
=> fix(app-shell): to unset previously set cached value

packages/application-shell/src/components/application-shell/application-shell.js
This pull request is also around the infinite redirect loop which is not 100% tamped according to my debugging.
Whenever the user is deemed unauthorized (can occur by any request) with cached autorization state in local storge, then this error will be caught. Given the user does not have the `mcAccessToken` cookie _but_ the cached local storage state then the error will be caught here. However, when by redirecting to login the local storage state will never be unset leading to a another redirect loop.
I am not sure why we decided to go to /login here. Given we go to logout it will unset everything and redirect to login anyway after.
=> fix(app-shell): redirect to logout when catching unauthorized error

packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.js
This pull request changes the detection when rendering the `localizedMessage` coming from an request having gone through an API Extension.
Note that the response of an API Extension contains:
```json
"errorByExtension": {
"id": "<extension-id>",
"key": "my-extension"
}
```
The `localizedMessage` does not have to be present but can be set by the user of the API Extension.
More can be found here: https://docs.commercetools.com/http-api-projects-api-extensions.html#error-cases
=> fix(react-notifications): to use errorByExtension field

packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.js
This pull request adds the ability to add the `launchdarklyTrackingTenant` alone without the other user information.
Today we learned that sign up will not be available on all environments at the same time. Given this needs to be toggled, we need to be able to at least specify the `launchdarklyTrackingTenant`. When running the sign up application we don't have any other user information (as there is no user). 
Before we assumed that we can "get way" with toggling for all environments we deploy to equally.
=> feat(app-shell): add allowing to pass ldTrackingTenant alone

packages/application-shell/src/configure-apollo.js
Now that we are starting to play with Stores in orders, we need a filter for stores in the orders list.
Because we want to use our `ReferenceFilter` this means that we will use GraphQL for reading values from the cache when it is needed.
The "problem" is that the main attribute for identifying a store is the `key` rather than the `id` as clarified by @yanns (👏 ) and similar to the  `project` entity from Core API. So we need a special mapping for it in the apollo cache 🚀
=> feat(configure-apollo): add special mapping for Store entity

jest.eslint.config.js, jest.stylelint.config.js, package.json, packages/jest-preset-mc-app/jest-preset.js, packages/jest-preset-mc-app/package.json, yarn.lock
Initial dependency installation is broken, because of jest-plugin-filename dep
```
yarn
yarn install v1.13.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/terkelg/prompts.git
Directory: /Users/armi/projects/test
Output:
fatal: unable to connect to github.com:
github.com[0: 140.82.118.3]: errno=Connection refused
github.com[1: 140.82.118.4]: errno=Connection refused
```
Because jest-plugin-filename has dependency with url format that can be invalid on some systems
``git://github.com/terkelg/prompts.git#792824f8e5bfe3d632da0e48be23ab718b8f6646``
vs
``git+ssh://git@github.com/terkelg/prompts.git#792824f8e5bfe3d632da0e48be23ab718b8f6646``
=> fix: replace deprecated and broken package jest-plugin-filename with jest-watch-typeahead

application-templates/starter/package.json, packages/application-components/package.json, packages/application-shell/package.json, packages/application-shell/src/components/application-shell-provider/application-shell-provider.js, packages/application-shell/src/components/application-shell-provider/application-shell-provider.spec.js, packages/application-shell/src/components/application-shell-provider/utils.js, packages/application-shell/src/components/application-shell/application-shell.js, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/i18n/async-locale-data/async-locale-data.js, packages/i18n/load-i18n.js, packages/i18n/utils.js, packages/react-notifications/package.json, playground/package.json, yarn.lock
Following the [suggestions from ui-kit](https://github.com/commercetools/ui-kit/pull/643), we can actually treat the ui-kit translations as we do for the other localization files.
=> refactor(i18n): to load the i18n messages async

application-templates/starter/src/components/main-view/main-view.mod.css, packages/application-components/src/components/dialogs/internals/dialog-styles.mod.css, packages/application-shell/src/components/app-bar/app-bar.mod.css, packages/application-shell/src/components/application-loader/application-loader.mod.css, packages/application-shell/src/components/application-shell-provider/reset.mod.css, packages/application-shell/src/components/loading-placeholder/loading-placeholder.mod.css, packages/application-shell/src/components/locale-switcher/locale-switcher.mod.css, packages/application-shell/src/components/navbar/navbar.mod.css, packages/application-shell/src/components/project-switcher/project-switcher.mod.css, packages/application-shell/src/components/quick-access/butler-command/butler-command.mod.css, packages/application-shell/src/components/quick-access/butler/butler.mod.css, packages/application-shell/src/components/user-settings-menu/user-settings-menu.mod.css, packages/react-notifications/src/components/notification/notification.mod.css, packages/react-notifications/src/components/notifications-list/notifications-list.mod.css, playground/src/components/state-machines-list/state-machines-list.mod.css
Just moving towards using the new custom properties 😄 😇
=> chore: use non deprecated custom properties

packages/application-shell/src/components/application-shell/__snapshots__/application-shell.spec.js.snap, packages/application-shell/src/components/project-container/project-container.js, packages/application-shell/src/components/project-container/project-container.spec.js
With new environments being rolled out and sign up being disabled on them for ever I would like to move away from a feature toggle to have an environment variable to enable it. This will also reduce confusing in the `appEnv` and `hubspot` variable as this variable will then take precedence. 
Moreover, having a feature flag doesn't work consistently as it is sometimes not yet fetched when the redirect occurs.
=> fix(app-shell): add env variable for enabling sign up

packages/application-shell/src/components/app-bar/app-bar.js
This refactors the back to project link to be a normal LinkButton. Design requested it to be a FlatButton but actually intends the colour to not be black like now
but primary liks this
=> fix(app-shell): back to project link colour

packages/application-shell/src/components/app-bar/app-bar.js, packages/application-shell/src/components/app-bar/app-bar.spec.js
This pull request fixes a previously non-existing case (or adds it).
Given a user creates his/her first project the `url` will be `mc.commercetools.co/null` instead of just the domain. This happens cause the user neither has a project key in localstorage, nor in the url nor on the user query. As a result we have to redirect to root and let the next pull page refresh handle it.
=> fix(app-shell): routing to project without key

packages/application-shell/src/components/project-container/project-container.js, packages/application-shell/src/components/project-container/project-container.spec.js
Given the user navigates to the account app and does not have a project yet and some prop for the project-container change, then the projectkey (which is not in the url) will be set to `null` (string `null`) in local storage. This is leaky as in it could also be handled on the consumer side but I think should be fixed properly here.
The result of this is that e.g. the logo will redirect to `mc.commercetools.co/null`.
=> fix(app-shell): project key being set to null

packages/application-shell/src/components/app-bar/app-bar.js, packages/application-shell/src/components/app-bar/app-bar.spec.js, packages/application-shell/src/components/application-shell/application-shell.js, packages/application-shell/src/utils/get-previous-project-key/get-previous-project-key.js, packages/application-shell/src/utils/get-previous-project-key/index.js, packages/application-shell/src/utils/index.js
This pull request extracts the project key determination logic into a little module. The whole ternary business is a bit spread out across the code base while essentially it's almost always the same.
1. Did the user select one (localStorage)
2. Does the user have a default one (mc-be)
3. Then either rendering something or not, redirect or not
=> chore(app-shell): extract logic into util

packages/application-shell/src/components/application-shell/application-shell.js
Given the mc runs in devleopment mode and the user does not have any projects we shoudl show a message. Given this happens when the mc runs behind the proxy we will be redirected to `account/projects/new` anyway.
=> chore(app-shell): add development mode message

packages/application-shell/src/components/application-shell/application-shell.js, packages/application-shell/src/components/project-container/project-container.js, packages/application-shell/src/components/redirect-to-project-create/index.js, packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.js, packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.spec.js
This pull request aims to improve how we redirect to project create while fixing a bug with it.
Generally three cases where we need to cover this exist (apart from multiple cache things):
1. User has previously visited a project _and_ a project key is in the url but his new account doesn't have access to it while she/he has no other projects
- Redirect to project create
- Given not served by proxy: show dev message
2. User never or has visited a project but no project key is in the url
- Redirect to project create
- Given not served by proxy: show dev message
Given that those cases overlap I extracted the logic into a component for reuse and isolated testing.
Moreover, we should contract (did already) UX/PO about how we may want to scope local stroage. Given you sign in and sign up across …
=> refactor(app-shell): to have redirect-to-project-create component

packages/application-shell/src/components/fetch-project/fetch-project.js, packages/application-shell/src/components/project-container/project-container.js, packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.js
This avoids a uncalled-for round trip and makes sign up smoother. Given the user doesn't have a project:
1. Either not in the url (claims she/he has one)
2. Or actually no `defaultProjectKey` from the users query which is `projects[0]`
Then we can omit the request. This makes the redirect smoother and less janky.
=> chore(app-shell): to not fetch project without key

CHANGELOG.md
Waiting to test out canary release first. Then releasing.
=> docs(changelog): for v13.3.8 [skip ci]

packages/application-shell/src/components/locale-switcher/locale-switcher.js, packages/application-shell/src/components/locale-switcher/locale-switcher.mod.css, packages/application-shell/src/components/locale-switcher/locale-switcher.spec.js
Experiment: Use `ui-kit` for the locale switcher instead of using react-select v1.
Before
After
=> refactor(application-shell): use ui kit select input for locale switcher

application-templates/starter/src/index.js, packages/application-shell/package.json, playground/package.json, playground/src/index.js, yarn.lock
Now that #617 and #618 are merged, `react-select v1` can be removed as a dependency, and it's CSS import can be removed as well.
Closes #554
=> chore: remove react-select v1

packages/application-components/package.json
Our peer dependency for `ui-kit` is wrong, because in `application-components`, we use customProperties that were added in version `9.2.0`. [ref](https://github.com/commercetools/merchant-center-application-kit/blob/877818249aa324bbe6af447aed2517fe4183d579/packages/application-components/src/components/dialogs/internals/dialog-container.js#L92)
Updates the peer dep in application components to `^9.2`.
Do we need to also update it in `application-shell`? Or will application-shell resolve it from `application-components`?
=> fix(application-components): ui-kit peer dep

packages/application-shell-connectors/src/components/application-context/application-context.js, packages/application-shell-connectors/src/components/application-context/index.js, packages/application-shell-connectors/src/index.js, packages/permissions/src/hooks/use-is-authorized/index.js, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.js, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.js
This pull request adds a `useIsAuthorized()` hook. It should be pretty self explanatory from the specs.
=> feat(permissions): add use-is-authorized hook

packages/application-shell/src/components/navbar/navbar.js
This pull request allows hiding main menu items without submenu items.
When this was first implemented the dashboard was not hidable as we didn't have the welcome page. Given now we do we can hide menu items which don't have submenus and automatically hide main menus when all submenus are hidden.
=> fix(app-shell): to default to menu if no submenus are defined

.circleci/config.yml
This release fixes the issue with a PR having one commit without an ancestor. 
https://github.com/iynere/compare-url/pull/23
=> fix(circleci): to use new compare-url orb

packages/application-shell/src/components/locale-switcher/locale-switcher.mod.css, packages/application-shell/src/components/project-switcher/project-switcher.mod.css
I saw this on our latest TGIF post:
and noticed the counter gets misaligned with more than 2 digits.
This PR fixes that. The number will now remain center aligned in the counter no matter how many digits it has.
=> fix(app-shell): Switcher counter not properly centered

packages/application-shell/src/components/quick-access/quick-access.js
We should not assume an env always to be set when evaluating here. This breaks quick access in the accounts app cause it currently doesn't have any custom env passed.
=> fix(app-shell): quick access env not always set

packages/mc-http-server/README.md, packages/mc-http-server/routes/logout.js
This might seem a breaking change, but for production usage it does not affect any one (besides our internal auth app).
=> refactor(http-server): to unset cookie only for local development

packages/mc-scripts/config/browserslist.js, packages/mc-scripts/config/create-webpack-config-for-development.js, packages/mc-scripts/config/create-webpack-config-for-production.js, packages/mc-scripts/package.json, rollup.config.js
This pull request attempts to solve a regression caused by postcss where it warns about lacking a `browserlistrc`-file.
I am not 100% sure this solves it but it is closer to what the docs suggest. Furthermore, I couldn't see the `config/browserlist` being used anywhere. Does anybody have an idea?
=> fix(mc-scripts): browserlist config

packages/application-shell/src/index.js
Fixes the error
```
TypeError: Cannot set property version of [object Object] which has only a getter
```
This is caused by the proxy export of flopflip, which also contains a `version` field that conflicts with the app-shell `version` export. The reason is that the exported keys in cjs are exported as following:
```js
Object.keys(reactBroadcast).forEach(function (key) {
Object.defineProperty(exports, key, {
enumerable: true,
get: function () {
return reactBroadcast[key];
}
});
});
```
=> fix(app-shell): do not re-export the version field from flopflip

.eslintrc.yaml, @types/sentry-testkit/index.d.ts, packages/sentry/package.json, packages/sentry/src/sentry-user-tracker/sentry-user-tracker.tsx, packages/sentry/src/sentry.ts, packages/sentry/src/type-utils.ts
To expose both type declarations and prop-types, we tried #719 using a babel plugin but unfortunately it currently has some limitations (https://github.com/commercetools/merchant-center-application-kit/pull/719#issuecomment-499959171).
This is another approach that we can use which works the other way around: given prop-types, we infer TS types from them.
https://dev.to/busypeoples/notes-on-typescript-inferring-react-proptypes-1g88
=> refactor: to prefer type literal instead of interface, to infer type from prop-types

packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.example.js, packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.spec.js, packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.story.js, packages/application-components/src/components/dialogs/form-dialog/form-dialog.example.js, packages/application-components/src/components/dialogs/form-dialog/form-dialog.spec.js, packages/application-components/src/components/dialogs/form-dialog/form-dialog.story.js, packages/application-components/src/components/dialogs/info-dialog/info-dialog.example.js, packages/application-components/src/components/dialogs/info-dialog/info-dialog.spec.js, packages/application-components/src/components/dialogs/info-dialog/info-dialog.story.js, packages/application-components/src/components/internals/for-docs/example-wrapper/example-wrapper.js, packages/application-components/src/components/internals/for-docs/modal-controller/modal-controller.js, packages/application-components/src/components/modal-page/modal-page.story.js, website/src/layouts/content.js, website/src/layouts/internals/globals.js, website/src/layouts/internals/layout-main.js, website/src/layouts/marketing.js, website/src/templates/markdown.js
In order to provide a similar experience of testing components in storybook, but keeping the content and design of the website, we decided to render some input elements to control some of the component props.
A previous attempt was done in #721
=> refactor(website): to use custom knobs to control component props

packages/application-components/src/components/internals/for-docs/example-wrapper/example-wrapper.js
Changes usage of `Tooltip` in the website, to have a big z-index, biggli-er than the modal.
Can't upload the GIF on starbucks wifi.
=> fix(website): tooltip z-index fix

packages/permissions/src/components/authorized/authorized.spec.tsx, packages/permissions/src/components/authorized/authorized.tsx, packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx, packages/permissions/src/components/branch-on-permissions/branch-on-permissions.tsx, packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.spec.tsx, packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.tsx, packages/permissions/src/constants.ts, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts, packages/permissions/src/types.ts, packages/permissions/src/utils/has-permissions.spec.tsx, packages/permissions/src/utils/has-permissions.ts
So that we can generate proper prop-types. Yes it's a bit repetitive but the duplicated types are very simple, so I think it's worth the effort in this case.
**Before**
**After**
=> fix(permissions): do not use shared types, keep them within the component file

packages/application-shell/src/components/quick-access/create-commands.js, packages/application-shell/src/components/quick-access/quick-access.js, packages/application-shell/src/components/quick-access/quick-access.spec.js, packages/application-shell/src/feature-toggles.js
This removes the feature toggle for the org list. This may seem a bit quick given the release happened Thursday last week. However, the AC's views are to be turned off today too and we already rolled out 2-3 fixes.
=> chore(app-shell): remove org list toggle

packages/application-shell/src/components/application-shell/application-shell.js, packages/constants/src/constants.ts
This pull request adds redirecting a user, given his/her account does not exist, to logout with a `?reason=deleted`. Our internal app can then catch this an render an error accordingly instead of just showing a general "ice cream"-error.
=> feat(app-shell): add user deleted logout reason

.env.template, .github-labelsrc.json, package.json, yarn.lock
This PR simply creates an initial entry in version control about the current github labels. It uses a [new package](https://github.com/commercetools/github-labels) that we built recently to keep the labels in sync with a local config.
The idea is that the labels are managed through a config file, which can be better reviewed as it's in version control. It would also then make it easier to replicate the same config across different repositories.
=> chore: init github labels config

packages/application-shell/src/components/user-settings-menu/user-settings-menu.js, packages/application-shell/src/components/with-mouse-over-state/README.md, packages/application-shell/src/components/with-mouse-over-state/index.js, packages/application-shell/src/components/with-mouse-over-state/with-mouse-over-state.js, packages/application-shell/src/components/with-mouse-over-state/with-mouse-over-state.spec.js, packages/application-shell/src/components/wrap-display-name/index.js, packages/application-shell/src/components/wrap-display-name/wrap-display-name.js, packages/application-shell/src/components/wrap-display-name/wrap-display-name.spec.js
Moves the HOC `withMouseOverState` from UI-Kit internal.
FYI, I tried to refactor to not use it, but it's not so easy since `Avatar` accepts that prop and changes the image opacity and background colour of it's div. I guess we can modify Avatar to accept custom styling through (maybe accepting a default component?) and deal with it that way. But as the current Avatar component states, it's hard to change the appearance on hover without relying on it's implementation details...
=> chore: move with-mouse-over-state internal

packages/jest-stylelint-runner/package.json
The `run` file was omitted from package.json of `jest-stylelint-runner`. This PR adds that file.
=> fix(jest-stylelint-runner): include run file

packages/babel-preset-mc-app/index.js
As discussed on slack, we add `babel-plugin-transform-react-constant-elements` to our list of babel plugins 😇 
[ref](https://babeljs.io/docs/en/next/babel-plugin-transform-react-constant-elements.html)
=> chore: add babel plugin transform react constant

packages/application-shell/src/apollo-links/token-retry-link.js, packages/application-shell/src/apollo-links/token-retry-link.spec.js
This adds the admnistration service to support token retries. This is needed as when one creates an organization or project we will add a new permission which invalidates previous tokens while the request to load the just created project or org will fail as a result without generating a new token.
=> fix(app-shell): to support admin service target

packages/babel-preset-mc-app/index.js, packages/babel-preset-mc-app/package.json, yarn.lock
This breaks the MC tests in many ways. 
It's hard to say what the issue is as the plugin seems to massage the jsx. I would remove it to unblock the app-kit release. If we really have a case for the plugin we need to investigate some more.
=> fix(babel-preset): to remove plugin-transform-react-constant-elements

CHANGELOG.md
Quick release to get webpack loaders updated in the apps.
=> docs(changelog): for v13.12.3 [skip ci]

packages/application-shell/src/components/fetch-project/fetch-project.graphql, packages/application-shell/src/components/fetch-project/fetch-project.spec.js
I don't see us using this or reason for anybody else having to use this. This is now available through another separate query.
=> refactor(app-shell): to remove team count

CHANGELOG.md
13.13. This release can only go bad.
=> docs(changelog): for v13.13.0 [skip ci]

packages/jest-preset-mc-app/setup-tests.js
No more such "useless" errors like
Now we get at least a more readable error:
=> fix(jest/setup): to show actual error logs on CI when something is logged to console

packages/mc-scripts/config/create-webpack-config-for-production.js
As discussed, since we don't support IE11, it doesn't make sense to transpile vendor code.
=> v14 -> refactor: remove vendorsToTranspile

packages/mc-html-template/lib/compile-html.js, packages/mc-scripts/compile-html.js
=> fix(html-template/compile-html): to use correct option for useLocalAssets

packages/permissions/src/components/authorized/authorized.tsx
The `tiny-invariant` library will still throw in production which is radical. Plus it fails to give additional information in Sentry of what permission actually isn't configured.
I suggest to refactor this to sentry and not have the app stop working in case of unconfigured permissions but instead report. We could also send something to Prometheus and have a dashboard if this is not enough.
=> refactor(permissions): to use sentry for error reporting

CHANGELOG.md
I want to release this quickly and integrate it into apps so we get rid of this throwing asap as it got dangerous.
=> docs(changelog): for v13.13.2 [skip ci]

packages/application-shell/src/apollo-links/__snapshots__/header-link.spec.js.snap, packages/application-shell/src/apollo-links/header-link.js, packages/application-shell/src/apollo-links/header-link.spec.js, packages/application-shell/src/configure-store.js, packages/application-shell/src/constants.js, packages/application-shell/src/utils/index.js, packages/application-shell/src/utils/select-team-id-from-local-storage/index.js, packages/application-shell/src/utils/select-team-id-from-local-storage/select-team-id-from-local-storage.js, packages/sdk/src/middleware/middleware.js, packages/sdk/src/middleware/middleware.spec.js
_This PR is not needed before v14. It's just a spike or thought experiment_
This pull request adds passing along the `teamId` in the Apollo link or Redux middleware.
At some point the MC likely will have a team switcher. This allows e.g. admins to view permissions etc as if they were a member of another team.
All of the queries in the mc-be already work with a `teamId`, it's just not passed. The idea is for now to not have the switcher as a UI element but allow us to set the `teamId` somehow.
My first gut feeling is not to have the `teamId` as `?teamId=<UUID>` in the url. It's not really a sub-resource to anything, doesn't have to be passed around in a link. As a result we could start with the `teamId` in local storage (just like the `projectKey`). This would allow us to try this feature …
=> feat(app-shell): add passing `teamId` in link and middleware

packages/application-components/src/components/modal-pages/internals/modal-page-top-bar.js
=> [v14] fix(components): to use first-of-type instead of first-child

packages/l10n/src/create-l10n-injector/create-l10n-injector.spec.tsx, packages/l10n/src/create-l10n-injector/create-l10n-injector.tsx
This is a bit of a workaround, due to the issue with react 16.8 and `act`.
I still want to use the hook implementation under the hood though, but when running tests (and when react is still 16.8) we can fall back to use the class component.
=> [v14] refactor(l10n): to use class component in tests until react 16.9

packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx, packages/application-shell-connectors/src/components/application-context/application-context.tsx, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/fetch-project/fetch-project.graphql, packages/application-shell/src/components/fetch-project/fetch-project.js, packages/application-shell/src/components/fetch-project/fetch-project.spec.js, packages/application-shell/src/components/project-container/project-container.spec.js, packages/application-shell/src/test-utils/test-utils.js, packages/permissions/README.md, packages/permissions/src/components/authorized/authorized.spec.tsx, packages/permissions/src/components/authorized/authorized.tsx, packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx, packages/permissions/src/components/branch-on-permissions/branch-on-permissions.tsx, packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.spec.tsx, packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.tsx, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts, packages/permissions/src/utils/has-permissions.spec.tsx, packages/permissions/src/utils/has-permissions.ts
This pull request builds on our APIs offering an `allAppliedActionRights` while implementing what has been discussed in #879.
The addition of action rights touched on:
1. Fetching the project
2. Flushing things down the appliction context
3. Allowing our test-utils to pass things in
4. All Hocs, components and hooks in our permissions package
The `option` argument of components/hocs/hooks now accepts a `actionRights` property of shape `[{ group: string, name: string }]`. This type is called `TDemandedActionRight[]`.
The `allAppliedActionRights` are fetched in a similar shape of `[ group: string, name: string, value: boolean } ]`. Similar do the other `allApplied*`. The `name` here is in can case for consistency with permissions.
The application context then transforms this response to the …
=> feat: add support for action rights though `allAppliedActionRights`

.circleci/config.yml
Otherwise these won't be part of a canary.
=> fix(circleci): add save test-utils to workspace

CHANGELOG.md
The last canary isn't working but locally tested this release and I can't find any issues so far.
=> docs(changelog): for v14.1.0 [skip ci]

packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.tsx
This pull request fixes drilling the props through RestrictedByPermissions to Authorized. It's the only occurance where we missed this. 
The RestrictedByPermissions is still tested via shallow rendering which is why tests nor typing barked at us. I plan to refactor those after the fix is out this or early next week.
=> fix(permissions): to drill props

packages/mc-scripts/config/create-webpack-config-for-development.js, packages/mc-scripts/config/create-webpack-config-for-production.js, packages/mc-scripts/package.json, yarn.lock
The pull request removes the `regenerator-runtime` which to my understanding we only use to support `async`-fns in browsers which don't support them natively.
However, this illustrates with the removal of IE11 support async functions are actually supported by all our targeted browsers. As a result we can remove this (I'd hope).
=> chore: remove regenerator-runtime

jest.test.config.js, packages/jest-preset-mc-app/jest-preset-for-typescript.js, packages/jest-preset-mc-app/jest-preset.js
Projects that do not use typescript should not have typescript specific config into the default jest preset.
To use the TS preset, simply import the jest preset as following:
```js
// jest.config.js
module.exports = {
preset: '@commercetools-frontend/jest-preset-mc-app/jest-preset-for-typescript',
};
```
=> refactor(jest-preset): to split typescript config from default preset

packages/permissions/src/components/authorized/authorized.tsx, packages/react-notifications/src/components/notification/notification.spec.tsx, packages/react-notifications/src/components/notification/notification.tsx, packages/react-notifications/src/components/notifier/notifier.tsx, tsconfig.json
As I'm writing and testing the type declarations for ui-kit components (https://github.com/commercetools/ui-kit/pull/860) I noticed that the way we defined the `defaultProps` for TS is wrong.
After researching things a bit I found this solution, and actually since TS 3 they have much better support for `defaultProps`.
PS: in the future React will probably "deprecate" default props for functional components, preferring variable initializers.
=> refactor: default props type declarations

package.json
Thought it would be useful to have it listed. This is what I usually use to publish an alpha release of all packages, without creating a git tag/push.
You will be prompted to select/enter the version of your choice, select one of the `pre` versions:
=> chore: define command to publish an alpha release [skip ci]

packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.tsx, packages/application-components/src/components/modal-pages/internals/modal-page.tsx, packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.tsx
This PR fixes the website not correctly displaying the default form controls in FormModalPage and TabularModalPage, because the type-guard for the `customControls` prop checks for the existence of it on the prop list, but it can exist and be `undefined`, which also needs to be checked.
This PR also changes the `topBarPreviousPathLabel` to not be required in the ModalPages, because it has a default value in ModalPageTopBar and thus it should not be required in the parents. It was throwing warnings because of it.
=> fix: Modal Pages custom controls 

packages/application-shell/src/components/navbar/navbar.js, packages/application-shell/src/components/navbar/navbar.spec.js
This pull request adds the ability to hide menu items by action rights. This is eventually needed to hide e.g. "Add Products" or "Add Category".
To achieve this we basically just need to pass the config to the respective component.
=> feat(app-shell/navbar): add ability to hide menu by action rights

packages/jest-preset-mc-app/setup-test-framework.js
Fixes 
```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import 'unfetch/polyfill';
^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected string
```
=> fix(jest): use cjs syntax

packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.tsx, packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.tsx
**Before**
```js
FormModalPage.propTypes = (_FormModalPage$propTy = {
level: _pt.number,
title: _pt.string.isRequired,
isOpen: _pt.bool.isRequired,
onClose: _pt.func,
children: _pt.node.isRequired,
zIndex: _pt.number,
baseZIndex: _pt.number,
getParentSelector: _pt.func,
shouldDelayOnClose: _pt.bool,
topBarCurrentPathLabel: _pt.string,
topBarPreviousPathLabel: _pt.oneOfType([_pt.string, _pt.any]),
subtitle: _pt.oneOfType([_pt.string, _pt.element]),
isPrimaryButtonDisabled: _pt.bool,
dataAttributesPrimaryButton: _pt.objectOf(_pt.string),
dataAttributesSecondaryButton: _pt.objectOf(_pt.string),
},
_defineProperty(_FormModalPage$propTy, "customControls", _pt.node.isRequired),
_defineProperty(_FormModalPage$propTy, "level", _pt.number),
_defineProperty(_FormModalPage$propTy, "title", …
```
=> fix(application-components): rewrite conditional props logic, to account prop-types transformer

.percy.yml, package.json, website/.percy.yml, website/package.json, website/src/layouts/internals/layout-container.js
I contacted Percy support:
> Hi Percy team, we're very happy with your product so far but I have a couple of questions as I can't figure out how to do it:
> 1. we have a multi project setup (because of a monorepo) but the `.percy.yaml` is defined globally. I would like to specify different widths based on the percy project. Is that possible?
> 2. one of the projects uses static snapshots for a gatsby website. However, the snapshots do not take the full height of the page resulting in the page being "cut off" (https://percy.io/commercetools-GmbH/app-kit-website). Is this a known problem? Is that related to how the page layout is built? For instance, the layout consists in a css-grid with only the central column being scrollable.
And their answer:
> Hey Nicola,
>
> Thanks for reaching out! …
=> fix: percy snapshots for website

packages/application-shell-connectors/src/components/application-context/application-context.tsx, packages/permissions/README.md, packages/permissions/src/components/authorized/authorized.spec.tsx, packages/permissions/src/components/authorized/authorized.tsx, packages/permissions/src/components/branch-on-permissions/branch-on-permissions.tsx, packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.tsx, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts, packages/permissions/src/utils/has-permissions.ts
- adds support for `demandedDataFence` on `injectAuthorized`
- return `isAuthorized` as closure when `dataFence` is demanded on client
Until now, we supported `demandedPermissions` and `demandedActionRights` which key-value objects and easy to with their actualPermissions and actualActionRights counterparts from the MC-API
With `dataFences` however, we're adding another dimension to match with. Namely the values stored a key on a resource. This is to fulfil the following scenario:
```
GIVEN User A
WITH no projectPermission ManageOrders
AND WITH dataFencePermission ManageOrders
for orders of store A
GIVEN Order of store A 
THEN User A can manage order in the order details
```
----
At the moment, the problem I'm solving is allowing the user to view and manage orders.. **for the …
=> feat(permissions/authorized): add support for demandedDataFences for injectAuthorized

.circleci/config.yml, packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx, packages/application-shell-connectors/src/components/application-context/application-context.tsx, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/fetch-project/fetch-project.js, packages/application-shell/src/components/project-container/project-container.spec.js, packages/application-shell/src/test-utils/test-utils.js, packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx, packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.spec.tsx
Leftover of #941 
I also changed a bit the CI workflow to build the packages first, then run the linters and tests. This way we should be able to catch the prop-types warnings.
=> fix: prop-types for dataFences optional field

packages/application-shell/src/components/with-applications-menu/fetch-applications-menu.graphql, packages/application-shell/src/components/with-applications-menu/with-applications-menu.spec.js
This pull request adds loading of `actionRights` to the menu.
1. The data is already pushed to the storage bucket from the MC
2. The `navbar` already forwards props accordingly and has been released
3. This is blocked by a change to out internal infrastructure
=> feat(app-shell): load actionRights from gql for menu

packages/actions-global/src/actions/handle-action-error.spec.ts, packages/actions-global/src/actions/handle-action-error.ts
Customers keep complaining about obscure error messages show in MC (in `application-products` in particular), whenever CRUD operations are failing because of not passing server-side validation.
What happening in this case is that `handleActionError` tries to distinguish between `sdk errors` and `unknown errors` based on a wrong assumption that `sdk errors` are never subclasses of `Error` class. After that it strips away all valuable information about the actual failure from passed `sdk error` object. In reality though, `sdk errors` are always instances of `Error` class.
With this PR we are changing the way described check is made so that it will be based on presence of absence of `body` field of supplied error object.
=> fix(actions-global): distinguish unknown/api errors based on presence of body field

packages/application-shell/src/components/performance-timing/actions.js, packages/application-shell/src/components/quick-access/quick-access.js, packages/application-shell/src/components/quick-access/quick-access.spec.js, packages/application-shell/src/components/version-tracker/actions.js, packages/constants/src/constants.ts, packages/sdk/README.md, packages/sdk/src/middleware/middleware.js, packages/sdk/src/middleware/middleware.spec.js, packages/sdk/src/test-utils/README.md, playground/src/components/state-machines-details/actions.js, playground/src/components/state-machines-list-connector/actions.js, playground/src/components/state-machines-list-connector/state-machines-list-connector.js, playground/src/components/state-machines-list/state-machines-list.js, playground/src/components/state-machines-list/state-machines-list.spec.js, playground/src/routes.js, website/content/main-concepts/data-fetching.mdx, website/content/main-concepts/graphql.mdx, website/content/main-concepts/proxy-endpoints.mdx, yarn.lock
All requests (apart from graphql) to the MC API should be prefixed with `/proxy/<service>`.
This PR adds support for a `mcApiProxyTarget,` option in the SDK action creators to make it easier for consumers to configure the action. The available proxy target are also exposed as constants `MC_API_PROXY_TARGETS`.
PS: one of the reasons for having this is to help migrate our current action creators to use the `/proxy/ctp` endpoint instead of the legacy one (which is without the prefix).
Eventually we can remove the legacy route from the MC API.
=> feat(sdk): allow to pass a mcApiProxyTarget, to the SDK action

packages/permissions/README.md, packages/permissions/src/components/authorized/authorized.spec.tsx, packages/permissions/src/components/authorized/authorized.tsx, packages/permissions/src/components/branch-on-permissions/branch-on-permissions.tsx, packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.tsx, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts, packages/permissions/src/utils/has-permissions.ts
- passes `actualDataFence.values` into `selectDataFenceData` (previously named `selectDataFenceDataByType`
Previously we wrote `selectDataFenceDataByType` with the assumption that the data returned from `selectDataFenceDataByType` will come only from the resource we demand a dataFence for e.g `Orders`.  This is true in the case for Details and List Views.  
And it will look as the following:
```
{ 
dataFences: [
// N number of datafences
],
selectDataFenceData: ownProps => ({ type }) => {
switch(type) {
...
}
}
}
```
---
In the Navbar, we also need to apply datafences.
This is especially necessary because in the MC-API, [we are distinguishing](https://github.com/commercetools/merchant-center-services/pulls?q=is%3Apr+is%3Aclosed+author%3Aamine-benselim) project permissions (via …
=> refactor(permissions/has-permissions): pass `actualDataFenceValues` into `selectDataFenceData`

packages/application-shell/src/components/navbar/navbar.js, packages/application-shell/src/components/navbar/navbar.spec.js, packages/application-shell/src/components/with-applications-menu/fetch-applications-menu.graphql, packages/application-shell/src/components/with-applications-menu/with-applications-menu.spec.js
- adds `dataFences`(demandedDataFence) into RestrictedByPermission for NavBar
- follow up on https://github.com/commercetools/merchant-center-application-kit/pull/990
we know that we demand for DataFences to apply on `Authorized`, we are required to provide a `selectDataFenceData`.
For Details/List, we could use the resource to provide values e.g `order.storeRef.key`.
However in Navbar, we do not have any resource. So to "circumvent" this limitation, we let the `Authorized` give us the values we are looking for and return that as the default.
This is to enable the case where user has dataFence permissions but not project permissions
=> feat(application-shell/navbar): add demandedDataFences and return dataFenceValues given to the user

.renovaterc.json
This pull request changes renovate's behaviour to have one PR a week while splitting major and minor updates.
This is often seen as an anti-pattern and was also a feature request to Greenkeeper as far as I recall.
The downside is, that one breaking dependency update it is hard to spot.
The upside is, that we don't need to merge all updates by hand.
The alternative would be to enable automerging. However, that comes at the downside of releasing a canary per dep update while having long changelogs as a result.
Ref to GitHub: https://github.com/renovatebot/renovate/issues/48
=> refactor(renovate): update config to have one pr per week

.renovaterc.json
- Closes #1024 
The combination of different config snippets isn't really clear to me in the docs. This might be correct. What made me not "do it" at first was the global "groupName" which felt like one should be able to specify more than one of.
=> fix(renovate): config to not nest

packages/mc-html-template/README.md, packages/mc-html-template/lib/compile-html.js, packages/mc-html-template/lib/load-headers.js, packages/mc-http-server/bin/start-mc.js, packages/mc-scripts/compile-html.js, packages/mc-scripts/config/webpack-dev-server.config.js, playground/README.md, playground/csp.json, playground/headers.json, playground/package.json, playground/production-eu.csp.json, playground/production-eu.headers.json, playground/production-us.csp.json, playground/production-us.headers.json, website/content/deployment/example-aws-s3-cloudfront.mdx, website/content/deployment/example-firebase.mdx, website/content/deployment/example-now-v1.mdx, website/content/deployment/http-server.mdx, website/content/deployment/runtime-configuration.mdx
This pull request suggests to add the ability to add feature policies via the respective HTTP header.
Feature policies (as outlined [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy)) are a way to restrict what browser features an application should be able to request on a given "allow-list".
An example would be to:
1. Allow the microphone only to be used in the document
2. Allow geolocation in an iframe
Note that this also overlapps (the example of the iFrame) with CSPs.
In general I would suggest, for now, not to default feature policies as:
1. It should (likely can) be considered a breaking change was all of a sudden a custom app can't e.g. use the mic
2. The merging is a bit more complicated as zipping up a `connect-src` whitelist
If we want to support …
=> feat: add ability to specify feature policies

packages/mc-html-template/lib/load-headers.js
This pull request fixes an issue where the webpack-dev-server would not respect the new `--headers` option.
The `loadHeaders` are used from multiple parts: mc-http-server, webpack-dev-server etc. 
The `webpack-dev-server` passes both `cspPath` and `headersPath` as options 
https://github.com/commercetools/merchant-center-application-kit/blob/436cef0c9db8e67ed290068da6f2b9e0ed5705b1/packages/mc-scripts/config/webpack-dev-server.config.js#L12-L15
this is totally adequate cause it makes the transition backwards compatible. However the `loadHeaders` as a result does not not only have to check if `options.cspPath` is set but also if there is no `options.headersPath`. Otherwise the `headersPath` will never be picked up through webpack.
Loads of text for a few lines of changes :)
=> fix(mc-html-template): to load headers not from csp

packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
Not sure why it worked before, but when we're in the account section, the navbar does not fetch the menu data and therefore there is no data in the cache.
We should simply use the default `cache-first` policy here.
=> fix(app-shell): use default cache-first fetch policy for user account menu

packages/application-shell-connectors/src/components/application-context/application-context.tsx, packages/permissions/src/components/authorized/authorized.spec.tsx, packages/permissions/src/components/authorized/authorized.tsx, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts, packages/permissions/src/utils/has-permissions.ts
Reported the issue here: https://github.com/milesj/babel-plugin-typescript-to-proptypes/issues/23
=> fix: to avoid using Mapped Types as babel plugin does not properly generate prop-types

CONTRIBUTING.md, README.md, package.json, packages/actions-global/package.json, packages/application-components/package.json, packages/application-shell-connectors/package.json, packages/application-shell/package.json, packages/browser-history/package.json, packages/constants/package.json, packages/i18n/package.json, packages/l10n/package.json, packages/notifications/package.json, packages/permissions/package.json, packages/react-notifications/package.json, packages/sdk/package.json, packages/sentry/package.json, packages/url-utils/package.json, playground/README.md, rollup.config.js
After I [refactored Rollup](https://github.com/commercetools/nodejs/pull/1397) in the nodejs repo to build multiple outputs, I thought to do the same here.
Main benefits:
- faster build (_actually it varies a bit, I think it's more or less the same_ 😔 )
- simpler and centralized config (less boilerplate in the each `package.json`)
=> refactor(rollup): to build multiple bundles

packages/application-shell/src/utils/get-correlation-id/get-correlation-id.js, packages/application-shell/src/utils/get-correlation-id/get-correlation-id.spec.js
`X-Correlation-ID` header of requests sent to backend have to be -- quoting CT documentation -- "strings that may only contain alphanumeric characters, underscores and hyphens and have a length of 8 to 256 characters". 
`X-Correlation-ID` is being built using user-provided data (namely, projectKey). In case this data does not satisfies above-mentioned constraints, request fails with an error, describing malformed `correlation id`. This error, in turn is being reported to Sentry, which spoils FLD job. 
In order to avoid reporting this errors, this PR introduces `correlation id` sanitization. Original suggestion was to URL-encode provided `projectKey`, but that wont' work because, basically, `%` character would not pass `X-Correlation-ID` validation. 
Instead, we just gonna drop malformed …
=> fix(app-shell): sanitize correlation id parts

packages/application-components/src/components/modal-pages/internals/modal-page-header-title.tsx
The current style (with `& * + *`) doesn't work for cases where a user passed an element which will only render text without any wrapping HTML element tag (such as `FormattedMessage`), and would also break the style of any passed elements with more than one children.
The usage of `!important` could also be annoying in some cases.
This PR fixes this without breaking the current layout.
=> fix: modal page header title spacing

packages/application-shell/src/test-utils/test-utils.js, packages/application-shell/src/test-utils/test-utils.spec.js
this leads to tests failing when using 'LocalizedTextInput.createLocalizedString' because we pass the locales from the project and then in the test we check the locale the user chose.
=> data locale should be one of the project languages

.yarnrc
As you may know the older versions of yarn have a security vulnerability. Given that we now also use this version on dev machines and don't allow them to use their own there should be even more reason to keep is up-to-date.
=> chore: update yarn to 1.19.0 due to security vulnerability

packages/application-shell/package.json, packages/application-shell/src/components/performance-timing/measure-first-paint.js, packages/application-shell/src/components/performance-timing/measure-first-paint.spec.js, yarn.lock
Time to interactive is a metric which is not recommended anymore. It also is not exposed by most metric libraries as a result.
With this we use the First Input Delay which is said to reflect more what users experience. 
Before this is rolled out in our applications I will make sure our prometheus gateway is configured to consume it.
=> fix(app-shell): use first input delay

packages/permissions/src/components/authorized/authorized.spec.tsx, packages/permissions/src/components/authorized/authorized.tsx, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts, packages/permissions/src/utils/has-permissions.ts
If user has `*Manage` as their appliedPermissions, we simply discard dataFence since they would have permissions to manage orders, regardless what dataFence Permissions they have on their team.
This is because General Permissions overrules DataFence Permissions in the case of GeneralPermissions has `*Manage`
From an implementation POV, it doesn't look great that we "leak" appliedPermissions into `hasAppliedDataFence`, but I was not really sure how I want to ensure separate of concerns
=> feat(permissions): allow appliedPermission with Manage to bypass dataFence

packages/permissions/src/components/authorized/authorized.spec.tsx, packages/permissions/src/utils/has-permissions.ts
- use `startsWith` and `hasExactPermissions` for `hasAppliedDataFences`
previously I wrote this to use `hasManagePermission`. The issue is that `hasManagePermissions` returns a truth value if `demandedPermission` starts with `View*`. 
In the case of `hasAppliedDataFence`, we want to:
1. check if the demanded Permissions is `Manage*`
2. use `hasExactPermission` to `actualPermissions`
=> fix(permissions/has-permissions): use `hasExactPermission` in `hasAppliedDataFences`

CHANGELOG.md
- Let's release app-kit
The data-fence feature in MC is using the canary build right now
=> docs(changelog): add v15.1.8 [skip ci]

website/.percy.yml
This should help with the flaky website snapshots (hopefully).
=> fix(percy): to add idle timeout to allow assets to be properly loaded

packages/application-shell/package.json, yarn.lock
There was a bug with the `flags` argument in the ld adapter which I fixed. Want to have this in before people start using it. Verfied that it now works.
=> chore: update flopflip

packages/mc-http-server/server.js
This pull request comes after OPs intend to prefix request timing and application label metrics. Here we only have one request timing metric.
Why prefix? Cause cardinality explosions in Prometheus occur if you have a single, generically named metric, shared across services with lots of different labels. Promtheus can deal better with different metric names with similar labels. All due to its storage model. This all is aligned with best practices from the web and books.
Note, that by specifying two metrics here we expose both names and are backwards compatible for our dashboards. We can do the clean up after and expose just one.
=> chore(mc-http-server): to expose prefixed metric

CHANGELOG.md
Release for the `mc_` metrics prefix. To proceed in MC with it.
=> docs(changelog): for v15.2.2 [skip ci]

packages/i18n/data/core.json, packages/i18n/src/shared-messages.ts
add revert message to Form Modal button messages for use in MC-frontend in context of custom form controls, e.g.
`label={this.props.intl.formatMessage(FormModalPage.Intl.revert)}`
as a part of this ticket https://jira.commercetools.com/browse/PCM-1473
=> PCM-1473: add revert message to Form Modal button messages

packages/application-shell/src/components/performance-timing/measure-first-paint.js, packages/application-shell/src/components/performance-timing/measure-first-paint.spec.js
This pull request removes the first input delay tracking from the measure first paint component.
First input delay is triggered when the user typed for the first time. This is not really a metric we want to track here. Plus it prevents metrics being sent _until_ the user typed something the first time.
=> fix: remove first input delay

packages/jest-preset-mc-app/setup-tests.js
Ignore `CellMeasurerCache` warning when running jest tests on CI.
The following error is coming from ui-kit `Table` component and causes test failure on CI.
```
CellMeasurerCache should only measure a cell's width or height. You have configured CellMeasurerCache to measure both. This will result in poor performance.
```
=> test(setup-tests): ignore CellMeasurerCach warning

website/src/content/deployment/example-aws-s3-cloudfront.mdx
Replace "Merchant Center extensions" with "Merchant Center custom applications"
Replace "Merchant Center extensions" with "Merchant Center custom applications"
We no longer refer to these applications as "extensions". Updated with the new terminology.
=> Update description in cloudfront example

packages/application-shell/src/test-utils/test-utils.js, packages/application-shell/src/test-utils/test-utils.spec.js
Currently, it's not possible to use [rerender](https://testing-library.com/docs/react-testing-library/api#rerender). This PR fixes the issue.
When rendering using one of app-kit custom render functions, `renderApp`, `renderAppWithRedux` or `experimentalRenderAppWithRedux`, using `rerender` on the `rendered` result won't work and will result in errors.
**Why using rerender?**
Even though it's considered to be better to test the component updating the props instead of using `rerender`, we still need to be able to use it without errors when we want to.
> It'd probably be better if you test the component that's doing the prop updating to ensure that the props are being updated correctly (see the Guiding Principles section). That said, if you'd prefer to update the props of a rendered …
=> fix: cannot use rerender with app-kit custom render functions

packages/permissions/src/utils/has-permissions.spec.tsx, packages/permissions/src/utils/has-permissions.ts
As we are integrating dataFences more in the merchant center, we have encountered so far three use case: 
1- on the route level: check if the user has `manage` or `view` permissions in order to render the route. in this case, the demanded dataFence values are all always the `actualDataFenceValues`.
```
getSelectDataFenceData: () => ({ actualDataFenceValues }) =>
actualDataFenceValues || [],
```
2- for orders: we check if the `order.store.key` is inside the `acualDataFenceValues`:
```
const createSelectOrderDataFenceData = componentProps => demandedDataFence => {
switch (demandedDataFence.type) {
case 'store':
return componentProps.order.store?.key
? [componentProps.order.store.key]
: [];
default:
return null;
}
};
```
3- for customers. we also check if the `customer.stores` are inside …
=> refactor: only some subset of demanded DF values should belong to actual DF values

packages/application-shell/src/components/portals-container/portals-container.js
This PR fixes [the bug reported by Support](https://jira.commercetools.com/browse/SUPPORT-7309) about not being able to use the Tab key to navigate between elements when inside a Modal.
Apparently, the latest `react-modal` release now ignores focusing a Modal if its parent container doesn't have any `height` or `width`. See https://github.com/reactjs/react-modal/pull/774.
This PR simply adds a `height` to the `PortalsContainer` but keeping it hidden from sight, fixing the problem.
=> fix(app-shell): portal container height to fix tabbing in modals

CHANGELOG.md
Due to an network error during the last release not all packages got published. This intends to trigger a republish via `--force-publish=*`.
=> docs(changelog): for v15.4.2 [skip ci]

package.json
Same as https://github.com/commercetools/ui-kit/pull/1219.
> When doing a `yarn release`, if you forgot to log in to the `npm` CLI, lerna will still perform some of the steps but then fail on the `npm publish` process, resulting in dirty state (see https://github.com/lerna/lerna/issues/455).
> This PR prevents this problem by checking if the user is logged in to npm on the `prerelease` step.
=> chore: check npm authentication on prerelease

application-templates/starter/package.json, packages/application-components/package.json, packages/application-shell/package.json, packages/babel-preset-mc-app/index.js, packages/react-notifications/package.json, playground/package.json, visual-testing-app/package.json, website-components-playground/package.json, yarn.lock
In the react-intl upgrade PR the build works. Since the dep update of webpack it seems to fail. To stabalise master I propose to downgrade webpack in case this build passes.
=> chore: downgrade webpack

packages/application-shell/src/apollo-links/error-link.js, packages/application-shell/src/apollo-links/error-link.spec.js
Apparently the "apollo-link-retry" does not handle graphql errors, only network errors: https://www.apollographql.com/docs/link/links/retry/
We do want however to retry unauthenticated requests for graphql, to automatically refetch an access token as we do in the retry-link. 
I found this document that explains how to implement this use case: https://www.apollographql.com/docs/link/links/error/#retrying-failed-requests
=> fix(app-shell): retry unauthenticated requests for graphql errors

packages/actions-global/tsconfig.declarations.json, packages/application-components/tsconfig.declarations.json, packages/application-shell-connectors/tsconfig.declarations.json, packages/browser-history/tsconfig.declarations.json, packages/constants/tsconfig.declarations.json, packages/i18n/package.json, packages/i18n/tsconfig.declarations.json, packages/l10n/package.json, packages/l10n/tsconfig.declarations.json, packages/notifications/tsconfig.declarations.json, packages/permissions/tsconfig.declarations.json, packages/react-notifications/tsconfig.declarations.json, packages/sdk/tsconfig.declarations.json, packages/sentry/tsconfig.declarations.json, packages/url-utils/tsconfig.declarations.json
I noticed that the type declarations shipped with the packages were including all types from all packages, which is wrong:
Instead, only the type declarations of the related package should be built and shipped:
I think this has been "broken" since #1047
=> fix: building type declarations

packages/application-shell/src/test-utils/test-utils.js
By not initializing the reducer's accumulator we end up messing up the first value of the accumulated result.
=> fix(app-shell): denormalization of action rights

packages/actions-global/src/hooks/index.ts, packages/actions-global/src/hooks/use-hide-all-page-notifications.ts
This pull request adds a hook to hide all page notifications.
=> feat(actions-global): add use-hide-all-page-notifications

packages/mc-scripts/config/create-webpack-config-for-production.js
This pull request would allow us to opt out of parallel builds. E.g. when `proces.env.CIRCLE_CI` is true.
=> fix(mc-scripts): allowing to opt-out of parallel builds

CHANGELOG.md
The canary build shows that specifically the control over parallelism fixes the stability of our internal builds.
=> docs(changelog): for v15.7.0 [skip ci]

packages/babel-preset-mc-app/index.js, packages/babel-preset-mc-app/package.json, yarn.lock
With the latest release of babel some of the plugins we're still using are removable.
=> fix(babel-preset-mc-app): remove uncalled-for plugins

packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts, packages/permissions/src/utils/has-permissions.spec.tsx, packages/permissions/src/utils/has-permissions.ts
This pull request fixes an issue when a data fence is configured while the corresponding resource access permission should overwrite it.
This case is best described in ACs
```
In the permission configuration UI
Given I configure a resource access (e.g. orders) 
And I grant access to manage orders
Then any condition will be overruled by the general permission
```
```
Given I configure a resource access (e.g. orders)
And I grant access to view orders
Then I can add a condition for a specific store to allow managing orders in this store
```
 
In the evaluation of permissions
```
Given I configure a resource access (e.g. orders) 
And I grant access to manage orders
Then the condition will always gain precedence over the general permission
```
```
Given I configure a resource access to manage …
```
=> fix(permissions): data fences to be overwritten by manage resource permission

packages/babel-preset-mc-app/index.js, packages/babel-preset-mc-app/package.json, packages/jest-preset-mc-app/.gitignore, packages/jest-preset-mc-app/setup-tests.js, packages/permissions/package.json, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts, packages/permissions/src/utils/has-permissions.spec.tsx, packages/permissions/src/utils/has-permissions.ts, yarn.lock
This pull request iterates on observations and discusisons from the previous pull request by adding warnings to guide the user to a more appripriate usage of the permissions package.
There are some cases we seem to all agree on that they're dangerous:
1. Multiple demanded permissions: you can and should just use one and compose yourselr
2. `shouldMatchSomePermissions`: leads to unexpected behaviour when used with e.g. action rights and should be avoided
3. Multiple action rights: should also be avoided and multiple usages of the hook (or if used as HoC) should be preferred
4. Implied permissions: This should not happen when using a single demanded permission. Howeever, as we're only logging suggestions here I propsoe to inform the user about uncalled-for usage. So `['ManageOrders', …
=> chore(permissions): add warnings to propose improvements

packages/actions-global/package.json, packages/application-components/package.json, packages/application-shell-connectors/package.json, packages/application-shell/package.json, packages/assets/package.json, packages/babel-preset-mc-app/package.json, packages/browser-history/package.json, packages/constants/package.json, packages/create-mc-app/package.json, packages/eslint-config-mc-app/package.json, packages/i18n/package.json, packages/jest-preset-mc-app/package.json, packages/jest-stylelint-runner/package.json, packages/l10n/package.json, packages/mc-dev-authentication/package.json, packages/mc-html-template/package.json, packages/mc-http-server/package.json, packages/mc-scripts/package.json, packages/notifications/package.json, packages/permissions/package.json, packages/react-notifications/package.json, packages/sdk/package.json, packages/sentry/package.json, packages/url-utils/package.json
The `directory` field is for monorepo use cases (see https://docs.npmjs.com/files/package.json#repository)
=> chore: add homepage link and directory to each package.json

CHANGELOG.md
I started drafting the changelog for the v16 release
=> docs(changelog): for release v16.0.0 [skip ci]

packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.tsx, packages/application-components/src/components/dialogs/form-dialog/form-dialog.tsx, packages/application-components/src/components/dialogs/internals/dialog-footer.tsx, packages/application-components/src/components/modal-pages/custom-form-modal-page/custom-form-modal-page.tsx, packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.tsx, packages/application-components/src/components/modal-pages/info-modal-page/info-modal-page.tsx, packages/application-components/src/components/modal-pages/internals/default-form-buttons.tsx, packages/application-components/src/components/modal-pages/internals/modal-page-top-bar.tsx, packages/application-components/src/components/modal-pages/internals/modal-page.tsx, packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.tsx
The `MessageDescriptor` type imported from `react-intl` does not get parsed by the prop-types babel plugin because it's not "visible" within the file. For now, we need to explicitly define it.
Before:
After:
=> fix(components): explicitly define intl message type, to generate correct prop-types

packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/permissions/src/utils/has-permissions.spec.tsx, packages/permissions/src/utils/has-permissions.ts
This pull request fixes data fencing matching the inferred permission: view should be inferred by manage as with general permissions.
I went commit by commit and review should also be possible as such.
=> fix(permissions): to match inferred data fence (view when manage)

packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/application-shell/application-shell.tsx, packages/application-shell/src/components/quick-access/index.tsx, playground/src/components/state-machines-details/state-machines-details.js
I noticed that on the very first load of the page, where your localStorage is empty, the NavBar does not get rendered.
This is because the appshell does not render it when there is no "projectKey" in the URL.
However, when you open the MC at `/`, we then redirect you to a project `/:projectKey`.
The redirect works, but the part of the appshell where we read `selectProjectKeyFromUrl` does not re-render.
This PR adds a `useLocation` so that changes in the routes always cause a re-render.
=> fix(app-shell): to read project key from url again when location changes

package.json
TL;DR: canary releases only publish packages that changed in the last commit. This sometimes results in "broken" packages that refer to wrong versions, as multiple canary releases might not include the same package version.
See https://github.com/lerna/lerna/issues/2060
To ensure that each canary release is fully functioning, we can force all packages to be published.
=> fix: force canary releases to always publish all packages

packages/application-shell/src/components/navbar/navbar.tsx
`ApplicationMenu` expects `useFullRedirectsForLinks` https://github.com/commercetools/merchant-center-application-kit/blob/729b3104e952859521f27fd6f20eafabfca23973/packages/application-shell/src/components/navbar/navbar.tsx#L452 to let the menu items do a full redirect (so that the user gets redirected to the desired app )
But it's not passed https://github.com/commercetools/merchant-center-application-kit/blob/729b3104e952859521f27fd6f20eafabfca23973/packages/application-shell/src/components/navbar/navbar.tsx#L585
it was passed before here
https://github.com/commercetools/merchant-center-application-kit/pull/1069/files#diff-c897db78ece71d0d6d70adc9a40d41e4L776
=> fix(application-menu): pass `useFullRedirectsForLinks` to ApplicationMenu

.github/workflows/main.yml
This might help when we prepare a release changelog, as we don't need to run the workflow for those PRs.
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#example-ignoring-paths
=> chore(actions): skip workflow if CHANGELOG file changed

scripts/release_canary.sh
In #1311 we forced all packages to be published.
However, when commits do not contain any changes in packages, lerna tries to publish `null` versions.
This seems to be a known issue in lerna (https://github.com/lerna/lerna/issues/1769).
This PR attempts to fix that, by triggering the release only if lerna detects that packages have changed. For that, we can use the `lerna changed` command.
=> fix: publish canary only if lerna detects that packages changed

packages/application-shell/src/configure-apollo.ts, packages/application-shell/src/index.ts, packages/application-shell/src/utils/get-mc-api-url/get-mc-api-url.spec.js, packages/application-shell/src/utils/get-mc-api-url/get-mc-api-url.ts, packages/application-shell/src/utils/get-mc-api-url/index.ts, packages/application-shell/src/utils/index.ts, packages/sdk/src/middleware/client.ts, packages/sdk/src/utils/index.ts, packages/sdk/src/utils/utils.spec.ts, packages/sdk/src/utils/utils.ts
This pull request suggests to change building the `mcApiUrl` from the window's origin if no `mcApiUrl` is defined and the app runs behind the proxy.
Eventually the MC needs to be able to run on multiple hostnames (at least for some time). In GCP EU that means `https://mc-api.europe-west1.gcp.commercetools.com` and `https://mc-api.commercetools.com`.
This brings some challengens. Mainly around the cookie (yes cookie based auth ain't the best). 
```txt
Given you login on `mc.commercetools.com`
And your our app talks to `https://mc-api.europe-west1.gcp.commercetools.com` will log you out again
```
```txt
Given you login on `mc.europe-west1.gcp.commercetools.com`
And your our app talks to `https://mc-api.commercetools.com` will log you out again
```
This is rooted in the fact that the cookie …
=> refactor(app-shell): sdk and apollo to fallback to build `mcApiUrl` from origin

packages/application-shell/src/utils/gtm.ts
When iterating over the parents until reaching `document`, `parent.parentNode` will evaluate to `null`, and because of the `if` statement, the `parent` variable will never get assigned `null`, which will result in never breaking the `while` loop.
=> fix(tracking): infinite loop in getHierarchy

packages/application-shell/src/utils/get-mc-api-url/get-mc-api-url.spec.js, packages/application-shell/src/utils/get-mc-api-url/get-mc-api-url.ts, packages/sdk/src/utils/utils.spec.ts, packages/sdk/src/utils/utils.ts
Internally sometimes we run the MC on another origin than the underlying mc-api url requires (e.g. branch deployments). In this case we set this property `skipInferringOfApiUrlOnProduction`.
=> chore: add skipping of mc api url inferring process

CHANGELOG.md
Just so we have the changelog in sync without potential surprises.
=> docs: changelog to refer to v16.2.1 over v16.2.0

.github/workflows/main.yml
An attempt to fix this: https://github.com/commercetools/merchant-center-application-kit/pull/1332#issuecomment-585718980
=> fix(actions): kill server process running the app on port 3001 between cypress runs

packages/actions-global/package.json, packages/actions-global/src/actions/handle-action-error.ts, packages/actions-global/src/hooks/use-hide-all-page-notifications.ts, packages/actions-global/src/hooks/use-on-action-error.spec.tsx, packages/actions-global/src/hooks/use-on-action-error.ts, packages/actions-global/src/hooks/use-show-api-error-notification.ts, packages/actions-global/src/hooks/use-show-notification.ts, packages/actions-global/src/hooks/use-show-unexpected-error-notification.ts
`useOnActionError` implementation looks wrong to me. [This doc](https://github.com/commercetools/merchant-center-application-kit/blob/master/website/src/content/development/testing.mdx) supports my feelings that its current API is not what was actually desired. So, here is the fix.
Old (wrong) API:
```js
const error = new Error();
const onActionError = useOnActionError(error);
...
// error happened here
onActionError();
```
New (fixed) API:
```js
const onActionError = useOnActionError();
...
// error happened here
const error = new Error();
onActionError(error);
```
=> fix(actions-global): method signature of useOnActionError

.renovaterc.json
Reverts commercetools/merchant-center-application-kit#1345
This does not seem to be the issue with the dep updates.
https://github.com/commercetools/merchant-center-application-kit/pull/1342#issuecomment-587037365
=> Revert "chore: ignore ts-jest updates (for now)"

website/src/content/deployment/runtime-configuration.mdx, website/src/content/main-concepts/api-gateway.mdx
Closes #1343 
This PR aims to clarify how to configure the CSP directives, especially around the new hostnames.
=> docs(website): improve docs around csp and cloud regions

packages/application-shell/src/apollo-links/token-retry-link.spec.js, packages/application-shell/src/apollo-links/token-retry-link.ts
Ref #1352 
This pull request starts triggering token refetching on requests against the settings service. 
The assumption is that the first request in the custom application after x days is made against the settings service. This service then validates the CTP token using token introspection and detects that it is expired. Rejecting the request as unauthorized (rightfully).
=> fix(app-shell): token refetch triggerd by requests from settings service

packages/mc-scripts/config/webpack-dev-server.config.js
I noticed that the webpack dev server was throwing when starting
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
at validateString (internal/validators.js:112:11)
at Object.join (path.js:1040:7)
at noopServiceWorkerMiddleware
```
The dev server in react-scripts uses the noop service worker middleware in the `after` hook, which we don't use and we can simply remove it.
https://github.com/facebook/create-react-app/blob/2030ee162df0ca8f19efedcf0447e02613e2f53d/packages/react-scripts/config/webpackDevServer.config.js#L126-L136
=> fix(mc-scripts): remove noop service worker middleware from webpack dev server

packages/sdk/package.json, packages/sdk/src/test-utils/test-utils.spec.ts, packages/sdk/src/test-utils/test-utils.ts, yarn.lock
Properly print SDK actions containing fields with `undefined` as a value in a test output.  
Whenever `testMiddleware` fails to match an action against a list of provided mocks, it pretty-prints both an action and a list. The problem thought, is that in this pretty-printed version `undefined` values will be replaced with `null`, due to the reason that default JSON serializer drops `undefined` fields as being non-deserializable.
This may lead to a following situation. Imaging having the action and the mocks like this (the data shapes are invalid, but simplified for brevity reasons) :
```js
const action = { foo: undefined };
const mocksSdk = [{ action: { foo: null }, response: 'ok'}]; 
```
Running a test with this input will lead to failure to match action against mock (which is right), but …
=> fix(sdk/test-utils): serialize `undefined` as `undefined`

packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx, packages/application-shell-connectors/src/components/application-context/application-context.tsx, packages/application-shell-connectors/src/utils/get-mc-api-url/get-mc-api-url.spec.js, packages/application-shell-connectors/src/utils/get-mc-api-url/get-mc-api-url.ts, packages/application-shell-connectors/src/utils/get-mc-api-url/index.ts, packages/constants/src/constants.ts
> I closed the previous PR and opened another one cause this affects another package.
Please refer to https://github.com/commercetools/merchant-center-application-kit/pull/1367 for a more detailed reasoning.
Instead of exporting the function we patch the environment.
Note, that we can't export the function from the application-shell so we duplicate it again.
A third option is to overwrite/patch the window itself upon read/boot but I don't think that's really nice.
=> bug(app-shell-connectors): path mcApiUrl on context env

packages/jest-preset-mc-app/setup-tests.js
Library code uses createFactory which in turn will trigger throwing in our tests. Either we don't adopt the latest React version of we log the error instead of throwing it. When it is actually removed we truely need to make sure no library code uses it.
=> fix(jest-preset): to not throw on createFactory

packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts
This pull request aims to reduce the number of warnings we receive from the permissions package and the useIsAuthorized hook.
We could like to inform users and ourselves whenever we don't use the permissions package/api as recommended. In some cases we internally might even have to use a non-recommneded path but that should not eliminate that there is a recommended way.
To reduce the amount of warnings there are multiple ways:
1. Use a `once` function from lodash and create a cached callback only invoked once
- A bit non-React hooky I would argue
- Hard to trigger per incorrect usage
2. Use a `hasWarningFired` value and not warn again
- Requires setting the value creating quite imparative code
3. Using useEffect or useCallback
I decided to use an effect. A warning can be seen as an effect …
=> fix(permissions): to warn only once for condition and message

packages/mc-dev-authentication/views/login.pug
Made a one line change to have the tokens endpoint built in `mc-dev-authentication/views/login.pug` ignore any trailing slashes that are part of the mcApiUrl environment variable.  This should prevent unnecessary authentication failures when this variable has been adjusted for location.
* Adjusting the mcApiUrl environment variable in the dashboard application to a value with a trailing slash to represent a different location for the merchant-center-frontend causes the dev authentication view to build an invalid path for the tokens endpoint with two slashes side by side.
* The tokens endpoint builder ignores any trailing slashes that would prevent a local developer from proceeding through the authentication flow.
No technical debt is introduced by this minimal change.
cc: @emmenko
=> fix(dev authentication): replace trailing slash in mcApiUrl

packages/application-shell/src/components/navbar/navbar.tsx, packages/application-shell/src/components/navbar/use-navbar-state-manager.ts
The menu divider seems to have disappeared in the recent appkit versions, probably after the TS migration #1273 
You can see below that in older versions of appkit (like from the custom app) the divider is still there, but not on production.
=> fix(app-shell): regression to render menu divider

packages/application-shell/src/components/quick-access/quick-access.tsx
In which routing to Product Variant Details from the quick access is redirecting to the incorrect page in both instances. Fixed by correcting the string for the route
=> PCM-1600: routes to product varitns from quick access

application-templates/starter/src/components/main-view/main-view.spec.js, packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx, packages/application-shell/src/components/application-shell-provider/application-shell-provider.spec.js, packages/application-shell/src/components/fetch-project/fetch-project.spec.js, packages/application-shell/src/components/fetch-user/fetch-user.spec.js, packages/application-shell/src/components/inject-reducers/inject-reducers.spec.js, packages/application-shell/src/components/project-data-locale/project-data-locale.spec.js, packages/application-shell/src/components/project-switcher/project-switcher.spec.tsx, packages/application-shell/src/components/route-catch-all/route-catch-all.spec.js, packages/application-shell/src/components/service-page-project-switcher/service-page-project-switcher.spec.js, packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.spec.js, packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx, packages/react-notifications/src/components/notifications-list/notifications-list.spec.tsx, packages/react-notifications/src/components/notifier/notifier.spec.tsx, playground/src/components/state-machines-list/state-machines-list.spec.js
This uses the new findBy API. The other dep update PR is blocked by this. I just want to extract this out of a dependency update where possible.
=> refactor: to not use wait-for-element

packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.spec.tsx, packages/application-components/src/components/dialogs/form-dialog/form-dialog.spec.tsx, packages/application-components/src/components/dialogs/info-dialog/info-dialog.spec.tsx, packages/application-shell/src/components/application-loader/application-loader.spec.js, packages/application-shell/src/components/application-shell-provider/application-shell-provider.spec.js, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/authenticated/authenticated.spec.tsx, packages/application-shell/src/components/back-to-project/back-to-project.spec.tsx, packages/application-shell/src/components/gtm-application-tracker/gtm-application-tracker.spec.js, packages/application-shell/src/components/gtm-booter/gtm-booter.spec.tsx, packages/application-shell/src/components/gtm-user-logout-tracker/gtm-user-logout-tracker.spec.js, packages/application-shell/src/components/gtm-user-tracker/gtm-user-tracker.spec.js, packages/application-shell/src/components/project-suspended/project-suspended.spec.js, packages/application-shell/src/components/project-switcher/project-switcher.spec.tsx, packages/application-shell/src/components/quick-access/quick-access.spec.js, packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.spec.tsx, packages/application-shell/src/components/requests-in-flight-loader/requests-in-flight-loader.spec.tsx, packages/application-shell/src/components/route-catch-all/route-catch-all.spec.js, packages/application-shell/src/components/service-page-project-switcher/service-page-project-switcher.spec.js, packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js, packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.spec.js, packages/application-shell/src/hooks/use-applications-menu/use-applications-menu.spec.tsx, packages/application-shell/src/test-utils/test-utils.spec.tsx, packages/i18n/src/async-locale-data/async-locale-data.spec.tsx, packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.spec.tsx, packages/react-notifications/src/components/notifier/notifier.spec.tsx, playground/src/components/state-machines-list/state-machines-list.spec.js
The path to react-testing-library/{react,dom} on the latest versions is quite a bit of effort.
In this pull request I tackle:
1. wait to be waitFor
2. waitForElementToBeRemoved where possible
3. Clean up some tests which are just... confusing
In the process I renamed imports from wait to waitFor. This is trick to get the dependency update PR in the end to be lean by just renaming the import again.
=> refactor: to use waitFor and waitForElementToBeRemoved

packages/application-shell/src/components/quick-access/quick-access.spec.js
I noticed when updating the JSDOM v16 that this one is missing.
=> fix(quick-access): to not use global.replace under test

packages/jest-preset-mc-app/jest-preset-for-jsdom-sixteen.js, packages/jest-preset-mc-app/package.json, yarn.lock
This pull request suggests adding a jest preset for jsdom v16. 
There are multiple ways of doing this:
1. Change the existing presets to jsdom v16 (typescript and default)
- Definately breaking. Decided against it as jest by default also still uses the old version. Should be a separate step I think.
2. Adding another preset
- Not breaking as people can just consume it as opt-in
Some things to note:
1. I would like to change the TypeScript template to v16 but that would also be breaking
2. I feel like we should have a better way of merging presets e.g.
```js
const { defaultPreset, typeScriptPreset } = require('@commercetools-frontend/jest-reset-mc-app');
module.exports = defaultPreset.extend({
testEnvironment: 'jest-environment-jsdom-sixteen'
});
// or
module.exports = defaultPreset.use(); …
```
=> feat(jest-preset): add preset for jsdom sixteen

packages/jest-preset-mc-app/package.json, packages/jest-preset-mc-app/setup-tests.js, yarn.lock
This pull request adds the mutation-observer-shim to our jest preset.
The preset was removed within dom-testing-library v7. The library itself recommends adding it or using jsdom v16 (which contains it). We offer a preset for jsdom v16 but should patch out regular preset to include the shim so it works with dom-testing-library v7
Note, that dom-testing-library used this shim itself. Adding it on older dom-testing-library versions (overwriting it) on the window should not be an issue.
=> fix(jest-preset-mc-app): add mutation-observer-shim

packages/application-shell/src/components/route-catch-all/route-catch-all.tsx, packages/application-shell/src/utils/location/location.ts
`utils/location/replace` method invokes `window.location.replace` with a wrong `this` value, which lead to an error when navigation between apps:
This PR fixes that.
=> fix: proper invocation of window.location.replace

packages/sentry/src/sentry.spec.ts, packages/sentry/src/sentry.ts
At the moment we observe following uninformative reports in our Sentry instance:
That's happening because `PromiseRejectionEvent` and `ErrorEvent` captured by AppShell's global error handlers are passed to `Sentry.captureException` unmodified, whereas the latter expects instance of an `Error`.
This PR implements wrapping error events into `Error`s inside `reportErrorToSentry` before sending them to `Sentry`. Also default `Sentry`s reporting of unhandled rejections and global errors is disabled, to prevent double-reporting.
The better option, probably, is to rely on `Sentry`'s default reporting of unhandled rejections and remove our custom global handlers, but that will prevent us from showing error_id to users in MC in case of unhandled rejections. So that's probably a subject for a …
=> Properly report unhandled rejections and ErrorEvents to Sentry

CHANGELOG.md
I think somewhat a 14 day release cycle the least can be nice. It's about time :)
=> docs(changelog): update for v16.6.0 [skip ci]

packages/application-shell/src/test-utils/test-utils.tsx
This pull request fixes act warning when testing through the test-utils without flags with recent versions of flopflip.
flopflip and its adapters are inherently async. They integrate with LaunchDarkly APIs or poll from local-storage. So that all adapters have the same API even the memory-adapter's configure/reconfigure are async functions.
This comes with some "drawbacks" when testing with them. Given you test a small component without flags while using `getBy*` or `queryBy*` you are likely to get act warnings. These originate from the fact that your test passes, all components (by rtl) are unmounted while flopflip's async configuration is not finished. It then finishes _after_ your test is over yielding an act warning. This realisation took some time for me 😄.
This gives us multiple …
=> fix(app-shell/test-utils): to defer adapter initialization without flags

packages/application-shell/src/components/navbar/navbar.tsx, packages/application-shell/src/components/navbar/use-initial-forced-menu-state.ts, packages/application-shell/src/components/navbar/use-loading-menu-layout-effect.ts, packages/application-shell/src/components/navbar/use-navbar-state-manager.ts
- update the DOM immediately when `STORAGE_KEYS.IS_FORCED_MENU_OPEN=true`
We have `use-navbar-state-manager` to determine the state of the menu as the user loads the application. An issue within the state manager, is that we wait for the reducer to execute actions to determine the state.
This defers the experience of having the menu open _immediately_ when the user loads the application
For example
**Proposed solution**
Update the dom immediately, before the reducer executes action.
trade off, [this code](https://github.com/commercetools/merchant-center-application-kit/blob/adnasa-use-navbar-state-manage-flick-thousand-cuts/packages/application-shell/src/components/navbar/use-navbar-state-manager.ts#L178-L188) will no longer execute. I however decided to keep it, since I'm unsure about …
=> fix(app-shell): apply cached menu state synchronously as a layout effect, to avoid flickering

CHANGELOG.md
- adds changelog
locally I still get this
is something up with my setup?
```
packages/sentry/src/sentry.spec.ts:39:7 - error TS2322: Type 'new (options: TransportOptions) => Transport' is not assignable to type 'TransportClass<Transport>'.
Construct signature return types 'Transport' and 'Transport' are incompatible.
The types of 'sendEvent' are incompatible between these types.
Type '(event: import("/Users/adnasa/workspace/repos/merchant-center-application-kit/node_modules/@sentry/types/dist/event").Event) => PromiseLike<import("/Users/adnasa/workspace/repos/merchant-center-application-kit/node_modules/@sentry/types/dist/response").Response>' is not assignable to type '(event: import("/Users/adnasa/workspace/repos/merchant-center-application-kit/node_modules/@sentry/browser/node_modules/@ …
```
=> chore(changelog): add 16.6.1

packages-backend/express/README.md, packages-backend/express/src/auth.ts, packages-backend/express/src/index.ts, packages-backend/express/src/middlewares/session-middleware.spec.ts, packages-backend/express/src/middlewares/session-middleware.ts, packages-backend/express/src/types.ts
To better support the usage in serverless functions, I extracted the core logic into a `createSessionAuthVerifier`, which only requires `req, res` to be passed.
The middleware then is just a wrapper for express.
=> refactor(express): support request handler for serverless functions

packages-backend/express/README.md, packages-backend/express/src/auth.ts, packages-backend/express/src/constants.ts, packages-backend/express/src/middlewares/session-middleware.spec.ts, packages-backend/express/src/types.ts, packages-backend/express/src/utils.ts
In order to allow a non-breaking migration to v2, the middleware should handle the legacy hostnames when processing the request, based on a custom header sent by the MC API with the forwarded request.
=> refactor(express): support backwards compatibility for v1

packages/mc-html-template/lib/load-env.js, packages/mc-html-template/lib/load-headers.js, packages/mc-html-template/lib/utils/substitute-env-variable-placeholders.js, packages/mc-html-template/lib/utils/substitute-env-variable-placeholders.spec.js, website/src/content/deployment/runtime-configuration.mdx
Same as for the `env.json`, we should also support it for `headers.json`.
=> feat(headers.json): add support for env variable placeholders

packages/application-shell/src/apollo-links/header-link.ts, packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.ts, packages/application-shell/src/hooks/use-applications-menu/use-applications-menu.ts, packages/application-shell/src/index.ts, packages/application-shell/src/utils/apollo-context.ts, packages/application-shell/src/utils/index.ts, packages/sdk/README.md, packages/sdk/src/actions/actions.ts, website/src/content/main-concepts/data-fetching.mdx
This PR continues the improvements to work with the endpoint `/proxy/forward-to`.
The idea here is to allow users to keep using apollo graphql and our sdk action creators to make HTTP requests to their external API, without having to provide all the necessary configuration changes.
We can leverage the `context` option for Apollo queries to change a bit how the request is configured. The app-shell package now exposes an utility function to configure the Apollo context for the `/proxy/forward-to` usage.
```js
import { useQuery } from 'react-apollo';
import { createApolloContextForProxyForwardTo } from '@commercetools-frontend/application-shell';
const Fetcher = () => {
const { loading, data, error } = useQuery(MyQuery, {
context: createApolloContextForProxyForwardTo({
uri: …
```
=> feat: support forwardTo request config for apollo and sdk

packages-backend/express/index.ts, playground/config/transformer-now.js, playground/env.json, playground/menu.json, playground/now-deployments/state-machines-gcp-eu/api/echo.ts, playground/now-deployments/state-machines-gcp-eu/package.json, playground/now-deployments/state-machines-gcp-us/api/echo.ts, playground/now-deployments/state-machines-gcp-us/package.json, playground/package.json, playground/src/components/echo-server/echo-server.js, playground/src/components/echo-server/index.js, playground/src/routes.js, yarn.lock
Adds an echo server to the playground app (deployed on ZEIT). The serverless function uses the new "middleware" to authenticate the request.
The playground app then has a new page to demo the connection.
=> feat(playground): implement echo server view/api to demo /proxy/forward-to feature

.github/workflows/main.yml
Sometimes canary builds fail, so we should keep the publish step as the last one
=> chore(ci): keep publish to npm as last step

packages/application-shell-connectors/src/components/application-context/application-context.tsx, packages/application-shell-connectors/src/components/application-context/normalizers.ts, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts, packages/permissions/src/utils/has-permissions.ts
- refactored `DataFences` to use `Record`
I read up about `Record` and was curious about its use case. ref https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkt
This seemed a really awesome utility type and I could see that there is application for it.
For dataFences, we know that for each `key` in `DataFences` should represent a type (e.g `store`) and with that type have a specific shape, a group of resource type.
namely the following:
```
{
[<dataFenceType]: {
[<resourceType>]: {
[<permissionName>]: {
values: string[]
}
}
}
}
```
I doubt that the dataFence model will change (at least for a while). we can use `Record` to solidify this domain constraint within the code.
=> refactor(permissions): use Record for dataFences

packages/mc-html-template/package.json, packages/mc-scripts/package.json
Given that in #1471 we fixed the runtime helpers config, we should do the same here.
=> fix(babel): keep runtime helpers

packages-backend/loggers/src/formatters/rewrite-fields.ts, packages-backend/loggers/src/loggers.spec.ts
The generic type introduced in #1478 does not really work, because you can pass multiple fields with potentially different value types.
So I think we need to keep it `unknown` and the consumer will need to type cast.
=> refactor(loggers): remove generic type, as it doesn't really work as expected

.changeset/shiny-colts-eat.md, packages/mc-html-template/package.json, packages/mc-scripts/package.json
=> fix(mc-html-template): missing babel runtime dep

.changeset/calm-cats-drum.md, packages/mc-dev-authentication/views/logout.pug
The mc-dev-authentication is a temporary package. However, the fact that the link to `/login` does not preseve the query params is frustration. Especially with current work on the hostname migration where I would like to preserve the `redirectTo`.
This change has been tested locally.
=> Fix mc-dev-authentication's /login link keeping query params

.changeset/soft-beans-deliver.md, application-templates/starter/package.json
Closes #1494 
This is a peer dependency of react-apollo and causes the starter to not start.
=> Fix starter to have `apollo-client` as dependency

.changeset/tasty-beers-compete.md, package.json, packages-backend/loggers/src/index.ts, yarn.lock
This pull request attempts to update to TypeScript 3.9. I had to exclude it earlier today.
I haven't found the root of the issue but it seems in external types. Also the release notes do not mention something directly. Only around relating "exports" areas.
=> refactor: update to typescript 3.9

.github/workflows/publish-cloud-registry.yml, .github/workflows/release.yml
This is an attempt to fix the issue with the cloud registry workflow not being triggered when a tag is created through another workflow.
From the information that I could find, it seems that this restriction can be lifted by using a personal access token.
Let's see if this makes a difference or not.
=> fix(workflows): use a personal access token in checkout step, to allow the workflow to trigger a new workflow

.changeset/little-badgers-cough.md
The previous release failed. I will have this PR to create a new release with a patch changeset.
=> chore: empty commit for triggering mc-http-server release

.changeset/polite-camels-tap.md, packages/application-shell/src/components/project-suspended/project-suspended.spec.js, packages/i18n/README.md, packages/i18n/src/async-locale-data/async-locale-data.spec.tsx, packages/i18n/src/async-locale-data/async-locale-data.tsx, packages/i18n/src/async-locale-data/index.ts, packages/i18n/src/async-locale-data/use-async-intl-messages.ts, packages/i18n/src/index.ts, website-components-playground/src/components/intl-controller.js
- expose a `useAsyncLocaleData` hook. The `<AsyncLocaleData>` component now uses the hook internally.
- expose a `useAsyncIntlMessages` hook, to only load messages with dynamic imports (code splitting).
The second hook is useful for building UI packages (not custom apps) that ship with translations. The translation message should be encapsulated with the package itself and ideally they should be code splitted as well.
The UI package then can use a `IntlProvider` (which will be nested when used within a Custom Application) to load the messages of the package itself.
The `IntlProvider` then merges the messages with the "parent(s)" providers.
=> refactor(i18n): expose hook for AsyncLocaleData

.changeset/slow-comics-grin.md, .renovaterc.json, application-templates/starter/package.json, package.json, packages/application-components/package.json, packages/application-shell/package.json, packages/react-notifications/package.json, playground/package.json, visual-testing-app/package.json, website-components-playground/package.json, website/package.json, yarn.lock
I tried things locally and I didn't get any error this time. So maybe "it just works" now?
Eventually, we can also remove `babel-plugin-macros`. I don't know of any use case we have that require the macro plugin.
=> chore: ugrade to react-intl v4

.changeset/cool-geckos-know.md, packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx, packages/application-shell-connectors/src/components/application-context/application-context.tsx, packages/application-shell-connectors/src/components/application-context/normalizers.spec.ts, packages/application-shell-connectors/src/types/generated/mc.ts, packages/application-shell/src/components/fetch-project/fetch-project.mc.graphql, packages/application-shell/src/components/quick-access/quick-access.spec.js, packages/application-shell/src/test-utils/test-utils.spec.tsx, packages/application-shell/src/test-utils/test-utils.tsx, packages/application-shell/src/types/generated/mc.ts, packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx, packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.spec.tsx, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx
This pull request adds fetching the owner's name which is the organization through the project.
This will help more easily redirect SSO users to `login/sso/<orgName>` without the application having to fetch data. Overall the addition of owner.name feels small given we already load the id.
=> feat(app-shell): fetch organization name with owner

.github/workflows/release.yml
The new shapshot feature got released recently. I tried that in a personal project and it works.
=> refactor(release): publish canary using changeset snapshot feature

.changeset/dry-cars-kiss.md, packages/eslint-config-mc-app/index.js
As a developer, I want to be notified when I'm defining a proptype that is not used in my component (similar to when I get notified when there are unused variables). This is very useful during refactoring, where I don't want to manually check whether a proptype is used.
Checking unused proptypes is done manually by the developer.
Checking unused proptypes is done automatically by eslint [`react/no-unused-prop-types`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unused-prop-types.md) rule.
=> build(eslint): enable react/no-unused-prop-types rule

.changeset/slimy-grapes-joke.md, cypress/integration/playground/application-shell.js, packages/application-shell/src/components/user-settings-menu/messages.ts, packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js, packages/application-shell/src/components/user-settings-menu/user-settings-menu.tsx, packages/i18n/data/core.json
This pull request fixes the user settings menu labels to be translated and custom named.
Downshift's default naming of the `aria-label` is `open menu` and `close menu`. The library recommends to pass an own tranlation of this label
This then allows us to use better selectors and also one which would not break with a second Downshift dropdown on the page.
Note, that updating the tests and using the new labels prooves that this works.
=> fix(app-shell): user settings menu labels for opening and closing menu

.changeset/happy-donuts-jam.md, cypress/integration/playground/application-shell.js, packages/application-shell/src/components/user-settings-menu/user-settings-menu.tsx
This pull request fixes the with of the `<a />` within the user settings menu. 
The DOM structure of elements within the user settings is sort of like `div > div > div > a > TextNode` while the parent `div` has an adequate with the `a` within it has a computed height and width of 0.
This is not acessible and also not nicely testable through Cypress. Cypress will not allow the click the element by `findByRole('link', { name: /logout/i })` as the `a` (link) itself has a height and width of 0 and is not clickable as a result. This forces us to use `findByText` which is suboptimal. Any other text on the page with `logout` would break the test if the selector wasn't scoped. Moreover, Cypress is right that the element has a wrong width and height.
The solution is to make the `a` an …
=> fix(app-shell): user settings menu link width for testing

.changeset/empty-beers-reflect.md, package.json, packages/eslint-config-mc-app/index.js, yarn.lock
This pull request adds the jest-dom plugin to our eslint config.
Similar to our prior PR [here](https://github.com/commercetools/merchant-center-application-kit/pull/1570/files) we add another ESLint plugin.
The [eslint-plugin-jest-dom](https://github.com/testing-library/eslint-plugin-jest-dom) helps to use the right expectations towards checked, enabled state of DOM nodes etc.
=> feat(eslint-config-mc-app): to add jest-dom plugin

.changeset/quick-tools-wash.md, packages/application-components/src/components/maintenance-page-layout/README.md, packages/application-components/src/components/maintenance-page-layout/maintenance-page-layout.spec.tsx, packages/application-components/src/components/maintenance-page-layout/maintenance-page-layout.tsx, packages/application-components/src/components/page-not-found/page-not-found.tsx, packages/application-shell/src/components/application-shell-provider/application-shell-provider.spec.js, packages/application-shell/src/components/error-apologizer/error-apologizer.tsx, packages/application-shell/src/components/failed-authentication/failed-authentication.tsx, packages/application-shell/src/components/project-expired/project-expired.tsx, packages/application-shell/src/components/project-not-found/project-not-found.tsx, packages/application-shell/src/components/project-not-initialized/project-not-initialized.tsx, packages/application-shell/src/components/project-suspended/project-suspended.tsx
This pull request adds a label which is used on the images alt to all maintenance pages.
Our maintenance pages mostly have: title, two paragraphs and an image. The image itself however doesn't contain any alt text. It would be good to mostly use the `title` as the alt text on the image. 
This also eases querying for the image with `byRole('img', { name: //i })` under test.
I had multiple solution in mind when working on this:
1. Add a optional string of `label` which goes to the `img` alt. The `img` `alt` needs to be a string and can't be React.Node
2. Just use the `title` and pass it as the `alt`. Slighly less flexible but less noisy for consumers. However, the `title` is an React.Node as it's a FormattedMessage while the `alt` needs a string.
3. Refactor everything to just accept …
=> feat(app-shell): to add label to maintenance page layouts

.changeset/six-pillows-share.md, packages/jest-preset-mc-app/setup-test-framework.js
This pull request adds the abilty to configure react-testing-library.
The `react-testing-library` allows a custom configuration which it itself uses and exports from `dom-testing-library`.
This can be useful to configure timeouts for `findBy*` queries which can run slow on CI among other things
More information on configuration of the library can be found [here](https://testing-library.com/docs/nightwatch-testing-library/intro#configure).
=> feat(jest-preset-mc-app): add config for rtl

.changeset/great-otters-clean.md, .changeset/metal-meals-compete.md, application-templates/starter/package.json, packages/application-components/src/components/page-unauthorized/README.md, packages/application-components/src/components/page-unauthorized/index.ts, packages/application-components/src/components/page-unauthorized/messages.ts, packages/application-components/src/components/page-unauthorized/page-unauthorized.spec.tsx, packages/application-components/src/components/page-unauthorized/page-unauthorized.tsx, packages/application-components/src/index.ts, packages/jest-preset-mc-app/CHANGELOG.md, packages/jest-preset-mc-app/package.json, visual-testing-app/src/components/page-unauthorized/page-unauthorized.visualroute.tsx, visual-testing-app/src/components/page-unauthorized/page-unauthorized.visualspec.ts
This PR migrates the PageUnauthorized component from Merchant Center to Application Kit. It can be used for informing user they don't have permissions for certain resources in Merchant Center applications
=> refactor(appkit): migrate PageUnauthorized component to AppKit

.kodiak.toml
In [this issue](https://github.com/chdsbd/kodiak/issues/437) I proposed that Kodiak would change it's wording from `blacklist_*` to `denylist`. 
They now adopted the wording of `blocking_*`. The documentation PR is pending [here](https://github.com/chdsbd/kodiak/pull/454) while the change is already merged [here](https://github.com/chdsbd/kodiak/pull/444).
The deployment and deployment of Kodiak were done. I contacted them to make sure.
The documentation can also be found [here](https://kodiakhq.com/docs/config-reference#mergeblocking_title_regex).
=> fix(kodiak): to use blocking wording not blacklist

.changeset/chilled-kiwis-pretend.md, packages/babel-preset-mc-app/index.js, packages/babel-preset-mc-app/package.json
This pull request suggests to add the logical assignment operator to our babel config.
The logical assignment operator [TC39 proporal](https://github.com/tc39/proposal-logical-assignment) can help us when assignment optional values based on a condition. 
A simple use case is:
```js
a ||= b;
obj.a.b ||= c;
a &&= b;
obj.a.b &&= c;
```
More real world would be
```js
const books = [
{
isbn: '123',
},
{
title: 'ECMAScript Language Specification',
isbn: '456',
},
];
// Add property .title where it’s missing
for (const book of books) {
book.title ??= '(Untitled)';
}
```
I think in general we have cases internally where we assign values if they're not assigned yet through ternaries. These case could be simplified through this.
1. https://2ality.com/2020/06/logical-assignment-operators.html
2. …
=> feat(babel-preset-mc-app): add logical assignment operator

.changeset/three-bikes-attack.md, packages/application-config/README.md, packages/application-config/schema.json, website/.gitignore, website/package.json, website/scripts/postbuild.sh, website/scripts/prebuild.sh, website/src/content/development/application-config.mdx, website/src/releases/2020-07/application-config.mdx
Unfortunately using the unpkg URL doesn't work from VSCode, because the HTTP redirects are not followed.
The HTTP redirects occur because the URL https://unpkg.com/@commercetools-frontend/application-config/schema.json gets resolved by the latest published version.
After some thoughts I think the better option to host the JSON schema is to put it in the docs website.
=> fix(config): get JSON schema from website docs URL

.changeset/polite-taxis-shop.md, LICENSE, packages/actions-global/LICENSE, packages/application-shell-connectors/LICENSE, packages/application-shell/LICENSE, packages/assets/LICENSE, packages/babel-preset-mc-app/LICENSE, packages/browser-history/LICENSE, packages/constants/LICENSE, packages/create-mc-app/LICENSE, packages/eslint-config-mc-app/LICENSE, packages/i18n/LICENSE, packages/jest-preset-mc-app/LICENSE, packages/l10n/LICENSE, packages/mc-html-template/LICENSE, packages/mc-http-server/LICENSE, packages/mc-scripts/LICENSE, packages/notifications/LICENSE, packages/permissions/LICENSE, packages/react-notifications/LICENSE, packages/sdk/LICENSE, packages/sentry/LICENSE, packages/url-utils/LICENSE
Just a small chance to trigger a release and test the workflow triggers for the http-server when using the personal access token (https://github.com/commercetools/merchant-center-application-kit/commit/e1fb17138b53ecf96e863ae6a8f56d048d5ce85e)
=> chore: update copyright date to 2020 in LICENSE files

.changeset/tough-pears-join.md, .github/workflows/publish-cloud-registry.yml, packages/application-config/src/utils.ts, packages/application-config/test/process-config.spec.js
TL;DR: in case the `MC_APP_ENV` is defined, we consider that it's a production environment unless it's one of `development` or `test`. This allows to use for example the `staging` value, which from the application perspective is still considered a production environment.
=> refactor(config): to be more strict on deriving the prod env based on the MC_APP_ENV

.github/workflows/publish-cloud-registry.yml
I've been trying to find out more info about the proper trigger for the google cloud registry workflow.
I think we've been using the "wrong" trigger `on.push.tags`, because the release bot uses the `createRelease` function (https://github.com/changesets/action/blob/bfeb9e077e6cf393e4c4ef17e2bbc75b308b4364/src/run.ts#L35-L40) to create the release and implicitly the new tag.
So that's (maybe) why the workflow never got triggered.
Anyway, let's see what happens with this one.
=> fix(ci): use the release event type to trigger the google cloud registry workflow

.changeset/ninety-dancers-pump.md, packages/application-shell/src/components/application-shell/application-shell.tsx, packages/application-shell/src/components/application-shell/coerce-values.spec.ts, packages/application-shell/src/components/application-shell/coerce-values.ts, packages/application-shell/src/components/application-shell/fixtures/coerce-values.json
Nasty little edge case. I found this issue when passing a stringified array as an env variable, the injected value in the `window.app` has this value (note the double escaped quotes)
```
"foo":"[\\\"bar\\\"]"
```
This somehow causes the coercion to fail. The only solution I was able to find, was to do a `.replace` and remove the escaped character.
The mysteries of JS...
=> fix(app-shell): coercing values for stringified array with double escaped quotes

.changeset/gentle-brooms-mate.md, packages/application-shell/src/components/application-shell/application-shell.tsx, packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.tsx, packages/constants/src/constants.ts
PS: this is also to avoid relying on the `window.app.env` value.
=>  refactor(app-shell): allow to overwrite LD client ID via application config

.changeset/chilled-buckets-draw.md, packages/i18n/data/core.json, packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.spec.tsx, packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.tsx, packages/react-notifications/src/components/notification-kinds/api-error-message/messages.ts
This pull request adds an error message to be translated for the `MaxResourceLimitExceeded` API error.
The API error contains the message `You have exceeded the limit of $limit resources of type $resourceTypeId.`. I don't think it's feasible or valuable to translate the `resourceTypeId`. Lots of work in the MC goes into preventing users to run into the error itself.
=> feat(react-notifications) add max resource limit exceeded error translation

.changeset/breezy-shirts-dream.md, packages/mc-html-template/src/process-headers.js
This is not necessary anymore, as with the new application config, given that we pass the `env.production.cdnUrl`, the storage buckets are automatically assigned to the CSP headers.
=> refactor(html-template): remove legacy storage buckets from default CSP directives

.changeset/gold-olives-tie.md, packages/mc-scripts/src/extract-intl.js
- `mc-scripts/extract-intl` => fix the wrong usage of console warning. Replaced `console.warning` with `console.warn`
=> fix(mc-scripts/extract-intl): fix console warning

.changeset/serious-maps-sniff.md, website/src/content/deployment/example-deployment-vercel.mdx, website/src/content/getting-started/installing-a-starter-application.mdx, website/src/content/register-applications/configuring-a-custom-application.mdx
- closes https://github.com/commercetools/merchant-center-application-kit/issues/1710
=> refactor: consistent naming for `examples-starter`

.changeset/nervous-beers-exercise.md, website/src/content/getting-started/installing-a-starter-application.mdx
- add `account` to endpoints that can not be used by an external `custom-application`
=> docs(installing-starter): add `account` endpoint

website/src/content/getting-started/tooling.mdx
On the Custom Application [Tooling](https://docs.commercetools.com/custom-applications/getting-started/tooling) docs page 
**Application Shell link** currently points to the [wrong link](https://docs.commercetools.com/custom-applications/main-concepts/application-shell), but It should point to [correct link](https://docs.commercetools.com/custom-applications/components/application-shell).
=> Update Application Shell link in the docs

.changeset/chilled-snakes-thank.md, packages/application-shell/src/apollo-links/token-retry-link.spec.js, packages/application-shell/src/apollo-links/token-retry-link.ts, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/authenticated/am-i-logged-in.tsx, packages/application-shell/src/constants.ts, packages/application-shell/src/utils/apollo-context.ts, packages/constants/src/constants.ts
This pull request adds the ability to skip the token retry with a query variable.
In a prior PR we added the ability to retry the request while receiving a new token on requests to our MC API. While I think this is still valid I wonder if we can skip this for certain requests.
When a user is not logged in for example we should not have to retry the token refetching. Not that with it it's a problem but we can avoid a round trip.
The idea is to add a variable which instructs the apollo link to skip setting the header.
=> feat(app-shell): add ability to `skipTokenRetry` with variable

.changeset/cold-points-doubt.md, packages/application-shell/src/apollo-links/error-link.spec.js, packages/application-shell/src/apollo-links/error-link.ts, packages/application-shell/src/apollo-links/utils.ts
This pull request fixes token regeneration for GraphQL APIs which do not have an `extentions` property.
Some internal APIs do not expose an `extensions` property but an error which looks e.g. like this
```json
{"statusCode":401,"message":"invalid_token","errors":[{"code":"invalid_token","message":"invalid_token"}],"error":"invalid_token"}
```
As a result I propose that we don't only assume a GraphQL error based on the presence of the `extensions` property but also based on the `message` property which is part of the `GraphQLError` type. Please note that `code` is actually not part of it.
=> fix(app-shell): to handle errors without extentions property

.changeset/tall-eyes-deliver.md, packages/application-shell/src/components/navbar/use-navbar-state-manager.ts
- Moved updating the `STORAGE_KEYS.IS_FORCED_MENU_OPEN` into the `handleToggleMenu` callback from its own `useEffect` hook to avoid the timing issue described below.
After collapsing the navbar and expanding it, the `STORAGE_KEYS.IS_FORCED_MENU_OPEN` local storage value was not being updated soon enough. Upon resizing the browser, the navbar would open and close repeatedly in this state.
This issue is causing one of the dashboard widgets not to resize.
https://jira.commercetools.com/browse/PANGOLIN-414
**Before**
**After**
=> fix(navbar): timing of updating menu open local storage to eliminate navbar state change during window resize

.changeset/dry-onions-tap.md, application-templates/starter/src/components/entry-point/entry-point.spec.js, playground/src/components/entry-point/entry-point.spec.js
- removes use of `enzyme` in `playground` and `application-templates`
- address one of https://github.com/commercetools/merchant-center-application-kit/issues/1769
There is still use of `enzyme` in `SDK.Get`. I split that in a separate step.
EDIT:
I don't think it makes sense yet to update the docs.
=> test(app-kit): remove use of `enzyme` in playground and application-templates/starter

.changeset/beige-beers-join.md, packages/mc-html-template/src/process-headers.js
=> fix(csp): use wildcard for sentry.io for matching subdomains

.changeset/ninety-masks-repair.md, packages/application-shell/src/components/application-shell/application-shell.tsx
- removes support for `trackingEventWhitelist` 
- ref https://github.com/commercetools/merchant-center-application-kit/issues/1769
=> [Breaking] refactor(application-shell): remove support for `trackingEventWhitelist`

.changeset/clean-snakes-sort.md, packages/application-shell/src/components/user-settings-menu/user-settings-menu.tsx
This PR fixes the keyboard navigation on the user settings menu, so that the menu only opens when its toggle button is pressed (with `Enter` or `Space`) and doesn't remain open when the user navigates out of it.
It can also be closed with the `Esc` key.
=> fix(app-shell/components): keyboard navigation of user settings menu

.changeset/odd-bobcats-happen.md, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/navbar/navbar.tsx, packages/constants/src/constants.ts
This pull request removes the not documented `disabledMenuItems` prop.
This prop was only used internally and can be removed as handling this will be moved to the infrastructure level.
=> refactor(app-shell): to remove disabledMenuItems support

.changeset/violet-fireants-hope.md, packages/application-shell/src/components/quick-access/create-commands.ts, packages/application-shell/src/components/quick-access/quick-access.spec.js, packages/application-shell/src/components/quick-access/sub-commands.ts
Fix wrong navigation when using Quick Access Product commands.
Fix wrong navigation when using Quick Access Product commands.
- Using `Open Product List` and `Open Products` commands navigate the user to the old product list. Using them now navigate the user to the PIM list instead.
- Using `Open Variant` command navigates the user to a "We could not find this Project" page because of the malformed URL. Using it now navigates the user to the variant details page.
=> fix(quick access): wrong navigation when using product commands

.changeset/moody-melons-arrive.md, playground/src/components/echo-server/echo-server.js, playground/src/components/entry-point/entry-point.js, playground/src/components/state-machines-details/state-machines-details.js, playground/src/components/state-machines-list-connector/state-machines-list-connector.js
As an outcome of adopting the new JSX transform https://github.com/commercetools/merchant-center-application-kit/pull/1819 I suggest to add a small intermediate refactor to adjust the imports according to the codemod.
The benefits of this are that chore on codebase is separate and small when adopting transform and that we adopt the recommended style before.
=> refactor(playground): to use explicit imports of React

.changeset/plenty-hotels-suffer.md, packages/babel-preset-mc-app/index.js, packages/eslint-config-mc-app/has-jsx-runtime.js, packages/eslint-config-mc-app/index.js, packages/jest-preset-mc-app/has-jsx-runtime.js, packages/jest-preset-mc-app/transform-babel-jest.js, packages/mc-scripts/src/config/create-webpack-config-for-development.js, packages/mc-scripts/src/config/create-webpack-config-for-production.js, packages/mc-scripts/src/config/has-jsx-runtime.js, rollup.config.js
This pull request adds a `JSX_RUNTIME` environment variable which can be used to set the JSX runtime to e.g. `automatic`.
The JSX runtime is configured in the mc-babel-preset through the `preset-react`. It would always continue to default to `classic`. However, this way we'd allow experimentation with the `automatic` runtime. Which is not yet supported in TypeScript (starting 4.1). 
The new runtime doesn't require React to be in scope. This means we could potentially internally already experiment with it.
There are other ways to allow the configuration. We could also pass an `jsxRuntime` argument through our webpack configs and jest config to the babel preset. However, that seems far more invasive and also at times not possible as e.g. a webpack config just does
```js
presets: [ …
```
=> fix(babel): allow changing jsx runtime in babel

.renovaterc.json
To group major updates of some of our CT monorepositories, for example [like here](https://github.com/commercetools/merchant-center-graphql-explorer/pull/59).
https://docs.renovatebot.com/configuration-options/#sourceurlprefixes
=> feat(renovate): group some of our monorepos

.changeset/young-rings-kiss.md, packages/application-shell/src/apollo-links/utils.spec.js, packages/constants/src/constants.ts
As part of the work to integrate Change History with Merchant Center, a new GraphQL Target should be set up to be used for configuring a proxy for Change History API requests.
* Added new target value for change history
* Adjusted tests
=> feat(graphql targets): added change history graphql target

.changeset/plenty-lies-serve.md, packages/mc-scripts/src/config/create-webpack-config-for-development.js, packages/mc-scripts/src/config/create-webpack-config-for-production.js
See https://github.com/facebook/create-react-app/blob/545d4607c81dd876c06f66b8104056a3570af242/packages/react-scripts/config/webpack.config.js#L409-L416
No idea how this wasn't caught here in this repo...
=> fix(webpack): babel preset syntax

.changeset/dull-hounds-repair.md, packages/mc-html-template/src/process-headers.js
This was broken for 4 months 🤦‍♂️
We should probably migrate this package to TS as well.
=> fix(headers): eval of dev environment

.changeset/old-carpets-accept.md, packages/mc-scripts/src/config/create-webpack-config-for-development.js, packages/mc-scripts/src/config/create-webpack-config-for-production.js
This pull request intends to fix the mc-scripts to also pass the jsx runtime property to the babel preset on js files.
The prior addition seems to have only passed the babel config to svg files which "makes sense" as they are also transformed.
However by not passing it ot js files internally the build would fail. What I fail to understand is why it works in this repo.
=> fix(mc-scripts): to add jsx runtime for js files not only svg

.changeset/fifty-jeans-shave.md, packages/babel-preset-mc-app/index.js
This pull request fixes the `pragmaFrag` of the babel config to be `Fragment` when using the `automatic` runtime.
By default the babel transform seems to transform a `<></>` to `<React.Fragment></React.Fragment>` which will break in `automatic` mode as `React` is not in scope.
For instance at something like this.
It should just compile it to `Fragment` as `React` doesn't have to be in scope for then it to be picked up.
Reference: https://babeljs.io/docs/en/babel-plugin-transform-react-jsx#pragmafrag
=> fix(babel): pragma frag to be Fragment not React.Fragment

.changeset/thick-wasps-hang.md, packages/constants/src/constants.ts
This adds an `IMPORT_EXPORT` HTTP target. This will become relevant when the respected API will be started to be integrated. 
This is not publicly supported yet. We will have to do some internal work to add proxying support. We can keep this on hold until then or prepare for it already.
=> chore: add import export api target

.changeset/witty-emus-share.md, package.json, packages/babel-preset-mc-app/index.js, packages/babel-preset-mc-app/package.json, yarn.lock
This pull request intends to fix the setup of the automatic runtime in combination with emotion.
Emotion has recently added support for the automatic runtime. Then changed a bit again how it works
From this
To this
Ref: https://emotion.sh/docs/css-prop#babel-preset
So I guess we're lucky to have been sitting that change out quietly ;)
=> fix(babel): to use import source for emotion and automatic runtime

.changeset/new-baboons-hide.md, packages/application-shell-connectors/src/types/generated/mc.ts, packages/application-shell/src/components/application-shell/application-shell.tsx, packages/application-shell/src/components/gtm-application-tracker/gtm-application-tracker.spec.js, packages/application-shell/src/components/gtm-application-tracker/gtm-application-tracker.tsx, packages/application-shell/src/components/gtm-booter/gtm-booter.tsx, packages/application-shell/src/types/generated/ctp.ts, packages/application-shell/src/types/generated/mc.ts, packages/application-shell/src/utils/gtm.ts, schemas/ctp.json, schemas/mc.json
add user business role custom dimension tracking 
We want to always have the user business role custom dimensions information available when the application loads like we do for the application name and project key custom dimensions.
=> feat(application-shell): add user business role custom dimension tracking 

.changeset/young-months-sing.md, packages/l10n/README.md, packages/l10n/package.json, packages/l10n/src/index.ts, packages/l10n/src/localize.spec.ts, packages/l10n/src/localize.ts, packages/l10n/src/types.ts, packages/l10n/src/utils.ts, yarn.lock
- adds `injectTransformedLocalizedFields`
- adds `transformLocalizedFieldToString`
With an upcoming feature in `AppKit`, it makes sense to expose these utils.
These transformations are useful for transforming `graphql` shaped `*AllLocales` fields to a normalized [`LocalizedString`](https://docs.commercetools.com/api/types#localizedstring)
=> feat(l10n): add graphql transformers and `localize`

.changeset/eighty-dogs-brake.md, packages/application-shell/src/configure-store.ts, packages/application-shell/src/test-utils/test-utils.spec.tsx
The `storeState` render option of `renderAppWithRedux` is unusable.
Make it usable by passing preloaded state reducers to `combineReducers`.
Fixes https://github.com/commercetools/merchant-center-application-kit/issues/1900.
=> fix(application-shell/test-utils): `storeState` render option of `renderAppWithRedux` is unusable

.changeset/tricky-kiwis-drive.md, packages/l10n/src/index.ts, packages/l10n/src/localize.ts, packages/l10n/src/types.ts
- allow export of `transformLocalizedFieldToLocalizedString`
- allow `locale` to be passed as `null`, leverage type-guard for the "lookup"
---
This is cherry picked from a feature branch I'm working on
=> refactor(l10n/localize): export transformLocalizedFieldToLocalizedString

.changeset/fluffy-crews-fly.md, packages/mc-scripts/src/config/vendors-to-transpile.js
We shouldn't need this anymore.
=> chore: remove react-intl from vendors to transpile list

.changeset/chilled-bats-eat.md, babel.config.js
Our babel preset uses a `ROLLUP_BUILD` env variable that we forgot to set when we moved to preconstruct.
It only affected prop types.
=> fix(babel): regression, pass ROLLUP_BUILD env

.changeset/tall-meals-brush.md, graphql-test-utils/graphql-models/project.js, packages/application-config/src/schema.ts, packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx, packages/application-shell-connectors/src/components/application-context/application-context.tsx, packages/application-shell-connectors/src/components/application-context/index.ts, packages/application-shell-connectors/src/components/application-context/normalizers.spec.ts, packages/application-shell-connectors/src/components/application-context/normalizers.ts, packages/application-shell-connectors/src/index.ts, packages/application-shell-connectors/src/types/generated/mc.ts, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/application-shell/application-shell.tsx, packages/application-shell/src/components/fetch-project/fetch-project.mc.graphql, packages/application-shell/src/components/navbar/navbar.tsx, packages/application-shell/src/test-utils/test-utils.tsx, packages/application-shell/src/types/generated/mc.ts, packages/permissions/src/components/authorized/authorized.tsx, packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx, packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.spec.tsx, packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.tsx, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts, schemas/mc.json, test-data/project/transformers.ts, test-data/project/types.ts
As we are introducing some changes related to permissions in the MC API, we need to ensure that the menu links are not affected by that. This is because menu links are considered a "shared" resource across all applications.
~~**DO NOT MERGE THIS FOR NOW UNTIL THE CHANGES IN THE MC API ARE LIVE**~~
=> refactor: menu links to use their own permission data

.changeset/gentle-mayflies-heal.md, website/src/@commercetools-docs/gatsby-theme-docs/overrides/page-header-side.js
=> refactor: remove second border and spacing for the Github icon

.changeset/seven-clocks-smell.md, packages/application-shell/src/apollo-links/header-link.ts
I am investigating an error reported to Sentry from MC saying that `GraphQL target "undefined" is missing or is not supported`. Went manually through all the queries we sent in MC to try to find the one with a missing `target` param. No luck. 
So, I decided to extend the error message thrown from HttpLink so that it will include `operationName` to narrow down the scope of further investigation.
=> chore(header-link): add operation name to missing target error

.changeset/young-lions-confess.md, packages/application-shell/src/index.ts
This removes the `updateFlags` re-export from the `application-shell` package.
The re-export was not used internally and I presume nobody used it externally. The alternative is to use `ldAdapter.updateFlags`. The stand alone export was only a "redirect" anyway.
This re-export will not be present anymore in the upcoming major release of flopflip. Please apply the changeset you see adequate for this.
=> refactor(app-shell): remove updateFlags

.changeset/fuzzy-tomatoes-approve.md, packages/application-shell/src/components/navbar/navbar.mod.css
- Removed navbar title whitespace nowrap CSS
When translated into Spanish and French, the Change History navbar item is too long to fit into the navbar's fixed width. I believe this is the first item to run into this issue.
**Before:**
**After:**
=> fix(navbar): remove title nowrap to accommodate long application names

cypress/integration/template-starter/main.js
From time to time we get a flaky percy snapshot about the "Processing..." text being visible (or not).
This PR attempts to improve the test by ensuring that the text disappears before taking the snapshot.
=> test(starter): wait for processing text to be removed, before taking the snapshots

.changeset/eleven-feet-repeat.md, packages/jest-preset-mc-app/setup-tests.js
This pull request suggests to remove the `fail-tests-because-there-was-an-unhandled-rejection.lock` file which is written when a unhandled promise rejection is detected by the Node.js process. 
Jest can spawn various processes. This often made it hard to catch all unhandled promise rejections as some could originate in child processes and not communicate proper to the parent. As a result unhandled promise rejections might have gotten unnoticed when running a large test suite on machines with various cores.
The linked issue https://github.com/facebook/jest/issues/3251#issuecomment-299183885 discusses this at length.
However, in recent versions of Node.js unhandled promises will always immediately terminate the process. In addition in this https://github.com/facebook/jest/pull/4016 pull …
=> refactor(jest-preset): to remove unhandled promise lockfile

.github/workflows/release.yml
Suggesting to have `changesets` use a conventional commit pr title and commit.
I noticed that this breaks a husky v5 update in flopflip over the weekend.
=> ci(changesets): to use conventional commits

.github/renovate.json
Follow up of #1964 , as it seems that this rule does not play nicely with `manypkg`
=> chore: remove pinOnlyDevDependencies

.changeset/gold-doors-learn.md, packages/application-shell/src/index.ts
These have been around in flopflip for some time. They can be useful for us.
=> fix(app-shell): to re-export flag variation utils

.changeset/gentle-pets-glow.md, packages/mc-html-template/src/generate-template.js
This pull request suggests to add a `referrerpolicy="no-referrer"` to `link`-tags.
Generally, to my understanding, the `link`-tags do not need the referrer. Hence we can opt-out of them. 
This should not be an issue as our urls do not contain any sensitive information. However, a Custom App can put anything into the url. Also we do not use external CDNs but we can still add additional security by not sending it.
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link
=> fix(mc-html-template): add no-referer policy

.changeset/red-pigs-breathe.md, packages/mc-html-template/src/generate-template.js, packages/mc-html-template/src/utils/replace-html-placeholders.js
This pull request is very similar to the #1994 just focussed on `script`-tags.
I noticed that we could also apply the same directive to script tags.
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script
=> fix(mc-html-template): add no-referer policy to script-tags

.changeset/rich-rats-crash.md, packages/mc-html-template/src/generate-template.js
This pull request takes the idea of never sending a referrer a step further.
Given we have a script which as a no-referrer. Given this script loads another script. That child script will be loaded in the context of the HTMLs referrer policy not the parent script's one.
Given we can also specify the `no-referrer` on the HTML as a meta-tag I propose to do that. 
I don't think we ever rely on the `referer` (the header is misspelled on purpose) we should be able to do that. Also the origin header is similar to the Referer header, but, unlike this header, it doesn't disclose the whole path.
=> fix(mc-html-template): to never send a referrer

packages/application-components/src/components/public-page-layout/public-page-layout.tsx
| Before | After |
| - | - |
| <img width="1440" alt="before" src="https://user-images.githubusercontent.com/1379086/105968844-e1330200-6087-11eb-8f63-d32a248c79a3.png"> | <img width="1440" alt="after" src="https://user-images.githubusercontent.com/1379086/105968892-ee4ff100-6087-11eb-8c0d-cce122cfbdb6.png"> |
Modify styles to allow container to flex beyond 100vh when there is enough content that overflows the viewport.
=> fix(public-page-layout): allow container to flex beyond 100vh

.changeset/plenty-plums-camp.md, packages/cypress/README.md, packages/cypress/src/add-commands/index.ts, packages/cypress/src/task/index.ts
This is also helpful for us internally to migrate our Cypress tests to use the new workflow.
=> feat(cypress): add more options to loginByOidc command

website-components-playground/package.json, website/package.json, yarn.lock
Version 2.31 has some issues: https://github.com/gatsbyjs/gatsby/issues/29213
=> chore: keep gatsby version pinned to 2.30.3

.changeset/tidy-llamas-deliver.md, packages/application-shell/package.json, packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.tsx, packages/application-shell/src/test-utils/test-utils.tsx, yarn.lock
This pull request refactors our test-utils to use the new `TestProviderFlopFlip`.
The mentioned provider reduces the amount of complexity for the test setup:
1. No more `memory-adapter` and `reset` on each tets
2. No "async" state of flags which leak into tests (wait until flags are flushed otherwise act warnings)
=> refactor(test-utils): to use flopflip test provider

.changeset/late-ducks-confess.md, packages/application-shell/src/components/authenticated/has-cached-authentication-state.ts
- moves `cacheScope` logic to the bottom
- remove redundant key in `env`, already defined in `env.local`
=> fix(authenticated): cache lookup

.changeset/three-rabbits-rest.md, jest.eslint.config.js, jest.stylelint.config.js, jest.text.config.js, jest.visual.config.js, packages/jest-preset-mc-app/jest-preset.js, packages/jest-preset-mc-app/package.json, yarn.lock
We don't really need this, especially when we switch the branch to `main`.
=> refactor(jest): remove jest-watch-master plugin

.changeset/cuddly-kangaroos-hope.md, packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.tsx, packages/constants/src/constants.ts
This pull request suggests to rename `enableFeatureConfigurationFetching` to `enableLongLivedFeatureFlags`.
While integrating this feature it became apparent that we will now naturally distinguish between short-lived flags (through LaunchDarkly) and long-running flags (through our GraphQL API).
This also means that we can keep this environment variable. Custom Applications will not have to fetch our long-running flags while they could (if e.g. an internal app) as an opt-in.
As a result, I think it makes sense to enable this with a more descriptive environment variable which indicates more clearly what it will cause.
<hr />
As a follow-up we can also discuss with we should have a `enableShortLivedFeatureFlags`. This would mean that Custom Applications would not receive feature flags from …
=> refactor: to rename to enableLongLivedFeatureFlags

.changeset/nervous-cameras-visit.md
This pull request releases the create-mc-app and template package to fix an issue caused by moving to `main` as a default branch. We forgot to publish when performing that change. As `master` doesn't exist anymore pulling and installing fails at the moment.
- Closes #2035
=> fix: release to fix from main by default

website/src/content/help-needed.mdx
Application kit repo Github Discussion link is broken on the [docs](https://docs.commercetools.com/custom-applications/help-needed).
Updated the Application kit repository Github Discussion link.
=> Fix application kit Github discussion link.

CONTRIBUTING.md
- point to the correct yarn script command
- use `.graphqlrc.yml`
=> docs(contrib): update graphql files section to correct config files

.changeset/lovely-suns-drive.md, packages/application-components/package.json
I guess this was a leftover from removing the "experimental" entry point from the components package.
=> fix(components): remove unnecessary apollo client dependency

.changeset/breezy-taxis-tie.md, @types/commercetools__api-request-builder/index.d.ts, packages/sdk/src/middleware/middleware.spec.ts, packages/sdk/src/middleware/middleware.ts
-  support `apply` endpoint for `orderEdits`
- closes #2058
In `sdk/middleware`, we `build()` request [for the respective service](https://github.com/commercetools/nodejs/blob/master/packages/api-request-builder/src/default-services.js#L1:L1) in `sdk`.
It turned out that the `service.build()` is coupled to an option for `orderEdits` that determines whether an `order/edits/${id}/apply` endpoint should be build.
Here is how we reason when building the `order/edits/${id}/apply` endpoint in `sdk/middleware`:
- GIVEN that `service=orderEdits` and `applyOrderEditTo` has a value: [we build the apply endpoint](https://docs.commercetools.com/api/projects/order-edits#apply-an-orderedit)
- GIVEN that `service=orderEdits` and `applyOrderEditTo` has no value: [we build the update …
=> fix(sdk/middleware): support `apply` endpoint for `orderEdits`

.changeset/swift-pandas-punch.md, packages/mc-scripts/src/config/create-webpack-config-for-production.js
Internally CircleCI fails at times. The assumption is that it doesn't report the CPUs right. We already pass this value to Terser for the same reason. We now would also pass it to the thread lower to limit the CPUs used.
=> fix(webpack): to pass parallelism to thread-loader

package.json
While developing locally, the `yarn clean` command was failing due to unable to find the directories listed in the command. Reading the `manypkg` [readme](https://github.com/Thinkmill/manypkg#manypkg-exec-cli-command), it seems that we do not need to wrap the directories in single-quotes.
May be another dev can double check and confirm this.
=> fix(packages.json): fix the yarn:clean command

.github/workflows/main.yml, jest-puppeteer.config.js, package.json
I noticed that the VRTs seem to timeout at times as percy is not responding. This is odd and causes GitHub jobs to run for 3 hours or more. Causing significant pressure on our time budget there.
=> fix: vrt timeouts

.changeset/shiny-toes-tan.md, package.json, packages-backend/express/package.json, packages/application-shell/package.json, yarn.lock
To my memory only `msw` blocked this update. Let's see what CI says.
=> chore: update typescript to 4.2.3

.changeset/ninety-donuts-tickle.md, packages/l10n/scripts/generate-l10n-data.js
The PR updates the  `generate-l10n-data` script of `l10n` package which is responsible for generating CLDR data. i.e. countries, currencies, timezones etc. 
Back in December 2020, we have to update manually the auto-generated file of countries data and add `Northern Ireland` to them. It was needed due to Brexit. Doing this was kinda of hot fix but it also blocks updating the `cldr` package.
The latest versions of CLDR data is still missing territory data for `Northern Ireland`. It seems that it might take a while for them to add this. You can check the discussion on https://github.com/commercetools/merchant-center-application-kit/pull/2054.
 In order to unblock the update of the `cldr` package and also avoid manual update of the auto-generated file by `generate-l10n-data` script, we would …
=> feat(l10n): update generate-data script

packages/l10n/scripts/generate-l10n-data.js
`generate-l10n-data.js` => fix typo in the french locale name and also fix the initial name for the Chinese locale
=> fix(l10n/scripts): fix typo and locale name

.changeset/few-snails-hunt.md, packages-backend/express/src/auth.spec.js, packages-backend/express/src/auth.ts
Ref #2115 
Fix issue with invalid `audience` in case the request contains query parameters.
We now omit the search params when validating the audience (PR in MC API also needs to be merged first).
=> fix(express/auth): omit search params when reconstrucing audience URL

.changeset/bright-glasses-grin.md, packages/application-config/schema.json, packages/application-config/src/schema.ts, packages/application-config/test/fixtures/config-full.json, packages/application-config/test/process-config.spec.js, packages/mc-html-template/src/process-headers.js, packages/mc-scripts/src/compile-html.js, website/src/content/development/application-config.mdx
Chrome v90 introduced a `Permissions-Policy` header replacing (but being backwards compatible for now) `Feature-Policies`.
This adds support for the header to the schema.
Reference: https://github.com/w3c/webappsec-permissions-policy/blob/main/permissions-policy-explainer.md
=> feat(application-config): add permissions policy header

.changeset/heavy-ligers-admire.md, packages/application-shell/package.json, packages/application-shell/src/test-utils/test-utils.tsx
The more logic we move to hooks in MC the more we observe the need to pass a `wrapper` combined from all the `application-shell` providers used by a hook under test in `renderHook` function in corresponding tests. For instance, whenever we want to test a hook which use Apollo under the hood, we have to wrap rendered hook in `<ApolloProvider />`. When testing logic related to tracking we wrap everything in `<GtmContext.Provider />`. And so on. 
Given that our `renderApp*` functions from `test-utils` already nicely mock all the providers one option is to test hooks via these `render*` function and not rely on `renderHooks`. Add people do it indeed. But that's not really nice, because of all the boilerplate needed to map hook inputs/outputs to a wrapping test component, so that it can be …
=> feat(test-utils): add renderHook wrapper

.changeset/ninety-ravens-beam.md, packages/eslint-config-mc-app/helpers/eslint.js, packages/eslint-config-mc-app/index.js, packages/jest-preset-mc-app/jest-preset.js, packages/mc-scripts/src/config/create-webpack-config-for-development.js, packages/mc-scripts/src/config/create-webpack-config-for-production.js, packages/mc-scripts/src/config/paths.js
This pull request intends to add support for webpack configs with different file endings such as `webpack.config.prod.cjs`
The original reason for this pull request is to support webpack configs in projects running on ES modules. Those packages at times have a `type: "module"` in their `package.json`. 
Whenever, our `mc-scripts build` then loads the webpack configs from those modules the `package.json` config is read. Node.js will then throw as the e.g. `webpack.config.prod.js` contains `require` statements not only `import`.
ESLint solves this by supporting `.cjs` extension for their configurations while not supporting ES module configurations. This is a good middle ground to allow the ecosystem to migrate while not blocking them.
As a side-effect this pull request allows `ts` …
=> feat(mc-scripts): add support for webpack config extensions

.changeset/odd-dodos-tickle.md, packages/mc-html-template/src/process-headers.js
The permission policy header is joined by a `', '` separator in the specification. Not a `': '`.
=> fix(mc-html-template): permission policy to be joined with comma

.changeset/good-wolves-watch.md, .changeset/serious-actors-attend.md, @types-extensions/jest.d.ts, application-templates/starter/package.json, package.json, packages/jest-preset-mc-app/README.md, packages/jest-preset-mc-app/enzyme/base-setup-test-framework-for-enzyme.js, packages/jest-preset-mc-app/enzyme/create-jest-preset-for-enzyme.js, packages/jest-preset-mc-app/enzyme/jest-preset-for-enzyme-16.js, packages/jest-preset-mc-app/enzyme/jest-preset-for-enzyme-17.js, packages/jest-preset-mc-app/enzyme/setup-test-framework-for-enzyme-16.js, packages/jest-preset-mc-app/enzyme/setup-test-framework-for-enzyme-17.js, packages/jest-preset-mc-app/jest-preset.js, packages/jest-preset-mc-app/package.json, packages/jest-preset-mc-app/setup-test-framework.js, packages/jest-preset-mc-app/setup-tests.js, packages/sdk/package.json, packages/sdk/src/components/sdk-get/sdk-get.spec.tsx, yarn.lock
=> [Breaking] Drop Enzyme support from Jest preset and make it opt-in

.changeset/quiet-snails-reflect.md, packages/mc-html-template/src/process-headers.js
This fixes the processing of structured headers like the permissions policy.
A structured header format is `key=(), key2=()` not `key (),`.
In this fix I removed the seperator and created a second function. I subjectively found that easier to understand.
=> fix(mc-html-template): fix processing of structured headers

.changeset/moody-bikes-rest.md, packages/mc-html-template/src/process-headers.js, packages/mc-html-template/src/process-headers.spec.js
This adds tests for processing the headers of an application config.
I felt we should have some tests for this logic given it didn't work as we wanted. While writing the tests I noticed that it still doesn't 🤕.
=> test(mc-html-template): add test for processing headers

.changeset/tricky-crews-breathe.md, packages/mc-scripts/src/build.js
React-dev-utils doesn't support the webpack 5 stats, so this is an adapter to allow errors to propogate properly to `mc-scripts build`.
Resolves https://github.com/commercetools/merchant-center-application-kit/issues/2188
=> Bugfix for error messages not showing in `mc-build`

.changeset/rotten-foxes-bake.md, packages/mc-scripts/src/bin/cli.js, packages/mc-scripts/src/commands/build.js, packages/mc-scripts/src/commands/compile-html.js, packages/mc-scripts/src/commands/serve.js, packages/mc-scripts/src/commands/start.js
Leftover of #2191 
Now custom `--env` options are correctly evaluated first
=> fix(mc-scripts): loading and parsing of dotenv files

package.json, packages/cypress/package.json, yarn.lock
It seems that Cypress `7.3.0` has issues being downloaded. Let's downgrade to `7.2.0` in the meantime.
=> chore: downgrade cypress to 7.2.0

.changeset/tough-needles-move.md, packages-backend/loggers/package.json, packages/sentry/package.json, yarn.lock
No apparent breaking changes.
As for the release health, I think we can keep it enabled right?
=> chore: upgrade to sentry v6

.changeset/serious-numbers-mix.md, packages/mc-scripts/src/config/webpack-dev-server.config.js
Caused by #2199 
This slipped through in the latest dependency upgrade
causing local dev to not start:
=> fix(mc-scripts): regression when updating webpack-dev-server to 4.0.0-beta.3

.husky/pre-commit, lint-staged.config.js, package.json, yarn.lock
The project [tsc-files](https://github.com/gustavopch/tsc-files) allows to type check only files that changed. I wanted to suggest it as a pre-commit hook while CI still does the whole typecheck. I found out about it as the `lint-staged` owner recommended it online.
=> chore: add tsc-files to pre-commit hook

.changeset/five-spies-carry.md, website/src/content/main-concepts/data-fetching.mdx
Update outdated Apollo Query component import path. ([link to issue](https://github.com/commercetools/merchant-center-application-kit/issues/2219))
Since @apollo/client v3, Query component needs to be imported from this path:
`import { Query, Mutation, Subscription } from '@apollo/client/react/components';`
See this [PR on @apollo](https://github.com/apollographql/apollo-client/pull/6558) for details.
=> fix(website-content): Apollo Query component import path

.changeset/curvy-ears-move.md, packages/constants/src/constants.ts
There is a design decision to go from `- - - -` to `- -` across the MC. As `NO_VALUE_FALLBACK` is used in Application Shell too we have to change it in this repo. 
I guess that should be considered a braking change (custom apps relies on current value), hence there is a major version bump.
=> feat: new placeholder for missing values (i.e. NO_VALUE_FALLBACK)

.changeset/witty-oranges-compare.md, packages/eslint-config-mc-app/index.js
Updating and hence enabling these rules is a breaking change.
=> fix(eslint-config): to not error on new rtl rules

.changeset/soft-plants-destroy.md, packages/eslint-config-mc-app/index.js
Erroring for a use of container is a bit to strict. Warning is more accurate.
=> fix(eslint-config): to not error for container use

.changeset/fuzzy-hounds-agree.md, packages/mc-html-template/src/process-headers.js
This adds the `preload` and `includeSubDomains` attributes to the `Strict-Transport-Security` header.
Using [hstspreload.org](https://hstspreload.org) it is advised to `preload` (not part of the spec) and add the `includeSubDomains` attributes. More about HTS [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security).
I don't see a strict reason against adding those.
=> fix(mc-html-template): add preload and includeSubDomains to header

.changeset/wild-trees-love.md, packages/application-config/schema.json, packages/application-config/src/schema.ts, packages/application-config/test/fixtures/config-full.json, packages/application-config/test/process-config.spec.js, packages/mc-html-template/src/process-headers.js, packages/mc-html-template/src/process-headers.spec.js
Instead of changing the default let's make it configurable.
=> feat(mc-html-template): make transport security configurable

.changeset/tidy-boxes-drive.md, packages/jest-preset-mc-app/setup-tests.js
This pull request suggests to be able to add silenced and not throwing warnings of the console at run time.
Internally we at times want to silence warnings globally when e.g. the come from ui-kit or app-kit or libraries. However, at times we also want to log or warn but not have tests fail due to that.
As a result an initial idea is to add the ability to add silenced and not throwing warnings to the console at run time.
=> feat: add ability to additionally silence warnings

playground/src/components/echo-server/echo-server.js, playground/src/components/echo-server/messages.js, playground/src/i18n/data/core.json
This allows custom headers through the echo server. Was needed for a support ticket.
=> feat(playground): echo server to allow custom header forwarding

website/src/content/main-concepts/user-permissions.mdx
Because Custom Application developer might not know from which module the `useIsAuthorized` is from.
=> Add  useIsAuthorized import to the permissions code snippet.

.changeset/tender-eggs-joke.md, packages/babel-preset-mc-app/index.js
`core-js` causes troubles it tests when running together with `jest@27`. 
Beacuse `core-js` adds polyfills for `Promises` (and maybe `Date`, I'm not sure), that breaks some assumptions under the hood of resent version of `jest`. Which in turn leads to all tests relying on jest's fake timers to break.
I ran both app-kit and MC tests with this new setup and it seems to work fine.
=> test: disable core-js in test environment

.changeset/proud-cows-own.md, packages/babel-preset-mc-app/index.js
This sets the Node.js version to `current` instead of hard-coding it to `8`.
Current implies the the version of the hosting system will be used which under test is often exactly what you want given everything runs in the version prescribed by the `.nvmrc` if you ask me.
=> fix(babel-preset-mc-app): to set node.js version to current

.changeset/long-wolves-bake.md, .changeset/many-doors-fold.md, .changeset/perfect-mice-bow.md, .changeset/proud-cows-own.md, .changeset/tender-eggs-joke.md, packages/babel-preset-mc-app/index.js, packages/mc-scripts/src/config/create-webpack-config-for-development.js, packages/mc-scripts/src/config/create-webpack-config-for-production.js
This adds the ability to explicitly disable `core-js`.
Some environments or build targets might not require `core-js`. In order to opt-out of it you can specify a `disableCoreJs` option now.
=> feat(babel-preset-mc-app): add ability to disable core-js

.changeset/dirty-beans-yawn.md, packages/jest-preset-mc-app/jest-preset.js, packages/jest-preset-mc-app/load-config.js, packages/jest-preset-mc-app/transform-babel-jest.js
Adds support for a `babelConfig` in the cosmiconfig for jest (so the `jest-preset-mc-app.config.js in a project's root).
The babel config (babel-preset-mc-app) has various configuration options. At times it can make sense to pass down values to the config (e.g. to `disableCoreJs`).
=> feat(jest-preset-mc-app): add babelConfig to jest config

.changeset/modern-cheetahs-cry.md, packages/react-notifications/src/components/notification-kinds/api-error/api-error.tsx
`<ApiErrorNotification />` component, by design, logs reported error to the `console.error`. At the moment, that only happens in non `production` environment. That's find and good to ease figuring out what's going on in development, but leads to polluted terminal messages when this situation happens under test. 
I suggest we log these errors to console only if `NODE_ENV === 'development'`, silencing both `test` and `production` environments.
=> fix(api-error): log api errors to console only in development env

.changeset/purple-shirts-clap.md, packages/i18n/package.json, packages/i18n/src/load-i18n.ts, yarn.lock
Note (**tech debt**): we might want/need to rethink how to ship and consume i18n messages from packages/repositories. At the moment, they are all loaded from the i18n package in appkit, but it's not really scalable. Ideally, packages should ship they own messages instead of relying on a single i18n package that aggregates all messages. See also https://formatjs.io/docs/getting-started/message-distribution
=> feat(i18n): i18n messages from `@commercetools-community-kit/i18n`

.changeset/selfish-kangaroos-cry.md, packages/application-shell/src/components/navbar/navbar.tsx
=> fix(navbar): keep main menu item a link even when submenu group is expanded

.changeset/eighty-maps-explode.md, packages/application-shell/src/components/navbar/navbar.tsx
Small regression caused by #2281 
I forgot that we use the roles for testing. It's also fine apparently to have custom roles, so the eslint warning can be "ignored".
=> fix(navbar): keep custom aria role attributes

.changeset/few-timers-poke.md, package.json, packages/mc-scripts/package.json, playground/package.json, website-components-playground/gatsby-config.js, website-components-playground/src/layouts/layout-app.js, website/gatsby-config.js, website/package.json, yarn.lock
Somehow the dialogs buttons are wrongly positioned.
Apparently this is due to missing "reset" styles (which are included in the appshell). After applying those styles, it works as it should:
=> docs(playground): fix reset styles

.changeset/plenty-zoos-tap.md, packages/actions-global/src/export-types.ts, packages/actions-global/src/index.ts, packages/application-shell-connectors/src/export-types.ts, packages/application-shell-connectors/src/index.ts, packages/application-shell/src/index.ts, packages/browser-history/src/export-types.ts, packages/browser-history/src/index.ts, packages/i18n/src/export-types.ts, packages/i18n/src/index.ts, packages/notifications/src/index.ts, packages/permissions/src/index.ts, packages/react-notifications/src/export-types.ts, packages/react-notifications/src/index.ts
When developing in this repository, `preconstruct dev` [runs after installing the dependencies](https://preconstruct.tools/guides/using-preconstruct-dev-in-a-monorepo). This results in "placeholder" `dist` files to be generated, which are essentially symlinks to the package entry point.
However, those are not TS files, so if the entry point file has any `type` syntax, the file is kind of invalid and you will see this kind of error in the editor:
```
'import type' declarations can only be used in TypeScript files.ts(8006)
```
Therefore, we should avoid having type declarations in the entry point file and instead re-export them from a "special" file (I went with the name `export-types`). This way, types are still exported and the syntax is still valid.
=> chore: move exported types from package entry point into a separate file

.changeset/two-months-type.md, packages/mc-scripts/src/config/webpack-dev-server.config.js
I noticed that HMR wasn't working anymore. I changed it to be the same of what CRA uses.
=> fix(mc-scripts): web socket config to make HMR work

.changeset/lazy-eggs-glow.md, application-templates/starter/package.json, packages/application-shell-connectors/package.json, packages/application-shell/package.json, packages/application-shell/src/hooks/apollo-hooks/apollo-hooks.ts, packages/application-shell/src/hooks/use-applications-menu/use-applications-menu.ts, packages/application-shell/src/utils/select-user-id/select-user-id.spec.js, packages/mc-scripts/src/config/create-webpack-config-for-development.js, packages/mc-scripts/src/config/create-webpack-config-for-production.js, yarn.lock
Extracted ugrading changes related to Apollo `v3.4` from #2318 
This Apollo version seems to be a bit buggy, so we wait a bit to see if some of the issues are resolved.
=> chore: ugrade to apollo v3.4

.changeset/dry-cherries-whisper.md, packages/application-shell/src/components/application-shell/application-shell.tsx
The error notification overlaps with the modal container but the components in the background adjust itself whenever notification appears.
Moving the Portal container inside the same common parent div fixes the problem of overlapping.
=> PCM-2389: Overlapping portal container and notification bar

.changeset/shy-donuts-sin.md, packages/jest-preset-mc-app/jest-preset-for-typescript.js, packages/jest-preset-mc-app/jest-preset.js
It seems that using `ts-jest` causes issues with Emotion whenever we use [selectors as styled components](https://emotion.sh/docs/styled#targeting-another-emotion-component).
The error we get is
```
Component selectors can only be used in conjunction with @emotion/babel-plugin
```
Apparently we can just "go back" to use `babel-jest`.
=> refactor(jest): use babel-jest instead of ts-jest

.changeset/twelve-rabbits-look.md, packages/constants/src/constants.ts, packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.spec.tsx, packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.tsx, packages/react-notifications/src/components/notification-kinds/api-error/api-error.tsx, packages/react-notifications/src/components/notifications-list/notifications-list.spec.tsx
Closes #168 
This PR extends support for the the GraphQL API error object shape, `error.extensions.code`.
While migrating Discounts, I noticed that migrating all test cases did not pass cleanly. @ByronDWall and I discovered that the `useShowApiErrorNotification` hook's return value created an action (that we pass `errors` to) that `<ApplicationShell />`'s Redux context consumes, and it is here where `error.code` is expected.
This PR changes the `TAppNotificationApiError` type and all tests that rely on it.
I'm unsure if there are backwards compatibility issues / side effects for other projects given the changes here - should we extend the type as needed as a safeguard?
=> fix(api-errors): migrate to `error.extensions.code` for notifications

.changeset/four-ladybugs-smash.md, packages/application-shell/src/components/application-shell/helpers.spec.ts, packages/application-shell/src/components/application-shell/helpers.ts, packages/application-shell/src/components/application-shell/redirect-to-login.tsx, packages/application-shell/src/components/application-shell/redirect-to-logout.tsx, packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.tsx, packages/application-shell/src/components/route-catch-all/route-catch-all.tsx, packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.ts, packages/application-shell/src/hooks/use-is-served-by-proxy/index.ts, packages/application-shell/src/hooks/use-is-served-by-proxy/use-is-served-by-proxy.ts
Closes #2406 
Currently when you try to access a Custom Application directly to its URL, the application tries to reload itself to go to the `/login` route.
This ends up in an "infinite" loop as the Custom Application is not being served within the Merchant Center Proxy Router and thus there is no way to handle the `/login` request.
One way to avoid this is to manually configure a route handler for `/login` (and `/logout`) in your cloud provider and for example render a message.
To help simplifying the deployment setup, we can redirect to the `/login` and `/logout` pages using a full origin URL redirect.
For Custom Applications, this means that if you try to access the application directly, it will redirect to the login page of the configured MC environment, so there is no need to handle …
=> refactor(app-shell): redirect to `/login` and `/logout` using a full origin URL

.github/workflows/main.yml, .github/workflows/release.yml
This refactors using the native `setup-node` action support for `.nvmrc` files.
Prior to a recent release [here](https://github.com/actions/setup-node/releases/tag/v2.5.0) the `setuo-node` action didn't support `.nvmrc` files natively. As a result of the above we used an intermediate step. I cats out the `.nvmrc` file's content and makes it accessible to subsequent steps through its `nvm` step id as an output.
All of the above is not needed anymore as we can simply do `node-version-file: '.nvmrc'` on the `setup-node` job (see release notes above).
I quickly refactored private projects [here](https://github.com/tdeekens/flopflip/pull/1560) and it seems to work. I think removing the indirection of the additional step is nice. 
I just wanted to quickly propose this before I forget again. …
=> fix: to use native checkout action nvmrc support

CONTRIBUTING.md
Update CONTRIBUTING docs
In the packages overview section, there was an incorrect link title and another one pointing to a non-existing package
=> docs: update contributing to fix a couple of typos

.changeset/thin-cows-develop.md, packages/application-shell/src/components/application-entry-point/application-entry-point.tsx, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/application-shell/application-shell.tsx, packages/application-shell/src/components/authenticated/authenticated.spec.tsx, packages/application-shell/src/components/back-to-project/back-to-project.spec.tsx, packages/application-shell/src/components/fetch-project/fetch-project.spec.tsx, packages/application-shell/src/components/fetch-user/fetch-user.spec.tsx, packages/application-shell/src/components/inject-reducers/inject-reducers.spec.js, packages/application-shell/src/components/project-container/project-container.tsx, packages/application-shell/src/components/project-suspended/project-suspended.spec.js, packages/application-shell/src/components/project-switcher/project-switcher.spec.tsx, packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.spec.tsx, packages/application-shell/src/components/requests-in-flight-loader/requests-in-flight-loader.spec.tsx, packages/application-shell/src/components/route-catch-all/route-catch-all.spec.js, packages/application-shell/src/components/service-page-project-switcher/service-page-project-switcher.spec.js, packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js, packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.spec.js, packages/application-shell/src/hooks/use-applications-menu/use-applications-menu.spec.tsx, packages/application-shell/src/test-utils/test-utils.spec.tsx, packages/application-shell/src/test-utils/test-utils.tsx
Main branch: #2430 
With the new Custom Application permissions, users can assign permissions to Teams to grant or not to grant access to the application.
If a user is a member of a Team without permissions assigned to this Custom Application, the application should be not accessible to that user.
Usually it's up to the developer to enforce the check on the route level. However, people might forget to do so, resulting in the Custom Application (route) to be available to users even though they shouldn't have permissions to do so.
To enforce that as a default, this check is now performed within the AppShell.
NOTE: if a user does not have permissions, the API requests will fail anyway. This is more of a UX improvement to simply prevent the user to access the application in the first place.
=> feat(app-shell): enforce 'view' permission check for main application route

.changeset/old-ravens-wait.md, packages/create-mc-app/src/parse-arguments.js
Fix compatibility with Node `< v14.18` for reading user input.
closes #2484
=> fix(create-mc-app): fix compatibility with Node < v14.18 for reading user input

.changeset/tender-turkeys-relax.md, packages/application-config/scripts/load-js-module.js, packages/application-config/src/load-config.ts
Running the `mc-scripts start` in a custom application in a Windows OS machine is raising an error related to loading the application config file.
fixes #2486
When the scripts tries to load the configuration file, it tries to execute an [executable *nix script file](https://github.com/commercetools/merchant-center-application-kit/blob/main/packages/application-config/scripts/load-js-module.js) which fails to execute in Windows OS.
Since this is actually a javascript file, we can just change it to not execute the file itself but running it using the `node` command.
=> Fix application config file loading in Windows OS

.changeset/odd-rivers-impress.md, packages/actions-global/src/actions/show-notification.ts, packages/actions-global/src/hooks/use-show-api-error-notification.ts, packages/actions-global/src/hooks/use-show-notification.ts, packages/actions-global/src/hooks/use-show-unexpected-error-notification.ts, packages/actions-global/src/types.ts, packages/notifications/src/types.ts, packages/react-notifications/src/components/notifier/notifier.spec.tsx, packages/react-notifications/src/components/notifier/notifier.tsx
Some of the types around notifications are currently slightly inaccurate, causing unnecessary type errors.
For example, the notification `id` is internally generated, the user does not need to provide one.
This PR tries to refine these small inaccuracies.
=> refactor: refine notification types

.changeset/beige-bags-refuse.md, packages/eslint-config-mc-app/helpers/rules-presets.js, packages/eslint-config-mc-app/index.js, packages/eslint-config-mc-app/package.json, yarn.lock
Recently we've been seeing this kind of errors when we had to update dependencies.
To try avoiding this as much as possible, I thought it would make sense to remove the `eslint-config-react-app` dependency and include most of its configuration into our own config.
So most of the things are copied over.
=> refactor(eslint-mc-app): merge CRA config to avoid possible ESLint merge errors

.changeset/ninety-elephants-deliver.md, package.json, packages-backend/eslint-config-node/LICENSE, packages-backend/eslint-config-node/README.md, packages-backend/eslint-config-node/helpers/eslint.js, packages-backend/eslint-config-node/index.js, packages-backend/eslint-config-node/package.json, yarn.lock
This is a slightly simpler/different ESLint config for Node.js projects. We can use this in our backend services.
=> feat: add new `eslint-config-node` for Node.js projects

.changeset/funny-beds-sin.md, .github/workflows/main.yml, packages/mc-scripts/package.json, yarn.lock
Caused by #2528
Ref: https://github.com/facebook/react/pull/24235
=> fix(mc-scripts): downgrade react-refresh to v0.11.0

.changeset/funny-crabs-applaud.md, packages/babel-preset-mc-app/create.js
Sometimes we get an error like `Cannot find module @emotion/babel-preset-css-prop`.
Usually this relates to how dependencies are hoisted in `node_modules`.
I noticed though that we weren't using `require()` to resolve the babel preset. This now should hopefully fix that problem.
=> fix(babel): flaky resolution of emotion babel preset

.changeset/warm-actors-taste.md, packages/application-components/src/components/internals/page.styles.ts
=> fix(components): tab page itself should not scroll

.changeset/stupid-gorillas-attend.md, packages/application-config/src/transformers.ts, packages/application-config/test/process-config.spec.js, packages/application-shell/src/hooks/use-applications-menu/use-applications-menu.spec.tsx, packages/application-shell/src/hooks/use-applications-menu/use-applications-menu.ts
I was testing the CLI `config:sync` and noticed an inconsistency.
Currently, the API expects the submenu link `uriPath` to contain the full uri path (including the `entryPointUriPath`). For example, if the `entryPointUriPath` is `avengers`, a submenu link can be `avengers/new`.
However, for simplicity in both the MC UI and in the local Custom Application config, the user only needs to provide the value relative to the `entryPointUriPath`. This avoids having to re-enter the `entryPointUriPath` for every submenu link and to avoid possible typos.
This logic of computing the full uri path is already defined in the MC UI form and in the app shell, when rendering the navigation menu.
However, it was not defined in the application config, which is also used for the `config:sync` command.
This PR …
=> fix(config): compute submenu link `uriPath` when parsing local config

.changeset/hungry-bulldogs-joke.md, cypress/integration/playground/application-shell.js, cypress/integration/playground/notifications.js, cypress/integration/playground/state-machines.js, cypress/support/urls.js, packages/application-components/package.json, packages/application-components/src/components/portals-container/portals-container.tsx, packages/application-shell/src/components/application-shell/application-shell.tsx, packages/react-notifications/src/components/notifications-list/index.ts, packages/react-notifications/src/components/notifications-list/notifications-list.styles.ts, packages/react-notifications/src/components/notifications-list/notifications-list.tsx, packages/react-notifications/src/index.ts, playground/custom-application-config.mjs, playground/src/components/notifications-playground/index.js, playground/src/components/notifications-playground/notifications-playground.js, playground/src/routes.js, yarn.lock
Follow up of #2549 and #2541
Using fixed positioned layout for modal pages had obviously some consequences, for instance how the layout adjusts itself when notifications are rendered on a page.
With the fixed position we now need to adjust the offset/top positions, which are based on the heights of the notifications (global + page).
To calculate the heights we're using now a `ResizeObserver` to update the position whenever the notifications are rendered/removed.
To avoid possible regressions in the future I also added some e2e + percy tests using some new custom pages in the playground app.
=> fix: offset calculation of modal pages when notifications are opened

.changeset/fair-poets-watch.md
Mention using the codemod when enabling Vite bundler.
=> docs: improve changelog

.changeset/three-ways-peel.md, packages/application-components/src/components/portals-container/portals-container.tsx
Using `defaultProps` with `forwardRef` results in the type declarations to ignore the `defaultProps`. Therefore, the default props are typed as optional and we initialize the values with the default values within the component.
=> fix(components): type declarations for `<PortalsContainer>`

.changeset/polite-jars-fix.md, packages/application-config/schema.json
Improve regex for Entry Path Url to accept at least 2 alphanumeric characters.
Currently, the regex to validate the entryPointUriPath seems to prevent at least 2 characters. Find more information [here](https://jira.commercetools.com/browse/SHIELD-474)
=> Improve regex for Entry Point Uri Path to accept at least 2 characters

website/src/content/api-reference/commercetools-frontend-application-shell-connectors.mdx
The docs team has decided to change example email addresses in our docs to ensure that they use a domain that is suited for documentation purposes ([Issue](https://github.com/commercetools/commercetools-docs/issues/1998), [PR](https://github.com/commercetools/commercetools-docs/pull/2000)).
The goal was to amend any cases of example emails within the Custom Applications docs to fit the initiative.
In most cases, the example email should be [email@example.com](mailto:email@example.com), but anything on the [example.com](http://example.com/) domain would be acceptable.
**The regex used** to search for the email addresses: `[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+`
=> fix (docs): change domain for example emails

website/src/content/api-reference/application-config.mdx, website/src/content/api-reference/commercetools-frontend-application-shell-connectors.mdx, website/src/content/concepts/integrate-with-your-own-api.mdx, website/src/content/concepts/merchant-center-api.mdx, website/src/content/concepts/oauth-scopes-and-user-permissions.mdx, website/src/content/development/data-fetching.mdx, website/src/content/index.mdx, website/src/content/migrating-from-project-level-custom-applications.mdx, website/src/content/what-is-a-custom-application.mdx
Renamed Platform-related terms following the rebranding.
With a new Portfolio strategy for the company, some renaming of the used terms was done. For instance, the term "Platform" was replaced with the term "Composable Commerce".
As a result, all "Platform"-related text was replaced in the Custom Application documentation. The affected sentences were rephrased accordingly. Used the [existing PR](https://github.com/commercetools/commercetools-docs/pull/2007) for the rest of the documentation as a reference.
=> fix (docs): renamed platform-related terms

.changeset/fuzzy-comics-visit.md, packages/mc-dev-authentication/src/create-mc-dev-authentication-middleware.ts, packages/mc-scripts/src/config/webpack-dev-server.config.js
=> fix(mc-scripts): local login dev for internal usage

.changeset/bright-numbers-check.md, packages/application-components/src/components/public-page-layout/public-page-layout.tsx, visual-testing-app/package.json, visual-testing-app/src/components/public-page-layout/public-page-layout.visualroute.tsx, visual-testing-app/src/components/public-page-layout/public-page-layout.visualspec.ts, yarn.lock
Children in PublicPageLayout component are not correctly aligned when using a long legal message.
Provided children to PublicPageLayout component have a container with a fixed width but the legal message that can be rendered below does not. So if that message is too long, both contents do not align well.
Example:
We used the same with for the legal message to avoid this problem.
An alternative could be to allow different widths and use a center alignment between the children and the legal message.
=> Align children and legal message of PublicPageLayout component

.changeset/flat-hounds-switch.md, .github/workflows/docs.yml, packages/application-shell/src/components/app-bar/app-bar.tsx
Update the link for the logo in the topbar (top left corner) to be a native one
The link currently does a client-side redirect, which eventually ends up in a full page redirect anyway.
Also, it will help with some errors we've seen in Sentry.
closes #1832
=> Use a native link for top bar logo

.changeset/lazy-beds-matter.md, packages/mc-scripts/src/commands/build-vite.js, packages/mc-scripts/src/commands/start-vite.js
=> refactor(mc-scripts): allow to load a custom Vite config

.changeset/angry-days-swim.md, packages/application-shell-connectors/package.json, packages/application-shell-connectors/src/components/project-extension-image-regex/index.ts, packages/application-shell-connectors/src/components/project-extension-image-regex/project-extension-image-regex.spec.tsx, packages/application-shell-connectors/src/components/project-extension-image-regex/project-extension-image-regex.tsx, packages/application-shell-connectors/src/index.ts, yarn.lock
Create react hook to access Project's images URLs rewrite rules configurations  information from context.
See more on ticket here: https://github.com/commercetools/merchant-center-application-kit/issues/2571
=> Create a new React hook to access Projects Images rewrite configuration

website/src/content/concepts/merchant-center-proxy-router.mdx, website/src/content/development/going-to-production.mdx
This is a proposal to update the docs regarding the MC Proxy Router on how it forwards request to external deployed Custom Applications since we had several issues about it.
The idea is to further explain how MC Proxy Router forwards request to Custom Applications so users understand why they need to configure URL forwarding in their end.
We need their deployments to have this kind of setup where every request to the Custom Application configured URL must return the `index.html` file of their app, no matter what pathname is in the URL request.
[This is the preview link](https://appkit-pr-2645.commercetools.vercel.app/custom-applications/concepts/merchant-center-proxy-router) for the updated page.
=> Update MC Proxy Router docs to explain URL rewrites

.changeset/slimy-apples-grab.md, packages/mc-html-template/html-docs/application.html
Remove *user-scalable=no* property from `viewport` meta tag as it is a problem from the accessibility point of view.
One of the findings of the accessibility report is about having a meta tag with *viewport* name that contains a value of *no* for *user-scalable* property.
(_This property only affects zooming in touch screen devices_).
As stated [in the documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag#viewport_basics), this is an accessibility issue we should take care of.
=> Update viewport meta in main html template for applications

.changeset/silver-cobras-switch.md, packages/application-shell-connectors/src/components/project-extension-image-regex/index.ts, packages/application-shell-connectors/src/export-types.ts
This PR solves the issue with importing the `TImageRegexContext` type.
Allows to use:
`import type { TImageRegexContext } from '@commercetools-frontend/application-shell-connectors';`
instead of:
`import type { TImageRegexContext } from '@commercetools-frontend/application-shell-connectors/dist/declarations/src/components/project-extension-image-regex/project-extension-image-regex';`
Noticed while working [on docs](https://appkit-sha-a747a41965c62da2e0904ac906a67c69a185fb99.commercetools.vercel.app/custom-applications/api-reference/commercetools-frontend-application-shell-connectors#withprojectextensionimageregex)
=> chore: export `TImageRegexContext` type from `@commercetools-frontend/application-shell-connectors`

.changeset/quick-plums-wonder.md, packages/application-shell/src/components/application-shell/application-shell.tsx
There are some invalid accessibility aria roles being used in the `ApplicationShell` component.
* We are using a role named **application-layout** which does not exist. The most similar actual role id **application** but I don't think it applies to this use case as it is suitable for elements ["that do not follow a standard interaction pattern"](https://www.w3.org/TR/wai-aria/#application) which I don't think it is the case. So I think we should remove this role altogether.
* We are using a role named **header** (which does not exist) in a **header** element. We must remove that role.
* We are using a role named **aside** (which does not exist) in a **aside** element. We must remove that role.
* We are using a role named **global-notifications** which does not exist. Since the element …
=> Fix ApplicationShell component aria roles issues

.changeset/dry-planes-fry.md, packages/application-components/src/components/tab-header/tab-header.tsx, packages/application-components/src/components/tab-header/tab.styles.ts
Accessibility improvements of the `TabHeader` component.
> Every tab must have a tab aria role and all of them must be direct children of another element with tablist role.
`Lighthouse` benchmark changes (measured for the `visual-testing-app` at `/tabular-main-page`)
Before: 
After:
=> `TabHeader` component accessibility improvements

.github/actions/ci/action.yml, .github/workflows/deployment.yml, .github/workflows/docs.yml, .github/workflows/main.yml, .github/workflows/release.yml
As our CI pipeline is growing with many different things that we need to build and test, having one single workflow takes longer and longer. For example, having a second starter template (#2615 ) will increase the time even more.
As of now, a CI run takes between 15 and 20 minutes.
Using one workflow has some benefits, like installing dependencies and building packages once. However, it's highly sequential even though many steps don't relate with each other.
To speed things up and make our CI more resilient and useful, I experimented a bit with using multiple smaller jobs:
* `lint_and_test`: runs the main typechecking on the repo as well as all linters and tests
* `test_visual`: runs only the VRTs of the UI components
* `test_starter_template`: runs only the build and tests of the starter …
=> 🚀 Speed up CI time by splitting up jobs

.github/ISSUE_TEMPLATE/config.yml
According to the rebranding, changing Platform Support to Support.
=> chore: renamed Platform Support to Support

.changeset/bright-plants-fail.md, LICENSE, packages-backend/eslint-config-node/LICENSE, packages-backend/express/LICENSE, packages-backend/loggers/LICENSE, packages/actions-global/LICENSE, packages/application-config/LICENSE, packages/application-shell-connectors/LICENSE, packages/application-shell/LICENSE, packages/assets/LICENSE, packages/babel-preset-mc-app/LICENSE, packages/browser-history/LICENSE, packages/constants/LICENSE, packages/create-mc-app/LICENSE, packages/eslint-config-mc-app/LICENSE, packages/i18n/LICENSE, packages/jest-preset-mc-app/LICENSE, packages/l10n/LICENSE, packages/mc-html-template/LICENSE, packages/mc-scripts/LICENSE, packages/notifications/LICENSE, packages/permissions/LICENSE, packages/react-notifications/LICENSE, packages/sdk/LICENSE, packages/sentry/LICENSE, packages/url-utils/LICENSE
The copyright year is strictly not required. Keeping the year up to date is also annoying, so it's fine to drop it.
Other open source projects have done the same, for example React: https://github.com/facebook/react/pull/13593.
Alternative would be to use a format like `2017-present`.
=> chore: drop the copyright year from the license files

.changeset/ten-dogs-tickle.md, packages/create-mc-app/src/tasks/update-application-constants.js
To prevent lint errors when installing the template.
=> fix(create-mc-app): formatting of patched constants file

application-templates/starter-typescript/package.json
Fixes the pattern used to extract i18n messages in the `extract-intl` command (script in the `package.json`) for the Typescript starter template.
=> Fix i18n extract command in TS starter template

.changeset/ninety-drinks-relate.md, packages/mc-scripts/src/cli.ts, packages/mc-scripts/src/commands/compile-html.ts, packages/mc-scripts/src/commands/config-sync.ts, packages/mc-scripts/src/types.ts
Small regression of #2613 
The CLI options are now parsed as camelCase with the [parsing library we're using now](https://www.npmjs.com/package/cac).
I totally missed that part of the docs:
=> fix(mc-scripts): parsing of CLI options casing

.github-labelsrc.json, .github/workflows/close-inactive-issues.yml
Add a new GitHub workflow so we can automatically handle those opened issues which we already replied to but the author do not reply back for a long time.
Configuration:
* Requires the issue to have a specific label
* 14 days to mark it as stale
* another 14 days (on top of the previous ones) to close it
=> Add workflow to handle staled issues

website/src/content/concepts/merchant-center-api.mdx, website/src/content/help-needed.mdx
Currently, the documentation doesn't convey any information regarding the expiration period for the token issued by the MC. This question is being asked quite often by customers and various departments internally.
We need to document that the current expiration period for the token issued by the Merchant Center is  30 days.
=> Add information covering session expiration period

cypress/integration/playground/application-shell.ts, packages/application-shell/src/components/authenticated/oidc-callback.spec.tsx
Lately the E2E / Percy tests for the OIDC callback error pages seem to be consistently flaky.
This causes many PRs to fail the snapshot tests.
So instead of snapshot tests, let's just write some simple unit tests.
=> refactor(oidc-callback): replace flaky e2e/vrt tests with unit tests

.changeset/strong-windows-hammer.md, packages-backend/loggers/package.json, packages/sentry/package.json, packages/sentry/src/sentry.spec.ts, yarn.lock
Extracted from #2623
There are no breaking changes that affect us.
=> chore: update Sentry dependencies to `v7`

.github/workflows/docs-content-check.yaml, .github/workflows/main.yml, website/src/content/getting-started.mdx
See https://github.com/errata-ai/vale-action
TL;DR: We will get github inline comments whenever there are writing style errors.
=> ci: add separate workflow for content check, with reviewdog support

website/src/content/deployment-examples/aws-s3-cloudfront.mdx, website/src/content/deployment-examples/azure-static-web-apps.mdx, website/src/content/deployment-examples/azure.mdx, website/src/content/deployment-examples/cloudflare.mdx, website/src/content/deployment-examples/index.mdx, website/src/content/deployment-examples/netlify.mdx, website/src/content/deployment-examples/render.mdx, website/src/content/deployment-examples/surge.mdx, website/src/content/deployment-examples/vercel.mdx, website/src/data/navigation.yaml
PR adds example of Azure deployment in the docs. 
Closes [#2683](https://github.com/commercetools/merchant-center-application-kit/issues/2683)
=> docs: add example of Azure deployment with Static Web Apps

.changeset/many-balloons-appear.md, packages/constants/src/constants.ts, packages/mc-html-template/src/process-headers.spec.ts
Just moving this from the proxy router config, to avoid duplication.
=> refactor: to add `includeSubDomains` directive to STS header

.changeset/blue-cougars-worry.md, .changeset/thick-knives-tan.md, packages/application-shell/src/apollo-links/header-link.ts, packages/application-shell/src/configure-apollo.ts, packages/application-shell/src/types/generated/ctp.ts, playground/package.json, playground/src/apollo-client.js, playground/src/components/entry-point/entry-point.jsx, playground/src/components/state-machines-list/fetch-states.ctp.graphql, playground/src/components/state-machines-list/state-machines-list.jsx, playground/src/components/state-machines-list/state-machines-list.spec.js, schemas/ctp.json, yarn.lock
I've seen a couple of apps using the [apollo-link-rest](https://www.apollographql.com/docs/react/api/link/apollo-link-rest) to use Apollo but for REST requests via the `@rest` directive.
However, most of our Apollo configuration is managed internally and not exposed to, for example, let users create their own Apollo client. It's also important that the Apollo requests are properly configured, for example to include the necessary HTTP headers.
To making it easier to use the `apollo-link-rest`, we can allow users to pass this link as an option to [createApolloClient](https://docs.commercetools.com/custom-applications/api-reference/commercetools-frontend-application-shell#createapolloclient).
The main reason for being so specific is that this link (and the other internal links) must be …
=> refactor: add basic support for `apollo-link-rest` and provide example implementation

.changeset/pretty-wolves-drive.md, packages/application-shell/src/apollo-links/header-link.spec.js, packages/application-shell/src/apollo-links/header-link.ts, packages/application-shell/src/configure-apollo.ts, packages/application-shell/src/export-types.ts, packages/application-shell/src/utils/apollo-client-runtime-cache.ts, packages/application-shell/src/utils/apollo-context.ts, packages/application-shell/src/utils/http-client.spec.ts, packages/application-shell/src/utils/http-client.ts, packages/application-shell/src/utils/select-user-id/select-user-id.ts
Ref #2732
This PR iterates on the recent addition for the HTTP client utils #2734 
When using the `/proxy/forward-to` endpoint there are additional configuration headers to be provided.
Similarly to what we already have for the Apollo client [createApolloContextForProxyForwardTo](https://docs.commercetools.com/custom-applications/api-reference/commercetools-frontend-application-shell#createapollocontextforproxyforwardto), we enhance the `executeHttpClientRequest` config to support the `forwardToConfig`.
Since we now have most of the same logic in the Apollo client, I refactored things a bit to use the HTTP utils in the Apollo client, to avoid duplication.
=> feat(app-shell): enhance http utilities to configure custom HTTP clients for `/forward-to` endpoint

.changeset/odd-years-think.md, packages/l10n/src/index.ts, packages/l10n/src/localize.spec.ts, packages/l10n/src/localize.ts, playground/src/apollo-client.js
Similarly to the existing function `applyTransformedLocalizedFields`, we were missing the one for the opposite behavior.
=> feat(l10n): add `applyTransformedLocalizedStrings` utility function

.yarn/patches/babel-plugin-typescript-to-proptypes-npm-1.4.2-81920f5edd.patch, package.json, scripts/postinstall.sh, yarn.lock
Using the built-in [yarn patch](https://yarnpkg.com/cli/patch) functionality instead of the third-party `patch-package`.
=> refactor: use Yarn patch instead of patch-package

package.json, yarn.lock
Updates [@percy/cli](url) dependency from version `1.1.4` to `1.9.1`.
There's also an update available for package [@percy/cypress](https://togithub.com/percy/percy-cypress) from version `3.1.1` to `3.1.2` but I'm not including it here since that [changes cypress usage to v10](https://github.com/percy/percy-cypress/releases/tag/v3.1.2) which we are not using yet so I think it's better having a separate PR for those two packages combined.
=> Update percy dependency

.changeset/unlucky-goats-flash.md, packages/application-config/package.json, yarn.lock
To avoid using conflicting versions of `jsdom` (`v19` vs `v16`) we downgrade our explicit `jsdom` dependency to `v16`.
This is an old version of `jsdom` (latest is `v20`) which is used by `jest-environment-jsdom`.
Since we're still using Jest v27, we can't and probably shouldn't upgrade to latest versions of `jsdom`. Once we are able to upgrade to Jest v28+, we can then upgrade `jsdom` again.
=> chore: downgrade `jsdom` to v16

.changeset/cool-forks-share.md, packages/application-shell/src/utils/http-client.spec.ts, packages/application-shell/src/utils/http-client.ts, website/src/content/api-reference/commercetools-frontend-application-shell.mdx
See https://github.com/commercetools/merchant-center-application-kit/issues/2732#issuecomment-1220331401
=> refactor(app-shell): throw if required `forwardToConfig.uri` option is missing

.changeset/fifty-cows-reflect.md, .changeset/twenty-pears-admire.md, packages/application-shell/src/constants.ts, packages/application-shell/src/utils/http-client.spec.ts, packages/application-shell/src/utils/http-client.ts, packages/sdk/package.json, packages/sdk/src/actions/actions.spec.ts, packages/sdk/src/actions/actions.ts, packages/sdk/src/types.ts, yarn.lock
Allow custom claims in exchange JWT send in forwarded requests to external services.
Allow to request custom claims to be included in the exchange JWT sent from MC Gateway when sending requests from a Custom Application to an external service by using the `/proxy/forward-to` endpoint ([docs](https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api)).
NOTE: _we will have another PR for updating the docs_.
We agreed that requesting the Gateway to include custom claims will be _triggered_ by including a new header (*X-Forward-To-Claims*) with a space separated list of wanted claims (we will only support *permissions* in this first iteration).
In this PR we update our requests helpers to make it easy to include the new helper:
* GraphQL context
* Custom HTTP …
=> Allow to request custom claims in forward-to requests

.changeset/gorgeous-kings-cough.md, packages-backend/express/src/auth.spec.js, packages-backend/express/src/auth.ts, packages-backend/express/src/types.ts
Write (optional) user permissions in `request.session` object when validating an incoming requests in external services.
When using our _auth_ middleware in an external service to validate incoming requests, it read information from the exchange JWT included in the incoming request and writes it into an attribute (called `session`) in the request for consumers to be able to access that info.
Now that the Merchant Center API can include a new public claim with logged in user permissions (when configured at the time of making the request from a Custom Application), the middleware will also read that value and put it into the `request.session` object under a property called *userPermissions*.
The value will be an array of strings with the permissions names.
=> Read optional user permissions claim in backend auth middleware

.changeset/wise-garlics-grow.md, packages-backend/eslint-config-node/index.js, packages/eslint-config-mc-app/helpers/rules-presets.js
In `eslint-plugin-jest` v27 the rule `jest/no-jest-import` has been removed. So it can’t be used in the `eslint-config-mc-app`. Given that it’s not recommended to be used anymore already [here](https://github.com/jest-community/eslint-plugin-jest/releases/tag/v27.0.0) we could remove it already.
This will mean that consumers can update to v27 of `eslint-plugin-jest` already.
=> refactor: to remove jest/no-jest-import rule

.changeset/gold-adults-wonder.md, packages/application-shell/src/components/application-page-title/application-page-title.tsx
Fix page title re-render issue with title still displaying previous location instead of the current one.
Navigating to a new page actually persists the initial value, as a result, returning from a `products/<products_id>` page to say `/products` page, the title would still remain as though it was still in the `products/<products_id>` page instead of updating to the new location, in this case, `/products` .
=> Fix page title re-render issue with title still displaying previous location.

.changeset/mighty-files-vanish.md, packages/application-components/src/components/main-pages/custom-form-main-page/custom-form-main-page.tsx, packages/application-components/src/components/main-pages/internals/main-page.styles.ts, visual-testing-app/src/components/custom-form-main-page/custom-form-main-page.visualroute.tsx, visual-testing-app/src/components/form-main-page/form-main-page.visualroute.tsx, visual-testing-app/src/components/info-main-page/info-main-page.visualroute.tsx
Previously, the height of the content was cropped in the layout. This was fixed by allowing the content to take the remaining spaces on the layout. 
This issue was pointed out [here](https://github.com/commercetools/merchant-center-frontend/pull/12782#issuecomment-1241702339)
Before
After
=> refactor(main-pages): Fix customMainPage height

.changeset/green-chefs-judge.md, packages/jest-preset-mc-app/fail-on-console.js, packages/jest-preset-mc-app/setup-test-framework.js, packages/jest-preset-mc-app/setup-tests.js
Some time ago I stumbled upon this library [jest-fail-on-console](https://www.npmjs.com/package/jest-fail-on-console) and I tried it out in our test-data repository (https://github.com/commercetools/test-data/pull/148).
Essentially it does more or less what we were already doing but I noticed the output is more readable. Therefore I tried to implement it in out jest-preset and (partially) replace our own custom implementation.
**Before**
**After**
=> refactor(jest): improve output for console logs warnings

.changeset/dirty-queens-obey.md, packages/application-config/src/formatters.ts, packages/application-config/src/transformers.ts, packages/application-config/src/validations.ts, packages/application-config/test/fixtures/config-full.json, packages/application-config/test/json-schema.spec.js, packages/application-config/test/process-config.spec.js, packages/mc-scripts/src/utils/get-config-diff.spec.ts
Update the CLI to use additional permissions
=> feat(cli): Use additional permissions with config-sync command

.changeset/perfect-yaks-dance.md, package.json, packages/cypress/package.json, packages/cypress/src/add-commands/login.ts, yarn.lock
Follow up of #2823 now that [Cypress v10.9.0](https://docs.cypress.io/guides/references/changelog#&#8203;10-9-0) has added the option `cacheAcrossSpecs` 🥳
=> feat(cypress): enable caching session across spec by default

.changeset/stale-points-divide.md, packages/cypress/package.json, packages/cypress/src/add-commands/login.ts, yarn.lock
=> fix(cypress): backwards compat for version < 10.9.0

website/src/content/api-reference/commercetools-frontend-application-shell.mdx, website/src/releases/2022-09/readable-page-title.mdx
This is a follow up doc improvement of the remaining [feedback]( https://github.com/commercetools/merchant-center-application-kit/pull/2793#discussion_r984436515) from the Readabkle page title documentation PR (already merged)
=> Update readable page title document with  feedback

.changeset/friendly-wolves-buy.md, packages/application-config/src/formatters.spec.ts, packages/application-config/src/formatters.ts, packages/application-config/src/types.ts
Currently the output type of  e.g. `entryPointUriPathToResourceAccesses` function does not work as expected.
The goal of this PR is to fix that. 
I had to refactor a little the `Split` utility type taken from the `type-fest` library to work well in our case.
Refactoring [this test](https://github.com/commercetools/merchant-center-application-kit/blob/af9f6681dcd5d28ba036c5fd07140cbf904a3c52/packages/application-config/src/formatters.spec.ts#L22:L55) to enable static type checking (without any type assertion) turned out to be a bigger challenge than this fix 😕, so I left this test as is.
To play with this PR you might want to use [this playground](https://codesandbox.io/s/typescript-playground-export-forked-u297ue)
=> fix(application-config): enable proper type inference in permission keys and resource accesses formatters

.changeset/tame-llamas-heal.md, packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx, packages/application-shell-connectors/src/components/application-context/application-context.tsx, test-data/user/types.ts
Fixes https://jira.commercetools.com/browse/SHIELD-616
=> fix(application-shell-connectors): prevent Sentry reports when `additionalClaims` value is falsy

.changeset/stale-apes-watch.md, packages/application-config/src/process-config.ts, packages/application-config/test/process-config.spec.js
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19i0jHdJEBrgUEtirTtEAU7l3QjlVc0yE%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=U74fN8l)
When users use an application URL without an ending backslash we add an invalid URL to CSP meta element in compiled HTML when building a Custom Application.
Related to #2851 (end of the thread)
When compiling the main `index.html` file for a Custom Application we add a `meta` element with some CSP directives so we can control from which sources scripts/styles can be loaded.
In those directives we need to include the Custom Application hosting provider public URL since the application is going to be loaded from a commercetools …
=> Fix problem when calculating CSP headers from Custom Application config file

.changeset/lemon-roses-camp.md, packages/application-shell/src/configure-store.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1Dqiph3gpq9veiNK6hiyuZld9OSLU4h88%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Lszhi3H)
Disable dev-only redux immutability check
We've seen some tests randomly failing in the frontend due to [this default check](https://redux-toolkit.js.org/api/immutabilityMiddleware) `redux-toolkit` middleware is adding to our store.
The check tries to make sure you don't mutate your store state directly by traversing all the state tree and it logs a warning to the console if it takes more that 32ms by default.
The message it logs is not very helpful to really understand what is causing the process to take so long.
In the …
=> Disable dev-only redux immutability check

.changeset/smart-ants-wash.md, packages/application-config/src/index.ts, packages/application-config/src/sanitize-svg.ts, packages/application-config/src/ssr.ts, packages/application-config/src/transformers.ts, packages/application-config/test/process-config.spec.js, packages/mc-scripts/src/utils/get-config-diff.ts
I noticed when using the CLI `config:sync` command that the SVG icon was always marked as changed.
The problem is in the fact that the API sanitizes the SVG before saving the data but we were also pre-sanitizing it when the config was parsed. This lead to updates to have run the sanitize 2 times.
Now we don't sanitize when parsing the icon but only during the diffing, so ensure the diffed data is the same.
=> refactor(config): expose `sanitizeSvg` function, fix diffing logic

.changeset/curvy-fireants-hug.md, codegen.mc.yml, graphql-test-utils/graphql-models/user.js, packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx, packages/application-shell-connectors/src/components/application-context/application-context.tsx, packages/application-shell-connectors/src/types/generated/mc.ts, packages/application-shell/src/components/fetch-user/fetch-user.mc.graphql, packages/application-shell/src/test-utils/test-utils.tsx, packages/application-shell/src/types/generated/mc.ts, packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx, packages/permissions/src/types/generated/mc.ts, schemas/client-schema.graphql, schemas/mc.json, test-data/types/generated/mc.ts, test-data/user/generator.ts, test-data/user/types.ts
This PR proposes a `verificationStatus` field following work [from this PR](https://github.com/commercetools/merchant-center-services/pull/2292) within `mc-services`.
One of the goals of the First Contact team is to improve email verification flow for users of the Merchant Center. We have identified that the `User` entity will require a field indicating verification status, which will be eventually implemented by the Distributed Systems team. 
However, we also wanted to get a head start on refactoring components in other Merchant Center applications that will require use of this field.
The goal of this PR is to:
1. Access this field in `ApplicationShell`'s `FetchLoggedInUser` query from the stubbed `mc-services` field, and
2. Expose this field in the `ApplicationShell` connectors for …
=> feat(application-kit): implement `verificationStatus` field

.changeset/proud-ants-flow.md, packages/application-shell/src/components/quick-access/create-commands.ts, packages/application-shell/src/components/quick-access/quick-access.spec.js
This PR aims to fix the product list quick access. Currently the url to which it directs to is `/products/pim-search` which displays the text `We could not find what you are looking for`. In other to solve this, we need to use the real link which is `/products`.
=> PCM-2794: fix quick access to product list

website/linkinator.config.json, website/src/data/top-menu.yaml, website/src/data/top-side-menu.yaml
**This pull request**
changes the top nav frontend links to point to the new frontend websites. 
This will be merged along with the **go live** PR in the docs repo.
https://github.com/commercetools/commercetools-docs/pull/2472
=> `GO LIVE` [Frontend docs migration] Change frontend links in top nav to the new frontend websites :rocket:

.changeset/twenty-wombats-accept.md, packages/application-shell/src/utils/gtm.ts, packages/sentry/src/sentry.ts
Not all environments require Sentry and Google Tag Manager to run. This is usually the case when defining a Custom Application Config without the respective values then being parsed and placed on `window.app`. 
However, in some scenarios we intend to disable Sentry and GTM with a shared Custom Application Config.
The values read in a Custom Application Config and defined as `env:FOO` have to be defined otherwise the script will rightfully throw an error. Whenever a value is set as e.g. `process.env.FOO` it will be parsed and replaced as `"null"`. This string is then coerced before putting it onto the application's context for usage.
The booting of Sentry and GTM however, happens outside of React. As such those values are read from `window.app` and are not covered. So `"null"` and …
=> fix: to allow disabling Sentry and GTM through environment variable

.changeset/lucky-squids-kick.md, packages/application-shell/src/components/application-shell/application-shell.tsx, packages/application-shell/src/components/theme-switcher/index.ts, packages/application-shell/src/components/theme-switcher/theme-switcher.tsx, packages/application-shell/src/feature-toggles.ts
Prepare the theme to be switched based on a feature flag. This will be used initially for testing purposes only.
=> refactor(app-shell): render theme based on feature flag

.changeset/spicy-actors-roll.md, packages-backend/loggers/package.json, packages/sentry/package.json, packages/sentry/src/sentry-user-logout-tracker/sentry-user-logout-tracker.tsx, packages/sentry/src/sentry-user-tracker/sentry-user-tracker.spec.tsx, packages/sentry/src/sentry-user-tracker/sentry-user-tracker.tsx, packages/sentry/src/sentry.spec.ts, packages/sentry/src/sentry.ts, yarn.lock
This PR enables [Performance monitoring](https://docs.sentry.io/product/performance/) within Sentry, to help use monitoring important metrics within one tool.
As a follow up we can stop sending performance metrics to our own custom endpoint `/metrics`.
=> refactor(sentry): enable performance tracing

.changeset/rude-cups-scream.md, packages/mc-scripts/src/config/create-webpack-config-for-development.ts, packages/mc-scripts/src/config/create-webpack-config-for-production.ts
Leftover of #2883 
Instructs Webpack to treat `*.css` file imports as side effects.
References:
* https://github.com/facebook/create-react-app/pull/5197
* https://github.com/webpack/webpack/issues/6571
PS: interestingly enough, Vite handles this automatically.
=> fix(mc-scripts): treat `*.css` imports as side effects

.changeset/tough-avocados-shop.md, packages/application-shell/src/components/navbar/legacy-icons/box.tsx, packages/application-shell/src/components/navbar/legacy-icons/cart.tsx, packages/application-shell/src/components/navbar/legacy-icons/gear.tsx, packages/application-shell/src/components/navbar/legacy-icons/list-with-search.tsx, packages/application-shell/src/components/navbar/legacy-icons/speedometer.tsx, packages/application-shell/src/components/navbar/legacy-icons/tag-multi.tsx, packages/application-shell/src/components/navbar/legacy-icons/tree-structure.tsx, packages/application-shell/src/components/navbar/legacy-icons/user-filled.tsx, packages/application-shell/src/components/navbar/navbar.tsx
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX194YlURFaXRvB3F6cMjU5EyPK4RwVws%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Ih1JkWt)
Restore legacy app named icons
This is a consequence of this PR: #2894.
Over there we removed some legacy icons used in legacy custom applications where you could configure the application icon (to be used in the navigation bar) using a code name.
The new policy is to provide the actual SVG at configuration level and we made an update to MC applications to set it up like this (github.com/commercetools/merchant-center-frontend/pull/13243/).
We catch an issue when deploying the new versions of the applications since their …
=> Restore legacy app named icons

.changeset/lovely-days-kiss.md, packages/sentry/src/sentry.ts
We're getting lots of transaction events which adds to our spending limit. Let's reduce the number of transactions we send.
=> refactor(sentry): decrease transactions sample rate to 5%

website/src/content/api-reference/application-config.mdx, website/src/content/concepts/oauth-scopes-and-user-permissions.mdx, website/src/content/development/permissions.mdx, website/src/releases/2022-12/custom-applications-multiple-permissions.mdx
In preparation for the Custom Applications Multiple Permissions support.
Relates to #2799
=> docs: Custom Applications multiple permissions

.changeset/silent-planets-live.md, packages/application-config/schema.json, packages/application-config/src/schema.ts, packages/application-config/test/fixtures/config-full.json, packages/application-config/test/process-config.spec.js, packages/mc-html-template/src/process-headers.spec.ts, packages/mc-html-template/src/process-headers.ts, website/src/content/api-reference/application-config.mdx
The (experimental) `Feature-Policy` header is deprecated and only the `Permissions-Policy` header should be used instead.
=> fix: remove deprecated and experimental support for `Feature-Policy` header

.changeset/dry-crabs-joke.md, packages/application-components/src/theming.ts, packages/application-shell/src/components/app-bar/app-bar.tsx, packages/application-shell/src/components/locale-switcher/locale-switcher.tsx, packages/application-shell/src/components/project-switcher/project-switcher.tsx, packages/application-shell/src/components/user-settings-menu/user-settings-menu.tsx, packages/application-shell/src/constants.ts
I already checked with @FilPob and is approved from his side.
=> refactor: apply new design tokens for appbar and user menu

.changeset/selfish-timers-teach.md, packages/application-components/src/components/page-content-containers/page-content-narrow/page-content-narrow.tsx
Update `PageContentNarrow` max width
After first reviews in MC frontend, UX wanted to make the maximum width of the `PageContentNarrow` component a little bigger (=> **742px**).
=> Update `PageContentNarrow` max width

.changeset/gentle-foxes-explain.md, packages/application-components/src/components/public-page-layout/public-page-layout.tsx
Updates the `PublicPageLayout` Container's padding from `padding-top: ${customProperties.spacingXl};` 
to `padding: ${customProperties.spacingXl} 0;` per conversation [here](https://commercetools.slack.com/archives/CCL83RA06/p1673993172112769).
|Before|After|
|----|----|
|![Screenshot 2023-01-18 at 9 06 57 AM](https://user-images.githubusercontent.com/49931992/213237784-b0fc9fcc-09e5-4813-a1ba-0f0a46b400f3.png)|![Screenshot 2023-01-18 at 9 06 09 AM](https://user-images.githubusercontent.com/49931992/213237918-565cb498-e657-41af-9e9a-940c865dcb0c.png)|
=> fix(PublicPageLayout): add padding-bottom

.changeset/gorgeous-files-judge.md, packages/react-notifications/package.json, packages/react-notifications/src/components/notification/notification.styles.ts, packages/react-notifications/src/components/notification/notification.tsx, yarn.lock
Update notifications ui for the redesign
Adjusted notifications styles for them to look as expected in both the current and the new theme.
Default theme:
New theme:
=> Update notifications ui for the redesign

.changeset/rich-jokes-grow.md, packages/application-components/src/components/page-content-containers/page-content-wide/page-content-wide.spec.tsx, packages/application-components/src/components/page-content-containers/page-content-wide/page-content-wide.tsx, visual-testing-app/src/components/page-content-container-wide/page-content-container-wide.visualroute.tsx, visual-testing-app/src/components/page-content-container-wide/page-content-container-wide.visualspec.ts
Update `PageContentWide` to render all its children in single-column mode.
The way this component was implemented counted on consumers to provide only one children when using it for rendering a single columns, so it only rendered its first children and skip any other one received.
Since this is causing some issues with its adoption (people having to provide a fragment wrapper over existing children to be used within the `PageContentWide`), we're changing its behaviour for it to render all received children when using a single column.
When using two columns, the component will still render just the first two received children (and skip any other it might receive).
=> Update `PageContentWide` to render all its children in single-column mode

website-components-playground/src/components/modal-controller.tsx, website-components-playground/src/components/playground-controller.tsx, website-components-playground/src/pages/confirmation-dialog.tsx, website-components-playground/src/pages/custom-form-modal-page.tsx, website-components-playground/src/pages/form-dialog.tsx, website-components-playground/src/pages/form-modal-page.tsx, website-components-playground/src/pages/info-dialog.tsx, website-components-playground/src/pages/info-modal-page.tsx, website-components-playground/src/pages/tabular-modal-page.tsx
=> fix(docs): use PortalsContainer to correctly render stacked modal pages

vercel.json, website-components-playground/src/application.tsx, website-components-playground/src/hooks/use-window-height.ts, website-components-playground/vite.config.js, website/src/components/playground.js
Regression for serving the components playground pages.
I don't since when we had this regression to be honest. We switched the components playground to use Vite back in november #2879 but it seems weird to me that nobody noticed that in 3 months.
Anyway, this is a quick fix, we need to reconsider a bit the page structure and how we want to handle the playground components.
=> fix: use base path for playground app

.changeset/good-foxes-wonder.md, packages/application-components/src/components/public-page-layout/public-page-layout.tsx
The `PublicPageLayout` is used internally mainly on the login pages. With the redesign the text alignment on the header and the spacing on the footer (legal message) should change.
There are different ways to achieve this:
1. Add `props` such as `welcomeMessageTextAlignment` and `legalMessageScale`
2. Using `themedValue` for old and new spacings
I wanted to suggest 2. first. I don't see any reason we should allow different text alignments in the header nor different paddings of the legal message to the top.
=> refactor: change spacing on page-content-layout

.changeset/five-chairs-greet.md, packages/application-components/src/components/page-content-containers/page-content-wide/page-content-wide.tsx
Add `themeParentSelector` prop to `PageContentWide`.
It's needed for the MC `WelcomePage` refactor.
=> refactor(application-components): add `themeParentSelector` prop to `PageContentWide`

.changeset/thirty-countries-happen.md, packages/application-shell-connectors/src/types/generated/mc.ts, packages/application-shell/src/components/application-entry-point/application-entry-point.tsx, packages/application-shell/src/components/application-shell-provider/application-shell-provider.tsx, packages/application-shell/src/components/application-shell-provider/use-coerced-environment-values.ts, packages/application-shell/src/components/application-shell/application-shell.tsx, packages/application-shell/src/components/authenticated/authenticated.spec.tsx, packages/application-shell/src/components/authenticated/authenticated.tsx, packages/application-shell/src/components/authenticated/oidc-callback.tsx, packages/application-shell/src/components/fetch-project/fetch-project.mc.graphql, packages/application-shell/src/components/fetch-project/fetch-project.tsx, packages/application-shell/src/components/fetch-user/fetch-user.tsx, packages/application-shell/src/components/navbar/navbar.tsx, packages/application-shell/src/components/project-container/project-container.tsx, packages/application-shell/src/components/project-suspended/project-suspended.spec.js, packages/application-shell/src/components/quick-access/index.tsx, packages/application-shell/src/components/quick-access/quick-access.tsx, packages/application-shell/src/components/service-page-project-switcher/service-page-project-switcher.spec.js, packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.tsx, packages/application-shell/src/components/suspended-route/suspended-route.tsx, packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.ts, packages/application-shell/src/hooks/use-applications-menu/use-applications-menu.ts, packages/application-shell/src/test-utils/test-utils.spec.tsx, packages/application-shell/src/types/generated/mc.ts, packages/constants/src/constants.ts, packages/permissions/src/types/generated/mc.ts, schemas/mc.json, test-data/types/generated/mc.ts, visual-testing-app/src/application.tsx
Extracted from #2821
* The generic type argument `AdditionalEnvironmentProperties` is not really used and needed by the internal components. Let's remove it.
* Renamed some types for component props.
* Refactored `<Route>` components to render as children ([as recommended when upgrading to v6](https://reactrouter.com/en/main/upgrading/v5)).
=> refactor: clean up unnecessary props and types, refactor `<Route>` to always render as children

.changeset/gentle-bats-begin.md, packages/babel-preset-mc-app/create.js
Based on this: https://jamie.build/last-2-versions
=> fix(babel-preset): refine browser targets

.changeset/hip-beers-cry.md, .changeset/late-donkeys-film.md, .changeset/polite-squids-argue.md, application-templates/starter-typescript/src/load-messages.ts, application-templates/starter/src/load-messages.js, packages/application-config/src/substitute-variable-placeholders.ts, packages/application-config/test/fixtures/i18n/data/de.json, packages/i18n/README.md, packages/i18n/src/async-locale-data/async-locale-data.spec.tsx, packages/i18n/src/async-locale-data/async-locale-data.tsx, packages/i18n/src/async-locale-data/use-async-intl-messages.ts, packages/i18n/src/export-types.ts, packages/i18n/src/index.ts, packages/i18n/src/load-i18n.ts, packages/i18n/src/utils.ts, playground/src/messages.js
As we're looking into adopting [Transifex's Structured JSON format](https://help.transifex.com/en/articles/6220899-structured-json), we can provide better support for it in our tools.
=> feat(config): support loading intl messages that use TX Structured JSON format

.changeset/lucky-apricots-camp.md, packages/application-components/src/components/public-page-layout/public-page-layout.tsx
Missed this requirement a few days ago when making changes to the login page design.
Old theme:
New theme:
=> chore(appkit): use `Text.Detail` for login page footer

.changeset/weak-poets-drive.md, packages/application-shell/src/components/navbar/navbar.mod.css
For long labels, when the menu is collapsed and hovered, the main menu label overflows with the submenu items.
Before
Due to limitations in how the navbar menu is implemented, we need a workaround to fix this edge case. We can set a max height for the main menu label to approx 2 lines, after which it gets truncated. This way we control the spacing with the submenu items.
The truncation is done using the [`-webkit-line-clamp`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp) CSS property, which is [supported by all browsers](https://caniuse.com/css-line-clamp).
After
=> fix(app-shell): spacing for long label in menu items

website/src/content/help-needed.mdx
Remove the Cache limitation part of the docs in the [help-needed section.](https://docs.commercetools.com/custom-applications/help-needed#configuration-changes-to-the-custom-application-are-not-reflected-immediately)
=> refactor(docs): remove limitation for cache in docs

.changeset/moody-glasses-tell.md, application-templates/starter-typescript/package.json, package.json, packages/application-components/src/components/internals/page-header-title.tsx, packages/codemod/package.json, playground/package.json, yarn.lock
No breaking changes are expected for us.
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/#breaking-changes-and-deprecations
=> chore: update typescript to v5

.changeset/five-coats-thank.md, cypress/e2e/playground/application-shell.cy.ts, packages/application-shell/src/components/navbar/menu-items.tsx, packages/application-shell/src/components/navbar/navbar.mod.css
Having in mind [the regression we had yesterday](https://github.com/commercetools/merchant-center-application-kit/pull/3046) with the pop up submenu when the navbar is collapsed I thought about adding a test to prevent this in the future.
=> test: prevent regressions with scrollable menu

.changeset/four-seas-do.md, packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.spec.tsx, packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.tsx
`useShowApiErrorNotification` from `@commercetools-frontend/actions-global` is not properly formatting `DuplicateField` errors.
The following (broken) message is rendered in Standalone Prices web app when rendering a `DuplicateField` error with the `useShowApiErrorNotification` hook.
=> fix: add special format for DuplicateField error

website/src/content/api-reference/commercetools-frontend-application-shell.mdx
As pointed out by peers, the table on [@/application-shell](https://docs.commercetools.com/custom-applications/api-reference/commercetools-frontend-application-shell#options) page overflows it's parent container. Moreover, the content makes the table look sparse as the `description` column is densely packed.
As a solution, we'll reformat the tables on this page for better readability and fix the overflow issues as a result.
**Preview**: https://appkit-pr-3045.commercetools.vercel.app/custom-applications/api-reference/commercetools-frontend-application-shell
=> docs: Fix formatting to avoid table content overflow

.changeset/gold-tips-push.md, .github/workflows/main.yml, packages/mc-scripts/src/commands/build-vite.ts
Until now Vite (Rollup) had some issues when running production builds with the [sourcemaps option](https://vitejs.dev/config/build-options.html#build-sourcemap) activated.
You can read a bit the thread here: https://github.com/vitejs/vite/issues/2433
However, yesterday an attempt to mitigate this issue was released in Rollup: https://github.com/vitejs/vite/issues/2433#issuecomment-1363786257
The fix is opt-in via the `cache` option of Rollup by turning it off. To quote the outcome:
> The memory still scales proportionately to the number of files, but it should consume less memory per file now.
Let's try it out then!
=> fix(mc-scripts): support prod sourcemaps when using Vite

.changeset/quick-scissors-melt.md, packages/cypress/src/add-commands/login.ts
With the redesign turned on for GCP EU (where our e2e tests run) we have the announcement dialog popping up, which we need to hide.
To keeps things simple, we simply set the localstorage flag during the cypress login command.
=> fix(cypress): hide redesign announcement

website/src/content/api-reference/commercetools-frontend-application-shell-connectors.mdx, website/src/content/concepts/merchant-center-api.mdx, website/src/releases/2023-02/support-sso-login-local-development.mdx
Fix the broken link to MC SSO because we remove `beta` from the URL.
=> docs: fix broken links to MC SSO

packages/jest-stylelint-runner/package.json, pnpm-lock.yaml
In #2976 (not sure why) I added a peer dep in the `jest-stylelint-runner` package. This causes changeset to consider it as a breaking change, which we don't want / need, so removing the peer dep should restore the normal behavior.
=> fix: remove peer dependency (regression)

.changeset/unlucky-worms-sniff.md, packages/application-shell/src/components/authenticated/oidc-callback-error-page.tsx
We forgot to apply the new design to the oidc callback error page, as it's rendered "outside" the main application shell rendering path.
=> fix: apply new design to oidc callback error page

website/src/content/concepts/merchant-center-api.mdx, website/src/data/top-side-menu.yaml
We recently changed the status homepage to: https://status.commercetools.com. This PR applies the same change on the status link on Custom Apps documentation website.
=> docs: update top-menu status link 

.changeset/thirty-beans-occur.md, packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.tsx, packages/application-components/src/components/dialogs/form-dialog/form-dialog.tsx, packages/application-components/src/components/dialogs/info-dialog/info-dialog.tsx, packages/application-components/src/components/dialogs/internals/dialog-container.tsx, packages/application-components/src/components/dialogs/internals/dialog.styles.ts, packages/application-components/src/theming.ts, visual-testing-app/src/components/confirmation-dialog/confirmation-dialog.visualroute.tsx, visual-testing-app/src/components/form-dialog/form-dialog.visualroute.tsx, visual-testing-app/src/components/info-dialog/info-dialog.visualroute.tsx
This PR introduces an `xl` prop to the `FormDialog` component, which translates to a `784px` width. See [this discussion](https://commercetools.slack.com/archives/C03B6NKTA83/p1685023794530089) for context.
=> feat: add new size `16` to dialog components

.changeset/eleven-files-end.md, packages/jest-preset-mc-app/setup-test-framework.js
Support when `process.env.CI` is `undefined`.
Changes in https://github.com/commercetools/merchant-center-application-kit/pull/3086 are not working when `process.env.CI` is evaluated to `undefined`.
=> test(setupFilesAfterEnv): support undefined use case

pnpm-lock.yaml, website/gatsby-config.mjs, website/package.json
Starting `custom-applications` docs in dev mode results in problems with resolving some transitive dependencies after migration to `pnpm`:
```bash
Module not found: Error: Can't resolve 'query-string' in
‘…/merchant-center-application-kit/website/.cache'
Module not found: Error: Can't resolve 'lodash/merge' in
‘…/merchant-center-application-kit/website/.cache'
``` 
From what I found out [the accepted solution](https://github.com/pnpm/pnpm/issues/991#issuecomment-1120101531) is using a special gatsby plugin for that. It's just a proposal, perhaps you have a better idea how to solve that.
Side note:
Adding as a dev dependency as advised here:
https://github.com/Js-Brecht/gatsby-plugin-pnpm/#how-to-install
=> fix(website): resolving transitive dependencies in dev mode

.changeset/old-sheep-thank.md, packages/application-components/src/components/page-content-containers/page-content-wide/page-content-wide.tsx
FIX: The warning will be shown if the first param is `false` so we needed to adjust the condition.
=> `PageContentWide` warning fix

website/README.md, website/src/content/api-reference/commercetools-frontend-application-shell.mdx
A couple weeks ago @ahmehri and I found that you could only provide one of store, storeState or sdkMocks to renderAppWithRedux testUtil function while debugging an integration test. We found this requirement in the code comments of test-utils but it wasn't in the documentation.
```
invariant(
!(store && storeState),
'@commercetools-frontend/application-shell/test-utils: You provided both `store` and `storeState`. Please provide only one of them.'
);
invariant(
!(store && sdkMocks.length > 0),
'@commercetools-frontend/application-shell/test-utils: You provided both `store` and `sdkMocks`. Please provide only one of them.'
```
Also I changed the README to say that you need to use pnpm because I got an error when running it with yarn.
=> [docs] Clarifying renderAppWithRedux props requirements

.changeset/fair-peas-pull.md, .github/renovate.json, application-templates/starter-typescript/package.json, application-templates/starter/package.json, package.json, packages/application-shell-connectors/package.json, packages/application-shell/package.json, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/jest-preset-mc-app/package.json, packages/mc-scripts/package.json, playground/package.json, pnpm-lock.yaml
Downgrade `graphql` dependency version
Some users using our `@commercetools-frontend/create-mc-app` to create a new Custom Application are experiencing problems when running the command because of a peer dependency miss match with the `graphql` package.
More info here: #3110 
Our starter templates rely on the [eslint-plugin-graphql](https://github.com/apollographql/eslint-plugin-graphql/tree/master) package to add static validation to graphql mutations and queries.
This package uses the `graphql` one as a peer dependency and the one we are currently using is `16.x` which [is not supported](https://github.com/apollographql/eslint-plugin-graphql/blob/master/package.json#L50) by the former.
We're downgrading our `graphql` version to the latest supported by the plugin (`v15`) as we don't want …
=> Downgrade `graphql` dependency version

.changeset/fresh-lizards-remain.md, packages/create-mc-app/src/tasks/install-dependencies.ts, packages/create-mc-app/src/utils.ts
Fixes #3110 
Refers to comment https://github.com/commercetools/merchant-center-application-kit/pull/3134#issuecomment-1637648922
=> fix(create-mc-app): run `npm install` cmd with `--legacy-peer-deps` option

.changeset/mighty-donkeys-sip.md, packages-backend/loggers/src/formatters/rewrite-fields.ts, packages-backend/loggers/src/loggers.spec.ts
In 90% of the cases you intend to unset the from field when rewriting log field. In the other 10% however you may want to keep the from field.
This use case particularly holds when you want to gracefully migrate fields logged from an old to a new field without breaking dashboards in logging tools.
The process there would be to:
1. Rewrite a field to a new field
2. Keep the old field (feature here)
3. Keep logs ingesting for a while
4. Update all dashboards and saved queries in the logging tool
5. Unset the old from field
Internally this use case is needed when migrating to standardized logging field names
=> feat(packages-backend/loggers): support to not unset from field

.changeset/six-bananas-sort.md, packages/application-config/schema.json, packages/application-config/src/process-config.ts, packages/application-config/src/schema.ts, packages/application-config/test/fixtures/config-oidc.json, packages/application-config/test/process-config.spec.js, packages/application-shell/src/components/authenticated/has-cached-authentication-state.ts, packages/application-shell/src/components/redirect-to-login/redirect-to-login.tsx, packages/application-shell/src/constants.ts, packages/application-shell/src/utils/oidc.ts, packages/constants/src/constants.ts, packages/cypress/src/add-commands/login.ts
Further changes needed to enable Custom App development for non-admins ([ref](https://github.com/commercetools/merchant-center-application-kit/issues/3122))
=> feat(app-shell, app-config): enable sending `application_id` claim

website/src/content/api-reference/application-config.mdx
Added missing cloud identifier for China environment (`aws-cn`) in the [application config page](https://docs.commercetools.com/custom-applications/api-reference/application-config#cloudidentifier) of docs
=> fix: added missing cloud identifier

.changeset/rare-cups-applaud.md, packages/application-config/schema.json, packages/application-config/src/process-config.ts, packages/application-config/src/schema.ts, packages/application-config/src/utils.ts, packages/application-config/test/fixtures/config-oidc-with-team-id.json, packages/application-config/test/process-config.spec.js
Follow up based on review https://github.com/commercetools/merchant-center-application-kit/pull/3143#pullrequestreview-1544844500
=> refactor: reading `applicationId` value from custom application config

.changeset/lemon-horses-count.md, packages/application-components/src/components/custom-views/custom-panel-container/custom-panel-container.tsx, packages/application-components/src/components/custom-views/custom-panel/custom-panel.tsx, packages/application-components/src/components/custom-views/custom-panel/index.ts, packages/application-components/src/components/modal-pages/internals/modal-page-top-bar.tsx, packages/application-components/src/components/modal-pages/internals/modal-page.styles.ts, packages/application-components/src/components/modal-pages/internals/modal-page.tsx, packages/application-components/src/index.ts, playground/custom-application-config.mjs, playground/src/components/custom-views/custom-panel-demo.jsx, playground/src/components/custom-views/index.js, playground/src/routes.jsx, visual-testing-app/src/components/custom-panel/custom-panel.visualroute.tsx, visual-testing-app/src/components/custom-panel/custom-panel.visualspec.ts
This PR introduces a new component (`CustomPanel`) which will be used in the context of the **Custom Views** project.
I thought about two strategies to implement this new component which will contain the customer's custom views when they select to use a sidebar panel.
The first one is try to reuse the same component we use for our modal page components.
This is easier as we don't need to implement everything from the scratch but maybe the transition is not the exact one expected (need to confirm this point). Also, we're extending our current shared `ModalPage` component to include new use cases, making it a little more complex.
The second one is to implement a brand new component.
This one takes a little more time since we need to build everything (maybe we can search for a package that …
=> `CustomPanel` new component

.changeset/afraid-timers-work.md, packages/mc-scripts/src/commands/config-sync.ts, packages/mc-scripts/src/commands/login.ts, packages/mc-scripts/src/utils/auth.ts, packages/mc-scripts/src/utils/graphql-requests.spec.ts, packages/mc-scripts/src/utils/graphql-requests.ts
To ensure that the logic around permissions in the API works, as it relies on the application identifier.
=> fix(mc-scripts): sends the app identifier header when using the MC API

.changeset/popular-trainers-sparkle.md, packages/mc-scripts/package.json, packages/mc-scripts/src/commands/start-vite.ts, pnpm-lock.yaml, visual-testing-app/package.json, website-components-playground/package.json
The issue:
This worked for me.
As an alternative we could downgrade `vite` in the monorepo to `4.1.4`.
=> fix: vite config for playground app

website/src/content/maintenance-guidelines.mdx
Remove the reference to the support policy on the Maintenance guidelines page. For more info: https://github.com/commercetools/commercetools-docs/issues/3606
=> docs: remove support policy section on maintenance guidelines page

.changeset/lazy-jokes-train.md, packages/mc-html-template/html-docs/application.html, visual-testing-app/index.html, website-components-playground/index.html
Adjust Google Fonts loader url.
We've noticed some issues in the text styles of all Merchant Center applications that seems related to how fonts are loaded in the document.
We load fonts using [Google Fonts API v2](https://developers.google.com/fonts/docs/css2?hl=en).
It seems using the `slant` attribute somehow it's making fonts to fail loading the right ones based on the text styles so we're removing it from the loader URL. We didn't notice any downsides from removing this parameter.
Also, we are taking the opportunity to remove `Open Sans` from the loader URL since we're not using it anymore.
=> Adjust Google Fonts loader url

.changeset/tame-lizards-walk.md, packages-backend/loggers/package.json, packages/sentry/package.json, packages/sentry/src/sentry.ts, pnpm-lock.yaml
I noticed that the `@sentry/tracing` library has been deprecated
=> fix(sentry): replace deprecated tracing library

.changeset/yellow-moose-lie.md, packages/mc-dev-authentication/package.json, packages/mc-dev-authentication/src/create-mc-dev-authentication-middleware.ts, packages/mc-dev-authentication/src/routes/logout.ts, packages/mc-scripts/src/vite-plugins/vite-plugin-custom-application.ts, pnpm-lock.yaml
Fixes the issue when developing locally against local API that `response.send` is not a function.
I also refactored the types to use the ones from `connect`, as this is also what [Vite uses for its middlewares](https://vitejs.dev/guide/ssr.html#setting-up-the-dev-server)
=> fix(dev-auth): request / response compatibility

.changeset/hungry-trees-vanish.md, packages/application-components/src/components/main-pages/internals/main-page.styles.ts
Change `MainPageContent` style from margin to padding to avoid cutting off some stylings from it's component's children
The current styling from the `MainPageContent` used in the `CustomFormMainPage` has a margin property to space the container children from external contents but this seems like the property should be padding instead. The current margin property seems to cut of some of the features of the pagination dropdown box shadow. 
Before: 
After:
=> Change <MainPageContent> style from margin to padding

.changeset/stupid-dolphins-decide.md, packages/application-shell/src/components/navbar/navbar.mod.css
The issue was identified by and solution was proposed by @jaikumar-tj.
Many thanks for that 🙇 
|  Before |  After | 
|---|---|
| <img width="348" alt="Screenshot 2023-08-23 at 18 21 27" src="https://github.com/commercetools/merchant-center-application-kit/assets/49066275/b5b84fab-56e1-4f14-a5a7-1f4457495c18"> |  <img width="337" alt="Screenshot 2023-08-23 at 18 22 30" src="https://github.com/commercetools/merchant-center-application-kit/assets/49066275/b618cfab-16c9-4167-90ac-897ecf14d1fc"> |
The root cause is hidden submenu not being removed from the visual flow due to `visibility: hidden`
[Link to demo](https://mc-15223.mc-preview.europe-west1.gcp.escemo.com/test-with-big-data-44/welcome)
=> fix: hidden submenu overflow

packages/application-shell/src/components/navbar/menu-items.tsx, packages/application-shell/src/components/navbar/navbar.mod.css
…ri behaviour
Alternative to fix `NavBar` unexpected behaviour in Safari.
Here I'm trying to refactor the styles to avoid User-Agent sniffing.
Maybe this is not the most elegant solution but it seems to work in Safari, Chrome an Firefox. 
Also, this would be a temporary fix anyway until we implement the new scrolling behaviour for the navbar.
=> Alternative to fix `NavBar` unexpected behaviour in Safari

.changeset/slow-zoos-tap.md, packages/application-shell/src/components/application-shell-authenticated/application-shell-authenticated.tsx, packages/application-shell/src/components/navbar/menu-items.tsx, packages/application-shell/src/components/navbar/navbar.mod.css
|  Before |  After | 
|---|---|
|  ![2023-08-21 18 27 36](https://github.com/commercetools/merchant-center-application-kit/assets/49066275/8a6ed215-35e9-4904-95e7-10b5ba580c69) |  ![2023-08-21 18 28 36](https://github.com/commercetools/merchant-center-application-kit/assets/49066275/53a33a0d-3906-42ab-a8c3-1a1573a5779c) | 
This PR aims at solving an issue with `z-index` of navbar in Safari.
I came a long way to arrive at this solution.
Unfortunately, due to the way we compile navbar CSS styles we can't easily add Safari-targeted styles to https://github.com/commercetools/merchant-center-application-kit/blob/main/packages/application-shell/src/components/navbar/navbar.mod.css
because the respective [Safari-specific class names](https://stackoverflow.com/questions/16348489/is-there-a-way-to- …
=> fix(app-shell): Navbar's z-index in Safari

.changeset/fluffy-tables-notice.md, packages/application-components/src/components/main-pages/internals/main-page.styles.ts, packages/application-shell/src/components/navbar/navbar.mod.css
This PR reverts MainPageContent styling changes due to breaking DataTable styles
Also fixes `z-index` of Navbar's submenu title.
=> fix: styling issues with MainPageContent and Navbar

.changeset/wicked-terms-brake.md, packages/application-shell/src/components/navbar/navbar.mod.css
Apologies for introducing the 🐛 [here](https://github.com/commercetools/merchant-center-application-kit/pull/3188) 🤦‍♂️ 
This PR overwrites styles from the upper rule:
```
.sublist-expanded__active,
.sublist-collapsed__active {
opacity: 1;
display: unset;
text-align: left;
/* stylelint-disable-next-line csstools/value-no-unknown-custom-properties */
background-color: var(--background-color-for-navbar-when-active);
}
.sublist-expanded__active {
display: block;
}
```
=> fix(Navbar): proper sublist indentation when expanded

.changeset/rude-trains-allow.md, packages/application-shell/src/components/navbar/use-navbar-state-manager.ts
Fixing inconsistencies in the Navbar's behavior. Check E2E tests now passing [here](https://github.com/commercetools/merchant-center-frontend/pull/15223)
For more context, currently the Navbar's behavior is somewhat inconsistent. For viewport widths below 1024 px until  `isForcedMenuOpen` is set by clicking the expand button, it sometimes renders with menu expanded and sometimes collapsed (some kind of race condition takes place).
=> fix: use default value for `isForcedMenuOpen`

.changeset/dirty-tomatoes-jump.md, packages/application-shell/src/components/navbar/navbar-new/menu-items.tsx, packages/application-shell/src/components/navbar/navbar-new/navbar.mod.css, packages/application-shell/src/components/navbar/navbar-new/navbar.tsx, packages/application-shell/src/components/navbar/use-navbar-state-manager.ts, packages/application-shell/src/constants.ts
Since now we have a [separate folders](https://github.com/commercetools/merchant-center-application-kit/pull/3198) for new and old navigation, I updated the changes from [previous footer PR](https://github.com/commercetools/merchant-center-application-kit/pull/3191) accordingly.
**The requirements done with this PR stay the same as the previous one:**
- Footer should be sticky on the bottom
- Imported new icons for expander
- New color tokens
- New divider
- Hover effect on the expander
- Change breakpoint when the expander is hidden (less than 1200 px)
**Will be done later:**
- Adjust width and spacings of the footer
- Add correct styling to 'Support' (will be done when changing MenuItem style)
- Space added so that the Faded component doesn’t hide the last MenuItem of the side nav
=> Updating style of navigation footer (part 1)

.changeset/warm-hairs-suffer.md, packages/application-shell/src/components/navbar/navbar-new/menu-items.tsx, packages/application-shell/src/components/navbar/navbar-new/navbar.mod.css, packages/application-shell/src/components/navbar/navbar-new/navbar.tsx, packages/application-shell/src/constants.ts
This PR adds a tooltip with the app name in the collapsed mode of the navbar.
It is deployed [here](https://mc-15303.mc-preview.europe-west1.gcp.escemo.com/main-navigation-test/welcome).
Please note that for now the submenu pops up on click when the navbar is expanded. I assumed the correct behaviour (submenu showing up on hover) will be part of [this](https://commercetools.atlassian.net/browse/SHIELD-884) ticket.
=> refactor(Navbar): Show submenu and a tooltip when collapsed 

.changeset/afraid-ads-punch.md, packages/application-shell/src/components/navbar/navbar-new/menu-items.tsx, packages/application-shell/src/components/navbar/navbar-new/navbar.mod.css
**Spacings changes**
- horizontal padding for the submenu should be 16px
- spacing between the submenu items should be 0px
- spacing between the icon and the label in `menu-item` should be 12px
**Color changes**
- replace `color-primary` with `color-primary-40`
- replace `color-primary-30` with `color-primary`
- replace `color-primary-20` with `color-primary-25`
https://github.com/commercetools/merchant-center-application-kit/assets/52276952/90a8a472-2088-4eb9-8877-25df5a7745b1
=> Small UI improvements

.changeset/many-dryers-camp.md, packages-backend/loggers/package.json, packages-backend/loggers/src/middlewares/create-access-logger.ts, pnpm-lock.yaml
The `request.connection` has been [deprecated in Node since a long time](https://nodejs.org/api/http.html#requestconnection) in favor of `request.socket`.
When accessing `request.ip` or `request.ips` in Express, these methods attempt to resolve the `remoteAddress` using the deprecated `request.connection` (https://github.com/jshttp/forwarded/blob/af3830a175dbe316be3d943f505171c73853eb04/index.js#L46-L50).
Furthermore, the `request.socket` is not guaranteed to be defined as it can be `null` (see https://github.com/nodejs/node/issues/41011 and https://github.com/nodejs/undici/issues/1115).
This PR prevents using `request.ip` or `request.ips` to avoid the outdated implementation and instead attempts to parse these values manually, using the `x-forwarded-for` header.
=> refactor(loggers): avoid using deprecated methods to parse client IP addresses

.changeset/fast-students-look.md, packages/application-shell/src/components/navbar/navbar-new/menu-items.tsx, packages/application-shell/src/components/navbar/navbar-new/navbar.tsx, packages/application-shell/src/components/navbar/use-navbar-state-manager.ts
Create an instance of IntersectionObserver for each menu item only once (at first render) and reuse between re-renders.
We're comparing apples and oranges, but still the profiling results suggest it's at least making things a tad better.
I have no certainty it's the ultimate fix.
At least some garbage collection takes place over time and there are way less JS event listeners.
| Current prod (Welcome app) <br>Old Navbar <br> (that's our baseline) | Current staging (Welcome app) <br >New Navbar  |  Playground app in local prod mode (15 menu items) <br> New Navbar with changes from this PR |
|---|---|---|
|  <img width="401" alt="Screenshot 2023-10-04 at 15 29 51" src="https://github.com/commercetools/merchant-center-application-kit/assets/49066275/4de9213c-5537-45b5-9484-fa39b4a3e4c1"> | …
=> fix(Navbar): performance issues

.changeset/big-mayflies-bake.md, packages/application-shell/src/components/navbar/navbar-new/menu-items.tsx, packages/application-shell/src/components/navbar/navbar-new/navbar.mod.css, packages/application-shell/src/components/navbar/navbar-new/navbar.tsx
In previous work we disabled clicking on the menu item parent when it contained a submenu. 
This could lead to users reporting it as a bug, since it's not straightforward why some menu items are clickable and some not. 
But more importantly custom apps  can have different links from the parent menu item and the first submenu child, so it's a potentially a breaking change.
Therefore, we decided to have all menu items as links and clickable.
=> Menu item as a clickable link

.changeset/gold-countries-rhyme.md, packages/application-shell/src/components/navbar/navbar-new/navbar.tsx
Apologies, In #3247 a bug was introduced 🙈.  We need to make lifecycle of the Navbar dependent on `props.isMenuOpen`. Otherwise the `IntersectionObserver` callback is stale.
You can see it [here](https://mc.europe-west1.gcp.escemo.com/almond-40/welcome) after clicking expand button.
=> fix(Navbar): wrong submenu position on expand button click

.changeset/pretty-glasses-kneel.md, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/navbar/navbar-new/navbar.tsx
The issue was caused by [`aria-owns`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-owns) attribute value not referencing a valid id in DOM 🤯
=> fix(navbar): crashing Chrome tab with DevTools open

.changeset/many-bottles-exercise.md, packages/application-shell/src/components/navbar/navbar-new/menu-items.tsx
This PR hides the navbar on initial render to prevent the glitchy behavior
=> refactor(navbar): prevent glitchy behavior on initial render

.changeset/stupid-camels-allow.md, packages/application-shell/src/components/navbar/navbar-new/menu-items.tsx, packages/application-shell/src/components/navbar/navbar-new/navbar.mod.css
fix issue with NavBar submenu having a border radius at the bottom when expander icon is hovered on, when navbar is collapsed.
Issue:
https://github.com/commercetools/merchant-center-application-kit/assets/19975842/fef4228d-eadf-4921-85e6-7acbfc185fbb
Fix:
https://github.com/commercetools/merchant-center-application-kit/assets/19975842/26000701-2b9e-4c92-ba9a-86a89978c500
=> De fix border bottom nav radius issue when expander icon is hovered on.

.changeset/nine-cows-add.md, packages/jest-preset-mc-app/setup-tests.js
This PR adds `Request` and `Response` to the Fetch API polyfill. Unfortunately `jsdom` [does not provide a way](https://github.com/jsdom/jsdom/issues/1724) to use Node native Fetch API, I used the same approach for the `Headers` class and also exported `Request` and `Response` from `node-fetch`.
This PR will allow running jest tests with `jsdom` env that relies on the Fetch API fixing https://github.com/commercetools/merchant-center-frontend/pull/15461
In [setup-test-framework.js#L2](https://github.com/commercetools/merchant-center-application-kit/blob/main/packages/jest-preset-mc-app/setup-test-framework.js#L2) we are using the `unfetch/polyfill` to export the Fetch function and relying on `node-fetch` to export `Headers`, `Request` and `Response`. I tried to change `unfetch/polyfill` …
=> fix: fetch api polyfill

.github/renovate.json
As elsewhere applying similar fixes here:
1. The order matters for `packageRules`. You go from not important to important as they're evaluated in order and subsequent rules overwrite prior rules (Renovate docs)
2. `sourceUrlPrefixes` has not worked well elsewhere. We can use `matchSourceUrls` instead which works in all other repos
3. Isolate the update of our runtime in Node.js
=> Fix `renovate.json` and order of `packageRules`

packages/application-components/package.json, packages/application-components/src/components/custom-views/custom-views-selector/custom-views-selector.spec.tsx, packages/application-components/src/test-utils/test-utils.tsx, pnpm-lock.yaml
Follow up of #3255 
Using the `@commercetools-frontend/application-shell` as a dev dependency still causes a warning for a circular dependency (app-shell <--> app-components), even though we only use the test utils.
So let's get rid of the dependency again. However, we need to ensure the correct test-utils setup in the application-components package is correct. At the moment we only need to add the `<ApolloProvider>` in order to handle the graphql requests.
Apologies for the back and forth.
=> test(components): define apollo provider

.changeset/giant-papayas-sit.md, packages/application-shell-connectors/src/hooks/apollo-hooks/apollo-hooks.ts
`useMcQuery`, `useMcLazyQuery` and `useMcMutation` accept a `TypedDocumentNode` as query/mutation param.
The goal of this PR is to unblock projects where `@commercetools-frontend/application-shell-connectors` is used and start using [`TypedDocumentNode`](https://the-guild.dev/graphql/codegen/plugins/typescript/typed-document-node).
The idea is to test `TypedDocumentNode` in the Standalone Prices web app and check if it improves DX by reducing the amount of boilerplate code needed to use the hooks.
=> feat: allow `TypedDocumentNode` as a type for query and mutation params in MC Apollo hooks

.changeset/cool-flies-fail.md, packages/application-components/src/hooks/use-custom-view-locator-selector/use-custom-view-locator-selector.spec.tsx, packages/application-components/src/hooks/use-custom-view-locator-selector/use-custom-view-locator-selector.ts, visual-testing-app/src/components/tabular-detail-page/tabular-detail-page.visualroute.tsx, visual-testing-app/src/components/tabular-main-page/tabular-main-page.visualroute.tsx, visual-testing-app/src/components/tabular-modal-page/tabular-modal-page.visualroute.tsx
Fix Custom Views locator hook
There's an issue in the hook we use to calculate the Custom View locator for tab page components based on the URL.
It's configured to match URLs without being exact, which does not allow for using nested routes, which is something we use in MC frontend for tabs URLs.
=> Fix Custom Views locator hook

.changeset/thick-papayas-wave.md, @types-extensions/graphql-settings/index.d.ts, packages/application-components/src/types/generated/settings.ts, packages/application-config/src/generated/settings.ts, packages/application-shell-connectors/src/types/generated/settings.ts, packages/application-shell/src/types/generated/settings.ts, packages/constants/src/generated/settings.ts, packages/mc-scripts/package.json, packages/mc-scripts/src/commands/config-sync.ts, packages/mc-scripts/src/generated/settings.ts, packages/mc-scripts/src/utils/create-custom-view.settings.graphql, packages/mc-scripts/src/utils/fetch-custom-view.settings.graphql, packages/mc-scripts/src/utils/get-config-diff.spec.ts, packages/mc-scripts/src/utils/get-config-diff.ts, packages/mc-scripts/src/utils/graphql-requests.spec.ts, packages/mc-scripts/src/utils/graphql-requests.ts, packages/mc-scripts/src/utils/update-custom-view.settings.graphql, pnpm-lock.yaml, schemas/settings.json
=> feat(mc-scripts): support custom views in the `config:sync` command

.changeset/six-needles-kiss.md, packages/application-shell/src/components/locale-switcher/locale-switcher.tsx, packages/application-shell/src/components/project-switcher/project-switcher.tsx
**Changes with this PR:**
- Removing the counters from both project and locale switchers
- Setting the switchers inputs to `horizontalConstraint={'auto'}` and adjusting the dropdown menu's width
**Before the changes:**
**After the changes:**
=> Project and locale switcher changes

.changeset/cuddly-clouds-pull.md, .changeset/late-masks-fold.md, .changeset/long-insects-marry.md, .changeset/nervous-candles-move.md, custom-views-templates/starter-typescript/src/components/channels/channels.tsx, packages/application-config/src/formatters.spec.ts, packages/application-config/src/formatters.ts, packages/application-shell-connectors/src/components/custom-view-context/custom-view-context.tsx, packages/application-shell/src/components/custom-view-shell/custom-view-shell.tsx, packages/application-shell/src/test-utils/custom-views-utils.tsx
Custom Views context hook adjustment
In this PR I propose refactoring the `useCustomView` hook to not only return the Custom Views context but also the internal Application context. This way, Custom Views developers requirement some data from any of the context can access to them from the same hook (dedicated to Custom Views) without them needing to know we manage two context internally.
=> Custom Views context hook adjustment

.changeset/little-rules-wash.md, .changeset/quick-hats-trade.md, packages/application-components/package.json, packages/application-components/src/components/custom-views/custom-views-selector/custom-views-selector.tsx, packages/mc-html-template/html-docs/application.html, pnpm-lock.yaml, visual-testing-app/index.html, website-components-playground/index.html
This PR changes the UI of the custom views selector component.
It doesn't cover the correct placement of the selector.
https://github.com/commercetools/merchant-center-application-kit/assets/49066275/f7342014-22ae-45fb-88ea-afdb0e5a43e4
The changes can be observed in visual regression tests output 👇.
Open questions:
| designs  | PR  |
|---|---|
|  <img width="175" alt="Screenshot 2023-11-27 at 10 50 32" src="https://github.com/commercetools/merchant-center-application-kit/assets/49066275/8ee45c89-0ce0-4ec7-93fd-de00470e40fb"> | <img width="140" alt="Screenshot 2023-11-27 at 10 43 59" src="https://github.com/commercetools/merchant-center-application-kit/assets/49066275/8cf13199-9092-432f-9827-e32adc8a4299">  |
- for now I haven't changed the icon and the title. 
Regarding the icon, it felt …
=> refactor(custom views selector): ui refinement

.changeset/twenty-files-tie.md, packages/application-components/src/components/drawer/drawer.tsx
When I first added the drawer, I added it with a bug sadly. 
When the drawer has long content the scrollbar doesn't appear to allow the user to see the content in the bottom of the drawer. This PR fixes that by adopting the same behavior from the higher level modal components
=> chore: allow drawer to expand height with a scrollbar

.changeset/angry-apes-marry.md, packages/mc-scripts/src/config/create-webpack-config-for-development.ts, packages/mc-scripts/src/config/create-webpack-config-for-production.ts, packages/mc-scripts/src/vite-plugins/vite-plugin-svgr.ts
> [!NOTE]
> Original PR #3332 but somehow some CI jobs were failing there 🤷‍♂️
Fixes issue where `svgo`'s `cleanupIds` default preset would cause id collisions between different svg files.
For more context see the [svgo docs for cleanupIds](https://svgo.dev/docs/plugins/cleanup-ids/), [this svgo issue](https://github.com/svg/svgo/issues/1746), and [this mc-frontend PR](https://github.com/commercetools/merchant-center-frontend/pull/15854).
=> fix: svgo plugin to use collision resistant IDs

.changeset/four-kids-flow.md, .changeset/hot-parents-study.md, packages/application-components/src/components/modal-pages/internals/modal-page.styles.ts, packages/application-components/src/components/portals-container/portals-container.tsx, packages/constants/src/constants.ts
Custom Views panels are overlapping navigation bar in narrow viewports.
Custom Views panels can have a `small` or `large` size which are defined as a fixed width for them.
The issue we were having is that, by using only fixed values, we get to situations where viewport width is not enough so we run out of space and overlap things:
[Customers - test-project-with-sample-data - Merchant Center.webm](https://github.com/commercetools/merchant-center-application-kit/assets/97907068/6f189232-c3b7-4c54-a556-a69112457199)
The expected behaviour is for the Custom Views panels to have that fixed width as long as there's enough viewport space. Whenever it's not, it should behave like the other modal components and get to a max width. If the viewport is narrower, the panel itself must shrink. …
=> Fix Custom Views panel width behaviour

website-custom-views/src/content/api-reference/cli.mdx, website-custom-views/src/content/concepts/merchant-center-api.mdx, website-custom-views/src/content/concepts/oauth-scopes-and-user-permissions.mdx, website-custom-views/src/content/help-needed.mdx
Fix Custom Views docs links and naming references
Some issues have been spotted in the Custom Views documentation:
* Links to the MC docs need to be verified and updated if necessary.  There are some underlying links under the [Limitations](https://docs-beta-custom-views.commercetools.vercel.app/custom-views/help-needed#limitations) section no longer go to specific sections (because the section name was changed in MC docs) and they default to the top of the page instead. There will likely be other links to the MC docs elsewhere (you know best where they might be) and need to be verified.
* The cards in use in the [Concepts](https://docs-beta-custom-views.commercetools.vercel.app/custom-views/concepts/oauth-scopes-and-user-permissions) section (multiple pages) show "Application Config" and …
=> Fix Custom Views docs links and naming references

.changeset/olive-pots-raise.md, packages/application-components/src/components/internals/page.styles.ts, packages/application-components/src/components/main-pages/internals/main-page.styles.ts, packages/application-shell/src/components/custom-view-shell-authenticated/custom-view-shell-authenticated.tsx, packages/application-shell/src/components/custom-view-shell/custom-view-shell.tsx
In this PR we're tackling some last minute issues found around Custom Views rendering.
These are the issues addressed in this PR:
* Unstyled Page Layout components when rendered within a Custom View
* Routing issues when navigating within a Custom View
* Custom View not including `PortalsContainer` component (required for modals, dialogs,...).
Regarding the last point, I included the component so it does not break the Custom View if a `Dialog`, `Modal` is used, but I don't think this is the solution we want.
Here's an example of how it looks like:
I think it would be better for Custom Views to have a different mechanism for modals and dialogs that we should discuss.
=> Fix Custom Views issues

.changeset/chilled-deers-shout.md, packages/application-components/src/components/internals/page.styles.ts, packages/application-components/src/components/main-pages/internals/main-page.styles.ts, packages/application-shell/src/components/custom-view-shell/custom-view-shell.tsx
Fix Page Layout components scrolling issue
This is a follow-up of #3343, where we updated some styles for page layout components to address a problem when rendering them inside a Custom View which makes them incorrectly manage scroll. Instead of the header to be fixed and the content scrollable, the whole page component is scrollable. It was spotted thanks to MC frontend e2e tests.
The right solution is to include some global styles (that we are including in the host applications) also in the Custom View content iframe.
=> Fix Page Layout components scrolling issue

.changeset/purple-otters-behave.md, .changeset/seven-falcons-turn.md, packages/application-config/src/constants.ts, packages/application-config/src/index.ts, packages/application-config/src/validations.ts, packages/constants/src/constants.ts
To have a single source of truth for validation regex that we use in the MC apps.
=> refactor(constants): expose regex

.changeset/big-beans-grin.md, packages/application-shell/src/components/navbar/menu-items.tsx, packages/application-shell/src/components/navbar/navbar.mod.css, packages/application-shell/src/components/navbar/use-navbar-state-manager.ts
[Deployment link in the MC](https://mc-15795.mc-preview.europe-west1.gcp.escemo.com/adnan-nodejs-test-project/welcome)
To test out, navigate within the Navbar using `Tab` / `Shift` + `Tab`.
This PR introduces keyboard navigation to the Navbar component, adhering to the default browser focus ring color, as discussed with Filip.
~~Known limitation:
Primary limitation is in Firefox, details provided below 👇~~
=> refactor(Navbar): keyboard navigation

.changeset/real-rabbits-scream.md, packages/application-shell/src/components/project-switcher/project-switcher.tsx
This PR improves the Project selector's interface that's too narrow, by setting up the `min-width`. Specifically when users start typing to search in the `SelectInput`.
**Before**:
**After**:
=> Setting up the `min-width` for Project selector

.changeset/happy-trainers-reflect.md, .changeset/large-rats-begin.md, application-templates/starter-typescript/src/components/entry-point/entry-point.tsx, application-templates/starter/src/components/entry-point/entry-point.jsx, custom-views-templates/starter-typescript/src/components/entry-point/entry-point.tsx, custom-views-templates/starter/src/components/entry-point/entry-point.jsx, packages/application-shell-connectors/src/utils/oidc-storage.ts, packages/application-shell/src/components/authenticated/oidc-callback-error-page.tsx, packages/application-shell/src/components/authenticated/oidc-callback.tsx, packages/application-shell/src/components/redirect-to-login/redirect-to-login.tsx, packages/application-shell/src/components/redirect-to-logout/redirect-to-logout.tsx, packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.tsx, packages/application-shell/src/components/redirector/index.ts, packages/application-shell/src/components/redirector/redirector.tsx
Fixes #3361
The actual fix is to move the logic with side effects (e.g. redirects, interacting with storage) within a React `useEffect` (_who would have thought of that_ 🤪). This solves the issue with the component re-rendering due to strict mode as the effect is run once.
Additionally, I found some minor things to adjust to some dev-related pages.
> [!NOTE]
> Also a useful note from the legacy docs:
> Once we upgrade to React 18, we can expect multiple (duplicate) logs in the devtools due to strict mode re-rendering.
=> fix: local login side effects when running in strict mode

.github/workflows/release.yml
I supposed we somehow missed that announcement: https://github.blog/2023-04-19-introducing-npm-package-provenance/
NPM allows to include a [provenance statement](https://docs.npmjs.com/generating-provenance-statements) to increase security:
> [!NOTE]
> You can generate provenance statements for the packages you publish. This allows you to publicly establish where a package was built and who published a package, which can increase supply-chain security for your packages.
See example with Vercel
=> ci: include provenance info when publishing packages

.changeset/rich-grapes-cheat.md, packages/application-shell/src/utils/setup-global-error-listener/setup-global-error-listener.ts, packages/sentry/src/sentry.ts
When a page uses ResizeObserver API, it may occasionally throw "ResizeObserver loop completed with undelivered notifications" (Firefox) or "ResizeObserver loop limit exceeded" (Chrome). The error has weird semantics, it never gets printed to browser console, only gets caught by window.onerror listener (used by the error overlay)
This error is a known false alarm: https://github.com/w3c/csswg-drafts/issues/5488
This PR is to ignore the `ResizeObserver` loop error in sentry.  For more context see [this github issue](https://github.com/vercel/next.js/discussions/51551)
=> FCT 615: suppress ResizeObserver error

website/src/content/deployment-examples/commercetools-connect.mdx, website/src/content/deployment-examples/index.mdx, website/src/data/navigation.yaml
Add documentation for deploying a Custom Application to commercetools Connect.
Preview: https://appkit-pr-3307.commercetools.vercel.app/custom-applications/deployment-examples/commercetools-connect
Original draft: https://docs.google.com/document/d/1-BokqprvJhq-K6w2TbD-0RLQi3mPzD23vl-0rLX-sYA/
=> docs: Add deployment with commercetools Connect

.changeset/cuddly-zoos-hang.md, application-templates/starter-typescript/package.json, application-templates/starter/package.json, custom-views-templates/starter-typescript/package.json, custom-views-templates/starter/package.json, package.json, packages-backend/eslint-config-node/package.json, packages/eslint-config-mc-app/package.json, pnpm-lock.yaml
In noticed plugins start to require this version. I presume it's either due to them having strict peer dependencies by default (🤦🏼) or the version starting to support something in regards to e.g. the flat config format.
In any case it's a simple update which unblocks other things.
=> Update ESLint to v8.56.0

.github/actions/test-template-action/action.yml, .github/workflows/main.yml, cypress.config.ts, packages/cypress/add-commands/index.d.ts, packages/cypress/src/add-commands/index.ts, packages/cypress/src/add-commands/login.ts, packages/cypress/src/task/index.ts, website-custom-views/src/content/api-reference/commercetools-frontend-cypress.mdx
This PR addresses the issue related to [caching processed custom view configs](https://github.com/commercetools/merchant-center-application-kit/pull/3350#discussion_r1429811666).
This approach involves using `entryPointUriPath` for caching Custom App configs (not changing anything here for backwards compatibility) and `entryPointUriPath`-`templateName` combination as the cache key for Custom Views. The template name is expected to be passed as a Cypress environment variable.
=> refactor(e2e): use package name for caching custom views configs

.changeset/fair-trains-brake.md, packages/application-shell/src/components/authenticated/has-cached-authentication-state.ts
Fix issue with login flow in local development
When working locally in a Custom Application, there's a use case when a developer can be blocked in the login page due to cached configuration.
Here is how the issue can be reproduced:
1. Let's say a developer starts working on a Custom Application and, accidentally, the[ project key used to configure the application](https://docs.commercetools.com/custom-applications/api-reference/application-config#envdevelopmentinitialprojectkey) is wrong
2. When starting the Custom Application locally, the login flow will try to log in into that project which does not exist
3. The developer notice it and updates the configuration to use the right project key
4. The developer starts the Custom Application locally again, but the login flow still tries to …
=> Fix issue with login flow in local development

.changeset/spotty-worms-check.md, packages/application-shell/src/components/navbar/main-navbar.styles.ts, packages/application-shell/src/components/navbar/menu-items.styles.ts, packages/application-shell/src/components/navbar/menu-items.tsx, packages/application-shell/src/components/navbar/navbar.tsx, packages/application-shell/src/components/navbar/shared.styles.ts, packages/application-shell/src/constants.ts
[Deployment link](https://mc-15822.mc-preview.europe-west1.gcp.escemo.com/)
This PR resolves tech debt by migrating navbar styles from globally applied classname-based styles within `<Global>` to encapsulated component-level styles. It retains specific styling for '.body__menu-open' class within `<Global>`.
=> refactor(main nav): use emotion for styling - follow up

website-components-playground/vercel.json
Leftover of #3400 
I thought Vite framework preset in Vercel was already configured to support SPAs but it's not because Vite can also be used for SSR.
https://vercel.com/docs/frameworks/vite#using-vite-to-make-spas
=> fix: components playground rewrite rules for spa support

.changeset/stupid-mugs-end.md, packages/application-shell/src/components/navbar/menu-items.styles.ts
Fix navigation sidebar menu icons alignment.
We noticed a vertical misalignment in the main navigation sidebar between the icons and their corresponding label text:
This is how it looks after applying the fix:
=> Fix navigation sidebar menu icons alignment

.changeset/hungry-rules-shop.md, packages/application-shell/src/components/custom-view-shell/custom-view-shell.tsx
`CustomViewShell` component not using provided custom Apollo client
The `apolloClient` property in the `CustomViewShell` component was not being used internally, making it impossible for consumers to user a custom Apollo client.
=> `CustomViewShell` component not using provided custom Apollo client

.changeset/silver-buses-collect.md, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/navbar/main-navbar.styles.ts, packages/application-shell/src/components/navbar/navbar.tsx
Show tooltip on support link when hovered
When the navbar is collapsed, onhover, the support menu item should display a tooltip.
Screenshot:
=> Shield 1129 support link tooltip

packages/application-shell/src/components/application-shell-authenticated/application-shell-authenticated.tsx, packages/application-shell/src/components/application-shell/application-shell.tsx, packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.tsx
Allow delaying rendering of ApplicationShell contents until all feature flags are fetched
The idea implemented in this PR is that we want to have the opportunity to delay the applications rendering until the remote feature flags are resolved.
This is to avoid potential UI flickers when the initial rendering of the application is based on a feature flag.
Currently, since we don't wait for the flags, the application is first rendered with the default (hardcoded) values and later, when the remote flags are resolved, the application re-renders. So, if the default value and the remote value are different, users will see this flicker effect.
The new behaviour can be controlled by consumer applications using the new `shouldWaitForRemoteFlags` prop in the `ApplicationShell` component.
Its default …
=> Allow delaying rendering of ApplicationShell contents until all feature flags are fetched

.github/actions/test-template-action/action.yml, application-templates/starter-typescript/package.json, application-templates/starter/package.json, custom-views-templates/starter-typescript/package.json, custom-views-templates/starter/package.json
Fix starter templates tests
fixes #3443
**TL;DR** -> there'a s problem with a transitive dependency
Running starter templates tests fail due to GraphQL requests mocks not working. When inspecting the GraphQL error, we just see a generic message:
```
ApolloError: Error message not found.
```
After a lot of debugging, I found an inconsistency in dependencies declaration in the http mocking library we use (`msw`).
This library has a dependency on the `headers-polyfill` package set with this version range: `^3.1.0`, which means that any new minor or patch versions of that package can and will be used.
The main problem is that ` headers-polyfill` package removed some public APIs in a minor version ([v3.3.0](https://github.com/mswjs/headers-polyfill/releases/tag/v3.3.0)) and `msw` relies on one …
=> Fix starter templates tests

.changeset/lemon-points-peel.md, packages/application-components/src/components/custom-views/custom-views-selector/use-custom-views-connector.ts, packages/application-components/src/test-utils/test-utils.tsx, packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.tsx, packages/constants/src/feature-toggles.ts, playground/src/test-utils/index.js, visual-testing-app/src/application.tsx
We want to keep the flag as a long-lived flag (MC API), so that we can remove the one in LD.
=> refactor: enable feature flag for Custom Views by default

.changeset/olive-bananas-dress.md, packages/create-mc-app/src/cli.ts
Adjust documentation links used in cli.
In this PR we update the links to the docs we show in the terminal when a user bootstraps a new Custom Application or Custom View.
We've unified the link for both of them so we now link [here](https://docs.commercetools.com/merchant-center-customizations/).
=> Adjust documentation links used in cli

.changeset/large-bats-travel.md, packages/cypress/src/add-commands/login.ts
The `onBeforeLoad` never seems to be called which this intends to fix.
In the `loginByOidc` we call the `onBeforeLoad` like:
```js
if (commandOptions.onBeforeLoad) {
commandOptions.onBeforeLoad(win);
}
```
I noticed that we do not do this when logging in via the form. This causes issues internally when we use the general `loginToMerchantCenter` command which we often pass an `onBeforeLoad` to e.g. set local storage values to hide collapse the menu or hide certain models (like for rebranding). 
We could either invoke the `onBeforeLoad` in the `authCallback` or when navigating to the `initialRoute`. The latter seems unexpected as you then only invoke the callback when another parameter is passed.
=> fix(cypress): onBeforeLoad being called during login

pnpm-lock.yaml
Fixes https://github.com/commercetools/merchant-center-application-kit/security/dependabot/162
=> chore: update `@babel/traverse` to use security patch version

.changeset/lovely-squids-cross.md, packages/mc-html-template/html-docs/application.html, packages/mc-html-template/src/replace-html-placeholders.ts
No idea why this started "failing" now but in the [graphql-explorer Custom Application](https://github.com/commercetools/merchant-center-graphql-explorer) (built with Vite) the deployment was broken as the CSP policy refused to execute the injected script `window.app = ` due to a mismatch with the SHA hash.
After some debugging and try/error, it appeared that the browser expected the hash to be created from a one-liner of the script.
In other words, instead of
```
<script>
window.app = 
</script>
```
it should be
```
<script>window.app = </script>
```
Update: it looks like this was introduced due to Prettier in #3379
=> fix: to inject app env script as one liner

.changeset/real-steaks-brush.md, packages-backend/eslint-config-node/index.js
=> fix: migration leftovers for `eslint-plugin-n`

.changeset/nine-goats-return.md, packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.tsx
This PR increase `flop-flip` polling interval from 1 minute to 15 minutes.
I was working locally (and same thing happens on prod) when saw that we have requests for `AllFeatures` going every minute which seemed a bit wasteful since we don't update those values and when we do, we don't expect an instant change since it requires a PR and a CI run
=> chore(flopflip): increase pooling interval from 1 to 15 minutes

.changeset/brown-planets-approve.md, packages/constants/src/constants.ts, packages/constants/src/validations.spec.ts
=> refactor: refine some regex

.changeset/clever-worms-juggle.md, packages/application-config/src/load-config.ts, packages/codemod/test/transforms.spec.ts, packages/create-mc-app/src/tasks/download-template.ts, packages/create-mc-app/src/utils.ts, packages/create-mc-app/src/validations.ts, packages/cypress/src/task/index.ts, packages/l10n/scripts/generate-l10n-data.js, packages/mc-scripts/src/cli.ts, packages/mc-scripts/src/commands/build.ts, packages/mc-scripts/src/commands/start.ts, packages/mc-scripts/src/config/paths.ts, packages/mc-scripts/src/utils/credentials-storage.ts, packages/mc-scripts/src/utils/does-file-exist.ts
- https://github.com/commercetools/fe-chapter-notes/issues/490
=> chore: to replace fs.exists with fs.access

.changeset/modern-vans-smile.md, packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.tsx
As agreed with @tdeekens as a temporary workaround.
=> fix: do not use lazy cache mode for feature flags when Cypress runs

application-templates/starter-typescript/package.json, application-templates/starter/package.json, custom-views-templates/starter-typescript/package.json, custom-views-templates/starter/package.json
Reverting ` header-polyfill` dependency resolution (fix starter templates tests)
closes #3498
We have the starter templates tests failing again.
The original problem was a dependency update which was incompatible with our version of `msw` as we explained and fixed in [this PR](https://github.com/commercetools/merchant-center-application-kit/pull/3451).
We have the issue again because we unintentionally updated the dependency resolution we had set.
That dependency resolution can't be updated until we move to `msw` version 2, which requires some effort.
=> Reverting `header-polyfill` dependency resolution (fix starter templates tests)

.changeset/new-walls-rest.md, packages/i18n/data/core.json, packages/react-notifications/src/components/notification-kinds/api-error-message/messages.ts
This PR adds a new error code: `DuplicateStandalonePriceScope`
https://docs.commercetools.com/api/errors#duplicatestandalonepricescope
In Standalone Prices web app we are intercepting this error code, although it make more sense to make the error notification available for any app using the API of CT
https://github.com/commercetools/merchant-center-prices/blob/main/packages-frontend/application-standalone-prices/src/hooks/use-show-standalone-price-api-error-notification/messages.ts#L11
=> feat(react-notifications): add `DuplicateStandalonePriceScope` error code

application-templates/starter-typescript/package.json, application-templates/starter/package.json, custom-views-templates/starter-typescript/package.json, custom-views-templates/starter/package.json
Fix starter templates failing tests.
When a Custom Application / Custom View is installed, running the default test suites yield some errors.
The problem seem to be with the latests versions of a transitive dependency ([nwsapi](https://github.com/dperini/nwsapi/)) which is used as part of the tests setup (`jest`, `jsdom`, `react-testing-library`).
[Here](https://github.com/jsdom/jsdom/issues/3055) is a related issue I found in `jsdom` repository and [here](https://github.com/dperini/nwsapi/issues/47) is another one in the `nwsapi` one.
I wasn't able to track down the exact change in `nswapi` which causes our problem, but I found it was introduced in the `2.8.0` version. That's why I'm adding a custom resolution rule in the templates `package.json` file to use the latest functioning …
=> Fix starter templates failing tests

.changeset/ten-buses-appear.md, packages/i18n/data/core.json, packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.spec.tsx, packages/react-notifications/src/components/notification-kinds/api-error-message/messages.ts
This PR adds two new error codes: OverlappingPriceValidity and OverlappingStandalonePriceValidity that are present in priceless API
=> feat(react-notifications): add OverlappingPriceValidity and OverlappingStandalonePriceValidity error codes

.github/actions/ci/action.yml, .github/actions/test-template-action/action.yml
Update GitHub `pnpm` install action
I've noticed some warnings in GitHub jobs about the `pnpm/action-setup` using an old `nodejs` version so I'm updating that dependency in this PR.
According to the [release notes](https://github.com/pnpm/action-setup/releases), it's safe for us to update to its latest major version.
I've also noticed this warning:
So I'm introducing the missing input declaration in the `test-template-action`.
=> Update GitHub `pnpm` install action

.changeset/afraid-cherries-deny.md, packages/mc-scripts/src/commands/build-vite.ts, packages/mc-scripts/src/config/create-webpack-config-for-production.ts, packages/mc-scripts/src/utils/get-i18n-message-format.tsx, packages/mc-scripts/src/vite-plugins/vite-plugin-i18n-message-compilation.ts, packages/mc-scripts/src/webpack-loaders/i18n-message-compilation-loader.ts
Implements the same functionality added to webpack build on https://github.com/commercetools/merchant-center-application-kit/pull/3496 for vite.
=> feat(message-loader): add a simple i18n message compilation plugin for vite

.changeset/wise-lizards-switch.md, packages/i18n/data/core.json, packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.spec.tsx, packages/react-notifications/src/components/notification-kinds/api-error-message/messages.ts
This PR fixes wrong notification messages 🤞
Amends https://github.com/commercetools/merchant-center-application-kit/pull/3517/files
=> fix: wrong default OverlappingPriceValidity and  OverlappingStandalonePriceValidity error codes messages

playground/.env, playground/custom-application-config.mjs
Fix Playground Custom Application deployment previews
We can't use a fixed value for the Custom Application configured URL but the one provided by Vercel for each deployment (`VERCEL_URL` env variable; [reference](https://vercel.com/docs/projects/environment-variables/system-environment-variables)).
=> Fix Playground Custom Application deployment previews

.changeset/sharp-cups-think.md, application-templates/starter-typescript/package.json, application-templates/starter/package.json, custom-views-templates/starter-typescript/package.json, custom-views-templates/starter/package.json, pnpm-lock.yaml
Creating and starting a new customization using yarn v3 is currently failing:
```
Error: Your application tried to access @commercetools-frontend/babel-preset-mc-app, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
Make sure that all the Babel plugins and presets you are using
are defined as dependencies or devDependencies in your package.json
file. It's possible that the missing plugin is loaded by a preset
you are using that forgot to add the plugin to its dependencies: you
can workaround this problem by explicitly adding the missing package
to your top-level package.json.
```
Adding the babel preset dependency appears to solve the issue.
The alternative would be to only allow yarn classic.
=> fix(customizations templates): include babel-preset package as a dependency

.changeset/khaki-icons-smoke.md, packages/application-components/src/components/page-content-containers/page-content-wide/page-content-wide.tsx
=> fix: ensure page content layout columns have the correct sizes

.changeset/metal-hotels-judge.md, packages/application-components/src/components/internals/default-form-buttons.tsx
In @commercetools/priceless-team-fe, we have a design where `CustomFormDetailPage.FormPrimaryButton` and `CustomFormDetailPage.FormSecondaryButton` have an icon (see screenshots https://commercetools.atlassian.net/browse/PRC-3533).
Currently `CustomFormDetailPage.FormPrimaryButton` does not accept an `iconLeft` prop (`CustomFormDetailPage.FormSecondaryButton` does)
=> feat: add `iconLeft` prop to `CustomFormDetailPage.FormPrimaryButton`

packages/cypress/tsconfig.json
TypeScript errors when running `pnpm build` in merchant-center-application-kit
The issue occurs occasionally when running the pnpm build command in the root of the app-kit directory. The build process encounters TypeScript errors related to missing basic DOM types. Specifically, TypeScript is unable to recognize the names Window, HTMLElement, and ScrollLogicalPosition, which are essential for browser-based environments.
The issue was related to the cypress directory within the merchant-center-application-kit repository. The missing types (Window, HTMLElement, ScrollLogicalPosition) are typically available in a browser environment but are not found during the TypeScript build process. Including "DOM" and "DOM.Iterable" helps TypeScript provide better type safety and error checking for the …
=> chore(tsconfig): include DOM and DOM.Iterable for improved type checking

.changeset/dry-eagles-sin.md, packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx, packages/application-shell-connectors/src/components/application-context/application-context.tsx
Forward application context project's `isProductionProject`.
This is to be able to exclude non-production projects from Fullstory.
References
- https://commercetools.atlassian.net/browse/PCM-3731
- https://commercetools.slack.com/archives/CCL83RA06/p1721392732288309.
=> chore: forward application context project's isProductionProject

.changeset/lemon-cameras-yawn.md, packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.tsx
We have two adapters in flopflip: one for LaunchDarkly and one for our GraphQL endpoint. The first acts lazy and the latter eager. 
When we pass the menu flags to LaunchDarkly's adapter, they will be used to build a subscriptions to LaunchDarkly and then be persisted as a in the cache of the adapter. The value then cached is `false` (as the default). This means the menu item will not show unless the page is reloaded until the cache updates. This is cause the default value from the cache is used as LaunchDarkly has precedence over the MC API flags.
In short: we should not use LaunchDarkly to toggle menu visibility. In fact no team right now does. Instead we should use the MC API. For this to work eagerly (menu items show without reloading) we need to have the MC API adapter have precedence …
=> fix(app-shell): feature flags for menu to not use launchdarkly

.changeset/spotty-dragons-peel.md, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/navbar/navbar.tsx, packages/application-shell/src/components/navbar/use-navbar-state-manager.ts
https://commercetools.atlassian.net/browse/SHIELD-1378
If the user tries to access a project that either does not exist or has no access, the navbar component must not fetch project extensions information.
=> fix(app-shell): do not fetch project extensions if user has no project access

.changeset/nasty-dragons-grin.md, packages/application-components/src/components/dialogs/form-dialog/form-dialog.spec.tsx, packages/application-components/src/components/dialogs/form-dialog/form-dialog.tsx, packages/application-components/src/components/dialogs/internals/dialog-footer.tsx, visual-testing-app/src/components/form-dialog/form-dialog.visualroute.tsx, website-components-playground/src/pages/form-dialog.tsx
Add a new property `leftAlignedFooterContent`to the form dialog. This provides an additional content positioned to the left area of the form dialog footer.
=> Provide new prop to add content to left area of form dialog

.changeset/loud-files-eat.md, packages-backend/loggers/src/helpers.spec.ts, packages-backend/loggers/src/helpers.ts, packages-backend/loggers/src/middlewares/create-access-logger.ts, packages-backend/loggers/src/types.ts
In the access logger the option `ignoreUrls` supports both strings and regular expressions.
For strings, the value is matched as-is. You can now use the regular expression to match a certain path structure, for example to ignore requests to load assets.
```ts
const access = createAccessLoggerMiddleware({
level: 'info',
json: true,
ignoreUrls: ['/', '/health', /^\/static\/(.*)/],
});
```
=> feat(loggers): allow to ignore urls by regex

.changeset/sixty-knives-play.md, packages/application-shell/src/components/navbar/menu-items.styles.ts, packages/application-shell/src/components/navbar/menu-items.tsx, packages/application-shell/src/components/navbar/navbar.tsx, packages/application-shell/src/components/navbar/use-navbar-state-manager.ts
Using the Safe triangle  pattern to improve submenu navigation
Improve the submenu navigation by adding a safe area for users to smoothly navigate diagonally between the main menu and the submenu items, without awkwardly going out of focus.
Background: 
https://x.com/shadeed9/status/1745707615517032449?t=XnNt9gNwPHLyfrMfHEnFuA&s=03
Before: 
After (The visible triangle is only for the demo. It is not included in the PR):
=> Using Safe triangle to improve submenu navigation

.changeset/calm-students-mix.md, packages/application-shell/src/components/navbar/navbar.tsx
Fix issue with submenu vertical position when text wraps
When the submenu has a text link that wraps to the next line, the vertical position of the submenu is adjusted, causing the submenu submenu position to be recalculated but already out of visibility. This makes the submenu card to be hidden. This change fixes the issue by adding a 12-pixel buffer to the height calculation when determining if the submenu fits within the viewport below the menu item, this value accounts for the padding introduced on link hover. This ensures that the submenu is displayed correctly even when the text wraps to the next line.
Before: 
After: 
Shorter submenu items still fit when the buffer is added and it has enough vertical space:
=> proposed Fix: issue with submenu vertical position when text wraps

.changeset/tricky-islands-wash.md, cypress/e2e/custom-application-template-starter/channels.cy.ts, packages/application-shell/src/components/application-page-title/application-page-title.spec.tsx, packages/application-shell/src/components/application-page-title/application-page-title.tsx
The case transformations in the browser tab title component were removed. This affects all the custom and native applications. 
The custom application "commercetools Checkout" was displaying "Commercetools-checkout" in the browser tab title, with the first letter of "commercetools" incorrectly capitalized. This issue stemmed from intentional case transformations in the `ApplicationPageTitle` component. 
To address this, the case transformations in the getPageTitle function were removed to ensure that all the custom and native applications remains in lowercase as required. 
Corresponding ticket: [SHIELD-1092](https://commercetools.atlassian.net/browse/SHIELD-1092)
[SHIELD-1092]: https://commercetools.atlassian.net/browse/SHIELD-1092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
=> feat(application-page-title): remove case transformations in browser tab title

.changeset/khaki-dragons-stare.md, packages/i18n/src/utils.ts
When bootstrapping the MC Discount web app I noticed that 400ms from the TBT metric are coming from the load of the i18n messages. 
The i18n object loaded seems to be quite big and spreading the object on the loop (which is not needed) makes the load of the i18n messages 200x slower (I've tested it on my local env) for the Discounts app
This is a trace from the load of the MC Discounts app.
=> fix(i18n): `parseChunkImport` helper function performance issue

.changeset/wicked-actors-smile.md, packages/i18n/src/load-i18n.ts
While debugging https://github.com/commercetools/merchant-center-application-kit/pull/3607 I realized we have an opportunity to improve the `loadI18n` helper function by loading the translations in parallel.
It's a small improvement, but it could save ~50ms on each cold load.
This is the network waterfall (Discounts app) that this PR avoids.
[
](url)
=> fix(i18n): parallel loading of translations

.changeset/silly-emus-end.md, packages-backend/express/src/auth.ts, packages-backend/express/src/constants.ts, packages/application-config/src/constants.ts, packages/application-config/src/utils.ts
Add Azure EU as a new target in the MC configuration.
Introduce a new cloudIdentifier configuration option for Custom Applications and Custom Views, allowing them to select Azure EU as the target environment.
=> feat: extend the list of cloud identifiers to include Azure EU

.changeset/late-ears-shout.md, packages/sentry/src/sentry.ts
The goal of this PR is to add more info of any ErrorEvent reported to Sentry. 
The captured error message (see https://commercetools.sentry.io/issues/5880399228 as an example) is not enough to have a picture of the issue happening on production.
As an example: introducing the filename to the extra data, we will be able to understand if issues are caused by browser extensions.
=> feat(sentry): send extra info for reported ErrorEvent

.changeset/serious-trainers-cough.md, packages/mc-html-template/html-docs/application.html, packages/mc-html-template/src/webpack-html-template.ts, packages/mc-scripts/src/commands/build-vite.ts, packages/mc-scripts/src/commands/start-vite.ts
The goal of this PR is to avoid network falls when downloading MC apps initial JS chunks (runtime and app bundles.See screenshots below).
By moving initial JS chunks to the HTML head and deferring them, we allow the browser to concurrently download the initial JS chunks and the initial CSS files.
We save ~60ms when cold loading a MC app.
You can use https://github.com/commercetools/merchant-center-frontend/pull/17738 to test the Webpack changes (I've patched `@commercetools-frontend/mc-html-template` in that branch of the monorepo).
https://mc.europe-west1.gcp.escemo.com/sunrise-data-alex/discounts
https://mc-17738.mc-preview.europe-west1.gcp.escemo.com/sunrise-data-alex/discounts
=> perf: defer application main JS chunks

.changeset/early-ducks-itch.md, packages/application-components/src/components/detail-pages/tabular-detail-page/tabular-detail-page.spec.tsx, packages/application-components/src/components/main-pages/tabular-main-page/tabular-main-page.spec.tsx, packages/application-shell/src/components/application-entry-point/application-entry-point.tsx, packages/application-shell/src/components/application-shell-authenticated/application-shell-authenticated.tsx, visual-testing-app/src/components/tabular-detail-page/tabular-detail-page.visualroute.tsx, visual-testing-app/src/components/tabular-main-page/tabular-main-page.visualroute.tsx, visual-testing-app/src/components/tabular-modal-page/tabular-modal-page.visualroute.tsx, website-components-playground/src/pages/tabular-detail-page.tsx, website-components-playground/src/pages/tabular-main-page.tsx, website-components-playground/src/pages/tabular-modal-page.tsx
Migrate react-router redirects
As part of the preparations for the upcoming `react-router` v6 migration, there are some changes related to how client-side redirects are managed ([reference](https://reactrouter.com/en/main/upgrading/v5#remove-redirects-inside-switch)) that we can already apply to our codebase (supported in v5).
=> [FEC-96] Migrate react-router redirects

.changeset/nasty-zoos-shop.md, packages/mc-html-template/html-docs/application.html
When a user Googles "Merchant Center commercetools", we don't want the various MC's to appear in the search result pages.
We add a meta-tag to the `application.html` file to prevent search engines from indexing the apps and potentially following  links.
Breakdown of the meta-tag directive:
- `noindex`: Prevents search engines from indexing the page, so it won’t appear in search results.
- `nofollow`: Tells search engines not to follow the links on the page
=> refactor(application.html): add meta tag to prevent search engine indexing

.github/workflows/preview-release-on-comment.yml
Validate branch name in preview release workflow
We detected some attempts to exploit the new workflow for preview releases so we want to include a quick and simple validation for the branch names we use in order to protect the flow.
We now only allow numbers, letters, underscores, and hyphens in the branch name.
=> Validate branch name in preview release workflow

.github/workflows/preview-release-on-comment.yml
Update prerelease workflow
The initial goal of this PR was to fix an error we currently have in the prerelease workflow regarding an invalid version number we're using for the `myrotvorets/set-commit-status-action@v2` action:
That action [has not published](https://github.com/myrotvorets/set-commit-status-action/tags) any `v2` tag so we need to use a specific version. I was suggesting to use the latest available (`2.0.1`).
You can take a look at this PR's first commit.
Afterwards, I thought about the purpose of using that action in the workflow: it seems we want to set a visual mark on the last commit before the preview release comment was written.
Since that mark is very subtle (visually) and we are also adding a comment when the release process in finished so we know whether it went …
=> [FEC-157] Update prerelease workflow

.changeset/fuzzy-tips-scream.md, packages/application-shell/src/components/application-entry-point/application-entry-point.tsx
We recently updated how redirects are handled (see [PR #3630](https://github.com/commercetools/merchant-center-application-kit/pull/3630)). Unfortunately, this introduced a regression in project switching behavior. This fix addresses the issue by properly resolving route parameters during redirects.
=> fix(AppShell): project switching

.changeset/bright-olives-yell.md, packages/application-shell-connectors/src/configure-apollo.ts
To help debugging the GraphQL requests in the network tab:
=> refactor: append graphql operation name as query param

.changeset/four-zebras-arrive.md, packages/application-components/src/components/detail-pages/custom-form-detail-page/custom-form-detail-page.tsx, packages/application-components/src/components/detail-pages/form-detail-page/form-detail-page.tsx, packages/application-components/src/components/detail-pages/tabular-detail-page/tabular-detail-page.tsx, packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.tsx, packages/application-components/src/components/dialogs/form-dialog/form-dialog.tsx, packages/application-components/src/components/dialogs/internals/dialog-container.tsx, packages/application-components/src/components/dialogs/internals/dialog-footer.tsx, packages/application-components/src/components/drawer/drawer.tsx, packages/application-components/src/components/internals/default-form-buttons.tsx, packages/application-components/src/components/internals/page-header-title.tsx, packages/application-components/src/components/internals/page-top-bar.tsx, packages/application-components/src/components/main-pages/custom-form-main-page/custom-form-main-page.tsx, packages/application-components/src/components/main-pages/form-main-page/form-main-page.tsx, packages/application-components/src/components/main-pages/tabular-main-page/tabular-main-page.tsx, packages/application-components/src/components/modal-pages/form-modal-page/form-modal-page.tsx, packages/application-components/src/components/modal-pages/internals/modal-page.tsx, packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.tsx, packages/application-components/src/components/modal-pages/utils/modal-page-top-bar.tsx, packages/application-components/src/components/page-content-containers/page-content-wide/page-content-wide.tsx, packages/application-components/src/components/public-page-layout/public-page-layout.tsx, packages/application-components/src/components/tab-header/tab-header.tsx, packages/application-shell/src/components/application-page-title/application-page-title.tsx, packages/application-shell/src/components/inject-reducers/inject-reducers.tsx, packages/application-shell/src/components/navbar/menu-items.tsx, packages/application-shell/src/components/navbar/navbar-skeleton.tsx, packages/permissions/src/components/authorized/authorized.tsx, packages/react-notifications/src/components/notification/notification.tsx, packages/react-notifications/src/components/notifier/notifier.tsx, packages/sdk/src/components/sdk-get/sdk-get.tsx
Update the way we manage default properties in React components.
As part of the preparations for the upcoming update to the newest React version, we need to update how we manage components default properties as our current implementation will no longer be supported ([reference](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops)).
```ts
// BEFORE
type TMyComponentProps = {
message: string;
size: string;
}
function MyComponent(props: TMyComponentProps) {
...
}
MyComponent.defaultProps = {
size: 'big'
}
// AFTER
type TMyComponentProps = {
message: string;
size?: string; // <--- Note this property is now defined as optional
}
function MyComponent({ size = 'big', ...props }: TMyComponentProps) {
...
}
```
=> [FEC-139] Refactor React components "defaultProps" management

.changeset/purple-panthers-attack.md, packages/codemod/README.md, packages/codemod/src/cli.ts, packages/codemod/src/transforms/react-default-props-migration.ts, packages/codemod/src/types.ts
The way we are using React components `defaultProps` in our codebase is no longer supported in the new React 19 version ([reference](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops)).
This is the main concept:
```tsx
// BEFORE
type TMyComponentProps = {
prop1: string;
prop2: string;
prop3: string;
};
function MyComponent(props: TMyComponentProps) {
return (
<ul>
<li>Prop 1: {props.prop1}</li>
<li>Prop 2: {props.prop2}</li>
<li>Prop 3: {props.prop3}</li>
</ul>
);
}
MyComponent.defaultProps = {
prop1: 'My default value',
};
// AFTER
type TMyComponentProps = {
prop1?: string; // <--- Make sure this is marked as optional
prop2: string;
prop3: string;
};
function MyComponent({ prop1: 'My default value', ...props }: TMyComponentProps) {
return (
<ul> …
```
=> New codemod to help migrating React components "defaultProps" usage

packages/codemod/src/transforms/react-default-props-migration.ts
Improve js components migration
I discovered another use case we were not covering: when we have a React component in a Javascript file and it does not have already destructured properties in the function declaration.
```jsx
import * as PropTypes from 'prop-types';
function MyComponent(props) {
return <div>{props.foo}</div>;
}
MyComponent.defaultProps = {
foo: 'bar',
};
MyComponent.propTypes = {
foo: PropTypes.string,
};
```
=> [FEC-138] Improve js components migration

.changeset/purple-rice-bow.md, packages/babel-preset-mc-app/create.js, packages/babel-preset-mc-app/package.json, packages/babel-preset-mc-app/production.spec.js, packages/mc-scripts/src/commands/build-vite.ts, packages/mc-scripts/src/config/create-webpack-config-for-production.ts, packages/mc-scripts/src/types.ts, pnpm-lock.yaml
The goal of this PR is to add `babel-plugin-formatjs` to the `babel-preset-mc-app` and `mc-scripts` packages in order to avoid bloating bundles with useless data from `formatjs` messages (`description`, `defaultMessage` props).
A couple of flags are added (see https://formatjs.github.io/docs/tooling/babel-plugin/#options):
* `i18nAst`: Pre-parse `defaultMessage` into AST for faster runtime perf
* `i18nRemoveDefaultMessage`: Remove `defaultMessage` field in generated js after extraction
=> feat: add `babel-plugin-formatjs` to `babel-preset-mc-app`

.changeset/hungry-clouds-peel.md, .changeset/mean-camels-nail.md, .changeset/short-lies-whisper.md, packages/application-config/custom-application.schema.json, packages/application-config/custom-view.schema.json, packages/application-config/src/schemas/generated/custom-application.schema.ts, packages/application-config/src/schemas/generated/custom-view.schema.ts, packages/application-config/test/fixtures/custom-applications/config-full.json, packages/application-config/test/process-config-custom-application.spec.js, packages/constants/src/constants.ts, packages/mc-html-template/src/process-headers.spec.ts, packages/mc-html-template/src/process-headers.ts, pnpm-lock.yaml
https://commercetools.atlassian.net/browse/SHIELD-1580
This is a follow up of some improvements we are doing around the security headers.
There is no need to override the `Strict-Transport-Security` header, so we are deprecating the config option.
=> refactor: deprecate STS header

.changeset/beige-coats-smoke.md, packages/application-components/src/components/custom-views/custom-views-selector/custom-views-selector.tsx, packages/application-components/src/components/custom-views/custom-views-selector/index.ts, packages/application-components/src/components/custom-views/custom-views-selector/types.ts, packages/application-components/src/components/detail-pages/tabular-detail-page/tabular-detail-page.tsx, packages/application-components/src/components/main-pages/tabular-main-page/tabular-main-page.tsx, packages/application-components/src/components/modal-pages/tabular-modal-page/tabular-modal-page.tsx, packages/application-components/src/hooks/use-custom-view-locator-selector/use-custom-view-locator-selector.ts, packages/application-components/src/test-utils/test-utils.tsx
Main goals:
* decouple loading of the Custom View selector when tabular component is used outside of MC (evaluate if `window.app` is defined)
* implies also a decoupling of react-router (used by the custom view selector)
=> refactor(components): lazy load custom view selector in modular tab components

.github/workflows/merge-blocking-labels.yml
This GitHub Action, once merged and configured as a branch protection, prevents merging PRs with these labels.
We want to synchronize the use of these labels and the GitHub Action across repos for the FE Chapter which as long-running PRs across repos which must not be merged.
I've made sure that all labels exist on the repo. I'll also setup branch protection after merging this.
=> feat(ci): add github action to block merging by labels

.changeset/witty-birds-pump.md, packages/mc-scripts/src/commands/build-vite.ts
As part of the migration from Webpack to Vite, we will be updating the Vite configuration to output all build assets directly under the `public` folder (as opposed to the default nested assets directory).
This approach ensures compatibility with our existing scripts and avoids requiring updates across all consuming applications
=> FEC-220 - Update file output of build assets

.changeset/perfect-pianos-greet.md, packages/application-shell-connectors/src/configure-apollo.ts
Remove graphql debug query param
This PR rolls back the change introduced in the `/graphql` endpoint that added the operation name query parameter (
[reference](https://github.com/commercetools/merchant-center-application-kit/pull/3679)).
The reasons behind it are:
* We noticed this change is actually affecting consumers (eg: some tests asserting GraphQL request not expecting any query parameter)
* We are changing some runtime contract between frontend and backend to improve DX when that can be achieved by using tailored tools such as [this Chromium plugin](https://chromewebstore.google.com/detail/graphql-network-inspector/ndlbedplllcgconngcnfmkadhokfaaln).
* We are introducing more code (to maintain) in the repository when we can achieve the same DX by using tailored tools.
* Maybe not …
=> Remove graphql debug query param

.github/workflows/preview-release-on-comment.yml, package.json, pnpm-lock.yaml, scripts/update-npm-tag.mjs
Update preview releases NPM dist-tag every time we release a new RC version
Out current [GH job](https://github.com/commercetools/merchant-center-application-kit/blob/main/.github/workflows/preview-release-on-comment.yml) to release preview RC candidates to NPM publishes release candidates versions to NPM and also creates a `dist-tag` the first time and links it to the very first released RC.
There's an issue though because, when we release a new RC, the `dist-tag` is not updated to point to the new RC version. This mean we can't get automatically the most recent version in the consumers, forcing us to go to each one and update the version manually.
In this PR we include a script that we use in the GH job so we make sure the `dist-tag` is updated every time we publish a new RC version. …
=> Update preview releases NPM dist-tag every time we release a new RC version

.changeset/brown-singers-build.md, packages/application-components/src/components/public-page-layout/public-page-layout.tsx
Regression of #3676 
The login screen card was compressed and and moved to the left
The props were not being passed in `PublicPageLayoutContent` due to which `ContainerColumn` was being applied instead of `ContainerColumnWide`. This PR fixes the issues by ensuring that `contentScale` is passed correctly
Existing layout:
=> fix: updated public-page-layout to send props correctly

.changeset/short-panthers-remember.md, packages/jest-preset-mc-app/package.json, packages/jest-preset-mc-app/setup-tests.js, pnpm-lock.yaml
Mock `crypto.randomUUID` function in test environment
We're stating to use `crypto.randomUUID` function in some the the `app-kit` consumers and currently it is not implemented in the underlying `jsdom` library `jest` uses in the testing context.
The `jsdom` library added support for it in its `22.1.0` [version](https://github.com/jsdom/jsdom/blob/95c80863618dfa43f29166134e263da16433ce05/Changelog.md#2210), but `jest` is currently using the `20.x` version and won't use the `22.x` until its next major release.
In the meantime, I thought it would be helpful to mock this function at `app-kit` level so we don't have to do it at the consumer level.
=> mock crypto.randomuuid in test environment

.github/workflows/preview-release-on-comment.yml, .github/workflows/release.yml, .gitignore, .npmrc
Regression after upgrading to PNPM v9 (#3695).
The error occurs when bumping the version in one of the workspace packages which hasn't been published to the NPM registry.
In [v9](https://github.com/orgs/pnpm/discussions/7932) they changed the following setting:
Therefore, we are configuring the setting `link-workspace-packages=true` to restore the previous behavior.
Since PNPM config relies on `.npmrc` file, we also need to commit that. The release CI jobs have also been amended to "inject" the NPM auth token.
PS: using the `workspace` protocol is actually our intention as well. However, there were some issues with Changesets where packages would be published with the `workspace` protocol in the dependencies.
Maybe we need to revisit this setup and see if we can make it work again.
=> fix: pnpm v9 regression with linking workspace packages

.changeset/fifty-chairs-pull.md, packages/application-components/src/components/dialogs/internals/dialog-container.tsx, packages/application-components/src/components/modal-pages/internals/modal-page.tsx
Hoping to fix error happening in CI:
=> fix: modals and dialogs with default attributes added by radix-ui

.changeset/lovely-donuts-mate.md, packages/application-components/src/components/dialogs/form-dialog/form-dialog.spec.tsx, packages/application-components/src/components/dialogs/form-dialog/form-dialog.tsx, packages/application-components/src/components/dialogs/internals/dialog-footer.tsx
This pull request introduces a new prop `iconLeftPrimaryButton` to the `FormDialog` component in the `@commercetools-frontend/application-components` package. The new prop allows an icon to be displayed to the left of the primary button in the form dialog. The changes include updates to the component's type definitions, rendering logic, and tests.
* Added a new prop `iconLeftPrimaryButton` to the `FormDialog` component to allow an icon to be displayed to the left of the primary button.
=> Add an iconLeftPrimaryButton prop to enable formDIalog display primary button with icon in the label

.changeset/itchy-houses-vanish.md, packages/sentry/src/sentry.ts
Include a new tag in Sentry context.
This is a **proposal** for adding a new `tag` in Sentry's context that can help filtering error logs in a multi-application context.
Since I noticed we were using some deprecated APIs I also took the time to update those ones:
=> Include a new tag in Sentry context

.github/CODEOWNERS
update CODEOWNERS to reflect team ownership for various components. This change reflects the decision taken by both the First-contact and Shield team as seen in the [miro board](https://miro.com/app/board/uXjVIWRWTV0=/)
See the github [documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) for more information on CODEOWNERS file.
=> chore: update CODEOWNERS to reflect team ownership for various components

.changeset/thirty-crabs-mix.md, packages/jest-preset-mc-app/setup-test-framework.js
Update console messages handling in tests.
We've updated how `console` messages are handled in local environments: previously, `console.warn` and `console.error` messages did not make tests to fail locally but they did in CI; this behaviour led to several cases where we did not realize about an issue until some code reached CI whereas it could be detected locally.
With this change we expect some errors to be caught earlier in the development lifecycle and thus shorten the time to fix them.
=> Update console messages handling in tests

.changeset/six-dragons-grow.md, packages/mc-scripts/src/commands/start-vite.ts
Update Vite config when running applications locally.
This PR suggests to update the `vite` configuration so when running an application locally, a browser will automatically open to match the behaviour we currently have with `webpack`.
=> [mc-scripts] Update Vite config when running applications locally

.changeset/spotty-elephants-think.md, package.json, packages/codemod/bin/mc-codemod.js, packages/codemod/package.json, packages/codemod/src/cli.ts, packages/create-mc-app/package.json, packages/create-mc-app/src/cli.ts, packages/mc-scripts/package.json, packages/mc-scripts/src/cli.ts, packages/mc-scripts/src/types.ts, pnpm-lock.yaml
Unfortunately the `cac` library hasn't been actively maintained in the past years. So we're back at using `commander`, which actually has a very similar API of `cac` so switching between them is pretty simple.
=> refactor: migrate CLIs from `cac` to `commander`

.changeset/chatty-jeans-prove.md, .changeset/curly-nails-raise.md, .github/workflows/main.yml, jest.test-node.config.ts, jest.test.config.js, package.json, packages-backend/express/package.json, packages-backend/express/src/auth.spec.ts, packages-backend/express/src/auth.ts, packages-backend/express/src/middlewares/fixtures/jwt-token.ts, packages-backend/express/src/middlewares/session-middleware.spec.ts, packages-backend/express/src/middlewares/session-middleware.ts, packages-backend/express/src/types.ts, packages-backend/loggers/package.json, pnpm-lock.yaml
* Uses `jose` (ESM version)
* Because of ESM, we need to instruct Jest to transpile it correctly
* Uses `babel-jest` by default
* Separated Jest config for "node" related tests
=> refactor: simplify jwks validation with jose, no extra libs

.changeset/mean-dolls-pretend.md, packages/application-shell/src/test-utils/test-utils.tsx
Update `app-shell` test utils.
The `test-utils` package used for rendering apps in the test environment creates an _in-memory_ router by default. We're adding a new property to it ([getUserConfirmation](https://v5.reactrouter.com/web/api/MemoryRouter/getuserconfirmation-func)) to cover for cases when logic wants to be used before a navigation is executed (eg: "warn on leave").
=> Update `app-shell` test utils

.changeset/kind-adults-learn.md, packages/codemod/tsconfig.json, packages/create-mc-app/tsconfig.json, packages/mc-scripts/tsconfig.json
=> fix: use `moduleResolution: bundler` to be compatible with ESM packages

.changeset/mighty-parents-exercise.md, packages/mc-scripts/src/cli.ts
Follow up of #3749 to clarify the usage of variadic CLI option `--env`.
=> refactor(cli): clarify variadic option behavior

.changeset/fresh-sheep-remain.md, packages/sentry/src/sentry.ts
Tags are useful for filtering in Sentry. We can also tie them to an internal service catalog using the service tag.
As the service tag in its nature needs to be more precise it's longer than the application tag. As a result I suggest to keep both. Open for alternative views of course.
=> refactor: add service tag to be sent to sentry

.changeset/metal-clocks-sin.md, packages/cypress/src/add-commands/login.ts, packages/cypress/src/constants.ts
This PR refactors the `loginByForm` command so it retries the action if the login action fails and the login request sent to the server (`/tokens` endpoint) returns a 429.
We've found some issues while running our e2e test suites regarding the backend login endpoint rejecting some legit attempts due to the fact that we run several tests in parallel using the same credentials and the backend only allows one login attempt with a set of credentials at a time.
In this PR we introduce an update to the `loginByForm` command that will retry the login attempt if the server responds with a 429 status code.
It will retry a configurable amount of times (3 by default) and it will wait between 1 and two seconds between each attempt.
=> Retry login action on certain condition

.changeset/good-mayflies-exist.md, .changeset/lovely-monkeys-relate.md, packages/application-shell-connectors/src/apollo-links/error-link.spec.js, packages/application-shell-connectors/src/apollo-links/error-link.ts, packages/application-shell-connectors/src/utils/apollo-context.ts, packages/application-shell/src/components/fetch-project/fetch-project.tsx, packages/application-shell/src/components/fetch-user/fetch-user.tsx
We're updating the way we report unhandled GraphQL errors to Sentry.
In a previous PR ([reference](https://github.com/commercetools/merchant-center-application-kit/pull/3768)) we introduced a change for reporting all the errors happening in GraphQL operations to Sentry (if the latter is enabled).
We've realized this is a very wide decision which can uncover potential problems in consumers that would be difficult to address all at once.
In this PR we change the approach to not report those errors by default and allow consumers to configure this behaviour with a new `context` (_boolean_) property named `enableSentryErrorReporting`.
Here's an example:
```ts
const { loading, data, error } = useMcQuery<
TFetchLoggedInUserQuery,
TFetchLoggedInUserQueryVariables
>(LoggedInUserQuery, {
context: { …
```
=> Update Graphql errors reporting to Sentry

.github/actions/ci/action.yml
A regular install appears to also run the post install script for Puppeteer.
Assumption is that this can fail builds too.
=> fix(ci): to add puppeteer download url to regular install

.changeset/rare-apples-compete.md, packages/application-components/src/components/custom-views/custom-view-loader/custom-view-loader.tsx
Fix Custom Views integration
We found an issue with the integration of Custom Views which made them unusable.
The issue is related to how the communication between the host application and a Custom View is managed: there are a number of events exchanged between both systems and the readiness one form the Custom View was sent before the host application was actually listening for events so the initialization never happened.
In this PR we change when the host application starts listening for messages (way earlier) so we overcome the situation.
=> Fix Custom Views integration

.changeset/quick-clocks-cover.md, packages/application-components/src/components/custom-views/custom-view-loader/custom-view-loader.tsx, packages/application-shell/src/components/custom-view-shell/custom-view-shell.tsx
This improves Custom View initialization by a backwards compatible bidirectional communication in which the Custom View (managed by `custom-view-shell`) informs the host application (managed by `custom-view-loader`).
This is a follow-up from the React v19 migration in which we initially tried to implement a bidirectional approach but reverted it as we _can not assume_ Custom Views to be updated. As a result this communication needs to be backwards compatible. Hence, even if the Custom View does not send a "ready message" the host has to assume - in this case after 500ms - for the Custom View to be ready. 
1. Add a ready message sent from Custom View to host
2. Adjust the host to be able to react to the ready message to send initialization message and payload
3. Host to remain backwards …
=> Add backwards compatible bidirectional initialization of Custom Views

.changeset/polite-mugs-peel.md, packages/application-shell/src/components/suspended-route/protected-route.tsx, packages/application-shell/src/components/suspended-route/suspended-protected-route.tsx
This refactors the ProtectedRoute and SuspendedProtectedRoute to both support a `fallback` component which is not the Suspense boundary but rather the fallback rendered whenever the condition is not met.
=> Refactor `SuspendedProctedRoute` to support loader and fallback component

.changeset/sour-rings-call.md, packages/application-shell/src/components/suspended-route/protected-route.tsx
Fixes rendering the string fallback instead of the value from props.
=> Fix rendering fallback as string

.github/workflows/preview-release-on-comment.yml
Removed a condition to fix an issue with the preview deployment workflow trigger.
The condition `github.event.issue.pull_request.head.repo.full_name == github.repository` was causing problems in the workflow. It was added by me in a previous PR. Removing this check resolves the issue and ensures the preview deployment workflow triggers correctly when a member comments with [preview_deployment] on a pull request.
=> fix: preview deployment workflow

.changeset/violet-impalas-travel.md, packages/constants/src/constants.ts
https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/X-XSS-Protection
=> refactor: deprecated and remove `x-xss-protection` from default security headers

.changeset/small-chicken-count.md, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/navbar/menu-items.tsx, packages/application-shell/src/components/navbar/messages.ts, packages/application-shell/src/components/navbar/navbar.tsx, packages/i18n/data/core.json
Fixes accessibility issues in application shell navbar component by adding proper ARIA attributes and accessible names to interactive elements.
Resolves multiple ARIA accessibility violations in the navbar component:
- **MenuExpander**: Added `role="menuitem"` and localized `aria-label` for expand/collapse actions
- **MenuGroup**: Removed conflicting `aria-expanded` attribute that caused ARIA role validation errors  
- **MenuItem & MenuItemLink**: Added `ariaLabel` props and `aria-label` attributes for accessible names
- **Support link**: Added localized `aria-label` attribute
- **Helper function**: Created `getMenuAccessibleLabel()` to consistently extract localized menu labels
- **Localization**: Added new message keys for menu expander actions with proper i18n support
All changes are …
=> chore(appkit): accessibility improvements to navbar

.github/CODEOWNERS
This pull request updates the `.github/CODEOWNERS` file to assign the Craft team as the new default code owners, replacing the Bots team and removing several explicit path assignments to the Craft team. The main effect is to simplify ownership and ensure the Craft team is responsible for the majority of the codebase by default.
Ownership updates:
* Changed the default code owners from `@commercetools/bots-team-engineers` to `@commercetools/craft-team-fe`, and removed explicit path-based assignments to the Craft team, consolidating ownership under a single default rule.
_Note: Along with this change, the #design-system-technical Slack channel was subscribed to `issues` for this repo._
=> chore(codeowners): change ownership

.changeset/sharp-toys-join.md, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/project-container/project-container.tsx
I can't remember why we decided to log users out in case they have no projects.
We should redirect them to the project creation page in the account app.
@tdeekens can you recall any specific logic or requirement around that?
=> fix: always redirect to account project creation when user has no projects

.changeset/six-parents-invent.md, packages/cypress/src/add-commands/login.ts
By default the `cy.get` command waits for 4s. In Identity, the login is a 2-step flow and the loading of the second step might take a bit longer.
The PR adds a new command option `timeouts` to allow to configure timeouts for the login command interactions.
Options:
* `waitForEmailInput` (defaults to `4000`)
* `waitForPasswordInput` (defaults to `8000`)
Example:
```ts
cy.loginToMerchantCenter({
// ...
timeouts: {
waitForPasswordInput: 10000,
},
});
```
=> feat(cypress): define configurable timeouts for login command interactions

.github/renovate.json
This pull request prevents automatic rebasing of dependency update pull requests by setting the `rebaseWhen` option to "never".
=> fix(renovate): set renovate to never rebase

.changeset/small-balloons-film.md, packages/mc-scripts/src/commands/login.ts
Accept an env var for the MC project key in the login command
For some internal use cases we need to use this command outside of a Custom Application and we need to be able to get a token bound to a project.
In this PR we're introducing the ability to read an env var (`CTP_PROJECT_KEY`) to get that value within the command.
This won't be documented as we don't know yet if this would be temporary or permanent.
=> Accept an env var for the MC project key in the login command

.changeset/spotty-buses-chew.md, packages/cypress/src/add-commands/login.ts, packages/mc-dev-authentication/src/create-mc-dev-authentication-middleware.ts
The flow now should be more robust and we don't need to rely much on artificial `cy.wait`.
=> refactor(cypress): improve login command
