.env.template, .gitignore, CHANGELOG.md, CONTRIBUTING.md, jest.eslint.config.js, lerna.json, lint-staged.config.js, package.json, scripts/changelog.js, yarn.lock
Let's use `lerna changelog` to generate a basic release changelog
See CONTRIBUTING for release process
=> Add script to output lerna changelog

.travis.yml, scripts/push_translations.sh
Same as we do in the MC.
The `TRANSIFEX_PASSWORD` value has been already defined in travis:
=> chore(travis): add step to push translations to tx (master branch only)

packages/application-shell-connectors/package.json, packages/permissions/package.json, packages/react-notifications/package.json, packages/sdk/package.json, packages/sentry/package.json, yarn.lock
Follow up of #20
Define peer deps for other packages
=> chore: define peer deps for other packages, ref #20

CHANGELOG.md
- updates changelog for the next release, `v1.0.0-rc-3`
- I will release once this is merged.
=> docs(changelog): document new release (v1.0.0-rc-3)

packages/application-shell/src/from-core/page-not-found/__snapshots__/page-not-found.spec.js.snap, packages/application-shell/src/from-core/page-not-found/page-not-found.js
Looks like I accidentally added some text in my last PR. Sorry about that. I think my branch name says it all.
=> chore: accidentally added text to page-not-found

packages/l10n/country-information.js, packages/l10n/currency-information.js, packages/l10n/language-information.js, packages/l10n/time-zone-information.js
=> chore: rework code splitting for l10n

packages/application-shell/src/components/menu-state-container/index.js, packages/application-shell/src/components/menu-state-container/menu-state-container.js, packages/application-shell/src/components/menu-state-container/menu-state-container.spec.js, packages/application-shell/src/components/user-settings-menu/user-settings-menu.js, packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js, yarn.lock
We used downshift in one component, to do `isOpen` and `toggleMenu`. I replaced it as simply as I could.
=> refactor: drop downshift

packages/application-shell-connectors/src/components/application-context/application-context.js, packages/application-shell-connectors/src/components/application-context/index.js, packages/application-shell-connectors/src/index.js
I couldn't resist 😜 (https://github.com/commercetools/merchant-center-application-kit/pull/72#discussion_r231988805)
=> feat(app-context): add forward-compatible useApplicationContext 🎉

packages/jest-preset-mc-app/package.json, packages/jest-preset-mc-app/setup-tests.js, yarn.lock
This pull request aims to fix looking up the root directory correctly.
Currently we seem to fail with this on CI:
=> fix(jest-preset-mc-app): to look up root dir

packages/application-shell/src/components/fetch-project/fetch-project.js
=> fix: deprecated withProject fix

packages/mc-scripts/package.json, yarn.lock
I would like to do a release to get the withProject bug fix in, and @emmenko mentioned that this gave us a problem with CI, so I'd rather be safe than sorry. [ref](https://github.com/commercetools/merchant-center-application-kit/pull/87#discussion_r232945706)
🙏
=> chore: revert mini css update

CHANGELOG.md
Updates changelog. Let me know if something is off or missing. 🙏
=> chore: update changelog for `2.0.1` release

CHANGELOG.md
=> chore: update changelog for v2.0.3 release

packages/application-shell/src/components/login-sso-callback/login-sso-callback.js, packages/application-shell/src/components/login-sso-callback/login-sso-callback.spec.js, packages/application-shell/src/components/login-sso/login-sso.js, packages/application-shell/src/components/login-sso/login-sso.spec.js
Fixes #98
...because I'm dumb! 😵
=> fix(login-sso): objects saved in storage need to be serialized/deserialized

packages/l10n/language-information.js
=> Fix selection of language chunk

packages/application-shell/src/components/quick-access/butler/butler.js, packages/application-shell/src/components/quick-access/create-commands.js, packages/application-shell/src/components/quick-access/quick-access.graphql, packages/application-shell/src/components/quick-access/quick-access.js, packages/application-shell/src/components/quick-access/quick-access.spec.js, packages/application-shell/src/components/quick-access/sub-commands.js, packages/permissions/src/index.js
Went through with @dferber90 together.
=> refactor(quick-access): correctly apply permissions to all commands and queries

packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap, packages/application-shell/src/components/app-bar/app-bar.js
We want to have an E2E test targeting the back to project link in the apps.
=> fix(app-shell): add back-to-project data test target

packages/application-shell/src/components/user-settings-menu/__snapshots__/user-settings-menu.spec.js.snap, packages/application-shell/src/constants.js
This pull request updates the support link to the new destination.
=> fix(app-shell): update support link

CONTRIBUTING.md, package.json, playground/README.md, playground/package.json
Improve the documentation about the playground and developing custom apps.
=> docs(playground): update and improve README about developing custom applications

README.md, packages/actions-global/README.md, packages/application-shell-connectors/README.md, packages/application-shell/README.md, packages/assets/README.md, packages/babel-preset-mc-app/README.md, packages/browser-history/README.md, packages/constants/README.md, packages/eslint-config-mc-app/README.md, packages/i18n/README.md, packages/jest-preset-mc-app/README.md, packages/l10n/README.md, packages/mc-html-template/README.md, packages/mc-http-server/README.md, packages/mc-scripts/README.md, packages/notifications/README.md, packages/permissions/README.md, packages/react-notifications/README.md, packages/sdk/README.md, packages/sentry/README.md, packages/storage/README.md, packages/url-utils/README.md
=> feat: add badges.

CHANGELOG.md
=> chore: update changelog in prep for `v3.0.0` [skip-ci]

README.md
Steps to get started don't tell our users they need to build the apps.
Tell users they should build the apps.
=> chore: update docs to include build step

packages/application-shell/package.json, packages/react-notifications/package.json, playground/package.json, yarn.lock
So @qmateub can have the `Avatar`
=> chore: update ui-kit

packages/application-shell/src/components/fetch-project/fetch-project.graphql
This is the PR corresponding to the mc-be to improve the names to be more consistent with the platform.
A follow-up is ready where the initial permissions will be integrated into the menu.
=> Improve permission names

CHANGELOG.md
=> chore: update changelog for `4.1.0`

packages/application-shell/src/configure-apollo.js, packages/application-shell/src/from-core/modal-container/modal-container.js, packages/application-shell/src/middleware/logger.js, packages/application-shell/src/test-utils/README.md, packages/application-shell/src/test-utils/test-utils.js
While I was implementing tests for an application, I encountered some problems and missing things that can be provided by the `test-utils` out of the box.
I recommend a review-per-commit.
=> fix(test-utils): improve test setup

packages/constants/index.js
A new GraphQL target is there. We need to proxy to it.
=> Add core-ws graphql target to constants

packages/application-shell/src/components/application-shell/application-shell.js, packages/application-shell/src/feature-toggles.js
🎉 Now that Quick Access is out, we can remove the feature toggle for it.
=> Remove Quick Access feature toggle

CHANGELOG.md
The change log. Essentially this release contains two unrelated things:
1. Removal of the feature toggle for Quick Access
2. Update of dependencies
The feature in the changelog is needed to proceed on the Manage Projects section.
=> docs(changelog): for v4.3.0 [skip ci]

packages/application-shell/src/components/fetch-project/fetch-project.js, packages/application-shell/src/components/fetch-project/index.js, packages/application-shell/src/components/fetch-user/fetch-user.js, packages/application-shell/src/components/fetch-user/index.js, packages/application-shell/src/index.js, packages/permissions/README.md, packages/sdk/src/test-utils/README.md
As suggested here: https://github.com/commercetools/merchant-center-application-kit/pull/241#issuecomment-450898994
=> chore: drop deprecated components

CHANGELOG.md
In preparation for the upcoming `v5.0.0` release.
~~_NOTE: wait for #197 to be merged first_~~
=> docs(changelog): for release v5.0.0

rollup.config.js
We need to run the babel plugin to transform the import `lodash` to `lodash-es` only when bundling ES modules, not CJS 🙈
=> fix(rollup): rename lodash import to lodash-es only for es bundle

packages/create-mc-app/bin/create-mc-app.js, packages/create-mc-app/package.json, packages/create-mc-app/src/logger.js, packages/create-mc-app/src/steps/download-template.js, packages/create-mc-app/src/steps/index.js, packages/create-mc-app/src/steps/install-dependencies.js, packages/create-mc-app/src/steps/parse-arguments.js, packages/create-mc-app/src/steps/success.js, packages/create-mc-app/src/steps/update-package-info.js, yarn.lock
Branch experiment for fancy loggers using https://github.com/klaussinani/signale
=> feat(create-mc-app): use fancy logger

application-templates/starter/package.json, packages/application-shell/package.json, packages/application-shell/src/components/login-sso/__snapshots__/login-sso.spec.js.snap, packages/application-shell/src/components/login-sso/login-sso.js, packages/application-shell/src/components/login/login.js, packages/react-notifications/package.json, playground/package.json, yarn.lock
Update ui-kit to 6.1.1.
And allow login on enter (that's why I put semvar fix)
=> chore: update ui-kit and make login submit on enter

CHANGELOG.md
I would like to do a release so I can update MC-FE to implement the fix from #290
=> chore: update changelog for 6.0.1

application-templates/starter/package.json, packages/application-shell/package.json, packages/react-notifications/package.json, packages/react-notifications/src/components/notification/notification.js, playground/package.json, scripts/install_app_template.sh, yarn.lock
Updates UI Kit to latest version.
=> chore: update ui kit to v7

application-templates/starter/src/index.js
=> fix(template/starter): add missing react-select css import [skip ci]

application-templates/starter/package.json, package.json, packages/application-shell-connectors/package.json, packages/application-shell/package.json, yarn.lock
Closes #317 
Closes #318 
Closes #319 
Closes #320 
Closes #321 
Closes #322
=> chore: update reps

packages/application-shell/package.json, packages/application-shell/src/components/login-sso-callback/login-sso-callback.js, packages/application-shell/src/components/login-sso-callback/login-sso-callback.spec.js, packages/browser-history/index.js, packages/browser-history/package.json, packages/sdk/package.json, packages/sdk/src/utils/utils.js, packages/sdk/src/utils/utils.spec.js, yarn.lock
This pull request proposes to also remove `query-string` for `qss` in app-kit.
There are some change I will comment on inline.
=> Replace `query-string` with `qss`

yarn.lock
I was checking if tests are still working with a fresh lockfile.
=> chore: regenerate lockfile

packages/application-shell/src/components/application-shell/application-shell.js, packages/application-shell/src/components/application-shell/application-shell.spec.js
⚠️ Do not merge yet ⚠️ 
This pull requests suggest to redirect to the welcome page.
=> fix(application-shell): redirect to welcome by default

CHANGELOG.md
I gave this changelog my ❤️ and 👻. Hope it make sense. Feel free to comment or even push. Cheers.
=> docs(changelog): for v8.0.0 [skip ci]

application-templates/starter/package.json, packages/application-components/package.json, packages/application-shell/package.json, packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap, packages/application-shell/src/components/login-sso/__snapshots__/login-sso.spec.js.snap, packages/i18n/package.json, packages/react-notifications/package.json, playground/package.json, yarn.lock
Nothing to be migrated in the app-kit
=> chore: update to ui-kit v9.0.0

CHANGELOG.md
Updates changelog for next release
=> docs(changelog): for release v10.0.0 [skip ci]

packages/mc-scripts/config/create-webpack-config-for-production.js
Sensible defaults for the minimizer.
=> chore: add sourcemap

packages/application-shell/src/configure-apollo.js
This reverts commit 05c21274ac5f77ce3d0bb8e1e6dc32ff4ef86fdd.
Sorry 🙏 for the noise here
=> Revert "refactor(configure-apollo): add special mapping for deliveryItem type

packages/application-components/src/components/dialogs/internals/dialog-footer.js, packages/application-components/src/components/dialogs/internals/dialog-styles.mod.css
=> fix(components/dialog): to have L spacing between buttons

application-templates/starter/package.json, packages/application-shell/package.json, packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap, packages/react-notifications/package.json, playground/package.json, visual-testing-app/package.json, yarn.lock
See https://github.com/ReactTraining/react-router/releases/tag/v4.4.0-beta.7
=> chore: upgrade to react-router v4.4.0-beta.7

application-templates/starter/package.json, application-templates/starter/src/components/entry-point/entry-point.js, package.json, packages/application-shell/package.json, packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap, packages/react-notifications/package.json, playground/package.json, playground/src/components/entry-point/entry-point.js, visual-testing-app/package.json, yarn.lock
Refs:
- https://github.com/ReactTraining/react-router/issues/6611
- #415 
Fixes #424
=> fix: pin react-router to 4.4.0-beta.6

packages/application-shell/src/components/public-page-container/public-page-container.js, packages/application-shell/src/components/quick-access/create-commands.js, packages/application-shell/src/components/user-settings-menu/user-settings-menu.js
=> chore: update privacy link

application-templates/starter/package.json, package.json, packages/application-shell/package.json, packages/application-shell/src/components/app-bar/__snapshots__/app-bar.spec.js.snap, packages/browser-history/package.json, packages/react-notifications/package.json, playground/package.json, visual-testing-app/package.json, yarn.lock
See https://github.com/ReactTraining/react-router/releases/tag/v4.4.0-beta.8
=> React Router v4.4.0

packages/application-shell/src/index.js
These two components can be re-exported. It is preparation for having sign-up, login and password reset in a stand alone application.
=> feat(app-shell): add re-export of gtm logout and flopflip

packages/application-shell/src/components/quick-access/butler/butler.js, packages/application-shell/src/components/quick-access/butler/butler.mod.css
This pull request adds loading feedback to Quick Access.
=> feat(app-shell): quick access to have loading indicator

.prettierignore, packages/application-components/.storybook/addons.js, packages/application-components/.storybook/config.js, packages/application-components/.storybook/decorators/intl/intl.js, packages/application-components/.storybook/webpack.config.js, packages/application-components/package.json, packages/application-components/src/components/dialogs/confirmation-dialog/confirmation-dialog.story.js, packages/application-components/src/components/dialogs/form-dialog/form-dialog.story.js, packages/application-components/src/components/dialogs/info-dialog/info-dialog.story.js, packages/application-components/src/components/maintenance-page-layout/maintenance-page-layout.story.js, yarn.lock
This pull request updates to the latest storybook version for our application-components package.
=> fix: update storybook to v5

packages/mc-html-template/load-headers.js
=> chore: remove csp report-uri

.circleci/config.yml
=> fix: add node_modules to cache

.circleci/config.yml
=> fix: save other dist folders too

.circleci/config.yml
I presume we can update the orb and pass the working directory as the project dir.
=> Fix orb for compare urls

packages/application-shell/package.json, yarn.lock
Just simplified something interally. Nothing too jazzy,
=> chore: update launchdarkly-adapter

CHANGELOG.md
Would like to release this to unblock a branch by @jonnybel on sign up.
=> docs(changelog): for v12.1.0

packages/assets/package.json
=> fix(assets): publish all files and folders

packages/application-shell/src/components/application-shell/application-shell.mod.css
=> fix(app-shell): prevent main content to be scrollable when modals are open

CHANGELOG.md
=> docs(changelog): add v13.2.0

packages/application-components/src/components/dialogs/form-dialog/form-dialog.visualroute.js, packages/application-components/src/components/dialogs/form-dialog/form-dialog.visualspec.js, packages/application-components/src/components/dialogs/internals/dialog-styles.mod.css
I want to check the Percy diff first
=> fix: form dialog overflow fix, add vrt

packages/application-components/src/components/dialogs/internals/dialog-styles.mod.css
In #534 there was a change to attempt to fix #533 
Unfortunately that change broke the normal scrolling behaviour, so we need to find another solution for the dropdown problem.
=> fix(dialogs): content overflow. Refs #534

application-templates/starter/src/messages.js, package.json, packages/application-shell/src/components/failed-authentication/index.js, packages/i18n/load-i18n.js, packages/l10n/country-information.js, packages/l10n/currency-information.js, packages/l10n/data/currencies/de.json, packages/l10n/data/currencies/en.json, packages/l10n/data/currencies/es.json, packages/l10n/data/currencies/fr-FR.json, packages/l10n/data/currencies/zh-CN.json, packages/l10n/data/time-zones/de.json, packages/l10n/data/time-zones/en.json, packages/l10n/data/time-zones/es.json, packages/l10n/data/time-zones/fr-FR.json, packages/l10n/data/time-zones/zh-CN.json, packages/l10n/language-information.js, packages/l10n/package.json, packages/l10n/scripts/generate-l10n-data.js, packages/l10n/time-zone-information.js, playground/src/messages.js, yarn.lock
Closes #536 
Closes #537 
Closes #538 
Closes #539  
Closes #540  
Closes #541
=> chore: update deps

packages/i18n/load-i18n.js
Whoever merged last broke `master` due to a formatting issue. This fixes it just formatting with prettier.
=> chore: fix formatting

CHANGELOG.md
Tested it with the canary. All fine. Would like the release.
=> docs(changelog): for v13.3.2 [skip ci]

packages/sentry/sentry.js
I'm reorganizing a bit our sentry projects, as we are rolling out more environments. For example, we can use more the new Sentry environment UI to differentiate between the different environments of a project (e.g. gcp prod eu/us).
=> refactor(sentry): to also pass location to sentry environment, enable sentry based on tracking value

website/src/images/external-link.svg, website/src/templates/markdown.js
Inspired by https://www.gatsbyjs.org/docs/gatsby-link/#reminder-use-link-only-for-internal-links
=> fix(website): to differentiate between internal and external links

packages/application-shell/src/components/quick-access/create-commands.js, packages/application-shell/src/components/quick-access/messages.js, packages/i18n/data/core.json
This pull request adds "Manage Projects" to Quick Access.
=> feat(app-shell): add "Manage Projects" to Quick Access

website/content/getting-started/development.mdx, website/src/images/anchor-link.svg, website/src/layouts/content.js, website/src/layouts/internals/layout-header.js, website/src/layouts/internals/layout-sidebar.js, website/src/layouts/internals/layout-toc.js, website/src/templates/markdown.js
=> feat(website): add table of content sidebar

CHANGELOG.md
Waiting for canary then releasing again.
=> docs(changelog): for v13.4.1 [skip ci]

packages/application-shell/package.json, yarn.lock
Hot off the press: new flopflip. Mainly been working on the hooks.
1. `useDebugValue` is now used in `useFeatureToggle` and `useAdapterStatus` giving nice output in the new but not yet released DevTools.
2. `useAdapteReconfiguration` is a super nice way to reconfigure the adapter (we don't need it)
=> 👯‍♀️ chore: update flopflip 👯‍♀️

packages/application-components/test-utils/visual/spec.js
Replace deprecated custom properties from ui kit.
=> refactor: use non deprecated custom props

packages/application-shell/src/components/app-bar/app-bar.mod.css, packages/application-shell/src/components/user-settings-menu/user-settings-menu.mod.css, packages/react-notifications/src/components/notification/notification.mod.css
Stop using deprecated ui-kit custom properties.
=> chore: move deprecated custom prop internal

packages/application-shell/src/components/project-switcher/__snapshots__/project-switcher.spec.js.snap, packages/application-shell/src/components/project-switcher/project-switcher.js, packages/application-shell/src/components/project-switcher/project-switcher.mod.css, packages/application-shell/src/components/project-switcher/project-switcher.spec.js
Same idea as #617 
Before
After
I removed the logic around adjusting the width of the select box based on the value, I don't think it really adds much value.
=> refactor(project-switcher): refactor to use ui kit select input

CHANGELOG.md
Updates changelog for version `13.4.2`
Note: I used a `patch` version because it seems like the go-to to use for refactoring?
=> chore: update changelog for version 13.4.2

packages/application-shell/src/components/app-bar/app-bar.mod.css, packages/react-notifications/src/components/notification/notification.mod.css
In #616, I introduced some invalid shadows 😓
=> fix(application-shell, react-notifications): fix invalid shadow

CHANGELOG.md
Changelog update for release cutting ceremony
=> chore: update changelog for `13.5.0`

packages/application-components/src/components/modal-page/README.md, packages/application-components/src/components/modal-page/index.js, packages/application-components/src/components/modal-page/modal-page.js, packages/application-components/src/components/modal-page/modal-page.mod.css, packages/application-components/src/components/modal-page/modal-page.story.js, packages/application-components/src/components/modal-page/modal-page.visualroute.js, packages/application-components/src/components/modal-page/modal-page.visualspec.js, packages/application-components/src/index.js
Moving the ModalPage component from the MC app to here. Lots of changes will be done to the component, but this is the first part of the job -- to have storybook and visual regression tests first and then build on top of it.
TODO:
=> feat(components): add ModalPage component

application-templates/starter/package.json, lerna.json, packages/application-shell/package.json, packages/application-shell/src/components/with-applications-menu/fetch-applications-menu.graphql, packages/application-shell/src/components/with-applications-menu/with-applications-menu.spec.js, playground/package.json
This pull request adds loading the menu visibility to app-kit and the menu query.
Note, that this is blocked until an internal change to the proxy-http-server has been published and deployed to all envs. In the mean time I will publish a pre-release of this to test it on a branch deployment.
=> feat(app-shell): add menuVisibility to menu query

CHANGELOG.md
=> docs(changelog): for v13.6.0 [skip ci]

packages/application-shell/src/components/quick-access/create-commands.js, packages/application-shell/src/components/quick-access/messages.js, packages/application-shell/src/components/quick-access/quick-access.js, packages/application-shell/src/components/quick-access/quick-access.spec.js, packages/i18n/data/core.json
This pull request adds "Manage Organizations` to QuickAccess while respecting the feature toggle.
=> feat(app-shell): add manage organizations

packages/application-shell/package.json, website/gatsby-config.js, website/package.json, website/src/components/external-link.js, website/src/components/index.js, website/src/layouts/internals/layout-header.js, website/src/pages/index.js, website/src/templates/markdown.js, yarn.lock
=> feat(website): to link to current release page

application-templates/starter/package.json, packages/application-components/package.json, packages/application-shell/package.json, packages/application-shell/src/components/project-switcher/__snapshots__/project-switcher.spec.js.snap, packages/react-notifications/package.json, playground/package.json, website/package.json, yarn.lock
I don't think there is anything to migrate...or?
=> chore: update ui-kit to v9.8.1

visual-testing-app/webpack.config.js
As of percy-puppeteer 1.0.8 there is first class CSS in JS support.
Special thanks to @robdel12
=> chore: remove note and usage of dev mode in webpack for vrt app

.stylelintignore, .stylelintrc, jest.stylelint.config.js, package.json, packages/application-components/src/components/dialogs/internals/dialog-container.js, packages/application-components/src/components/dialogs/internals/dialog-footer.js, yarn.lock
This enables/adds css-in-js linting. More comments inline with the code.
Closes #684
=> refactor: add css-in-js linting

packages/mc-scripts/build.js, packages/mc-scripts/start.js
=> fix(mc-scripts): do not assume that the application entry point is at src/index.js

application-templates/starter/env.json, packages/application-shell-connectors/src/components/application-context/README.md, packages/application-shell-connectors/src/components/application-context/application-context.js, packages/application-shell-connectors/src/components/application-context/application-context.spec.js, packages/application-shell/src/components/application-shell-provider/application-shell-provider.spec.js, packages/application-shell/src/components/application-shell/__snapshots__/application-shell.spec.js.snap, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/project-container/project-container.spec.js, packages/application-shell/src/configure-apollo.js, packages/application-shell/src/test-utils/test-utils.js, packages/application-shell/src/version.js, packages/jest-preset-mc-app/setup-tests.js, packages/mc-html-template/lib/load-env.js, packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.js, packages/sdk/package.json, packages/sdk/src/middleware/client.js, packages/sdk/src/version.js, playground/README.md, playground/env.json, playground/env.prod-eu.json, playground/env.prod-us.json, website/content/getting-started/deployment.mdx, yarn.lock
Requires #693 to be merged first.
=> refactor: for the http clients to send a x-user-agent with the package versions

packages/application-shell/src/configure-apollo.js, packages/sdk/package.json, packages/sdk/src/middleware/client.js
=> fix: setup of custom user agent

packages/application-shell/src/components/application-shell/application-shell.js, packages/application-shell/src/components/version-tracker/actions.js, packages/application-shell/src/components/version-tracker/index.js, packages/application-shell/src/components/version-tracker/version-tracker.js
This pull request adds a `VersionTracker` component (name TBD).
This `<VersionTracker />` will be used within the `<ApplicationShell />` that means no need to configure anything for e.g. a custom app.
It uses a new field `applicationName` from the `env.json` (we can make it a breaking change or not).
=> feat(app-shell): add version tracker

packages/application-shell/src/components/version-tracker/version-tracker.js
This pull request adds tracking of react's version.
=> feat(app-shell): add reporting react version

packages/actions-global/package.json, packages/application-components/package.json, packages/application-shell-connectors/package.json, packages/browser-history/package.json, packages/i18n/package.json, packages/l10n/package.json, packages/notifications/package.json, packages/permissions/package.json, packages/react-notifications/package.json, packages/sentry/package.json, packages/url-utils/package.json
Ref: https://github.com/commercetools/merchant-center-application-kit/issues/701#issuecomment-499501254
=> fix: define @babel/runtime-corejs3 in each (browser) package

lint-staged.config.js, packages/actions-global/package.json, packages/application-components/package.json, packages/application-shell-connectors/package.json, packages/application-shell/package.json, packages/browser-history/package.json, packages/constants/package.json, packages/i18n/package.json, packages/l10n/package.json, packages/notifications/package.json, packages/permissions/package.json, packages/react-notifications/package.json, packages/sdk/package.json, packages/sentry/package.json, packages/storage/package.json, packages/url-utils/package.json, playground/package.json
=> fix(i18n): missing peer dep

CHANGELOG.md
Release notes. Would like to get the version tracking.
=> docs(changelog): for v13.9.0 [skip ci]

.stylelintignore, jest.stylelint.config.js, website/src/components/code-block.js, website/src/layouts/internals/globals.js, website/src/templates/markdown.js
Adds stylelint for the website. Fixes a few lint errrors.
Closes #680
=> feat: lint css for website

packages/sentry/tsconfig.json, packages/storage/index.js, packages/storage/index.ts, packages/storage/package.json, packages/storage/src/index.ts, packages/storage/src/version.ts, packages/storage/tsconfig.declarations.json, packages/storage/tsconfig.json
Use typescript for the `storage` package.
=> feat(storage): use typescript

packages/mc-scripts/config/create-webpack-config-for-development.js, packages/mc-scripts/config/create-webpack-config-for-production.js, rollup.config.js
Let's kill that `autoprefixer` warning :)
=> fix(build): use `overrideBrowsersList` to comply with new autoprefixer API

packages/sdk/README.md
This PR refactors readme sdk example
=> docs(sdk): fix example code

playground/src/components/state-machines-details/actions.js, playground/src/components/state-machines-details/index.js, playground/src/components/state-machines-details/state-machines-details.js, playground/src/components/state-machines-list/state-machines-list.js, playground/src/components/state-machines-list/state-machines-list.spec.js, playground/src/mocks/apply-ui-kit-mocks.js, playground/src/mocks/index.js, playground/src/routes.js
This pull request implements a details page for state machines
=> [Feat] implement state-machines details page

CHANGELOG.md
@montezume and I would like to release for the translation fixes.
=> docs(changelog): for v13.11.0 [skip ci]

packages/application-components/src/components/page-not-found/page-not-found.js, packages/application-shell/src/components/navbar/navbar.js, packages/application-shell/src/components/quick-access/create-commands.js, packages/application-shell/src/components/user-settings-menu/user-settings-menu.js, packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js, packages/application-shell/src/constants.js, packages/constants/src/constants.ts
I was looking to make some changes in order to open a PR and trigger Percy (#767 ) and noticed that the support url was not consistent.
I moved it then to constants.
=> fix: support link url

.github-labelsrc.json, lerna.json, package.json, yarn.lock
Follow up of #751 
This PR updates the label config, following some new ideas:
- labels that have similar meanings and that are part of the same type, use the same color
- update colors
- add new labels
~~NOTE: I need to apply/sync the changes before merging this~~
=> chore: update github labels config

packages/application-shell/src/components/quick-access/butler/butler.mod.css
Removes usage of a deprecated custom property.
=> chore(application-shell): remove usage of deprecated custom property

packages/application-components/src/components/modal-pages/internals/modal-page.styles.js
Just a style adjustment, requested by the design team.
=> style(modal-pages): increase modal content top padding

packages/application-components/package.json, packages/application-shell-connectors/package.json, packages/application-shell-connectors/src/components/application-context/application-context.tsx, packages/application-shell/package.json, packages/i18n/package.json, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts, packages/react-notifications/package.json, packages/sdk/package.json, yarn.lock
=> [v14] chore: bump react peer deps to >=16.8 (hooks support)

package.json, packages/jest-preset-mc-app/package.json, yarn.lock
=> [v14] chore(jest-preset): bump enzyme-extensions dep to v5

package.json, packages/jest-stylelint-runner/package.json, packages/mc-scripts/config/create-webpack-config-for-development.js, packages/mc-scripts/config/create-webpack-config-for-production.js, packages/mc-scripts/package.json, visual-testing-app/package.json, visual-testing-app/webpack.config.js, website/package.json, yarn.lock
This pull request mainly takes a shot at updating the webpack loaders which we failed to update in the past. In all to be able to more easily update to the next version of webpack.
=> chore: update webpack loaders

cypress/integration/playground/state-machines.js, cypress/integration/template-starter/main.js, cypress/support/commands.js, cypress/support/urls.js, packages/mc-scripts/package.json, packages/permissions/README.md, playground/menu.json, playground/src/components/state-machines-list/state-machines-list.js, playground/src/components/state-machines-list/state-machines-list.spec.js, playground/src/constants.js, playground/src/routes.js
@montezume is this everything that's left?
=> [v14] refactor(mc-scripts): to remove IE from browserslit

package.json, packages/actions-global/package.json, packages/application-shell-connectors/package.json, packages/application-shell/package.json, packages/permissions/package.json, packages/react-notifications/package.json, playground/package.json, yarn.lock
Closes #819 
Closes #820 
Closes #821 
Closes #822 
Closes #823 
Closes #824 
Closes #833 
Closes #837
=> chore: update dependencies

packages/application-shell/src/components/quick-access/constants.js, packages/application-shell/src/components/quick-access/create-commands.js, packages/application-shell/src/components/quick-access/quick-access.js, packages/application-shell/src/components/quick-access/quick-access.spec.js
This pull request refactors Quick Access to use the new permissions. Given organizations will start being migrated we otherwise might allow users to navigate to a part of the MC through Quick Access where we then show a `PageUnauthorized`.
=> refactor(app-shell/quick-acess): to use new permissions

packages/application-shell/src/components/quick-access/create-commands.js, packages/application-shell/src/components/quick-access/sub-commands.js
=> refactor(quick-access): leftover for permissions cleanup

packages/application-shell/src/components/quick-access/create-commands.js, packages/application-shell/src/components/quick-access/quick-access.js, packages/application-shell/src/components/quick-access/quick-access.spec.js, packages/application-shell/src/components/quick-access/sub-commands.js, packages/permissions/src/index.ts
As discussed here: https://github.com/commercetools/merchant-center-application-kit/pull/851#issuecomment-511341982
=> [v14] refactor(permissions): to not expose hasPermission

CHANGELOG.md, packages/l10n/README.md, packages/l10n/package.json, packages/l10n/src/country-information.ts, packages/l10n/src/create-l10n-injector/create-l10n-injector.spec.tsx, packages/l10n/src/create-l10n-injector/create-l10n-injector.tsx, packages/l10n/src/create-l10n-injector/index.ts, packages/l10n/src/currency-information.ts, packages/l10n/src/index.ts, packages/l10n/src/language-information.ts, packages/l10n/src/time-zone-information.ts, yarn.lock
...so that we also ship hooks for the l10n package.
=> [v14] refactor(l10n): to implement loading data with hooks, refactor internals of HOCs

CHANGELOG.md, packages/application-components/package.json, packages/application-shell/package.json, packages/react-notifications/package.json
In preparation for the release. Let me know if it's not clear enough or if I forgot something.
=> docs(changelog): for release v14.0.0 [skip ci]

packages/jest-preset-mc-app/package.json, packages/jest-preset-mc-app/polyfills/intl-pluralrules.js, packages/jest-preset-mc-app/polyfills/intl.js, packages/jest-preset-mc-app/setup-test-framework.js, yarn.lock
TL;DR; the polyfill for `PluralRules` was missing (for nodejs/test environment).
=> [v14] fix(jest-preset): missing polyfill for plural rules

package.json, packages/application-shell/src/utils/select-project-key-from-url/select-project-key-from-url.spec.js, yarn.lock
Closes #866 
Closes #867 
Closes #868 
Closes #869 
Closes #870 
Closes #871
=> [v14] update deps

package.json, packages/application-shell/src/utils/select-project-key-from-url/select-project-key-from-url.spec.js, yarn.lock
Ref: https://github.com/jest-community/eslint-plugin-jest/issues/334
=> chore: update jest eslint to patch version

packages/actions-global/src/hooks/use-show-notification.ts
=> fix(actions-global): typing of useShowNotification

CHANGELOG.md
I tested the canary/build locally already and worked with it to verify the bug fixes work.
=> docs(changelog): for v14.1.1 [skip ci]

packages/permissions/src/components/restricted-by-permissions/restricted-by-permissions.spec.tsx
This pull request refactors, as promised, the `RestrictedByPermissions` to use RTL.
=> refactor(permissions): restricted-by-permissions to rtl

.github-labelsrc.json, .kodiak.toml
This pull request adds the config for the Kodiak merge bot. https://github.com/chdsbd/kodiak#prior-art
=> chore(ci): add kodiak

yarn.lock
=> chore: use recent version 5.4.3 of intl-messageformat

packages/mc-http-server/Dockerfile
This pull request suggests to update the `mc-http-server` to Node.JS v12.
=> chore(mc-http-server): update to node v12

.eslintrc.yaml, packages/application-shell/src/components/configure-intl-provider/configure-intl-provider.js, packages/react-notifications/src/components/notifications-list/notifications-list.tsx, packages/react-notifications/src/components/notifier/notifier.tsx, website/src/layouts/internals/layout-sidebar.js, website/src/templates/markdown.js
PS: I'll merge #896 first, as there is a component that needs to be adjusted in react-notifications
=> chore: enable eslint rules for react hooks

@types/commercetools-frontend__ui-kit/index.d.ts, packages/application-shell-connectors/package.json, packages/react-notifications/src/components/notification/notification.tsx, yarn.lock
See https://github.com/commercetools/ui-kit/pull/860#issuecomment-517238813
TL;DR: we will maintain the uikit type declarations here for now. **If needed**, we can also publish the types as a package, or publish them to DefinitelyTyped.
=> feat: add some uikit declaration types

packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx, packages/application-shell-connectors/src/components/application-context/application-context.tsx, packages/application-shell/src/components/fetch-project/fetch-project.graphql, packages/application-shell/src/components/fetch-project/fetch-project.js, packages/application-shell/src/components/fetch-project/fetch-project.spec.js, playground/env.json
- adds `allAppliedDataFences` to `FetchProject` query
=> feat(application-shell/project-query): add `allAppliedDataFences`

.circleci/config.yml, .percy.yml, website/gatsby-config.js, website/src/pages/index.js
Source: https://docs.percy.io/docs/command-line-client#section-generating-snapshots
Let's see how good it works, to snapshot a statically built website.
=> feat(circleci): snapshot testing for documentation website

packages/application-shell/src/test-utils/test-utils.js, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx
=> fix(test-utils): to set default required dataFences option

packages/react-notifications/src/components/notification/notification.tsx
=> fix(react-notifications): onCloseClick is optional

packages/application-components/src/components/modal-pages/info-modal-page/info-modal-page.tsx
=> fix(application-components): prop is optional

packages/constants/src/constants.ts
Found this here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions
=> refactor(constants): use const assertion

application-templates/starter/package.json, packages/application-components/package.json, packages/application-shell/package.json, packages/react-notifications/package.json, playground/package.json, visual-testing-app/package.json, website/package.json, yarn.lock
This pull request updates `react-intl` to contain the last fixes from @emmenko to the library 😄.
=> chore: update react-intl

packages/application-shell/src/components/navbar/navbar.js, packages/application-shell/src/components/with-applications-menu/fetch-applications-menu.graphql, packages/application-shell/src/components/with-applications-menu/with-applications-menu.spec.js, packages/permissions/src/components/authorized/authorized.spec.tsx, packages/permissions/src/utils/has-permissions.ts
the prop drilling we were doing was incomplete 😅 I needed to pass dataFences one more level down. 
TODO:
=> CON-187: properly pass dataFences from menu to `Authorized.js`

CHANGELOG.md, application-templates/starter/package.json, lerna.json, packages/application-shell/package.json, packages/permissions/package.json, playground/package.json
=> docs(changelog): update for release 14.6.1 [skip ci]

packages/mc-html-template/lib/load-headers.js, packages/mc-http-server/package.json, packages/mc-http-server/server.js, yarn.lock
Adds a referrer policy header to the mc-http-server. More details on the interal PR.
=> fix(mc-http-server): to add referrer policy

packages/application-shell/src/components/navbar/navbar.js, packages/application-shell/src/components/navbar/navbar.spec.js
=> fix(app-shell): null check for dataFences in navbar component

netlify.toml, website/gatsby-config.js, website/package.json, yarn.lock
Based on this: https://github.com/gatsbyjs/gatsby/issues/8056#issuecomment-503339955
=> Try to improve Netlify build time for website

packages/application-shell/src/components/authenticated/authenticated.js
Fixes an issue with the cache policy. Paired with @emmenko.
=> fix(app-shell): fetch policy on AmILoggedIn

packages/mc-html-template/lib/load-headers.js
=> fix(csp): to whitelist sentry.io in connect-src

.renovaterc.json
This pull request excludes packages which have been causing issues the last update cycles.
I want to try the configuration first. If we continuously do this we should also keep track of these and document what issues they have caused which needs resolving in order for us to upgrade again.
=> fix: exclude package names causing issues

packages/application-shell/src/apollo-links/header-link.js, packages/application-shell/src/apollo-links/header-link.spec.js
This pull request omits empty header values. Instead of passing potentially `null` through the links we remove the value.
This is an attempt to reduce the "Failed to fetch"-errors. On some issues on Apollo it was said that doing this or passing `''` removed the issue. I think it might be worth a shot.
=> fix(app-shell): apollo header link to omit empty headers

packages/mc-scripts/compile-html.js
=> fix(mc-scripts): to read headers path

website/content/deployment/example-aws-s3-cloudfront.mdx, website/content/deployment/example-firebase.mdx
See https://github.com/commercetools/merchant-center-application-kit/pull/932#issuecomment-532742626
=> docs(website): fix malformed hyphens

.eslintignore, .gitignore, .prettierignore, packages/application-shell-connectors/package.json, packages/application-shell-connectors/src/test-utils/README.md, packages/application-shell-connectors/src/test-utils/index.ts, packages/application-shell-connectors/src/test-utils/test-utils.spec.ts, packages/application-shell-connectors/src/test-utils/test-utils.ts, packages/application-shell-connectors/test-utils.ts
=> feat(app-connectors): expose mock functions for image-regex settings as test-utils

CHANGELOG.md
=> docs(changelog): for v15.2.1 [skip ci]

packages/mc-http-server/bin/start-mc.js, packages/mc-http-server/server.js
This pull request carries out the same refactoring we did on all services in regards to: start up logic and graceful shutdown while splitting code into the same functions.
=> refactor(mc-http-server): startup logic

packages/mc-http-server/server.js
This pull request removes the duplicate metric again.
=> chore(mc-http-server): remove duplicate prom metric

CHANGELOG.md
Needed internally. Blocking a team.
=> docs(changelog): for v15.3.0 [skip ci]

packages/application-shell/src/components/performance-timing/measure-first-paint.js
This is a strange inconsistency in `perfume.js` API.
The function does not return a promise whenever the value is not supported in a browser.
=> fix(app-shell): how metric is read

packages/application-shell/src/utils/gtm.js
This pull reques improves the logging without our tracking module.
We know use the shared logger to omit tracking on production.
We also get some nicer messages which helps a lot when working with this.
The colors match in collapsed and expanded console groups so it's easy to spot what's happening.
=> chore(app-shell): add logging to tracking

packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.js, packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.spec.js, packages/application-shell/src/feature-toggles.js
=> fix(app-shell): to merge internal feature flags with provided ones

packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.js
The default is the origin. We only allow configuring.
=> fix(app-shell): falling back to default

packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.js, packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.spec.js
We mnissed that we need to return defaulted values for the flags.
=> fix(app-shell): return object with default values

packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.js
We need this config. Not flag as it's now.
=> fix(app-shell): passing of flag config

packages/i18n/data/en.json
Somehow we didn't get a PR from TS regarding this change.
=> chore(i18n): add missing translation

CHANGELOG.md
=> docs(changelog): for v15.3.8 [skip ci]

application-templates/starter/package.json, packages/application-components/package.json, packages/application-shell/package.json, packages/babel-preset-mc-app/index.js, packages/react-notifications/package.json, playground/package.json, visual-testing-app/package.json, website-components-playground/package.json, yarn.lock
I found this comment and wanted to give it a shot so at least we tried and have a PR documented with the attempt.
https://github.com/formatjs/react-intl/issues/1511#issuecomment-563191853
=> fix: babel macros with react-intl

.vscode/settings.json, .yarnrc, packages/mc-scripts/package.json, visual-testing-app/package.json, website-components-playground/package.json, yarn.lock
Otherwise we will always forget these versions I think.
=> chore: update yarn and missing deps

packages/application-shell/src/apollo-links/error-link.js
=> fix(app-shell): null check

packages/l10n/README.md
Add `ja` to the list of supported locales.
=> chore: update docs

packages/application-shell/src/components/project-data-locale/project-data-locale.js, packages/application-shell/src/components/project-data-locale/project-data-locale.spec.js
Extracting some changes during the TS migration (#1218)
=> refactor(app-shell): rewrite tests for ProjectDataLocale, use functional components

packages/actions-global/src/actions/handle-action-error.ts, packages/actions-global/src/hooks/index.ts, packages/actions-global/src/hooks/use-on-action-error.ts
Similar to the prior PR this adds useOnActionError.
=> feat(actions-global): to add use-on-action-error

packages/sdk/src/hooks/use-async-dispatch.ts, packages/sdk/src/index.ts
Addresses this: https://github.com/commercetools/merchant-center-application-kit/pull/1246#discussion_r368243447
=> feat(sdk): add useAsyncDispatch for resolving async sdk actions (static types)

lint-staged.config.js
=> refactor(lint-staged): remove unnecessary git add

packages/application-shell/src/components/application-shell-provider/application-shell-provider.js, packages/application-shell/src/components/application-shell/application-shell.js, packages/application-shell/src/components/gtm-application-tracker/gtm-application-tracker.js, packages/application-shell/src/components/gtm-application-tracker/gtm-application-tracker.spec.js, packages/application-shell/src/components/gtm-application-tracker/index.js, packages/application-shell/src/track-performance.js, packages/application-shell/src/utils/gtm.js
=> feat: send performance timing values to GTM

application-templates/starter/menu.json, application-templates/starter/src/routes.js, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/quick-access/create-commands.js, packages/application-shell/src/test-utils/README.md, packages/permissions/README.md, packages/permissions/src/hooks/use-is-authorized/use-is-authorized.spec.tsx, packages/sdk/README.md, playground/menu.json, playground/src/routes.js
This pull request extracts items from #1261 to stop proposing/using to be deprecated APIs in the docs.
=> refactor: fix and improve docs and usage of permissions

recommended.code-workspace
=> chore: add missing settings to vscode recommended workspace

packages/application-shell-connectors/src/components/application-context/application-context.tsx, packages/application-shell/src/components/gtm-application-tracker/gtm-application-tracker.js, packages/application-shell/src/components/version-tracker/version-tracker.js, packages/application-shell/src/configure-apollo.js, packages/application-shell/src/utils/gtm.js, packages/constants/src/constants.ts, packages/mc-html-template/lib/load-env.js, packages/sdk/src/middleware/client.ts
> Part of the v16 breaking changes #1248
=> refactor: make applicationName a required field

website/gatsby-config.js, website/package.json, website/src/layouts/marketing.js, website/src/pages/fragments/based-on-design-system.mdx, website/src/pages/fragments/built-on-modern-technologies.mdx, website/src/pages/fragments/zero-config-development-tools.mdx, website/src/pages/index.js, yarn.lock
=> feat(website): enable search

website/gatsby-config.js, website/src/content/components/ui-kit.mdx, website/src/content/support-policy.mdx
Some leftovers:
- fix "Custom Application" title  letter case
- add basic info about ui-kit
=> docs(website): fix title case, add basic info about ui-kit

website/src/content/main-concepts/data-fetching.mdx
=> docs(website): improve documentation around data fetching

packages/create-mc-app/src/steps/download-template.js, packages/create-mc-app/src/steps/update-package-info.js
=> fix(create-mc-app): escape white spaces in project path

packages/application-components/package.json, packages/application-shell/package.json, packages/react-notifications/package.json
=> fix: keep ui-kit peer dep

website/src/content/main-concepts/user-permissions.mdx
This pull request aims to add a first draft to document the usage of permissions within a Custom Application.
This pull request focusses on the underlying components and mechanisms. In a follow up we would like to also document the current limitations when using permissions with or within a Custom Application.
=> docs(website): add first draft of user permissions

package.json, yarn.lock
Isolates the cypress update to v4.
=> chore: update cypress to v4

.github/workflows/main.yml
Just to potentially avoid future confusion.
=> chore: also kill second server

website/src/content/development/testing.mdx
Add missing left bracket to the link markdown
Add a missing left bracket for the link markdown
=> docs: testing.mdx

CHANGELOG.md
Contains the fixes in flopflip among other things.
=> docs: changelog for v16.2.2

website/package.json, yarn.lock
Includes improvements around bundle size and syntax highlighting.
=> chore(website): update to theme 1.7.7

.renovaterc.json
https://github.com/commercetools/merchant-center-application-kit/pull/1342#issuecomment-586849782
=> chore: ignore ts-jest updates (for now)

packages/mc-html-template/lib/load-headers.js
- adds `mc-production-asia` to `load-helpers`
=> feat(headers/csp): whitelist bucket for asia cloud region

website/src/content/main-concepts/api-gateway.mdx
=> docs(website): list legacy hostnames

.vscode/spellright.dict, packages/mc-html-template/README.md, website/src/content/deployment/runtime-configuration.mdx
> Wanted to start this before I forget.
Adds some docs regarding the placeholder addition to the readme. I didn't see any part of the custom application docs to put some details. Maybe @emmenko can show me if he had something in mind.
=> docs(mc-html-template): add docs for placeholders

jest.test.config.js, packages/application-shell/src/components/application-shell/application-shell.spec.js
This switches to using jsdom v16 under test.
=> chore: to use jsdom sixteen under test

CHANGELOG.md
Prepare CHANGELOG.md for release of v16.5.2.
=> docs: update changelog for v16.5.2

packages/application-shell/src/configure-apollo.ts
Fixes: https://github.com/commercetools/merchant-center-application-kit/issues/1390
=> fix(apollo-caching): simplify id from object logic

packages/permissions/src/hooks/use-is-authorized/use-is-authorized.ts
In prep for the onboarding session, I found this typo.. couldn't let it slide
=> refactor: hasDemandeDataFences -> hasDemandedDataFences

website/src/content/main-concepts/proxy-to-external-api.mdx
=> docs(website): mention limitations of forward-to proxy endpoint

application-templates/starter/package.json, package.json, packages/application-shell-connectors/package.json, packages/application-shell/package.json, packages/application-shell/src/components/application-shell-provider/application-shell-provider.spec.js, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/authenticated/authenticated.spec.tsx, packages/application-shell/src/components/back-to-project/back-to-project.spec.tsx, packages/application-shell/src/components/gtm-application-tracker/gtm-application-tracker.spec.js, packages/application-shell/src/components/gtm-booter/gtm-booter.spec.tsx, packages/application-shell/src/components/gtm-user-logout-tracker/gtm-user-logout-tracker.spec.js, packages/application-shell/src/components/gtm-user-tracker/gtm-user-tracker.spec.js, packages/application-shell/src/components/project-suspended/project-suspended.spec.js, packages/application-shell/src/components/project-switcher/project-switcher.spec.tsx, packages/application-shell/src/components/quick-access/quick-access.spec.js, packages/application-shell/src/components/redirect-to-project-create/redirect-to-project-create.spec.tsx, packages/application-shell/src/components/requests-in-flight-loader/requests-in-flight-loader.spec.tsx, packages/application-shell/src/components/route-catch-all/route-catch-all.spec.js, packages/application-shell/src/components/service-page-project-switcher/service-page-project-switcher.spec.js, packages/application-shell/src/components/user-settings-menu/user-settings-menu.spec.js, packages/application-shell/src/hooks/use-all-menu-feature-toggles/use-all-menu-feature-toggles.spec.js, packages/application-shell/src/hooks/use-applications-menu/use-applications-menu.spec.tsx, packages/application-shell/src/test-utils/test-utils.spec.tsx, packages/i18n/src/async-locale-data/async-locale-data.spec.tsx, packages/jest-preset-mc-app/package.json, packages/react-notifications/package.json, packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.spec.tsx, packages/react-notifications/src/components/notifier/notifier.spec.tsx, playground/src/components/state-machines-list/state-machines-list.spec.js, yarn.lock
This pull request attempts to update rtl to v10. 
The previous PRs should enabble this. However the types are not updated yet. More specifically the waitFor.
=> chore: update testing-library/react to v10

packages/jest-preset-mc-app/README.md, packages/jest-preset-mc-app/load-config.js, packages/jest-preset-mc-app/package.json, packages/jest-preset-mc-app/setup-tests.js
=> feat(jest-preset): allow to configure jest preset

website/package.json, yarn.lock
The UI component pages are currently broken on production. This version fixes that.
=> fix(website): rendering of UI component pages

.github/workflows/main.yml
The recent CI builds keep hanging on the cypress steps. I'm trying a different approach now
https://github.com/marketplace/actions/cypress-io#custom-install
=> refactor(ci): to not use cypress github action

packages/application-shell-connectors/package.json, packages/application-shell/package.json, packages/sdk/package.json, rollup.config.js, yarn.lock
=> fix: typings ref for test utils, treat crypto as an external module

packages-backend/express/src/auth.ts
Consider your server is hosted at `https://foo.com`, when you send the forwarded to request to that, the audience is set to `https://foo.com`.
However, the middleware attempts to append the request path (in this case `/`) to the configured audience value, resulting in the audience to be verified to be `https://foo.com/`.
Doing so, it will fail the token verification because of the mismatching audiences.
The fix is to not append the request path if it's just `/`.
cc @qmateub
=> fix(express): do not append trailing slash to audience if request path is "/"

packages-backend/loggers/src/create-application-logger.ts, packages-backend/loggers/src/middlewares/create-access-logger.ts
=> fix(loggers): silent option

.changeset/three-candles-shop.md
=> docs: missing changeset for eslint and jest preset packages

.gitignore, website/gatsby-config.js, website/package.json, website/src/@commercetools-docs/gatsby-theme-docs/overrides/page-header-side.js, website/src/@commercetools-docs/gatsby-theme-docs/overrides/use-additional-site-data.js, website/src/pages/index.js
=> refactor(website): update to docs-kit 4.0.0, do not show latest/next version

.github/workflows/publish-cloud-registry.yml
Fixes https://github.com/commercetools/merchant-center-application-kit/pull/1542#issuecomment-638174858
=> fix(workflows): use contains() to check for matching tag ref

website/src/content/main-concepts/api-gateway.mdx
=> docs(website): missing australia hostname

.changeset/fifty-balloons-buy.md, .github/workflows/main.yml, application-templates/starter/.env.template, application-templates/starter/README.md, application-templates/starter/env.json, application-templates/starter/headers.json, application-templates/starter/package.json, scripts/install-template.js, yarn.lock
Fixes #1548 
Ping @Rombelirk and @fuchodeveloper for awareness
=> fix(starter): ship it with headers.json and env vars placeholders, to use the new hostnames

website/src/content/getting-started/installing-a-starter-application.mdx
=> docs(website): update install steps setup

.changeset/spicy-panthers-clean.md, packages/eslint-config-mc-app/package.json
Adds the missing peer dep from the last version.
=> fix(eslint-config-mc-app): add missing peer dep

.changeset/great-otters-clean.md, packages/jest-preset-mc-app/setup-test-framework.js
This pull request fixes the import. My Monday morning SNAFU. Sorry.
=> fix(jest-preset-mc-app): to import with cjs

.changeset/three-pans-tickle.md, application-templates/starter/package.json, yarn.lock
This pull request adds the `bulk-update-versions` dependency and a run script to update appkit and uikit versions. Even though uikit is not used in the starter it might come in handy at later stages of a Custom Application lifespan.
=> feat(template/starter): to add version update script

.changeset/gentle-foxes-kiss.md, packages/application-shell/src/apollo-links/header-link.ts, packages/application-shell/src/constants.ts, packages/application-shell/src/utils/apollo-context.ts
=>  fix(app-shell): set headers for forward-to feature when using the Apollo client

graphql-test-utils/graphql-mocks/mc.js, graphql-test-utils/graphql-models/project.js, graphql-test-utils/graphql-models/user.js, packages/application-shell/package.json, packages/application-shell/src/components/authenticated/authenticated.spec.tsx, packages/application-shell/src/components/fetch-project/fetch-project.spec.js, packages/application-shell/src/components/fetch-user/fetch-user.spec.js, packages/application-shell/src/components/project-suspended/project-suspended.spec.js, yarn.lock
I would like to start refactoring the tests to avoid using Apollo mocks and instead using the MSW network mocks: https://mswjs.io/
This should be used in combination with the test data. In this repo we already have some test data mocks but eventually we want to use the new ones we're developing internally.
=> test: rewrite some tests using msw for mocking graphql requests

.changeset/tender-llamas-retire.md, packages/react-notifications/src/components/notification/notification.styles.ts
fixes https://github.com/commercetools/merchant-center-application-kit/issues/1711
=> Fix notifications styles issue (alignment and links color)

.changeset/odd-tips-sleep.md, website/src/content/support-policy.mdx
I'm just reading through the docs, and could improve the wording
=> docs(support-policy): improve wording

.changeset/three-readers-invent.md, website/src/content/main-concepts/proxy-to-external-api.mdx
- add description for decoded JWT and their claims
- closes https://github.com/commercetools/merchant-center-application-kit/issues/1739
=> docs(proxy-external): add description of decoded JWT claims

.github/workflows/main.yml, playground/custom-application-config.json, playground/vercel-deployments/state-machines-gcp-eu/package.json, playground/vercel-deployments/state-machines-gcp-us/package.json
Secret is added and it uses the wildcard hostname, for example `*.example.com`.
=> refactor(playground): allow to access playground app in our staging env

.changeset/long-cats-cheat.md, packages/actions-global/src/types.ts
=> refactor(actions-global/types): add `text` as optional to `TShowNotification`

.changeset/rotten-crabs-promise.md, @types/commercetools-uikit__icons/index.d.ts, packages/application-shell/src/components/navbar/navbar.tsx
- Added clock with arrow icon to available application icons for Change History
https://github.com/commercetools/mc-extension-operations/pull/622
=> feat(navbar): add clock with arrow icon to available application icons

.changeset/neat-chefs-tie.md, package.json, packages/i18n/package.json, playground/package.json, website-components-playground/package.json, website/package.json, yarn.lock
=> fix: update docs-kit to v11

.changeset/early-apples-lay.md, packages/babel-preset-mc-app/index.js
=> fix(babel): merging of options

application-templates/starter/CHANGELOG.md, application-templates/starter/src/components/entry-point/entry-point.js, application-templates/starter/src/components/entry-point/index.js, application-templates/starter/src/test-utils/index.js
=> refactor(starter): avoid using async routes in tests

.changeset/strong-dingos-vanish.md, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/application-shell/application-shell.tsx
Small regression related to our special `/account` route.
=> fix(app-shell): rendering of app with implicit routes when redirecting to /account route

.changeset/grumpy-lies-turn.md
Adds missing changeset for #2002
=> chore(public-page-layout): add changeset for #2002

.graphqlrc.yml
=> fix: graphql generator types path

packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.tsx
Adds a small comment to avoid future confusion.
=> docs(app-shell): add comment to process.env check

.changeset/odd-badgers-listen.md, application-templates/starter/package.json, packages/application-components/package.json, packages/application-shell/package.json, packages/application-shell/src/components/navbar/navbar.tsx, packages/react-notifications/package.json, playground/package.json, visual-testing-app/package.json, website-components-playground/package.json, yarn.lock
See https://jira.commercetools.com/browse/PANGOLIN-691 for full summary.
This change adds the new `ListWithSearch` icon as an option for an application's icon in the left-hand side navigation menu for Merchant Center.
=> chore(menu): add new icon for use in audit log app, upgrade ui-kit

.github/workflows/main.yml, jest-preset-mc-app.config.js
Something is wrong on `main` with the last update. I went through each dep one by one.
=> chore: fix dep update

.changeset/funny-students-remember.md, packages/mc-scripts/src/config/create-webpack-config-for-production.js
A bad on my end passing the options to the wrong loader.
=> fix(webpack): options passing to thread-loader

package.json
=> chore: typo is package.json

.changeset/angry-nails-grin.md, packages-backend/express/package.json, packages/application-shell/package.json, packages/application-shell/src/components/authenticated/authenticated.spec.tsx, yarn.lock
`msw` got a bit stricter with validating the handlers. Let's see where we end up here.
=> chore: update msw

.changeset/healthy-dingos-promise.md, packages/mc-html-template/src/generate-template.js
=> fix: respect cdnUrl value when loading favicons

.changeset/few-lamps-flow.md, packages/create-mc-app/src/hint-outdated-version.js
=> refactor(create-mc-app): only check for latest version for outdated version hint

.github/workflows/main.yml, application-templates/starter/src/routes.js, cypress/support/urls.js, playground/.env.local.template, playground/custom-application-config.json, playground/menu.json, playground/package.json, playground/src/components/echo-server/echo-server.js, playground/src/components/echo-server/messages.js, playground/src/components/entry-point/entry-point.js, playground/src/components/entry-point/entry-point.spec.js, playground/src/components/state-machines-list/state-machines-list.spec.js, playground/src/constants.js, playground/src/i18n/data/core.json, playground/src/routes.js
So that I can test it internally
=> refactor(playground): prepare app for production usage

.changeset/twenty-rabbits-admire.md, packages/l10n/src/index.ts, packages/l10n/src/localize.spec.ts, packages/l10n/src/localize.ts
- adds `transformLocalizedStringToLocalizedField`
reviewers selected by random
=> feat(l10n): adds `transformLocalizedStringToLocalizedField`

.changeset/heavy-ligers-admire.md
Follow up of https://github.com/commercetools/merchant-center-application-kit/pull/2144
/cc @emmenko
=> docs: changeset update [skip ci]

packages/mc-html-template/src/process-headers.js
=> fix(mc-html-template): to use separator

.changeset/cyan-jokes-marry.md, packages/create-mc-app/src/tasks/download-template.js
Resolves this bug:
https://github.com/commercetools/merchant-center-application-kit/issues/2167
Resolves and issue that prevents running `create-mc-app` on Windows
=> Add windows move command

.changeset/cyan-jokes-marry.md, packages/create-mc-app/src/tasks/download-template.js
Original PR #2168 
This PR only serves the purpose of running the CI workflow with all the secrets available, as secrets are not available from forks.
=> Add windows move command (#2168)

packages/jest-preset-mc-app/README.md, packages/jest-preset-mc-app/enzyme/apply-jest-preset-with-enzyme.js, packages/jest-preset-mc-app/enzyme/create-jest-preset-with-enzyme.js, packages/jest-preset-mc-app/enzyme/jest-preset-for-enzyme-16.js, packages/jest-preset-mc-app/enzyme/jest-preset-for-enzyme-17.js
=> refactor: improve Jest setup for Enzyme support

packages/application-components/src/components/dialogs/form-dialog/form-dialog.mdx
Add import code  to the  `FormDialog` component code snippet.
=> Add FormDialog import code snippet

.changeset/perfect-mice-bow.md, .changeset/wise-walls-know.md, packages/constants/src/constants.ts
This PR adds graphql and api proxy targets for order search
=> feat: to add api targets for order search

jest-preset-mc-app.config.js
=> fix: disable core-js in test environment

.stylelintignore, website/src/content/development/typescript.mdx, website/src/data/navigation.yaml
Until we have an official working template app in TS, let's avoid having this WIP page.
=> docs(website): remove coming-soon TS page for now

.changeset/proud-fans-wait.md, packages/mc-scripts/src/config/webpack-dev-server.config.js
=> fix: migrate webpack-dev-server options to v4.0.0-rc.0

website-components-playground/gatsby-node.js, website/gatsby-node.js
=> fix(website): instruct gatsby/babel to compile css prop

.changeset/tall-vans-warn.md, packages/actions-global/src/actions/handle-action-error.ts
=> fix(actions-global): support SSR

.changeset/kind-poets-agree.md, packages/application-config/schema.json, packages/application-config/src/schema.ts
[![UKIT-388](https://badgen.net/badge/JIRA/UKIT-379/0052CC)](https://jira.commercetools.com/browse/UKIT-388) ![Small PR](https://badgen.net/badge/Size/Small%20PR/green)
Introduce a "frame-src" directive to the Application Config
=> feat(application-config): Allow "frame-src" directive in the Custom Application Config

.changeset/lovely-hounds-carry.md, packages/application-shell/package.json, packages/application-shell/src/components/locale-switcher/locale-switcher.tsx, packages/application-shell/src/components/project-switcher/project-switcher.tsx, yarn.lock
=> fix(app-shell): container styles for locale switcher

.changeset/clean-chairs-unite.md, @types/commercetools__sdk-client/index.d.ts, packages/sdk/package.json, packages/sdk/src/actions/actions.spec.ts, packages/sdk/src/types.ts, website/src/content/development/data-fetching.mdx, yarn.lock
=> feat(sdk): allow to unset `content-type` by passing `null` as value

.changeset/giant-cougars-film.md, packages/eslint-config-mc-app/index.js
=> fix(eslint): regression of overriding test specific rules

.changeset/orange-dolphins-wave.md, packages/application-components/src/components/portals-container/portals-container.tsx, packages/application-shell/src/components/app-bar/app-bar.tsx, packages/application-shell/src/components/application-shell/application-shell.tsx, packages/application-shell/src/constants.ts, playground/src/components/entry-point/entry-point.js, playground/src/components/entry-point/index.js, playground/src/components/state-machines-details/state-machines-details.js, playground/src/components/state-machines-list/state-machines-list.js, playground/src/components/state-machines-list/state-machines-list.spec.js, playground/src/routes.js
=> fix(components): style position for `<PortalsContainer>` layout

.changeset/great-flies-mate.md, packages/application-components/src/components/portals-container/portals-container.tsx, packages/application-shell/src/components/app-bar/app-bar.tsx, packages/application-shell/src/components/application-shell/application-shell.tsx, packages/application-shell/src/constants.ts
=> fix(components): portals layout width based on left menu

.changeset/stale-eagles-serve.md, packages/application-shell/src/components/navbar/navbar.tsx, packages/application-shell/src/components/navbar/tracking-events.ts
Track the following events in the main navigation (Collapse, Expand and Support)
=> feat: implement ga tracking for main navigation

.changeset/ten-fishes-matter.md, packages/application-components/src/components/portals-container/portals-container.tsx
Damn, I forgot to actually make the props optional.
Leftover of https://github.com/commercetools/merchant-center-application-kit/pull/2586
=> fix(components): make props optional

.changeset/kind-impalas-tickle.md, .changeset/long-cougars-agree.md, .changeset/many-mangos-juggle.md, packages/codemod/README.md, packages/codemod/src/cli.ts, packages/codemod/src/transforms/remove-deprecated-modal-level-props.ts, packages/codemod/src/transforms/rename-js-to-jsx.ts, packages/codemod/src/types.ts, packages/codemod/test/__snapshots__/transforms.spec.ts.snap, packages/codemod/test/fixtures/remove-deprecated-modal-level-props.tsx, packages/codemod/test/transforms.spec.ts
Relates to #2581 
To help with the "migration" related to the Stacking Layer System.
=> feat(codemod): add transform `remove-deprecated-modal-level-props`

.github/workflows/docs.yml
=> ci: fix cache config for docs

package.json, yarn.lock
No relevant breaking changes are affecting us.
=> chore: update to puppeteer v14

.vscode/spellright.dict, website/src/releases/2022-05/release-v21.6.mdx
=> docs: add release note for `v21.6`

website/gatsby-config.js, website/linkinator.config.json, website/src/data/top-menu.yaml, website/src/data/top-side-menu.yaml
=> chore(website): add menu files for docs

.changeset/rude-cups-repeat.md, jest.test.config.js, jest.visual.config.js, packages/jest-preset-mc-app/README.md, packages/jest-preset-mc-app/jest-preset-for-typescript.js, packages/jest-preset-mc-app/typescript/index.js, packages/jest-preset-mc-app/typescript/jest-preset.js
Ref #1668
Simplifies using the Jest preset for TypeScript.
=> refactor(jest-preset): add proper typescript entry point

.github/ISSUE_TEMPLATE/bug_report.md
Update template to prevent duplicate bug issues.
=> Update template for bug issue

website/gatsby-config.js, website/src/content/help-needed.mdx, website/src/data/top-menu.yaml, website/src/releases/2022-06/general-availability.mdx
Custom Applications become generally available
The beta tag should be removed from all docs pages, and a new release note should be added.
=> 🚀 docs: Custom Applications become generally available

.vscode/spellright.dict, website/src/content/api-reference/commercetools-frontend-application-shell.mdx, website/src/content/concepts/integrate-with-your-own-api.mdx
=> docs: document audience policy for forward-to endpoint

website/src/content/concepts/integrate-with-your-own-api.mdx
=> docs: mention min version for the feature to be available

.changeset/great-terms-flow.md, packages-backend/express/src/auth.ts, packages-backend/express/src/middlewares/session-middleware.spec.ts, website/src/content/concepts/integrate-with-your-own-api.mdx
Ref: https://github.com/commercetools/merchant-center-application-kit/issues/2673#issuecomment-1172269087
=> refactor(express): improve validation check and docs

.changeset/bright-apples-live.md
Add changeset I forgot to create when working in moment locale metadata files [PR](https://github.com/commercetools/merchant-center-application-kit/pull/2679).
=> Add changeset for moment locale metadata improvement

website/src/content/migrating-from-project-level-custom-applications.mdx, website/src/releases/2022-07/migration-deadline-postponed.mdx
Updated migration deadline date.
As we are approaching an initially set deadline of 31st of July for migrating from Project-level to Organization-level for Custom Applications, we can see that there are still quite a few organizations that didn't do or didn't finish their migration yet. Hence, I'd suggest we postpone the migration deadline to 16th September 2022.
=> docs: updated migration deadline

.github/workflows/docs.yml, .github/workflows/release.yml, website/package.json, yarn.lock
=> chore: update deps for ci workflows

.changeset/blue-files-pull.md, application-templates/starter-typescript/package.json, application-templates/starter/package.json, packages/application-shell-connectors/package.json, packages/application-shell/package.json, yarn.lock
=> chore: update Apollo dependency to `v3.6.9`

.changeset/fuzzy-plums-beam.md, application-templates/starter-typescript/package.json, application-templates/starter/package.json, packages-backend/express/package.json, packages/application-shell/package.json, packages/mc-scripts/package.json, playground/src/components/state-machines-list/state-machines-list.spec.js, yarn.lock
=> chore: update `msw` dependency to `v0.44.0`

website/src/content/deployment-examples/azure-blob-storage.mdx, website/src/content/deployment-examples/azure-static-web-apps.mdx, website/src/content/deployment-examples/index.mdx, website/src/data/navigation.yaml
PR adds example of Azure deployment with Blob Storage in the docs.
Closes #2727
=> docs: add example of Azure deployment with Blob Storage

website/src/content/api-reference/custom-webpack-config.mdx, website/src/data/navigation.yaml
New documentation added for creating a custom webpack config.
ref #2719
=> docs: add custom webpack config docs

.changeset/tall-ties-jog.md, packages/application-shell/src/apollo-links/header-link.ts, packages/application-shell/src/constants.ts, packages/application-shell/src/export-types.ts, packages/application-shell/src/index.ts, packages/application-shell/src/utils/http-client.spec.ts, packages/application-shell/src/utils/http-client.ts
=> feat(app-shell): new utility functions to configure custom HTTP clients

.github/workflows/docs-content-check.yaml, .vscode/spellright.dict, website/src/content/api-reference/commercetools-frontend-application-shell.mdx, website/src/content/concepts/integrate-with-your-own-api.mdx, website/src/content/concepts/merchant-center-api.mdx, website/src/content/development/data-fetching.mdx
=> docs: document using custom HTTP clients

website/src/content/api-reference/commercetools-frontend-application-shell.mdx, website/src/content/concepts/integrate-with-your-own-api.mdx, website/src/content/concepts/merchant-center-api.mdx, website/src/content/development/data-fetching.mdx, website/src/releases/2022-08/custom-http-clients-support.mdx
Documentation for #2743
Ref #2732
=> docs: document using custom HTTP clients for `/forward-to`

website/src/content/api-reference/commercetools-frontend-application-shell.mdx, website/src/content/development/data-fetching.mdx
=> Document usage of Apollo REST link

website/src/content/api-reference/application-config.mdx
=> docs: add standalone-prices to list of reserved words

website/src/content/help-needed.mdx
=> docs: fix typo

playground/.env
=> fix(playground): add missing audience env variable

.changeset/chilly-parents-smile.md, packages/application-shell/src/components/application-page-title/application-page-title.spec.tsx, packages/application-shell/src/components/application-page-title/application-page-title.tsx, packages/application-shell/src/components/application-page-title/index.ts, packages/application-shell/src/components/application-shell-provider/application-shell-provider.tsx
Closes #1830 
Page titles should display a human readable title with respect to the user navigation.
=> Human readable page title

website/src/content/concepts/integrate-with-your-own-api.mdx
Follow-up PR with a leftover from #2783
Change "logged in user" to "logged-in user".
=> Fix docs about custom claims in MC gateway forwarded requests

.changeset/three-rice-battle.md, packages/application-shell/src/index.ts
Make page title component available.
=> feat(readable page title): make page title component available

.changeset/tiny-toes-bake.md, packages/application-config/src/formatters.spec.ts, packages/application-config/src/formatters.ts, yarn.lock
https://jira.commercetools.com/browse/SHIELD-583
In preparation for the Custom Applications Multiple Permissions support.
=> refactor(config): allow to pass additional permission groups to formatters

.changeset/fresh-coins-shout.md, packages/application-config/src/process-config.ts, packages/application-config/test/process-config.spec.js, packages/application-shell/src/components/application-shell/redirect-to-login.tsx, packages/application-shell/src/components/authenticated/has-cached-authentication-state.ts, packages/application-shell/src/utils/oidc.ts, packages/constants/src/constants.ts, packages/cypress/src/add-commands/index.ts
https://jira.commercetools.com/browse/SHIELD-581
In preparation for the Custom Applications Multiple Permissions support.
=> refactor(application-shell): include additional OAuth scopes in OIDC flow for local development

.changeset/perfect-numbers-leave.md, packages/application-shell/src/configure-store.ts
=> fix: disable redux serializable check

.changeset/khaki-rocks-kiss.md, application-templates/starter-typescript/src/components/channel-details/channel-details.tsx, application-templates/starter/src/components/channel-details/channel-details.jsx, cypress/e2e/template-starter/channels.cy.ts, jest.eslint.config.js, playground/src/components/formatters-demo/formatters-demo.jsx
Add human readable page title override  reference in the starter kit.
=> Add human readable page title reference

.changeset/strong-kangaroos-itch.md, packages/sdk/src/hooks/use-async-dispatch.ts
=> fix(sdk): return fixed reference for dispatch function

cypress/e2e/playground/notifications.cy.ts, cypress/e2e/template-starter/channels.cy.ts
=> test(e2e): attempt to refine some tests to improve stability

.changeset/bright-peaches-fetch.md, cypress.config.ts, cypress/e2e/playground/application-shell.cy.ts, cypress/e2e/playground/notifications.cy.ts, cypress/e2e/playground/state-machines.cy.ts, cypress/e2e/template-starter/channels.cy.ts, cypress/e2e/template-starter/welcome.cy.ts, packages/cypress/add-commands/index.d.ts, packages/cypress/src/add-commands/index.ts, packages/cypress/src/add-commands/login.ts
=> feat(cypress): use `cy.session` and add new command `cy.loginToMerchantCenter` 🚀

website/src/content/api-reference/commercetools-frontend-application-shell.mdx, website/src/content/development/adding-human-readable-page-title.mdx, website/src/content/development/human-readable-page-title.mdx, website/src/data/navigation.yaml, website/src/releases/2022-09/readable-page-title.mdx
Custom Applications the ability to display a more useful page title based on the page location.
This PR is to document how to make use of this feature.
=> Document human readable page title

website/src/content/what-is-a-custom-application.mdx
Removed the information regarding extending CoCo APIs, based on [the issue](https://github.com/commercetools/merchant-center-application-kit/issues/2850) that the information can be confusing for the users.
=> fix: removed info regarding extending APIs

.changeset/fifty-candles-sell.md, packages/application-shell/src/components/application-shell/global-styles.tsx, packages/mc-html-template/html-docs/application.html, visual-testing-app/index.html
Same as https://github.com/commercetools/ui-kit/pull/2326
Closes #2853
=> refactor(app-shell): use Google Fonts v2 API

.changeset/friendly-pears-type.md, .changeset/loud-badgers-attend.md, .changeset/thin-ladybugs-suffer.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18njmmmCEnoOKXqCcWD9aghCc5rqToe9PQ%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=EakYk5h)
Add missing changesets from a previous PR: #2883 .
=> Add missing changesets

.changeset/famous-cougars-smash.md, packages/mc-html-template/html-docs/application.html, packages/mc-html-template/src/replace-html-placeholders.ts
Suggestion to improve the connection time and thus rendering performance.
=> refactor: use `preconnect` hints for LaunchDarkly domains

.changeset/smooth-terms-share.md, .prettierrc, packages/mc-scripts/src/commands/build-vite.ts, packages/mc-scripts/src/commands/start-vite.ts, playground/src/components/entry-point/entry-point.jsx
=> fix(mc-scripts): add babel plugin do-expressions to default vite config

.github/workflows/docs.yml
Similar to https://github.com/commercetools/commercetools-docs-kit/pull/1399
=> ci(docs): try perf improvements to speed up build times

.changeset/kind-geese-breathe.md, package.json, packages/application-shell/package.json, packages/application-shell/src/test-utils/test-utils.tsx, yarn.lock
This PR aims to add `userEvent` method available on rtl tests. 
This was started actually more than a year ago and somehow forgotten...
=> chore: add user event to rtl

.changeset/tame-colts-guess.md, packages/application-shell/src/components/navbar/navbar.mod.css
=> fix(navbar): overlap with links

.changeset/gorgeous-yaks-unite.md, packages-backend/express/package.json, yarn.lock
=> chore: update `express-jwt` dependency

.changeset/honest-sheep-scream.md, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/navbar/navbar.mod.css, packages/application-shell/src/components/navbar/navbar.tsx
| Menu open | Menu collapsed |
| --- | --- |
| ![2023-01-20 10 50 18](https://user-images.githubusercontent.com/1110551/213683828-7ba73302-ef4e-443f-ae8e-03b5a6926740.gif) | ![2023-01-20 12 19 39](https://user-images.githubusercontent.com/1110551/213683866-e3c76f74-2547-43bc-940e-1a1adada2f04.gif) |
=> fix(navbar): overflow with long labels

website/src/content/api-reference/application-config.mdx, website/src/content/concepts/oauth-scopes-and-user-permissions.mdx, website/src/content/development/permissions.mdx
There was some confusion about this and I think we should clarify this in the docs as well.
=> docs: clarify what happens when menu link permissions are empty

website/src/content/api-reference/commercetools-frontend-application-components.mdx
=> docs: improve code snippets for `TabularModalPage` and `InfoModalPage`

website/linkinator.config.json, website/src/content/maintenance-guidelines.mdx
=> docs: update api contract link

website/src/data/top-side-menu.yaml
Applies the same top menu navigation changes to custom apps.
Changes in the other microsites:
https://github.com/commercetools/commercetools-docs/pull/2780/files#diff-24be61414e50999b7d7738093ab3d681078a1bfb4ed01689e8dfa15154915010
=> Adjust links in top menu navigation for the new offering website

.changeset/kind-mails-remain.md, packages/mc-dev-authentication/html-docs/login.html, website/src/content/concepts/merchant-center-api.mdx, website/src/content/getting-started.mdx, website/src/releases/2023-02/support-sso-login-local-development.mdx
=> docs: release note about SSO login for local dev

website/src/content/concepts/deployment-previews.mdx
Fixed the "adding the deployment preview" link.
=> fix(docs): internal link

.changeset/seven-foxes-sing.md, packages/application-shell/src/components/user-settings-menu/user-settings-menu.tsx
=> fix: avatar size for new design

.changeset/thirty-terms-burn.md, packages/application-components/src/components/public-page-layout/public-page-layout.tsx, packages/application-shell/src/components/locale-switcher/locale-switcher.tsx, packages/application-shell/src/components/project-switcher/project-switcher.tsx
=> refactor(app-bar): reskin locale and project switchers

.changeset/tough-tips-pump.md, packages/application-shell/src/components/navbar/navbar.mod.css, packages/application-shell/src/components/navbar/navbar.tsx
Small fix to mark submenu links as active for subroutes of that link.
=> fix(app-shell): matching of subroutes

website/src/releases/2020-10/release-v17.mdx, website/src/releases/2021-01/community-discussions.mdx, website/src/releases/2021-01/release-v18.mdx, website/src/releases/2021-04/release-v19.mdx, website/src/releases/2021-08/rewrite-starter-template.mdx, website/src/releases/2022-02/release-v21.mdx, website/src/releases/2022-04/release-v21.3.mdx, website/src/releases/2022-05/release-v21.6.mdx, website/src/releases/2022-06/general-availability.mdx, website/src/releases/2022-07/extending-private-installations.mdx, website/src/releases/2022-07/migration-deadline-postponed.mdx, website/src/releases/2022-07/release-v21.8.mdx, website/src/releases/2022-09/readable-page-title.mdx, website/src/releases/2022-12/custom-applications-multiple-permissions.mdx, website/src/releases/2023-03/button-sizes.mdx
Update the release notes topics to match the [updated topic list](https://commercetools.atlassian.net/wiki/spaces/DOCS/pages/105818548/Writing+release+notes).
- I've also added an `Info` box to all breaking changes release notes.
=> Docs: Update release notes topics

.changeset/small-walls-live.md, packages/application-shell/src/hooks/use-routes-creator/index.ts, packages/application-shell/src/hooks/use-routes-creator/use-routes-creator.spec.ts, packages/application-shell/src/hooks/use-routes-creator/use-routes-creator.ts, packages/application-shell/src/index.ts
Making the routes abstraction implementation available to everyone.
=> feat(app-shell): add hook `useRoutesCreator`

.changeset/rotten-papayas-camp.md, packages/application-shell/src/components/navbar/navbar.mod.css
fixes https://github.com/commercetools/merchant-center-redesign/issues/359
=> fix: scroll issue for closed navbar

.changeset/tidy-keys-taste.md, packages/application-shell/src/components/navbar/navbar.mod.css
=> fix: revert navbar scrolling fix

website/src/releases/2023-04/release-v22.mdx
=> docs: add release notes for v22

.changeset/large-bikes-boil.md, packages/application-shell/src/components/application-shell-authenticated/application-shell-authenticated.tsx
This PR adds a new placeholder container for rendering something above the top navigation (for internal usage only).
=> Add placeholder container above the top navigation

.changeset/clever-buckets-walk.md, packages/application-shell/src/components/navbar/navbar.tsx
=> fix: to use exact matching strategy for menu links

website/src/releases/2023-05/new-theme.mdx
Added the release note for Custom Applications developers about the new theme for the Merchant Center.
**IMPORTANT**: This PR depends on #3057
=> Custom applications new theme release note

website/src/content/development/data-fetching.mdx
Improve data fetching code example
The code example we're using in the "[Calling REST APIs inside your GraphQL queries](https://docs.commercetools.com/custom-applications/development/data-fetching#calling-rest-apis-inside-your-graphql-queries)" section of the docs is using a constant from a package which is not imported in the example so we add that missing import in this PR to avoid confusion.
=> Improve data fetching code example

.changeset/chilly-trainers-decide.md, .changeset/four-stingrays-change.md, .changeset/olive-carrots-sniff.md, .changeset/silver-pianos-itch.md, .changeset/slimy-squids-sleep.md, packages/create-mc-app/src/cli.ts, packages/create-mc-app/src/process-options.ts, packages/create-mc-app/src/tasks/install-dependencies.ts, packages/create-mc-app/src/tasks/update-package-json.ts, packages/create-mc-app/src/types.ts, packages/create-mc-app/src/utils.ts, packages/create-mc-app/src/validations.ts
=> feat(create-mc-app): support new cli options to specify preferred package manager

.changeset/young-rules-check.md, packages-backend/express/src/auth.ts, packages-backend/express/src/constants.ts, packages-backend/express/src/middlewares/session-middleware.spec.ts, packages/application-config/src/constants.ts, packages/application-config/src/utils.ts, website/src/content/concepts/merchant-center-api.mdx
Add the cloud identifier for China production.
=> chore: add cloud identifier for CN prod

.changeset/tiny-eels-tan.md, packages/application-shell/src/utils/select-team-id-from-storage/select-team-id-from-storage.ts
=> fix(app-shell): send `teamId` header in Custom Application local development

package.json, playground/package.json, pnpm-lock.yaml, website/package.json
Updates all kit dependencies.
Should be merged together with https://github.com/commercetools/commercetools-docs/pull/3681
=> [New kit release] Update all docs-kit dependencies

.changeset/kind-buckets-burn.md, graphql-test-utils/graphql-models/project.js, packages/application-shell-connectors/src/components/application-context/application-context.spec.tsx, packages/application-shell-connectors/src/components/application-context/application-context.tsx, packages/application-shell-connectors/src/types/generated/mc.ts, packages/application-shell-connectors/src/types/generated/settings.ts, packages/application-shell/src/components/fetch-project/fetch-project.mc.graphql, packages/application-shell/src/types/generated/ctp.ts, packages/application-shell/src/types/generated/mc.ts, packages/application-shell/src/types/generated/settings.ts, packages/mc-scripts/src/generated/core.ts, packages/mc-scripts/src/generated/settings.ts, packages/permissions/src/types/generated/mc.ts, schemas/core.json, schemas/ctp.json, schemas/mc.json, schemas/settings.json, test-data/project/generator.ts, test-data/project/types.ts, test-data/types/generated/mc.ts
This PR adds `sampleDataImportDataset` to application-context.
=> feat(context): add project extension import data

packages/application-shell/src/components/navbar/navbar-skeleton.styles.tsx, packages/application-shell/src/components/navbar/navbar-skeleton.tsx
Navbar skeleton menu items styles refactor proposal
This is a proposal to maybe simplify styles in this PR: #3165
=> Navbar skeleton menu items styles refactor proposal

.changeset/little-keys-retire.md, packages/application-shell/src/components/application-shell-authenticated/application-shell-authenticated.tsx, packages/application-shell/src/components/application-shell-authenticated/new-main-navigation-flag-wrapper.tsx, packages/application-shell/src/components/navbar/navbar-skeleton.styles.tsx, packages/application-shell/src/components/navbar/navbar-skeleton.tsx, packages/application-shell/src/components/navbar/navbar.tsx, packages/application-shell/src/components/navbar/use-navbar-state-manager.ts
|  Designs  |  Screencast |
|---|---|
| <img width="360" alt="Screenshot 2023-08-09 at 15 37 03" src="https://github.com/commercetools/merchant-center-application-kit/assets/49066275/89d031ad-45b5-42bf-a758-219b1a7c30f5"> | ![2023-08-09 15 31 18](https://github.com/commercetools/merchant-center-application-kit/assets/49066275/7c95acc3-69be-40a4-baa2-70db84613d2d)  |
[A direct link to deployment in the MC](https://mc.europe-west1.gcp.escemo.com/main-navigation-test/navbar-skeleton)
=> refactor(app-shell): new NavBar skeleton

.changeset/sharp-donkeys-move.md, packages/application-shell/src/components/navbar/navbar.mod.css
This PR reverts the change made in #3183.
The change led to failures of the e2e tests due to the submenu consistently appearing during testing.
~~While I'm not entirely certain that this pull request will definitively resolve the test issue, since I can't replicate the bug locally (it appears only in the CI), I've been thinking of using of a branch deployment in the MC FE with a canary release of the `@commercetools-frontend/*` packages to verify if it works.~~
I have a reason to believe this should work. In the last pipeline [here](https://github.com/commercetools/merchant-center-frontend/pull/15223) most cases were resolved (although it's worth noting that some issues in the `discounts` app remain unresolved)
=> fix: Navbar submenu causing issues in e2e tests

.changeset/serious-hats-prove.md, packages/application-shell/src/components/navbar/menu-items.tsx, packages/application-shell/src/components/navbar/navbar.mod.css, packages/application-shell/src/components/navbar/navbar.tsx
This PR adds first part of the new Submenu styles. 
**It does not cover the "Tooltip" and the correct positioning of the submenu**.
=> refactor(Navbar): new Submenu - part 1

.changeset/calm-hounds-remember.md, packages/application-shell/src/components/application-shell-authenticated/application-shell-authenticated.tsx, packages/application-shell/src/constants.ts
Fixes [SHIELD-907](https://commercetools.atlassian.net/browse/SHIELD-907)
=> refactor: update `PortalsContainer` offsets

.changeset/sharp-mirrors-reflect.md, packages/application-shell/src/components/navbar/navbar-new/navbar.mod.css
Fixes [SHIELD-906](https://commercetools.atlassian.net/browse/SHIELD-906)
|  Before |  After |
|---|---|
| <img src="https://github.com/commercetools/merchant-center-application-kit/assets/49066275/c055d5ad-2fc7-4457-8441-2d233614a0fd">  | <img width="832" alt="Screenshot 2023-09-12 at 12 57 18" src="https://github.com/commercetools/merchant-center-application-kit/assets/49066275/80238619-989b-4561-b094-a5e7c1579ffb">  |
=> fix: left navigation height when global notification is displayed

.changeset/silent-beers-drum.md, packages/application-shell/src/components/navbar/navbar-new/menu-items.tsx, packages/application-shell/src/components/navbar/navbar-new/navbar.mod.css, packages/application-shell/src/components/navbar/navbar-new/navbar.tsx
There were few issues:
- Bouncy Support menu
- The menu items moves slightly to the right when expanded
- An active menu item should not have a hover state.
- Added correct icon color
- Added correct title font-weight
https://github.com/commercetools/merchant-center-application-kit/assets/52276952/a67dcd0d-2534-4800-aa35-330976a72cfa
=> Smaller navigation UI improvements

website/src/content/development/testing.mdx
=> docs: use correct imports in code snippets

.changeset/ninety-dots-exercise.md, packages/application-shell/src/components/navbar/navbar-new/navbar.mod.css
Fixes https://github.com/commercetools/merchant-center-application-kit/pull/3218#issuecomment-1733772359
=> fix(Navbar): submenu item clickable area

.changeset/modern-days-beam.md, packages/application-config/src/process-config.ts, packages/application-config/test/fixtures/custom-applications/config-account-links.json, packages/application-config/test/process-config-custom-application.spec.js
=> fix: small regression when parsing links for the account application

cypress/tsconfig.json
=> fix(cypress): include node types

.changeset/red-apricots-battle.md, packages/application-shell/src/components/application-shell/application-shell.spec.js, packages/application-shell/src/components/navbar/navbar-new/menu-items.tsx, packages/application-shell/src/components/navbar/navbar-new/navbar.mod.css, packages/application-shell/src/components/navbar/navbar-new/navbar.tsx
=> Left navigation transition

packages/application-components/package.json, packages/application-components/src/components/custom-views/custom-views-selector/custom-views-selector.spec.tsx, pnpm-lock.yaml
Follow up of #3242 
Add basic tests for the `<CustomViewsSelctor>` component.
=> `CustomViewsSelctor` component RTL tests

.changeset/six-cars-fetch.md, playground/package.json, pnpm-lock.yaml, website/gatsby-config.mjs, website/package.json, website/src/data/footer.yaml, website/src/data/top-menu.yaml
=> feat: megamenu redesign docs-kit 22.8.2

.changeset/shaggy-bags-battle.md, packages/application-components/src/theming.ts, packages/application-shell/src/components/app-bar/app-bar.tsx, packages/application-shell/src/constants.ts
**Before the change:**
**After the change:**
=> App bar elements repositioning

.changeset/green-stingrays-compete.md, packages/application-shell/src/components/application-shell/application-shell.tsx, packages/application-shell/src/components/custom-view-shell/custom-view-shell.tsx
=> feat(app-shell): allow to enable StrictMode through shell

pnpm-lock.yaml
Some inconsistencies happened in `pnpm-lock.yaml` file on `main` while updating the dependencies. So I ran `pnpm install` in order to fix it.
=> Updating `pnpm-lock.yaml` file

.changeset/short-trainers-play.md, cypress/e2e/custom-view-template-starter/channels.cy.ts, cypress/e2e/custom-view-template-starter/welcome.cy.ts, cypress/support/urls.ts, packages/cypress/add-commands/index.d.ts, packages/cypress/package.json, packages/cypress/src/add-commands/index.ts, pnpm-lock.yaml
Follow up of https://github.com/commercetools/merchant-center-application-kit/pull/3339#discussion_r1425413776
=> test(custom views): custom view templates e2e tests - follow up

.changeset/three-wasps-peel.md, website-custom-views/src/content/concepts/merchant-center-api.mdx, website/src/content/concepts/merchant-center-api.mdx
=> docs(ml): remove ml proxy

website-custom-views/src/content/api-reference/commercetools-frontend-application-shell-connectors.mdx, website-custom-views/src/content/api-reference/commercetools-frontend-cypress.mdx, website-custom-views/src/content/api-reference/custom-view-config.mdx, website-custom-views/src/content/concepts/oauth-scopes-and-user-permissions.mdx, website-custom-views/src/content/deployment-examples/aws-s3-cloudfront.mdx, website-custom-views/src/content/deployment-examples/azure-blob-storage.mdx, website-custom-views/src/content/deployment-examples/azure-static-web-apps.mdx, website-custom-views/src/content/deployment-examples/cloudflare.mdx, website-custom-views/src/content/deployment-examples/google-cloud-static-web-apps.mdx, website-custom-views/src/content/deployment-examples/netlify.mdx, website-custom-views/src/content/deployment-examples/render.mdx, website-custom-views/src/content/deployment-examples/surge.mdx, website-custom-views/src/content/deployment-examples/vercel.mdx, website-custom-views/src/content/getting-started.mdx
Improve Custom Views docs
There are two main changes:
1. We rename all references to the configuration file name `custom-view-config.json` to `custom-view-config.mjs` as that's the one we use in our starter templates
2. We add the docs for the `env.development.hostUriPath` config property.
=> Improve Custom Views docs

.changeset/wild-cougars-share.md, package.json, playground/package.json, pnpm-lock.yaml, website-custom-views/gatsby-config.mjs, website-custom-views/package.json, website/gatsby-config.mjs, website/package.json
=> chore: upgrade to latest docs kit and enable AI assistant

website-components-playground/src/application.tsx, website-custom-views/linkinator.config.json
=> fix: components playground links

packages/application-components/src/components/project-stamp/project-stamp.tsx, packages/application-shell/src/components/app-bar/app-bar.tsx, packages/application-shell/src/components/locale-switcher/locale-switcher.tsx, packages/application-shell/src/components/project-switcher/project-switcher.tsx, packages/permissions/src/components/branch-on-permissions/branch-on-permissions.spec.tsx
AppBar selectors styling refactor proposal
In this PR I've implemented an alternative to the [AppBar restyling](https://github.com/commercetools/merchant-center-application-kit/pull/3403) trying to use as little custom CSS as possible.
=> AppBar selectors styling refactor proposal

.changeset/gorgeous-bags-matter.md, packages/application-shell/src/components/navbar/main-navbar.styles.ts, packages/application-shell/src/components/navbar/menu-items.styles.ts
[Deployment link](https://mc-15822.mc-preview.europe-west1.gcp.escemo.com/adnan-nodejs-test-project/welcome)
This solution worked for me in:
- Chrome 121.0.6167.160, 
- FF 122.0.1, 
- Edge 121.0.2277.112, 
- Safari Version 17.3.1 (19617.2.4.11.12)
=> fix(Navbar): cross-browser consistency of menu items width on hover

package.json, packages/i18n/data/core.json, packages/i18n/scripts/compile_data.sh, packages/i18n/transifex-compiler.js, transifex.yml
We want to use this to test out what happens in Transifex when we change an existing resource file format.
We will use the feedback to eventually plan the migration work for our main frontend repository.
=> refactor(i18n): change Transifex file format to Structured JSON

.changeset/good-pigs-sniff.md, packages/application-components/src/components/project-stamp/project-stamp.tsx, packages/react-notifications/src/components/notification/notification.styles.ts
Follow up changes on recolouring work. 
Icon color on project selection appbar component and update to the global notification background color for warning.
=> Follow up changes on rebranding

.changeset/odd-squids-relate.md
This is a follow-up of #3439 since I forgot to include the changeset in that PR.
=> Add missing changeset

.changeset/early-dots-obey.md, packages/application-shell/src/components/user-settings-menu/user-settings-menu.tsx
Recolouring follow-up: Update app-bar avatar background color
Screenshot:
=> Update app-bar avatar background color

.changeset/happy-dogs-divide.md, packages/application-shell/src/components/application-shell-authenticated/application-shell-authenticated.tsx, packages/application-shell/src/components/application-shell/application-shell.tsx, packages/application-shell/src/components/authenticated/oidc-callback-error-page.tsx, packages/application-shell/src/components/custom-view-shell/custom-view-shell.tsx, packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.tsx, packages/application-shell/src/components/theme-switcher/theme-switcher.tsx, packages/constants/src/feature-toggles.ts, packages/cypress/src/add-commands/login.ts, visual-testing-app/src/components/page-content-container-combinations/page-content-container-combinations.visualroute.tsx, visual-testing-app/src/components/page-content-container-narrow/page-content-container-narrow.visualroute.tsx, visual-testing-app/src/components/page-content-container-wide/page-content-container-wide.visualroute.tsx, visual-testing-app/src/index.tsx, website-components-playground/src/index.tsx
=> refactor: use `recolouring` theme without feature flag evaluation

.changeset/lazy-cows-jam.md, packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.tsx
Fixes https://github.com/commercetools/merchant-center-application-kit/security/code-scanning/10
=> refactor: regex to define start of match

.changeset/twenty-numbers-watch.md
=> docs: changeset

.changeset/poor-wolves-burn.md, website-components-playground/src/application.tsx, website-components-playground/src/pages/drawer.tsx, website-components-playground/src/pages/index.tsx
Playground for the drawer component required to write the drawer component docs.
=> Playground for the drawer component - docs

CONTRIBUTING.md
Fix typo.
The `build:bundles:watch` script doesn't exist.
=> chore(CONTRIBUTING.md): fix typo

pnpm-lock.yaml
```
pnpm up -r caniuse-lite
```
=> chore: update browserlist-db

playground/package.json, pnpm-lock.yaml
Issue https://commercetools.atlassian.net/browse/SHIELD-1497
Missing babel runtime dependency caused errors "Module not found: Error: Can't resolve '@babel/runtime-corejs3/core-js-stable/***'"
=> fix: Webpack build error in playground app

.changeset/silent-donuts-obey.md, packages-backend/express/src/auth.ts, packages-backend/express/src/constants.ts, packages-backend/express/src/middlewares/session-middleware.spec.ts, packages/application-config/src/constants.ts, packages/application-config/src/utils.ts
https://commercetools.atlassian.net/browse/SHIELD-1499
=> refactor: rename cloud identifiers

.changeset/honest-needles-pull.md, packages/application-shell/src/test-utils/custom-views-utils.tsx
Fixes https://commercetools.atlassian.net/browse/SUPPORT-29494
I will add a task to add tests as a follow-up.
=> fix(app-shell/custom-view-utils): `renderCustomView` helper

.github/workflows/preview-release-on-comment.yml
=> ci: define proper `.npmrc` file

.changeset/friendly-doors-end.md, packages-backend/express/src/auth.ts, packages-backend/express/src/constants.ts, packages/application-config/src/constants.ts, packages/application-config/src/utils.ts
https://commercetools.atlassian.net/browse/SHIELD-1558
=> refactor: remove unsupported cloud identifiers

.github/workflows/playground-deployment-preview.yml, .github/workflows/preview-release-on-comment.yml
This follows https://github.com/commercetools/merchant-center-application-kit/pull/3663, and more generally fixes these template injections.
I found these with [zizmor](https://github.com/woodruffw/zizmor).
**IMPORTANT**: I did *not* fix all of `zizmor's` findings, since there are 40+ of them on your repository. I strongly suggest going through each and evaluating them/your risk tolerance.
=> workflows: fix some exploitable template injections

.changeset/rich-forks-rescue.md, .changeset/shy-ducks-grin.md, .changeset/thick-kiwis-jam.md, packages/constants/src/constants.ts, packages/mc-html-template/src/process-headers.spec.ts, packages/mc-html-template/src/process-headers.ts, packages/mc-html-template/src/replace-html-placeholders.ts, packages/mc-scripts/src/commands/start-vite.ts, packages/mc-scripts/src/webpack-plugins/local-html-webpack-plugin.ts
Minor improvements as follow up of recent support findings.
=> refactor: refine security headers and ensure they are applied for local development

.changeset/few-adults-argue.md, packages/sdk/src/components/sdk-get/sdk-get.tsx
=> fix(sdk): regression for default props

.changeset/friendly-insects-grab.md, packages/constants/src/constants.ts
Adds new targets for GraphQL and HTTP.
=> Add new MC API and GraphQL targets

.changeset/giant-worms-clap.md, packages/i18n/data/core.json, packages/react-notifications/src/components/notification-kinds/api-error-message/api-error-message.spec.tsx, packages/react-notifications/src/components/notification-kinds/api-error-message/messages.ts
=> PRC-4138: Update duplicate prices scope error messages

.github/workflows/codecov.yaml, .gitignore, babel.config.js, cypress.config.ts, cypress/.eslintrc.yaml, cypress/support/e2e.ts, package.json, packages/babel-preset-mc-app/create.js, packages/babel-preset-mc-app/package.json, packages/mc-scripts/src/config/create-webpack-config-for-development.ts, pnpm-lock.yaml
=> ci: add Codecov workflow for test coverage reporting

.changeset/sharp-garlics-bathe.md, .github/workflows/main.yml, cypress.config.ts, packages/cypress/src/add-commands/index.ts, packages/cypress/src/add-commands/login.ts
Prepares our custom login command for the Merchant Center to support the Identity login flow.
=> feat(cypress): support login flow via Identity 

packages/mc-scripts/src/commands/login.ts
Accept an env var for the MC API URL in the login command
the `mc-scripts login` command expects to be run from a Custom Application directory so it can read its configuration file and get the `mcApiUrl` value to know what environment to log into. 
For some internal use cases we need to use this command outside of a Custom Application so we want the command to be able to pick that value from an environment variable as well.
This won't be documented as we don't know yet if this would be temporary or permanent.
=> Accept an env var for the MC API URL in the login command

.changeset/tough-eagles-bow.md, packages/application-config/src/process-config.ts, packages/application-config/test/process-config-custom-application.spec.js
=> fix: allow CSP to load source maps
